### ISSUE TITLE
flink to iceberg commit fail (Datastream API, hiveCatalog) 

### ISSUE THREAD

**Issue by SML0127** [apache/iceberg#10019]
### Apache Iceberg version

1.5.0 (latest release)

### Query engine

Flink

### Please describe the bug 🐞

First commit at create table is success, after commit is always fail
`org.apache.iceberg.exceptions.CommitStateUnknownException: @hive#my_db.my_db table not found`

Flink version: 1.17.0
Iceberg version: 1.5.0

## my code (scala)
```scala
object IcebergSinkConfiguration {

  val hadoopConf = new Configuration()
  var catalog = new HiveCatalog()
  var warehouse = ""
  val catalogName = "hive"
  var database = "my_db"
  lazy val tableName = "my_table"
  val hiveMetastoreUris = "thrift://hadoo-xxx:9083" // replaced for security 
  
  val tableProperties = JavaConverters.mapAsJavaMap(Map[String, String](
    (TableProperties.FORMAT_VERSION, "2"),
    (TableProperties.UPSERT_ENABLED, "true"),
    (TableProperties.METADATA_DELETE_AFTER_COMMIT_ENABLED, "true"),
    (TableProperties.ENGINE_HIVE_ENABLED, "true")
  ))
  val catalogProps = new java.util.HashMap[String, String]()
  var tableIdentifier: TableIdentifier = null
  var catalogLoader: CatalogLoader = null
  var table: Table = null
  var tableLoader: TableLoader = null


  def apply(phase: String): Unit = {
    
    warehouse = s"${hdfsHeadPath}warehouse"
    
    catalogProps.put(WAREHOUSE_LOCATION, warehouse)
    catalogProps.put(URI, hiveMetastoreUris)
    catalogProps.put(CLIENT_POOL_SIZE, "10")
    catalogProps.put("type", "iceberg")
    catalogProps.put("catalog-type", "hive")
    catalogProps.put("property-version", "2")


    hadoopConf.set(ENGINE_HIVE_ENABLED, "true")

    val namespaceProps = new util.HashMap[String, String]()
    namespaceProps.put(HiveCatalog.HMS_TABLE_OWNER, "my_name")
    namespaceProps.put(HiveCatalog.HMS_DB_OWNER, "my_name")

    catalogLoader = CatalogLoader.hive(catalogName, hadoopConf, catalogProps)
    catalog = catalogLoader.loadCatalog().asInstanceOf[HiveCatalog]


    val namespace = Namespace.of(database)
    tableIdentifier = TableIdentifier.of(namespace, tableName) 
    val table = catalog.createTable(
          tableIdentifier,
          getIcebergTableSchema,
          PartitionSpec.unpartitioned,
          warehouse + s"${database}.db/${tableName}",
          tableProperties

    FlinkSink.forRowData(rowDataJavaDataStream)
      .tableLoader(tableLoader)
      .upsert(true)
      .equalityFieldColumns(JavaConverters.mutableSeqAsJavaList(pkList))
      .append().setParallelism(1)
    }

}
```

## error log
```d
Committing existing table: hive.my_db.my_table

...

Committing rowDelta for checkpoint 1 to table hive.my_db.my_table branch main with summary: CommitSummary{dataFilesCount=1, dataFilesRecordCount=1, dataFilesByteCount=2696, deleteFilesCount=1, deleteFilesRecordCount=1, deleteFilesByteCount=465}

...

2024-03-22 07:53:39.004 ERROR org.apache.iceberg.hive.HiveTableOperations                  [] - Cannot tell if commit to my_db.my_table succeeded, attempting to reconnect and check.
org.apache.iceberg.exceptions.CommitStateUnknownException: @hive#my_db.my_db table not found
Cannot determine whether the commit was successful or not, the underlying data files may or may not be needed. Manual intervention via the Remove Orphan Files Action can remove these files when a connection to the Catalog can be re-established if the commit was actually unsuccessful.
Please check to see whether or not your commit was successful before retrying this commit. Retrying an already successful operation will result in duplicate records or unintentional modifications.
At this time no files will be deleted including possibly unused manifest lists.
	at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:292)
	at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:135)
	at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:408)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
	at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:382)
	at org.apache.iceberg.flink.sink.IcebergFilesCommitter.commitOperation(IcebergFilesCommitter.java:416)
	at org.apache.iceberg.flink.sink.IcebergFilesCommitter.commitDeltaTxn(IcebergFilesCommitter.java:388)
	at org.apache.iceberg.flink.sink.IcebergFilesCommitter.commitPendingResult(IcebergFilesCommitter.java:298)
	at org.apache.iceberg.flink.sink.IcebergFilesCommitter.commitUpToCheckpoint(IcebergFilesCommitter.java:280)
	at org.apache.iceberg.flink.sink.IcebergFilesCommitter.initializeState(IcebergFilesCommitter.java:198)
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.initializeOperatorState(StreamOperatorStateHandler.java:122)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.initializeState(AbstractStreamOperator.java:274)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:106)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:734)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.call(StreamTaskActionExecutor.java:55)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:709)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:675)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:952)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:921)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:745)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562)
	at java.lang.Thread.run(Thread.java:750)
Caused by: InvalidOperationException(message:@hive#my_db.my_table table not found)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$alter_table_with_environment_context_result$alter_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$alter_table_with_environment_context_result$alter_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$alter_table_with_environment_context_result.read(ThriftHiveMetastore.java)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_alter_table_with_environment_context(ThriftHiveMetastore.java:2270)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.alter_table_with_environment_context(ThriftHiveMetastore.java:2254)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.alter_table_with_environmentContext(HiveMetaStoreClient.java:405)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:208)
	at com.sun.proxy.$Proxy69.alter_table_with_environmentContext(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.iceberg.common.DynMethods$UnboundMethod.invokeChecked(DynMethods.java:60)
	at org.apache.iceberg.common.DynMethods$UnboundMethod.invoke(DynMethods.java:72)
	at org.apache.iceberg.hive.MetastoreUtil.alterTable(MetastoreUtil.java:78)
	at org.apache.iceberg.hive.HiveOperationsBase.lambda$persistTable$0(HiveOperationsBase.java:112)
	at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:58)
	at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:51)
	at org.apache.iceberg.hive.CachedClientPool.run(CachedClientPool.java:122)
	at org.apache.iceberg.hive.HiveOperationsBase.persistTable(HiveOperationsBase.java:110)
	at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:239)
```

## hdfs
```
hadoop fs -ls  hdfs://hadoop-xx/warehouse
24/03/22 17:03:54 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
24/03/22 17:03:54 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
Found 2 items
drwxrwxr-x   - my_name my_group          0 2024-03-22 16:53 hdfs://hadoop-xx/warehouse/my_db.db/my_table/data
drwxrwxr-x   - my_name my_group          0 2024-03-22 16:53 hdfs://hadoop-xx/warehouse/my_db.db/my_table/metadata
```

**Comment by pvary** [comment]
Seems like an issue with the HiveClient. Could you check the server HMS version, the HMSClient version in the job. Or alternatively if there is a connection issue between the tasks and the HMS, you could decrease the checkpoint interval and see if the connection failure happens because some idle timeout...

**Comment by pvary** [comment]
Also, could you check in some other way, whether the table exists, or not?

**Comment by SML0127** [comment]
HI @pvary !

- Hive, HMS version is `2.3.2`

- Current checkpoint interval is 60s. should I decrease checkpoint interval further?   

- I checked table exist in HDFS, table is exist and data is appended as parquet (default format).
```d
-rw-rw-r--   3 my_name my_group       3799 2024-03-22 21:39 /warehouse/my_db.db/my_table/data/00000-0-2b497ab9-0698-4168-b040-cbf15629f9d5-00001.parquet
-rw-rw-r--   3 my_name my_group        610 2024-03-22 21:39 /warehouse/my_db.db/my_table/data/00000-0-2b497ab9-0698-4168-b040-cbf15629f9d5-00002.parquet
-rw-rw-r--   3 my_name my_group       1524 2024-03-22 21:39 /warehouse/my_db.db/my_table/data/00000-0-2b497ab9-0698-4168-b040-cbf15629f9d5-00003.parquet
-rw-rw-r--   3 my_name my_group       2696 2024-03-22 21:39 /warehouse/my_db.db/my_table/data/00000-0-2b497ab9-0698-4168-b040-cbf15629f9d5-00004.parquet
-rw-rw-r--   3 my_name my_group        465 2024-03-22 21:39 /warehouse/my_db.db/my_table/data/00000-0-2b497ab9-0698-4168-b040-cbf15629f9d5-00005.parquet
```


- Also, I checked metadata.
```d
-rw-rw-r--   3 my_name my_group       7270 2024-03-22 21:39 /warehouse/my_db.db/my_table/metadata/04b48968-1fb1-47fd-b3cf-7aa523f80bb3-m0.avro
-rw-rw-r--   3 my_name my_group       7167 2024-03-22 21:39 /warehouse/my_db.db/my_table/metadata/04b48968-1fb1-47fd-b3cf-7aa523f80bb3-m1.avro
-rw-rw-r--   3 my_name my_group       4267 2024-03-22 21:39 /warehouse/my_db.db/my_table/metadata/snap-6602178353535113098-1-04b48968-1fb1-47fd-b3cf-7aa523f80bb3.avro
-rw-rw-r--   3 my_name my_group       3310 2024-03-22 21:39 /warehouse/my_db.db/my_table/metadata/00001-30bf3f39-28ca-49ca-aca0-3da5f383d331.metadata.json
-rw-rw-r--   3 my_name my_group       7273 2024-03-22 21:39 /warehouse/my_db.db/my_table/metadata/b8278e21-bbdf-465c-83b0-82751f22d474-m0.avro
-rw-rw-r--   3 my_name my_group       7166 2024-03-22 21:39 /warehouse/my_db.db/my_table/metadata/b8278e21-bbdf-465c-83b0-82751f22d474-m1.avro
-rw-rw-r--   3 my_name my_group       4265 2024-03-22 21:39 /warehouse/my_db.db/my_table/metadata/snap-4565585769524429621-1-b8278e21-bbdf-465c-83b0-82751f22d474.avro
-rw-rw-r--   3 my_name my_group       3310 2024-03-22 21:39 /warehouse/my_db.db/my_table/metadata/00001-ffa1186b-a38a-4fdf-9201-2c1a7bd412f7.metadata.json
-rw-rw-r--   3 my_name my_group       7270 2024-03-22 21:39 /warehouse/my_db.db/my_table/metadata/0a009fb8-3b4b-464f-9a6d-656310575e5f-m0.avro
-rw-rw-r--   3 my_name my_group       7167 2024-03-22 21:39 /warehouse/my_db.db/my_table/metadata/0a009fb8-3b4b-464f-9a6d-656310575e5f-m1.avro
-rw-rw-r--   3 my_name my_group       4265 2024-03-22 21:39 /warehouse/my_db.db/my_table/metadata/snap-250431147167954976-1-0a009fb8-3b4b-464f-9a6d-656310575e5f.avro
-rw-rw-r--   3 my_name my_group       3305 2024-03-22 21:39 /warehouse/my_db.db/my_table/metadata/00001-45d8c0e8-3762-4b7d-818b-4143c4a99a8c.metadata.json
```

**Comment by SML0127** [comment]
@pvary 
There's something strange about hive catalog.

When I check HiveCatalog.namespaceExists(namespace), it always return `false`.
But when I create name space, it return error `Namespace already exists: my_db`


Here is my code, and log

### code
```scala
val namespace = Namespace.of(database)
LOG.info(catalog.namespaceExists(namespace).toString)
if (!catalog.namespaceExists(namespace)) {  
  try {  
    catalog.createNamespace(namespace, namespaceProps)
  } catch {  
    case e: Exception => LOG.info(e.getMessage)  
  }  
}  
LOG.info("TMP2: ============================")  
try {  
  LOG.debug(catalog.loadNamespaceMetadata(namespace).toString)
} catch {  
  case e: Exception => LOG.info(e.getMessage)  
}
```

### log
```d
2024-03-23 04:33:23.373 INFO IcebergSinkConfiguration$ [] - false
2024-03-23 04:33:23.393 INFO IcebergSinkConfiguration$ [] - Namespace already exists: my_db
2024-03-23 04:33:23.393 INFO IcebergSinkConfiguration$ [] - TMP2: ============================
2024-03-23 04:33:23.396 INFO IcebergSinkConfiguration$ [] - Namespace does not exist: my_db
2024-03-23 04:33:23.467 INFO org.apache.iceberg.BaseMetastoreTableOperations [] - Refreshing table metadata from new version: /warehouse/my_db.db/my_table/metadata/00000-4ee89001-8f63-4648-96bb-606d753e00a7.metadata.json
2024-03-23 04:33:23.761 INFO org.apache.iceberg.BaseMetastoreCatalog [] - Table loaded by catalog: hive.my_db.my_table
```

**Comment by pvary** [comment]
@SML0127: Could you list the catalogs/databases/tables using only the HMSClient?

**Comment by SML0127** [comment]
Thank you @pvary !
I found the cause!

While setting up HMSClient, I found that the hive-metastore lib version in Flink project is the latest version (v3.x).
It works fine after lowering the hive-metastore library version to v2.3.2. (compatibility with our hive)
<img width="1252" alt="image" src="https://github.com/apache/iceberg/assets/13589283/3c4c475e-c4da-4bb2-82e3-4f39d7aa9bb8">

You can complete this issue. 
Thank you so much for your support.

**Comment by pvary** [comment]
@SML0127: Good to hear that your issue has been resolved!
