### ISSUE TITLE
 rewriting manifest can rewrite based on filter?

### ISSUE THREAD

**Issue by chenwyi2** [apache/iceberg#10129]
### Feature Request / Improvement

spark 3.1 iceberg 1.2.1
i always met the below error :
> org.apache.iceberg.exceptions.ValidationException: Manifest is missing: oss://xgimi-data/apps/spark/warehouse/xx.db/xxx/metadata/xx-m2.avro at org.apache.iceberg.BaseRewriteManifests.lambda$validateDeletedManifests$7(BaseRewriteManifests.java:261) at java.util.Optional.ifPresent(Optional.java:159) at 

i think this is concurrent commit, since i have a flink job and a spark job, and i set commit.manifest-merge.enabled=true, so can i rewrite manifest based on filter such as partition, since flink job always new partition, and i can rewrite manifest with old partition in order to decrease concurrent conflicts.

### Query engine

Spark

**Comment by chenwyi2** [comment]
`  private List<ManifestFile> findMatchingManifests() {
    Snapshot currentSnapshot = table.currentSnapshot();

    if (currentSnapshot == null) {
      return ImmutableList.of();
    }
    String partitionFilter =
            PropertyUtil.propertyAsString(options(), PARTITION_FILTER, PARTITION_FILTER_DFAULT);
    if (!partitionFilter.isEmpty()){
      return currentSnapshot.dataManifests(table.io()).stream()
              .filter(manifest -> manifest.partitionSpecId() == spec.specId() && predicate.test(manifest) &&
                      manifest.partitions() != null &&
                      partitionFilter.compareTo(Conversions.fromByteBuffer(
                              Types.StringType.get(),manifest.partitions().get(0).upperBound()))>=0)
              .collect(Collectors.toList());
    }

    return currentSnapshot.dataManifests(table.io()).stream()
        .filter(manifest -> manifest.partitionSpecId() == spec.specId() && predicate.test(manifest))
        .collect(Collectors.toList());
  }`
is that ok to only rewrite manifests whose upperBound is less than PARTITION_FILTER?

**Comment by chenwyi2** [comment]
https://github.com/apache/iceberg/pull/9447
