### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/jdk/CollectionConverters$

### ISSUE THREAD

**Issue by celltobig** [apache/iceberg#10175]
### Apache Iceberg version

1.5.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

use sparkSesson.SQL run  error  
maybe only spark3.3 has org.apache.spark.sql.catalyst.parser.extensions.IcebergSqlExtensionsAstBuilder.toBuffer  ,
spark3.5 has not  ?

<dependency>
            <groupId>org.apache.iceberg</groupId>
            <artifactId>iceberg-spark-runtime-3.5_2.12</artifactId>
            <version>1.5.0</version>
        </dependency>

-- 重写文件
CALL spark_catalog.system.rewrite_data_files(
  table => 'dl_test.t1',
  strategy => 'binpack',
  options => map(
    'rewrite-job-order','bytes-asc',
    'min-input-files','2'
  )
);

 
![image](https://github.com/apache/iceberg/assets/4598224/8db56958-d130-47a9-ac93-3b8ac13b3ce9)

**Comment by celltobig** [comment]
![Uploading image.png…]()

**Comment by nastra** [comment]
@celltobig are you by any chance running Scala 2.13?

**Comment by rshkv** [comment]
Got the same using `iceberg-spark-runtime-3.5_2.12`. Worked around the error by adding a dependency on `org.scala-lang.modules:scala-collection-compat_2.12`.

I'm not seeing any `_2.13` dependencies; only 2.12. `scala-collection-copmpat_2.12` genuinely does not come in as transitive dependency unless declared.

Unsure how you could repro this.

<details>
<summary>Stacktrace</summary>

```
scala/jdk/CollectionConverters$
java.lang.NoClassDefFoundError: scala/jdk/CollectionConverters$
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSqlExtensionsAstBuilder.toBuffer(IcebergSqlExtensionsAstBuilder.scala:68)
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSqlExtensionsAstBuilder.toSeq(IcebergSqlExtensionsAstBuilder.scala:69)
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSqlExtensionsAstBuilder.$anonfun$visitCall$1(IcebergSqlExtensionsAstBuilder.scala:75)
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergParserUtils$.withOrigin(IcebergSqlExtensionsAstBuilder.scala:369)
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSqlExtensionsAstBuilder.visitCall(IcebergSqlExtensionsAstBuilder.scala:74)
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSqlExtensionsAstBuilder.visitCall(IcebergSqlExtensionsAstBuilder.scala:66)
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSqlExtensionsParser$CallContext.accept(IcebergSqlExtensionsParser.java:214)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSqlExtensionsAstBuilder.$anonfun$visitSingleStatement$1(IcebergSqlExtensionsAstBuilder.scala:334)
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergParserUtils$.withOrigin(IcebergSqlExtensionsAstBuilder.scala:369)
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSqlExtensionsAstBuilder.visitSingleStatement(IcebergSqlExtensionsAstBuilder.scala:334)
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSqlExtensionsAstBuilder.visitSingleStatement(IcebergSqlExtensionsAstBuilder.scala:66)
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSqlExtensionsParser$SingleStatementContext.accept(IcebergSqlExtensionsParser.java:153)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSparkSqlExtensionsParser.$anonfun$parsePlan$1(IcebergSparkSqlExtensionsParser.scala:124)
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSparkSqlExtensionsParser.parse(IcebergSparkSqlExtensionsParser.scala:178)
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSparkSqlExtensionsParser.parsePlan(IcebergSparkSqlExtensionsParser.scala:124)
```
</details>

**Comment by Shekharrajak** [comment]
You need to have required dependency 
```
// https://mvnrepository.com/artifact/org.scala-lang.modules/scala-collection-compat
implementation 'org.scala-lang.modules:scala-collection-compat_2.12:2.12.0'
```

**Comment by MasterDDT** [comment]
I am using the correct iceberg runtime:

```
scala> classOf[org.apache.spark.sql.catalyst.parser.extensions.IcebergSparkSqlExtensionsParser].getProtectionDomain
ProtectionDomain  (file:/Users/mitesh/flame/assembly/target/scala-2.12/jars/iceberg-spark-runtime-3.3_2.12-1.8.1.jar
```

The problem here is `scala.jdk.CollectionConverters` does not even exist in Scala 2.12, its called something else. So how does this even compile for 2.12?
https://github.com/apache/iceberg/blob/1.8.x/spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala#L60

**Comment by MasterDDT** [comment]
I also hit this, make sure its newest upgraded scala-collection-compat 2.13+ for scala 2.12
