### ISSUE TITLE
Support for writing Parquet files from the Iceberg Java API without the Hadoop Configuration class

### ISSUE THREAD

**Issue by ms1111** [apache/iceberg#10180]
### Feature Request / Improvement

If the hadoop-common library is not present, trying to write a Parquet file:
```java
DataWriter<Record> dataWriter =
        Parquet.writeData(file)
                .schema(schema)
                .createWriterFunc(GenericParquetWriter::buildWriter)
                .overwrite()
                .withSpec(partitionSpec)
                .build();
```
... will fail with:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
        at org.apache.iceberg.parquet.Parquet$WriteBuilder.<init>(Parquet.java:164)
        at org.apache.iceberg.parquet.Parquet$WriteBuilder.<init>(Parquet.java:143)
        at org.apache.iceberg.parquet.Parquet.write(Parquet.java:129)
        at org.apache.iceberg.parquet.Parquet$DataWriteBuilder.<init>(Parquet.java:646)
        at org.apache.iceberg.parquet.Parquet$DataWriteBuilder.<init>(Parquet.java:637)
        at org.apache.iceberg.parquet.Parquet.writeData(Parquet.java:623)
```

In org.apache.iceberg.parquet.Parquet, an empty Configuration is created:
```java
    private WriteBuilder(OutputFile file) {
      this.file = file;
      if (file instanceof HadoopOutputFile) {
        this.conf = new Configuration(((HadoopOutputFile) file).getConf());
      } else {
        this.conf = new Configuration();
      }
    }
```

ParquetWriter eventually passes this to ParquetIO.file(), which ignores it if the file is not a HadoopOutputFile.

hadoop-common is a heavy dependency with many transitive dependencies, would be nice to avoid it.

Similar to Iceberg Flink issues - #3117 / #4183 

### Query engine

None

**Comment by ysn2233** [comment]
May I ask which Flink version you are using? Under Flink 1.18, I packaged the minimal Hadoop as you suggested and placed it in the /lib directory of the image, but it still seems to throw a NoClassDefFoundError: org.apache.hadoop.hdfs.HdfsConfiguration

**Comment by ms1111** [comment]
@ysn2233 We were using Flink 1.19 or 1.20 at the time, and Iceberg 1.9.x. This may help:

```java
/**
 * Overrides Iceberg's FlinkCatalogFactory to avoid a dependency on HdfsConfiguration,
 * a subclass of Configuration.
 *
 * For Flink to discover this class, an entry is needed in
 * META-INF/services/org.apache.flink.table.factories.Factory.
 */
public class NoHDFSFlinkCatalogFactory extends FlinkCatalogFactory {
    // This is an old, deprecated entrypoint, but it's the one available in Iceberg's FlinkCatalogFactory at the moment
    @Override
    @Deprecated
    public Catalog createCatalog(String name, Map<String, String> properties) {
        return createCatalog(name, properties, new org.apache.hadoop.conf.Configuration());
    }

    // This is the new entrypoint
    @Override
    public Catalog createCatalog(Context context) {
        return createCatalog(context.getName(), context.getOptions());
    }

    @Override
    public String factoryIdentifier() {
        return "iceberg-nohdfs";
    }
}
```

and src/main/resources/META-INF/org.apache.flink.table.factories.Factory:
```
# This is needed so StreamTableEnvironment.createCatalog() can find our catalog factory
your.package.NoHDFSFlinkCatalogFactory
```

To use it:
```java
Catalog catalogFactory = new NoHDFSFlinkCatalogFactory().createCatalog(catalogSettings.getCatalogName(), options);

Map<String, String> options = catalogFactory.requiredContext();
options.put("catalog-impl", "org.apache.iceberg.rest.RESTCatalog");
options.put(...);
Configuration catalogConfig = Configuration.fromMap(options);

// We already have the catalog factory, but Flink wants to find it by type.
// There was a streamTableEnvironment.registerCatalog() method but it was deprecated.
// Have to do it indirectly now.
catalogConfig.set(CommonCatalogOptions.CATALOG_TYPE, catalogFactory.factoryIdentifier());

CatalogDescriptor catalogDescriptor = CatalogDescriptor.of("<catalog name>", catalogConfig);
streamTableEnvironment.createCatalog("<catalog name>", catalogDescriptor);
```

**Comment by ysn2233** [comment]
Thank you very much! I applied your method in our scenario testing, and it works properly after additionally removing the dependencies on woodstox and commons-logging. Others who encounter similar issues can refer to this.
