### ISSUE TITLE
Flaky Test `TestIcebergSourceFailover > testBoundedWithSavepoint`

### ISSUE THREAD

**Issue by manuzhang** [apache/iceberg#10356]
### Apache Iceberg version

main (development)

### Query engine

Flink

### Please describe the bug 🐞

```
 TestIcebergSourceFailover > testBoundedWithSavepoint FAILED
    java.util.concurrent.ExecutionException: org.apache.flink.runtime.checkpoint.CheckpointException: Checkpoint triggering task Source: IcebergSource -> Map -> IcebergStreamWriter (2/2) of job 836d7b1e55afa7658279f5f0003c819f is not being executed at the moment. Aborting checkpoint. Failure reason: Not all required tasks are currently running.
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2005)
        at org.apache.iceberg.flink.source.TestIcebergSourceFailover.testBoundedWithSavepoint(TestIcebergSourceFailover.java:152)

        Caused by:
        org.apache.flink.runtime.checkpoint.CheckpointException: Checkpoint triggering task Source: IcebergSource -> Map -> IcebergStreamWriter (2/2) of job 836d7b1e55afa7658279f5f0003c819f is not being executed at the moment. Aborting checkpoint. Failure reason: Not all required tasks are currently running.
            at app//org.apache.flink.runtime.checkpoint.DefaultCheckpointPlanCalculator.checkTasksStarted(DefaultCheckpointPlanCalculator.java:143)
            at app//org.apache.flink.runtime.checkpoint.DefaultCheckpointPlanCalculator.lambda$calculateCheckpointPlan$1(DefaultCheckpointPlanCalculator.java:105)
            at java.base@11.0.23/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
            at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.lambda$handleRunAsync$4(PekkoRpcActor.java:451)
            at app//org.apache.flink.runtime.concurrent.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68)
            at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleRunAsync(PekkoRpcActor.java:451)
            at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleRpcMessage(PekkoRpcActor.java:218)
            at org.apache.flink.runtime.rpc.pekko.FencedPekkoRpcActor.handleRpcMessage(FencedPekkoRpcActor.java:85)
            at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleMessage(PekkoRpcActor.java:168)
            at org.apache.pekko.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:33)
            at org.apache.pekko.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:29)
            at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
            at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
            at org.apache.pekko.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:29)
            at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
            at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
            at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
            at org.apache.pekko.actor.Actor.aroundReceive(Actor.scala:547)
            at org.apache.pekko.actor.Actor.aroundReceive$(Actor.scala:545)
            at org.apache.pekko.actor.AbstractActor.aroundReceive(AbstractActor.scala:229)
            at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590)
            at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557)
            at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:280)
            at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:241)
            at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253)
            at java.base@11.0.23/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
            at java.base@11.0.23/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
            at java.base@11.0.23/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
            at java.base@11.0.23/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
            at java.base@11.0.23/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by manuzhang** [comment]
Another failure case 

```
TestIcebergSourceFailover > testBoundedWithSavepoint FAILED
    java.util.concurrent.ExecutionException: org.apache.flink.runtime.checkpoint.CheckpointException: Task local checkpoint failure.
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
        at org.apache.iceberg.flink.source.TestIcebergSourceFailover.testBoundedWithSavepoint(TestIcebergSourceFailover.java:152)

        Caused by:
        org.apache.flink.runtime.checkpoint.CheckpointException: Task local checkpoint failure.
            at org.apache.flink.runtime.checkpoint.PendingCheckpoint.abort(PendingCheckpoint.java:545)
            at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.abortPendingCheckpoint(CheckpointCoordinator.java:2147)
            at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.abortPendingCheckpoint(CheckpointCoordinator.java:2134)
            at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.lambda$null$9(CheckpointCoordinator.java:759)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:750)
```

**Comment by amogh-jahagirdar** [comment]
Reopening because we recently hit this on another PR https://github.com/apache/iceberg/actions/runs/10081030094/job/27872164965?pr=10771

**Comment by amogh-jahagirdar** [comment]
Actually maybe it's not backported to Flink 1.17/1.18 I'll double check that

**Comment by pvary** [comment]
Closing this in favour of #10671
