### ISSUE TITLE
Iceberg could support Hive1.1.0?

### ISSUE THREAD

**Issue by davidyuan1223** [apache/iceberg#10437]
### Query engine

spark-3.1.2
kyuubi-1.7.0
iceberg-spark-3.1.2_1.3.1

### Question

config
```
spark.authenticate=false
spark.sql.hive.metastore.version=1.1.0
spark.sql.hive.metastore.jars=path
spark.sql.hive.metastore.jars.path=file:///xxx/hive/lib/*/
spark.yarn.jars=hdfs://xxx/user/spark/share/lib/spark3_jars/*
spark.sql.legacy.createHiveTableByDefault=false
spark.sql.extensions=org.apache.kyuubi.sql.KyuubiSparkSQLExtension,org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.queryExecutionListeners=org.apache.kyuubi.plugin.lineage.SparkOperationLineageQueryExecutionListener
spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.spark_catalog.type=hive
spark.sql.catalog.spark_catalog.uri=thrift://host:port
```
[iceberg create SQL]
```
CREATE TABLE iceber_test (
  id bigint COMMENT 'unique id',
  data string)
USING iceberg;
```

[error info]
```
Caused by: org.apache.thrift.TApplicationException: Invalid method name: 'get_table_req'
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_table_req(ThriftHiveMetastore.java:1567)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_table_req(ThriftHiveMetastore.java:1554)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getTable(HiveMetaStoreClient.java:1350)`



`Caused by: java.lang.RuntimeException: Failed to get table info from metastore default.iceber_test
        at org.apache.iceberg.hive.HiveTableOperations.doRefresh(HiveTableOperations.java:171)
        at org.apache.iceberg.BaseMetastoreTableOperations.refresh(BaseMetastoreTableOperations.java:97)
        at org.apache.iceberg.BaseMetastoreTableOperations.current(BaseMetastoreTableOperations.java:80)
        at org.apache.iceberg.BaseMetastoreCatalog.loadTable(BaseMetastoreCatalog.java:47)
```

I want know how to make the iceberg support hms 1.1.0, so that we can create table based the hms

**Comment by ajantha-bhat** [comment]
Isn't Hive 1.1 is pretty ancient?

> 11 April 2024: EOL for release 1.x line
The Apache Hive Community has voted to declare the 1.x release line as End of Life (EOL). This means no further updates or releases will be made for this series.
We urge all Hive 1.x users to upgrade to the latest versions promptly to benefit from new features and ongoing support.

https://hive.apache.org/general/downloads/

Iceberg 1.1.0 that you are using required hive 2.x as per https://github.com/apache/iceberg/blob/ede085d0f7529f24acd0c81dd0a43f7bb969b763/versions.props#L5

**Comment by davidyuan1223** [comment]
> Isn't Hive 1.1 is pretty ancient?
> 
> > 11 April 2024: EOL for release 1.x line
> > The Apache Hive Community has voted to declare the 1.x release line as End of Life (EOL). This means no further updates or releases will be made for this series.
> > We urge all Hive 1.x users to upgrade to the latest versions promptly to benefit from new features and ongoing support.
> 
> https://hive.apache.org/general/downloads/
> 
> Iceberg 1.1.0 that you are using required hive 2.x as per
> 
> https://github.com/apache/iceberg/blob/ede085d0f7529f24acd0c81dd0a43f7bb969b763/versions.props#L5

yeah, hive1.1.0 is a very old version, but this version is on product environment, so that update the version i cannot decide, thanks for your answer
