### ISSUE TITLE
Flaky test `TestHadoopCommits > testConcurrentFastAppends(File)`

### ISSUE THREAD

**Issue by manuzhang** [apache/iceberg#11047]
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

```
14:26:54 TestHadoopCommits > testConcurrentFastAppends(File) FAILED
14:26:54     org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.apache.iceberg.hadoop.TestHadoopCommits that uses java.util.concurrent.atomic.AtomicInteger, java.util.concurrent.atomic.AtomicIntegerint, intint was not fulfilled within 10 seconds.
14:26:54         at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
14:26:54         at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
14:26:54         at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
14:26:54         at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
14:26:54         at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
14:26:54         at org.apache.iceberg.hadoop.TestHadoopCommits.lambda$testConcurrentFastAppends$3(TestHadoopCommits.java:448)
```

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [X] I cannot contribute a fix for this bug at this time

**Comment by manuzhang** [comment]
Fixed by #11654

**Comment by kevinjqliu** [comment]
Seeing this issue pop up again in CI https://github.com/apache/iceberg/pull/11923#issuecomment-2624791691

I also had trouble with this while verifying the 1.7.2RC0 candidate

**Comment by manuzhang** [comment]
Reopened for recent failure https://github.com/apache/iceberg/actions/runs/13618574381/job/38064821208

```
TestHadoopCommits > testConcurrentFastAppends(File) FAILED
    org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.apache.iceberg.hadoop.TestHadoopCommits that uses java.util.concurrent.atomic.AtomicInteger, java.util.concurrent.atomic.AtomicIntegerint, intint was not fulfilled within 10 seconds.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
        at app//org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
        at app//org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1160)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1129)
        at app//org.apache.iceberg.hadoop.TestHadoopCommits.lambda$testConcurrentFastAppends$3(TestHadoopCommits.java:462)
```

**Comment by kevinjqliu** [comment]
thanks @manuzhang i've been experiencing this when i verify a release, only happens on my m1 mac

**Comment by manuzhang** [comment]
I haven't seen this failure after #12714. Closing the issue.
