### ISSUE TITLE
Reading partitions metadata table for unpartitioned tables in Spark results in a cryptic error message

### ISSUE THREAD

**Issue by shardulm94** [apache/iceberg#1111]
Created an unpartitioned table `test.unpartitioned_table`
```
scala> spark.read.format("iceberg").load("test.unpartitioned_table.partitions").printSchema
java.lang.AssertionError: assertion failed: each serializer expression should contain at least one `BoundReference`
  at scala.Predef$.assert(Predef.scala:170)
  at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$$anonfun$11.apply(ExpressionEncoder.scala:238)
  at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$$anonfun$11.apply(ExpressionEncoder.scala:236)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
  at scala.collection.immutable.List.flatMap(List.scala:344)
  at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.<init>(ExpressionEncoder.scala:236)
  at org.apache.spark.sql.catalyst.encoders.RowEncoder$.apply(RowEncoder.scala:63)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:75)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:196)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:174)
  ... 87 elided
```

I was able to find a Spark Jira https://issues.apache.org/jira/browse/SPARK-20193 which suggests that it is due to Spark not fully supporting empty structs. Perhaps we should consider throwing a better error message when reading partitions metadata table for unpartitioned tables since the partition field will be an empty struct in such a case.

**Comment by RussellSpitzer** [comment]
In TypeToSparkType it may also make sense to either throw an error when an empty Struct in Spark is about to be created (since this will most likely break catalyst) or just replace an empty Struct with a dummy one. Something like

```  
if (fields.size() == 0) {
      sparkFields.add(StructField.apply("EmptyStruct", DataTypes.BinaryType, true, Metadata.empty()));
}
```

I did a quick test and this would clean up the error message but not inform the user that something impossible was tried
