### ISSUE TITLE
TestLocalScan.testFilterWithDateAndTimestamp failing in Europe/London Timezone for ORC

### ISSUE THREAD

**Issue by massdosage** [apache/iceberg#1113]
Steps to reproduce (on Ubuntu Linux):

1. Set timezone to Europe/London (test may fail in other timezones, just noticed it in this one):
`sudo timedatectl set-timezone Europe/London`
2. Run the tests
`./gradlew :iceberg-data:clean  :iceberg-data:test --tests org.apache.iceberg.data.TestLocalScan.testFilterWithDateAndTimestamp[1]`

This fails with output like so:
```
> Task :iceberg-data:test
org.apache.iceberg.data.TestLocalScan > testFilterWithDateAndTimestamp[1] FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.apache.iceberg.data.TestLocalScan.testFilterWithDateAndTimestamp(TestLocalScan.java:486)
1 test completed, 1 failed
> Task :iceberg-data:test FAILED
```
3. Set the timezone to America/Los_Angeles:
`sudo timedatectl set-timezone America/Los_Angeles`
4. Run the tests again:
`./gradlew :iceberg-data:clean  :iceberg-data:test --tests org.apache.iceberg.data.TestLocalScan.testFilterWithDateAndTimestamp[1]`
This succeeds:
`BUILD SUCCESSFUL in 36s`

The Iceberg build should run successfully regardless of the Timezone of the machine it is running on.

**Comment by massdosage** [comment]
Possibly related PR: #983

**Comment by massdosage** [comment]
From some debugging the failure appears to happen when the expected record has a date of "2337-10-05"...

**Comment by chenjunjiedada** [comment]
I also found this issue, see #1116.

**Comment by massdosage** [comment]
This is still failing on master:

TestLocalScan. testFilterWithDateAndTimestamp[1] 
```

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.apache.iceberg.data.TestLocalScan.testFilterWithDateAndTimestamp(TestLocalScan.java:486)
```

And now an additional test is failing:

TestMetricsRowGroupFilterTypes. testEq[20] 

```
java.lang.AssertionError: Should read: value is in the row group: 2018-06-29
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.apache.iceberg.data.TestMetricsRowGroupFilterTypes.testEq(TestMetricsRowGroupFilterTypes.java:284)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by edgarRd** [comment]
Can we close this issue if fixed?

**Comment by massdosage** [comment]
Yes, I merged master into the forks/branches where we saw these issues and the tests now pass.
