### ISSUE TITLE
Unsupported Spark Creating Views Operation for s3_catalog

### ISSUE THREAD

**Issue by liugs0213** [apache/iceberg#11440]
### Query engine

Spark

### Question

**Description:**

I encountered an issue while trying to create a view in an Iceberg catalog using Spark 3.4. The following command:
`CREATE VIEW test_view AS SELECT * FROM dataset_update_test;`
results in the following error:
`java.lang.UnsupportedOperationException: Creating a view is not supported by catalog: s3_catalog`
![image](https://github.com/user-attachments/assets/f587451a-c914-4b59-b451-f5b238c550e0)

**Environment**

- Spark Version: 3.4

- Iceberg Version: iceberg-spark-runtime-3.4_2.12-1.6.1.jar

Expected Behavior: I expected to create a view based on an Iceberg table.

**Comment by nastra** [comment]
@liugs0213 that most likely means that your catalog isn't an actual `ViewCatalog` (it doesn't implement org.apache.iceberg.catalog.ViewCatalog). Can you share your catalog configuration please?

**Comment by liugs0213** [comment]
> @liugs0213 that most likely means that your catalog isn't an actual `ViewCatalog` (it doesn't implement org.apache.iceberg.catalog.ViewCatalog). Can you share your catalog configuration please?

<img width="1177" alt="image" src="https://github.com/user-attachments/assets/9382bd5d-5840-480b-ac4a-591064364c40">

`spark-sql   --jars iceberg-spark-runtime-3.4_2.12-1.6.1.jar,/opt/jars/aws-java-sdk-bundle-1.11.271.jar,/opt/jars/url-connection-client-2.15.40.jar,/opt/jars/hadoop-aws-3.3.1.jar   
--conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions 
  --conf spark.sql.catalog.s3_catalog=org.apache.iceberg.spark.SparkCatalog   
  --conf spark.sql.catalog.s3_catalog.type=hadoop   
  --conf spark.hadoop.fs.s3a.access.key=*****  
  --conf spark.hadoop.fs.s3a.secret.key=****  
  --conf spark.hadoop.fs.s3a.endpoint=****
  --conf spark.sql.catalog.s3_catalog.warehouse=s3a://dataset-update-test/warehouse/`

**Comment by liugs0213** [comment]
> @liugs0213 that most likely means that your catalog isn't an actual `ViewCatalog` (it doesn't implement org.apache.iceberg.catalog.ViewCatalog). Can you share your catalog configuration please?

![image](https://github.com/user-attachments/assets/d2c53306-d6d9-4996-9336-6ceb9cafd2fa)
I've tested creating views in different catalogs, and I've found that creating Hive views is successful. However, when attempting to create views in the s3_catalog, I encounter an error indicating that it is not supported.

**Comment by SNgari** [comment]
@nastra which s3_catalog types support iceberg views?

**Comment by nastra** [comment]
> [@nastra](https://github.com/nastra) which s3_catalog types support iceberg views?

that would be rest/hive/nessie/jdbc

**Comment by SNgari** [comment]
I found a workaround that doesn't need an overhaul of current catalog settings: 

Work with the default catalog `spark_catalog`  and its default schema `default` for views. eg:

```
CREATE VIEW spark_catalog.default.view_name AS
SELECT ...
```

You'll need to include `spark_catalog.default` before the view name each time you need to access the view, but it's not a big inconvenience.

**Comment by jeesou** [comment]
Hey @nastra @SNgari is this issue still there
because I am on iceberg 1.10.0 release

and i am facing issues with views as well
my configs :

```
spark = SparkSession\
        .builder\
        .appName("SparkDataCreation")\
        .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")\
        .config("spark.sql.catalog.cat_iceberg", "org.apache.iceberg.spark.SparkCatalog")\
        .config("spark.sql.catalog.cat_iceberg.type", "hive")\
        .config("spark.sql.catalog.cat_iceberg.warehouse", "s3a://dev-cat")
        .enableHiveSupport()\
        .getOrCreate()
```

the queries I am running

```
spark.sql(f"USE cat_iceberg.mydb").show()

spark.sql(f"CREATE VIEW iceberg_view AS SELECT * FROM spark_iceberg_table").show()

spark.sql(f"SHOW VIEWS FROM cat_iceberg.mydb").show()

spark.sql(f"DROP VIEW IF EXISTS cat_iceberg.mydb.iceberg_view_new")
```

I cannot list any view created its coming under tables

```
show views ->
+---------+--------+-----------+
|namespace|viewName|isTemporary|
+---------+--------+-----------+
+---------+--------+-----------+

show tables -> 
+---------+--------------------+-----------+
|namespace|           tableName|isTemporary|
+---------+--------------------+-----------+
|     mydb|        iceberg_view|      false|
|     mydb| spark_iceberg_table|      false|
|     mydb|       iceberg_view1|      false|
+---------+--------------------+-----------+
```

Trying to drop the view gives error : 

```
Py4JJavaError: An error occurred while calling o1648.sql.
: org.apache.iceberg.exceptions.NoSuchViewException: View does not exist: cat_iceberg.mydb.iceberg_view
	at org.apache.iceberg.hive.HiveOperationsBase.validateIcebergTableNotLoadedAsIcebergView(HiveOperationsBase.java:132)
	at org.apache.iceberg.hive.HiveViewOperations.doRefresh(HiveViewOperations.java:95)
	at org.apache.iceberg.view.BaseViewOperations.refresh(BaseViewOperations.java:89)
	at org.apache.iceberg.view.BaseViewOperations.current(BaseViewOperations.java:79)
	at org.apache.iceberg.hive.HiveCatalog.dropView(HiveCatalog.java:279)
	at org.apache.iceberg.spark.SparkCatalog.dropView(SparkCatalog.java:705)
	at org.apache.spark.sql.execution.datasources.v2.DropV2ViewExec.run(DropV2ViewExec.scala:37)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:220)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:100)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:638)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:629)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:659)
	at jdk.internal.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:854)
```

An alter query like

```
spark.sql(f"""
        ALTER VIEW cat_iceberg.mydb.iceberg_view
        RENAME TO cat_iceberg.mydb.iceberg_view_new
    """).show()
```

gives error

```
26/03/26 08:20:34 WARN Tasks: Retrying task after failure: sleepTimeMs=100 Cannot parse missing int: last-column-id
java.lang.IllegalArgumentException: Cannot parse missing int: last-column-id
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
	at org.apache.iceberg.util.JsonUtil.getInt(JsonUtil.java:117)
	at org.apache.iceberg.TableMetadataParser.fromJson(TableMetadataParser.java:365)
	at org.apache.iceberg.TableMetadataParser.fromJson(TableMetadataParser.java:339)
	at org.apache.iceberg.TableMetadataParser.read(TableMetadataParser.java:309)
	at org.apache.iceberg.TableMetadataParser.read(TableMetadataParser.java:294)
	at org.apache.iceberg.BaseMetastoreTableOperations.lambda$refreshFromMetadataLocation$0(BaseMetastoreTableOperations.java:180)
	at org.apache.iceberg.BaseMetastoreTableOperations.lambda$refreshFromMetadataLocation$1(BaseMetastoreTableOperations.java:199)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
	at org.apache.iceberg.BaseMetastoreTableOperations.refreshFromMetadataLocation(BaseMetastoreTableOperations.java:199)
	at org.apache.iceberg.BaseMetastoreTableOperations.refreshFromMetadataLocation(BaseMetastoreTableOperations.java:176)
	at org.apache.iceberg.BaseMetastoreTableOperations.refreshFromMetadataLocation(BaseMetastoreTableOperations.java:171)
	at org.apache.iceberg.hive.HiveTableOperations.doRefresh(HiveTableOperations.java:131)
	at org.apache.iceberg.BaseMetastoreTableOperations.refresh(BaseMetastoreTableOperations.java:88)
	at org.apache.iceberg.BaseMetastoreTableOperations.current(BaseMetastoreTableOperations.java:71)
	at org.apache.iceberg.BaseMetastoreCatalog.loadTable(BaseMetastoreCatalog.java:49)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2406)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1924)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2404)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at org.apache.iceberg.CachingCatalog.loadTable(CachingCatalog.java:147)
	at org.apache.iceberg.spark.SparkCatalog.load(SparkCatalog.java:846)
	at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:170)
	at org.apache.spark.sql.connector.catalog.CatalogV2Util$.getTable(CatalogV2Util.scala:363)
	at org.apache.spark.sql.connector.catalog.CatalogV2Util$.loadTable(CatalogV2Util.scala:337)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.$anonfun$lookupTableOrView$2(Analyzer.scala:1228)
	at scala.Option.orElse(Option.scala:447)
```

Do you have any idea on this?
