### ISSUE TITLE
Error when creating table 'is not a directory or unable to create one'

### ISSUE THREAD

**Issue by allenfan2** [apache/iceberg#1163]
So I'm just following the [Getting Started](https://iceberg.apache.org/getting-started/)

All of this is being tested in spark-shell 2.3.0 with the iceberg-spark-runtime-0.8.0.jar

And when I run the step:
`val table = catalog.createTable(name, schema)`

This error occurs

```scala> val iceberg_table = catalog.createTable(name, schema)
java.lang.RuntimeException: Metastore operation failed for iceberg_test.test_table
  at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:206)
  at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:103)
  at org.apache.iceberg.BaseMetastoreCatalog.createTable(BaseMetastoreCatalog.java:70)
  at org.apache.iceberg.catalog.Catalog.createTable(Catalog.java:109)
  ... 49 elided
Caused by: org.apache.hadoop.hive.metastore.api.MetaException: file:/home/username/iceberg-test/spark-warehouse/iceberg_test.db/test_table is not a directory or unable to create one
  at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result$create_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:29983)
  at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result$create_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:29951)
  at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result.read(ThriftHiveMetastore.java:29877)
  at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
  at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_table_with_environment_context(ThriftHiveMetastore.java:1075)
  at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_table_with_environment_context(ThriftHiveMetastore.java:1061)
  at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.create_table_with_environment_context(HiveMetaStoreClient.java:2050)
  at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:669)
  at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:657)
  at org.apache.iceberg.hive.HiveTableOperations.lambda$doCommit$3(HiveTableOperations.java:191)
  at org.apache.iceberg.hive.ClientPool.run(ClientPool.java:54)
  at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:190)
  ... 52 more
```

Thing is I launched spark-shell while i was in `/home/username/iceberg-test` and it seems that it automatically created 
`spark-warehouse/iceberg_test.db/test_table` while running the code within it and yet its saying its not a directory or can't create one. Is this because its trying to look for it in HDFS rather than the UNIX FS?

```tree -d spark-warehouse
spark-warehouse
└── iceberg_test.db
    └── test_table
        └── metadata
```

**Comment by rdblue** [comment]
What Hive Metastore are you using? The error is that HMS couldn't create the path, so it is probably attempting to create the path locally because the table URI is `file:/home/...`.

**Comment by Niliria** [comment]
So I'm just following the [Getting Started](https://iceberg.apache.org/getting-started/)
Apache-Hive-2.1.0
iceberg-hive-runtime-0.12.1.jar
Metastore of Hive is deployed on the local Mysql server

When I perform

```
SET iceberg.engine.hive.enabled=true;
CREATE DATABASE IF NOT EXISTS iceberg_db;
ADD JAR /opt/software/hive/lib/iceberg-hive-runtime-0.12.1.jar;
CREATE TABLE iceberg_db.test_2 (
  id bigint,
  name string
)
STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
;
```
Job exception：

```
2022-05-10T16:30:54,595 INFO  [HiveServer2-Background-Pool: Thread-15666]: ql.Driver (:()) - Executing command(queryId=root_20220510163054_4db7c534-2f5d-47db-b515-618f64aa0ecc): CREATE TABLE iceberg_db.test_3 (
  id bigint,
  name string
)
STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
2022-05-10T16:30:54,595 INFO  [HiveServer2-Background-Pool: Thread-15666]: ql.Driver (:()) - Starting task [Stage-0:DDL] in serial mode
2022-05-10T16:30:54,595 INFO  [HiveServer2-Background-Pool: Thread-15666]: plan.CreateTableDesc (:()) - Use StorageHandler-supplied org.apache.iceberg.mr.hive.HiveIcebergSerDe for table test_3
2022-05-10T16:30:54,596 INFO  [HiveServer2-Background-Pool: Thread-15666]: exec.DDLTask (:()) - creating table iceberg_db.test_3 on null
2022-05-10T16:30:54,641 WARN  [HiveServer2-Background-Pool: Thread-15666]: conf.HiveConf (HiveConf.java:initialize(3683)) - HiveConf of name hive.metastore.event.db.notification.api.auth does not exist
2022-05-10T16:30:54,641 WARN  [HiveServer2-Background-Pool: Thread-15666]: conf.HiveConf (HiveConf.java:initialize(3683)) - HiveConf of name hive.internal.ss.authz.settings.applied.marker does not exist
2022-05-10T16:30:54,649 INFO  [ForkJoinPool.commonPool-worker-0]: hive.metastore (:()) - Closed a connection to metastore, current connections: 8
2022-05-10T16:30:54,658 INFO  [HiveServer2-Background-Pool: Thread-15666]: hive.metastore (:()) - Trying to connect to metastore with URI thrift://master:9083
2022-05-10T16:30:54,659 INFO  [HiveServer2-Background-Pool: Thread-15666]: hive.metastore (:()) - Opened a connection to metastore, current connections: 9
2022-05-10T16:30:54,661 INFO  [HiveServer2-Background-Pool: Thread-15666]: hive.metastore (:()) - Connected to metastore.
2022-05-10T16:30:54,666 INFO  [HiveServer2-Background-Pool: Thread-15666]: hive.HiveIcebergSerDe (:()) - Using hive schema {"type":"struct","schema-id":0,"fields":[{"id":0,"name":"id","required":false,"type":"long"},{"id":1,"name":"name","required":false,"type":"string"}]}
2022-05-10T16:30:54,667 INFO  [HiveServer2-Background-Pool: Thread-15666]: hive.HiveIcebergSerDe (:()) - Using hive schema {"type":"struct","schema-id":0,"fields":[{"id":0,"name":"id","required":false,"type":"long"},{"id":1,"name":"name","required":false,"type":"string"}]}
2022-05-10T16:30:54,819 WARN  [HiveServer2-Background-Pool: Thread-15666]: metastore.RetryingMetaStoreClient (:()) - MetaStoreClient lost connection. Attempting to reconnect.
org.apache.thrift.transport.TTransportException
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_lock(ThriftHiveMetastore.java:4549)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.lock(ThriftHiveMetastore.java:4536)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.lock(HiveMetaStoreClient.java:2104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:150)
        at com.sun.proxy.$Proxy22.lock(Unknown Source)
        at org.apache.iceberg.hive.HiveTableOperations.lambda$acquireLock$7(HiveTableOperations.java:430)
        at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:58)
        at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:51)
        at org.apache.iceberg.hive.CachedClientPool.run(CachedClientPool.java:76)
        at org.apache.iceberg.hive.HiveTableOperations.acquireLock(HiveTableOperations.java:430)
        at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:226)
        at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:127)
        at org.apache.iceberg.BaseMetastoreCatalog$BaseMetastoreCatalogTableBuilder.create(BaseMetastoreCatalog.java:165)
        at org.apache.iceberg.catalog.Catalog.createTable(Catalog.java:78)
        at org.apache.iceberg.mr.Catalogs.createTable(Catalogs.java:165)
        at org.apache.iceberg.mr.hive.HiveIcebergMetaHook.commitCreateTable(HiveIcebergMetaHook.java:147)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:738)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:724)
        at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:154)
        at com.sun.proxy.$Proxy22.createTable(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient$SynchronizedHandler.invoke(HiveMetaStoreClient.java:2254)
        at com.sun.proxy.$Proxy22.createTable(Unknown Source)
        at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:830)
        at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:845)
        at org.apache.hadoop.hive.ql.exec.DDLTask.createTable(DDLTask.java:3979)
        at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:333)
        at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:197)
        at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:100)
        at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1858)
        at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1562)
        at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1313)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1084)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1077)
        at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:235)
        at org.apache.hive.service.cli.operation.SQLOperation.access$300(SQLOperation.java:90)
        at org.apache.hive.service.cli.operation.SQLOperation$2$1.run(SQLOperation.java:299)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hive.service.cli.operation.SQLOperation$2.run(SQLOperation.java:312)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
2022-05-10T16:30:55,819 INFO  [HiveServer2-Background-Pool: Thread-15666]: hive.metastore (:()) - Closed a connection to metastore, current connections: 8
2022-05-10T16:30:55,819 INFO  [HiveServer2-Background-Pool: Thread-15666]: hive.metastore (:()) - Trying to connect to metastore with URI thrift://master:9083
2022-05-10T16:30:55,819 INFO  [HiveServer2-Background-Pool: Thread-15666]: hive.metastore (:()) - Opened a connection to metastore, current connections: 9
2022-05-10T16:30:55,820 INFO  [HiveServer2-Background-Pool: Thread-15666]: hive.metastore (:()) - Connected to metastore.
2022-05-10T16:30:55,825 ERROR [HiveServer2-Background-Pool: Thread-15666]: exec.DDLTask (:()) - org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Metastore operation failed for iceberg_db.test_3
        at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:840)
        at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:845)
        at org.apache.hadoop.hive.ql.exec.DDLTask.createTable(DDLTask.java:3979)
        at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:333)
        at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:197)
        at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:100)
        at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1858)
        at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1562)
        at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1313)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1084)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1077)
        at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:235)
        at org.apache.hive.service.cli.operation.SQLOperation.access$300(SQLOperation.java:90)
        at org.apache.hive.service.cli.operation.SQLOperation$2$1.run(SQLOperation.java:299)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hive.service.cli.operation.SQLOperation$2.run(SQLOperation.java:312)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: Metastore operation failed for iceberg_db.test_3
        at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:297)
        at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:127)
        at org.apache.iceberg.BaseMetastoreCatalog$BaseMetastoreCatalogTableBuilder.create(BaseMetastoreCatalog.java:165)
        at org.apache.iceberg.catalog.Catalog.createTable(Catalog.java:78)
        at org.apache.iceberg.mr.Catalogs.createTable(Catalogs.java:165)
        at org.apache.iceberg.mr.hive.HiveIcebergMetaHook.commitCreateTable(HiveIcebergMetaHook.java:147)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:738)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:724)
        at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:154)
        at com.sun.proxy.$Proxy22.createTable(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient$SynchronizedHandler.invoke(HiveMetaStoreClient.java:2254)
        at com.sun.proxy.$Proxy22.createTable(Unknown Source)
        at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:830)
        ... 22 more
Caused by: org.apache.thrift.transport.TTransportException
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_lock(ThriftHiveMetastore.java:4549)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.lock(ThriftHiveMetastore.java:4536)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.lock(HiveMetaStoreClient.java:2104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:150)
        at com.sun.proxy.$Proxy22.lock(Unknown Source)
        at org.apache.iceberg.hive.HiveTableOperations.lambda$acquireLock$7(HiveTableOperations.java:430)
        at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:58)
        at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:51)
        at org.apache.iceberg.hive.CachedClientPool.run(CachedClientPool.java:76)
        at org.apache.iceberg.hive.HiveTableOperations.acquireLock(HiveTableOperations.java:430)
        at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:226)
        ... 40 more

2022-05-10T16:30:55,825 ERROR [HiveServer2-Background-Pool: Thread-15666]: ql.Driver (:()) - FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. java.lang.RuntimeException: Metastore operation failed for iceberg_db.test_3
2022-05-10T16:30:55,825 INFO  [HiveServer2-Background-Pool: Thread-15666]: ql.Driver (:()) - Completed executing command(queryId=root_20220510163054_4db7c534-2f5d-47db-b515-618f64aa0ecc); Time taken: 1.23 seconds
2022-05-10T16:30:55,825 ERROR [HiveServer2-Background-Pool: Thread-15666]: operation.Operation (:()) - Error running hive query: 
org.apache.hive.service.cli.HiveSQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. java.lang.RuntimeException: Metastore operation failed for iceberg_db.test_3
        at org.apache.hive.service.cli.operation.Operation.toSQLException(Operation.java:387)
        at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:237)
        at org.apache.hive.service.cli.operation.SQLOperation.access$300(SQLOperation.java:90)
        at org.apache.hive.service.cli.operation.SQLOperation$2$1.run(SQLOperation.java:299)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hive.service.cli.operation.SQLOperation$2.run(SQLOperation.java:312)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Metastore operation failed for iceberg_db.test_3
        at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:840)
        at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:845)
        at org.apache.hadoop.hive.ql.exec.DDLTask.createTable(DDLTask.java:3979)
        at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:333)
        at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:197)
        at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:100)
        at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1858)
        at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1562)
        at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1313)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1084)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1077)
        at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:235)
        ... 11 more
Caused by: java.lang.RuntimeException: Metastore operation failed for iceberg_db.test_3
        at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:297)
        at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:127)
        at org.apache.iceberg.BaseMetastoreCatalog$BaseMetastoreCatalogTableBuilder.create(BaseMetastoreCatalog.java:165)
        at org.apache.iceberg.catalog.Catalog.createTable(Catalog.java:78)
        at org.apache.iceberg.mr.Catalogs.createTable(Catalogs.java:165)
        at org.apache.iceberg.mr.hive.HiveIcebergMetaHook.commitCreateTable(HiveIcebergMetaHook.java:147)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:738)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:724)
        at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:154)
        at com.sun.proxy.$Proxy22.createTable(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient$SynchronizedHandler.invoke(HiveMetaStoreClient.java:2254)
        at com.sun.proxy.$Proxy22.createTable(Unknown Source)
        at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:830)
        ... 22 more
Caused by: org.apache.thrift.transport.TTransportException
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_lock(ThriftHiveMetastore.java:4549)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.lock(ThriftHiveMetastore.java:4536)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.lock(HiveMetaStoreClient.java:2104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:150)
        at com.sun.proxy.$Proxy22.lock(Unknown Source)
        at org.apache.iceberg.hive.HiveTableOperations.lambda$acquireLock$7(HiveTableOperations.java:430)
        at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:58)
        at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:51)
        at org.apache.iceberg.hive.CachedClientPool.run(CachedClientPool.java:76)
        at org.apache.iceberg.hive.HiveTableOperations.acquireLock(HiveTableOperations.java:430)
        at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:226)
        ... 40 more

```
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/39268464/167585604-cdedb124-cafc-46d2-a65e-7ce5da534442.png">
The metadata folder is created on HDFS；
