### ISSUE TITLE
How an application can communicate with the Iceberg REST catalog like Dremio Arctic (Nessie), Snowflake’s Polaris , Gravitino

### ISSUE THREAD

**Issue by anusshetty** [apache/iceberg#11655]
### Query engine

We are using SPARK engine.

### Question

Hi Team,

How can I access the Iceberg REST catalog like Dremio Arctic (Nessie), Snowflake’s Polaris , Gravitino from my application .

Can I use the SPARK SQL APIs to fetch metadata and  Read/Write data to REST catalog or should I use only REST APIs to interact with REST catalog.

Any help would be appreciated.

Regards,
Anush

**Comment by ajantha-bhat** [comment]
Since you are using spark engine, spark session can be configured to use Iceberg catalogs. 
Just make sure catalog type is `rest`. 
https://iceberg.apache.org/docs/nightly/spark-configuration/#catalogs

Please go through config examples in each vendors page. 
For example
https://projectnessie.org/guides/try-nessie/#getting-started-with-nessie-and-iceberg-rest

polaris:
https://polaris.apache.org/in-dev/unreleased/quickstart/#connecting-with-spark

**Comment by anusshetty** [comment]
@ajantha-bhat Thank you for the quick help.

I'm trying to setup a polaris service locally by following the https://polaris.apache.org/in-dev/unreleased/quickstart/ page.

**While installing the docker image I could see following exception :

:~/polaris$ docker-compose -f docker-compose.yml up --build**
WARNING: The GOOGLE_APPLICATION_CREDENTIALS variable is not set. Defaulting to a blank string.
WARNING: The AZURE_TENANT_ID variable is not set. Defaulting to a blank string.
WARNING: The AZURE_CLIENT_ID variable is not set. Defaulting to a blank string.
WARNING: The AZURE_CLIENT_SECRET variable is not set. Defaulting to a blank string.
WARNING: The AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
WARNING: The AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
WARNING: The AWS_TEST_ENABLED variable is not set. Defaulting to a blank string.
WARNING: The AWS_STORAGE_BUCKET variable is not set. Defaulting to a blank string.
WARNING: The AWS_ROLE_ARN variable is not set. Defaulting to a blank string.
WARNING: The AWS_TEST_BASE variable is not set. Defaulting to a blank string.
WARNING: The GCS_TEST_ENABLED variable is not set. Defaulting to a blank string.
WARNING: The GCS_TEST_BASE variable is not set. Defaulting to a blank string.
WARNING: The AZURE_TEST_ENABLED variable is not set. Defaulting to a blank string.
WARNING: The AZURE_DFS_TEST_BASE variable is not set. Defaulting to a blank string.
WARNING: The AZURE_BLOB_TEST_BASE variable is not set. Defaulting to a blank string.
WARNING: The AWS_CROSS_REGION_TEST_ENABLED variable is not set. Defaulting to a blank string.
WARNING: The AWS_CROSS_REGION_BUCKET variable is not set. Defaulting to a blank string.
WARNING: The AWS_ROLE_FOR_CROSS_REGION_BUCKET variable is not set. Defaulting to a blank string.
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Building polaris
[+] Building 6.0s (12/15)
 => [internal] load build definition from Dockerfile                                                                                                     0.1s
 => => transferring dockerfile: 32B                                                                                                                      0.1s
 => [internal] load .dockerignore                                                                                                                        0.1s
 => => transferring context: 35B                                                                                                                         0.1s
 => [internal] load metadata for registry.access.redhat.com/ubi9/openjdk-21-runtime:1.20-2.1729089285                                                    1.7s
 => [internal] load metadata for registry.access.redhat.com/ubi9/openjdk-21:1.20-2.1726695192                                                            1.1s
 => [internal] load build context                                                                                                                        2.7s
 => => transferring context: 1.13MB                                                                                                                      2.7s
 => [build 1/5] FROM registry.access.redhat.com/ubi9/openjdk-21:1.20-2.1726695192@sha256:7666303e9b1463b3a42fd43b18367be1a932b4c9aac4684a011332ae1f2840  0.0s
 => [stage-1 1/5] FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.20-2.1729089285@sha256:fab89c4d8c652d881207027b27ee519e60fc210784160af66327  0.0s
 => CACHED [stage-1 2/5] WORKDIR /app                                                                                                                    0.0s
 => CACHED [build 2/5] COPY --chown=default:root . /app                                                                                                  0.0s
 => CACHED [build 3/5] WORKDIR /app                                                                                                                      0.0s
 => CACHED [build 4/5] RUN rm -rf build                                                                                                                  0.0s
 => ERROR [build 5/5] RUN ./gradlew --no-daemon --info ${ECLIPSELINK_DEPS+"-PeclipseLinkDeps=$ECLIPSELINK_DEPS"} -PeclipseLink=$ECLIPSELINK clean prepa  1.3s
------
 > [build 5/5] RUN ./gradlew --no-daemon --info ${ECLIPSELINK_DEPS+"-PeclipseLinkDeps=$ECLIPSELINK_DEPS"} -PeclipseLink=$ECLIPSELINK clean prepareDockerDist:
#12 1.139 [0.003s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#12 1.144 [0.008s][error  ][gc,task  ] Failed to create worker thread
------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c ./gradlew --no-daemon --info ${ECLIPSELINK_DEPS+"-PeclipseLinkDeps=$ECLIPSELINK_DEPS"} -PeclipseLink=$ECLIPSELINK clean prepareDockerDist]: exit code: 1
ERROR: Service 'polaris' failed to build


**Building Polaris locally I tried : cd ~/polaris
./gradlew runApp**

I'm hitting the following exception 

**Traceback (most recent call last):
  File "/home/devbld/polaris/polaris-venv/lib/python3.13/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
        (self._dns_host, self.port), self.timeout, **extra_kw
    )
  File "/home/devbld/polaris/polaris-venv/lib/python3.13/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/devbld/polaris/polaris-venv/lib/python3.13/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devbld/polaris/polaris-venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
        conn,
    ...<5 lines>...
        chunked=chunked,
    )
  File "/home/devbld/polaris/polaris-venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devbld/polaris/polaris-venv/lib/python3.13/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.13/lib/python3.13/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.13/lib/python3.13/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.13/lib/python3.13/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.13/lib/python3.13/http/client.py", line 1091, in _send_output
    self.send(msg)
    ~~~~~~~~~^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.13/lib/python3.13/http/client.py", line 1035, in send
    self.connect()
    ~~~~~~~~~~~~^^
  File "/home/devbld/polaris/polaris-venv/lib/python3.13/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/devbld/polaris/polaris-venv/lib/python3.13/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
        self, "Failed to establish a new connection: %s" % e
    )
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f44d7d25f30>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devbld/polaris/regtests/client/python/cli/polaris_cli.py", line 144, in <module>
    PolarisCli.execute()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/devbld/polaris/regtests/client/python/cli/polaris_cli.py", line 50, in execute
    client_builder = PolarisCli._get_client_builder(options)
  File "/home/devbld/polaris/regtests/client/python/cli/polaris_cli.py", line 136, in _get_client_builder
    token = PolarisCli._get_token(builder(), polaris_catalog_url, client_id, client_secret)
  File "/home/devbld/polaris/regtests/client/python/cli/polaris_cli.py", line 76, in _get_token
    response = api_client.call_api(
               ~~~~~~~~~~~~~~~~~~~^
        'POST',
        ^^^^^^^
    ...<7 lines>...
        }
        ^
    ).response.data
    ^
  File "/home/devbld/polaris/regtests/client/python/polaris/management/api_client.py", line 291, in call_api
    response_data = self.rest_client.request(
        method, url,
    ...<2 lines>...
        _request_timeout=_request_timeout
    )
  File "/home/devbld/polaris/regtests/client/python/polaris/management/rest.py", line 209, in request
    r = self.pool_manager.request(
        method,
    ...<5 lines>...
        preload_content=False
    )
  File "/home/devbld/polaris/polaris-venv/lib/python3.13/site-packages/urllib3/request.py", line 81, in request
    return self.request_encode_body(
           ~~~~~~~~~~~~~~~~~~~~~~~~^
        method, url, fields=fields, headers=headers, **urlopen_kw
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/devbld/polaris/polaris-venv/lib/python3.13/site-packages/urllib3/request.py", line 173, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devbld/polaris/polaris-venv/lib/python3.13/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/devbld/polaris/polaris-venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 830, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<11 lines>...
        **response_kw
        ^^^^^^^^^^^^^
    )
    ^
  File "/home/devbld/polaris/polaris-venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 830, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<11 lines>...
        **response_kw
        ^^^^^^^^^^^^^
    )
    ^
  File "/home/devbld/polaris/polaris-venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 830, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<11 lines>...
        **response_kw
        ^^^^^^^^^^^^^
    )
    ^
  File "/home/devbld/polaris/polaris-venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/home/devbld/polaris/polaris-venv/lib/python3.13/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8181): Max retries exceeded with url: /api/catalog/v1/oauth/tokens (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f44d7d25f30>: Failed to establish a new connection: [Errno 111] Connection refused'))**

Could you please help me to resolve these exceptions

Regards
Anush

**Comment by ajantha-bhat** [comment]
For polaris related question, you can ask in polaris github or polaris zulip chat.

**Comment by anusshetty** [comment]
@ajantha-bhat Thank you for the clarification.

I have posted the same question in polaris zulip chat.

Regards
Anush
