### ISSUE TITLE
Forbidden Exception creating Polaris Rest catalog with Flink 1.20

### ISSUE THREAD

**Issue by David-N-Perkins** [apache/iceberg#11836]
### Apache Iceberg version

1.7.1 (latest release)

### Query engine

Flink

### Please describe the bug 🐞

We attempted to upgrade Iceberg `1.6.1` and Flink `1.18.1` to Iceberg `1.7.1` and Flink `1.20.0`. When creating the Iceberg catalog in Flink SQL, we now encounter this exception.
```
Could not execute SQL statement. Reason:
org.apache.iceberg.exceptions.ForbiddenException: Forbidden:
```
Here is the create catalog statement.
```
CREATE CATALOG c_iceberg WITH (
  'type'='iceberg',
  'catalog-type'='rest',
  'uri'='http://polaris:8181/api/catalog',
  'credential'='xxx:xxx',
  'warehouse'='azure-catalog',
  'scope'='PRINCIPAL_ROLE:ALL'
);
```

I'm not positive, but believe the issue is with Iceberg and not Polaris since we didn't change the Polaris version and it still works fine with the older version. 

Here are the logs from Flink.
```
2024-12-19 21:09:16,010 WARN  org.apache.iceberg.rest.RESTSessionCatalog                   [] - Iceberg REST client is m
issing the OAuth2 server URI configuration and defaults to http://polaris:8181/api/catalogv1/oauth/tokens. This automati
c fallback will be removed in a future Iceberg release.It is recommended to configure the OAuth2 endpoint using the 'oau
th2-server-uri' property to be prepared. This warning will disappear if the OAuth2 endpoint is explicitly configured. Se
e https://github.com/apache/iceberg/issues/10537
2024-12-19 21:09:16,017 WARN  org.apache.iceberg.rest.ErrorHandlers                        [] - Unable to parse error re
sponse
java.io.UncheckedIOException: org.apache.iceberg.shaded.com.fasterxml.jackson.databind.exc.MismatchedInputException: No
content to map due to end-of-input
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1]
        at org.apache.iceberg.util.JsonUtil.parse(JsonUtil.java:101) ~[iceberg-flink-runtime-1.20-1.7.1.jar:?]
        at org.apache.iceberg.rest.responses.ErrorResponseParser.fromJson(ErrorResponseParser.java:71) ~[iceberg-flink-r
untime-1.20-1.7.1.jar:?]
        at org.apache.iceberg.rest.ErrorHandlers$DefaultErrorHandler.parseResponse(ErrorHandlers.java:194) ~[iceberg-fli
nk-runtime-1.20-1.7.1.jar:?]
        at org.apache.iceberg.rest.HTTPClient.throwFailure(HTTPClient.java:181) ~[iceberg-flink-runtime-1.20-1.7.1.jar:?
]
        at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:323) ~[iceberg-flink-runtime-1.20-1.7.1.jar:?]
        at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:262) ~[iceberg-flink-runtime-1.20-1.7.1.jar:?]
        at org.apache.iceberg.rest.HTTPClient.get(HTTPClient.java:358) ~[iceberg-flink-runtime-1.20-1.7.1.jar:?]
        at org.apache.iceberg.rest.RESTSessionCatalog.fetchConfig(RESTSessionCatalog.java:1045) ~[iceberg-flink-runtime-
1.20-1.7.1.jar:?]
        at org.apache.iceberg.rest.RESTSessionCatalog.initialize(RESTSessionCatalog.java:251) ~[iceberg-flink-runtime-1.
20-1.7.1.jar:?]
        at org.apache.iceberg.rest.RESTCatalog.initialize(RESTCatalog.java:78) ~[iceberg-flink-runtime-1.20-1.7.1.jar:?]
        at org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:274) ~[iceberg-flink-runtime-1.20-1.7.1.jar:?]
        at org.apache.iceberg.flink.CatalogLoader$RESTCatalogLoader.loadCatalog(CatalogLoader.java:163) ~[iceberg-flink-
runtime-1.20-1.7.1.jar:?]
        at org.apache.iceberg.flink.FlinkCatalog.<init>(FlinkCatalog.java:114) ~[iceberg-flink-runtime-1.20-1.7.1.jar:?]
        at org.apache.iceberg.flink.FlinkCatalogFactory.createCatalog(FlinkCatalogFactory.java:166) ~[iceberg-flink-runt
ime-1.20-1.7.1.jar:?]
        at org.apache.iceberg.flink.FlinkCatalogFactory.createCatalog(FlinkCatalogFactory.java:139) ~[iceberg-flink-runt
ime-1.20-1.7.1.jar:?]
        at org.apache.flink.table.factories.FactoryUtil.createCatalog(FactoryUtil.java:492) ~[flink-table-api-java-uber-
1.20.0.jar:1.20.0]
        at org.apache.flink.table.catalog.CatalogManager.initCatalog(CatalogManager.java:368) ~[flink-table-api-java-ube
r-1.20.0.jar:1.20.0]
        at org.apache.flink.table.catalog.CatalogManager.createCatalog(CatalogManager.java:322) ~[flink-table-api-java-u
ber-1.20.0.jar:1.20.0]
        at org.apache.flink.table.operations.ddl.CreateCatalogOperation.execute(CreateCatalogOperation.java:88) ~[flink-
table-api-java-uber-1.20.0.jar:1.20.0]
```
It appears that Flink is able to authenticate and get an access token from Polaris. But when attempting to fetch the Polaris configuration, a 403 response is received, and the body can't be parsed into JSON.

I also checked the Polaris logs.
```
WARN  [2024-12-19 21:09:16,008 - 171371485] [pool-3-thread-11] [] o.a.p.s.c.DefaultContextResolver: Failed to parse prin
cipal from headers ({x-request-id=a5a35de0-dcb6-40d0-8cc4-a66cba92f077, x-b3-parentspanid=730e3221997844e4, Accept=appli
cation/json, x-client-version=Apache Iceberg 1.7.1 (commit 4a432839233f2343a9eae8255532f911f06358ef), x-b3-sampled=0, Us
er-Agent=Apache-HttpClient/5.4 (Java/11.0.25), X-Forwarded-Proto=http, Host=polaris:8181, Accept-Encoding=gzip, x-gzip,
deflate, x-envoy-attempt-count=1, x-client-git-commit-short=4a43283, x-b3-traceid=43748bd2c2e73bc3730e3221997844e4, x-b3
-spanid=4f6cc905a0d0dbe1, x-forwarded-client-cert=By=spiffe://cluster.local/ns/data-platform/sa/polaris;Hash=55045c2d814
4e5d0718e2706502ac713201f42ec44b799fd508674c475b49465;Subject="";URI=spiffe://cluster.local/ns/data-platform/sa/flink, C
ontent-Length=116, Content-Type=application/x-www-form-urlencoded}); using default-principal
INFO  [2024-12-19 21:09:16,008 - 171371485] [pool-3-thread-11] [] o.a.p.s.tracing.TracingFilter: Started span with paren
t spanId="208f3f42abfc42ee" traceId="170feb2185813eb2f25a5c3306ced564" parentContext="{}"
WARN  [2024-12-19 21:09:16,008 - 171371485] [pool-3-thread-11 - POST /api/catalog/v1/oauth/tokens] [] o.g.j.servlet.WebC
omponent: A servlet request to the URI http://polaris:8181/api/catalog/v1/oauth/tokens contains form parameters in the r
equest body but the request body has been consumed by the servlet or a servlet filter accessing the request parameters.
Only resource methods using @FormParam will work as expected. Resource methods consuming the request body by other means
 will not work as expected.
[EL Fine]: sql: 2024-12-19 21:09:16.008--ServerSession(214651918)--Connection(166093349)--SELECT PRINCIPALCLIENTID, MAIN
SECRET, MAINSECRETHASH, PRINCIPALID, SECONDARYSECRET, SECONDARYSECRETHASH, SECRETSALT, VERSION FROM PRINCIPAL_SECRETS WH
ERE (PRINCIPALCLIENTID = ?)
        bind => [root]
[EL Fine]: sql: 2024-12-19 21:09:16.009--ServerSession(214651918)--Connection(166093349)--SELECT CATALOGID, ID, CREATETI
MESTAMP, DROPTIMESTAMP, ENTITYVERSION, GRANTRECORDSVERSION, INTERNALPROPERTIES, LASTUPDATETIMESTAMP, NAME, PARENTID, PRO
PERTIES, PURGETIMESTAMP, SUBTYPECODE, TOPURGETIMESTAMP, TYPECODE, VERSION FROM ENTITIES WHERE ((CATALOGID = ?) AND (ID =
 ?))
        bind => [0, 151]
INFO  [2024-12-19 21:09:16,010 - 171371487] [pool-3-thread-11] [] i.o.e.l.LoggingSpanExporter: 'POST /api/catalog/v1/oau
th/tokens' : 170feb2185813eb2f25a5c3306ced564 208f3f42abfc42ee SERVER [tracer: /api/catalog/v1/oauth/tokens:] Attributes
Map{data={url.path=/api/catalog/v1/oauth/tokens, server.address=polaris, http.request.method=POST, realm=default-realm,
url.scheme=http}, capacity=128, totalAddedValues=5}
```
I don't see anything in the Polaris logs related to fetching the configuration, which makes me think there is something wrong with the request that causes the HTTP server to reject it.

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [X] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

**Comment by shantanu-dahiya** [comment]
I believe the root cause of this issue is the envoy proxy on Istio sidecars not supporting the `Upgrade: TLS/1.2` header, causing client requests with this header to be [returned with a 403 error](https://github.com/istio/istio/issues/53239). Iceberg in the 1.7.0 release [upgraded httpclient5 from `5.3.1` to `5.4`](https://github.com/apache/iceberg/releases/tag/apache-iceberg-1.7.0). HttpClient5 5.4 sends this header to the Iceberg REST server, but the server's envoy proxy rejects the request with a 403.

Modifying the Iceberg HTTPClient config to not include this header should fix the issue.

**Comment by shantanu-dahiya** [comment]
Client logs for the same error when running Trino with the Iceberg connector:
```
2025-01-08T20:39:24.124Z	ERROR	dispatcher-query-22	io.trino.execution.QueryStateMachine	Error cleaning up query: org.apache.iceberg.exceptions.ForbiddenException: Forbidden:
2025-01-08T20:39:24.124Z	DEBUG	dispatcher-query-24	io.trino.execution.QueryStateMachine	Query 20250108_203923_00004_8edee is FAILED
2025-01-08T20:39:24.124Z	DEBUG	dispatcher-query-22	io.trino.execution.QueryStateMachine	Query 20250108_203923_00004_8edee failed
org.apache.iceberg.exceptions.ForbiddenException: Forbidden:
	at org.apache.iceberg.rest.ErrorHandlers$DefaultErrorHandler.accept(ErrorHandlers.java:212)
	at org.apache.iceberg.rest.ErrorHandlers$DefaultErrorHandler.accept(ErrorHandlers.java:188)
	at org.apache.iceberg.rest.HTTPClient.throwFailure(HTTPClient.java:211)
	at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:323)
	at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:262)
	at org.apache.iceberg.rest.HTTPClient.get(HTTPClient.java:358)
	at org.apache.iceberg.rest.RESTSessionCatalog.fetchConfig(RESTSessionCatalog.java:1045)
	at org.apache.iceberg.rest.RESTSessionCatalog.initialize(RESTSessionCatalog.java:251)
	at io.trino.plugin.iceberg.catalog.rest.TrinoIcebergRestCatalogFactory.create(TrinoIcebergRestCatalogFactory.java:133)
	at io.trino.plugin.iceberg.IcebergMetadataFactory.create(IcebergMetadataFactory.java:77)
	at io.trino.plugin.iceberg.IcebergTransactionManager$MemoizedMetadata.get(IcebergTransactionManager.java:90)
	at io.trino.plugin.iceberg.IcebergTransactionManager.get(IcebergTransactionManager.java:56)
	at io.trino.plugin.iceberg.IcebergConnector.getMetadata(IcebergConnector.java:127)
	at io.trino.metadata.CatalogTransaction.getConnectorMetadata(CatalogTransaction.java:71)
	at io.trino.metadata.CatalogMetadata.getMetadata(CatalogMetadata.java:87)
	at io.trino.metadata.MetadataManager$QueryCatalogs.registerCatalog(MetadataManager.java:2804)
	at io.trino.metadata.MetadataManager.registerCatalogForQuery(MetadataManager.java:2777)
	at io.trino.metadata.MetadataManager.lambda$getOptionalCatalogMetadata$76(MetadataManager.java:2732)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.trino.metadata.MetadataManager.getOptionalCatalogMetadata(MetadataManager.java:2732)
	at io.trino.metadata.MetadataManager.getMaterializedViewInternal(MetadataManager.java:1812)
	at io.trino.metadata.MetadataManager.getMaterializedView(MetadataManager.java:1774)
	at io.trino.tracing.TracingMetadata.getMaterializedView(TracingMetadata.java:1431)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:2267)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:522)
	at io.trino.sql.tree.Table.accept(Table.java:60)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:541)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:4893)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:3093)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:522)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:541)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:549)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1564)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:522)
	at io.trino.sql.tree.Query.accept(Query.java:119)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:541)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:501)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:490)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:98)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:87)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:289)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:222)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:892)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:153)
	at io.trino.$gen.Trino_465____20250108_152852_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

Trino envoy proxy debug logs, including the offending request header:
```
2025-01-08T22:03:12.990743Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1192	[Tags: "ConnectionId":"1654","StreamId":"2949485735478818330"] request headers complete (end_stream=false):
':authority', 'polaris:8181'
':path', '/api/catalog/v1/config?warehouse=azure-catalog'
':method', 'GET'
'accept', 'application/json'
'content-type', 'application/json'
'authorization', 'Bearer xxx'
'accept-encoding', 'gzip, x-gzip, deflate'
'x-client-git-commit-short', '5f7c992'
'x-client-version', 'Apache Iceberg 1.7.0 (commit 5f7c992ca673bf41df1d37543b24d646c24568a9)'
'connection', 'keep-alive,Upgrade'
'user-agent', 'Apache-HttpClient/5.4.1 (Java/23.0.1)'
'upgrade', 'TLS/1.2'
	thread=24
2025-01-08T22:03:12.990769Z	debug	envoy connection external/envoy/source/common/network/connection_impl.h:98	[Tags: "ConnectionId":"1654"] current connecting state: false	thread=24
2025-01-08T22:03:12.990793Z	debug	envoy http external/envoy/source/common/http/filter_manager.cc:1065	[Tags: "ConnectionId":"1654","StreamId":"2949485735478818330"] Sending local reply with details upgrade_failed	thread=24
2025-01-08T22:03:12.990823Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1803	[Tags: "ConnectionId":"1654","StreamId":"2949485735478818330"] closing connection due to connection close header	thread=24
2025-01-08T22:03:12.990837Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1869	[Tags: "ConnectionId":"1654","StreamId":"2949485735478818330"] encoding headers via codec (end_stream=true):
':status', '403'
'date', 'Wed, 08 Jan 2025 22:03:12 GMT'
'server', 'envoy'
'connection', 'close'
	thread=24
2025-01-08T22:03:12.990848Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1974	[Tags: "ConnectionId":"1654","StreamId":"2949485735478818330"] Codec completed encoding stream.	thread=24
2025-01-08T22:03:12.990853Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:247	[Tags: "ConnectionId":"1654","StreamId":"2949485735478818330"] doEndStream() resetting stream	thread=24
2025-01-08T22:03:12.990856Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:1938	[Tags: "ConnectionId":"1654","StreamId":"2949485735478818330"] stream reset: reset reason: local reset, response details: -	thread=24
2025-01-08T22:03:12.990865Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:146	[Tags: "ConnectionId":"1654"] closing data_to_write=116 type=2	thread=24
2025-01-08T22:03:12.990877Z	debug	envoy connection external/envoy/source/common/network/connection_impl_base.cc:47	[Tags: "ConnectionId":"1654"] setting delayed close timer with timeout 1000 ms	thread=24
2025-01-08T22:03:12.990891Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:146	[Tags: "ConnectionId":"1654"] closing data_to_write=116 type=2	thread=24
2025-01-08T22:03:12.990937Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:788	[Tags: "ConnectionId":"1654"] write flush complete	thread=24
2025-01-08T22:03:12.991147Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:788	[Tags: "ConnectionId":"1654"] write flush complete	thread=24
2025-01-08T22:03:13.746508Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:393	[Tags: "ConnectionId":"12"] new stream	thread=24
```

**Comment by shantanu-dahiya** [comment]
Envoy has [an issue](https://github.com/envoyproxy/envoy/issues/36305) and an [open PR](https://github.com/envoyproxy/envoy/pull/37642) to add configuration that allows upgrade headers to be ignored. If and when this gets released, we should be able to configure our Istio/envoy setup to ignore these headers.

**Comment by george-zubrienko** [comment]
if you struggled like me, upgrade httpcomponents to 5.4.2 which fixes this issue by... a simple change.
https://github.com/apache/httpcomponents-client/commit/5ab09ea39fed1c39ea35905532ba1567c785330a

**Comment by shantanu-dahiya** [comment]
@george-zubrienko does that work with Iceberg>=1.7? I looked through the Iceberg code but I don't see the HttpClient requests being set with a `Connection` header - it has to be set for the Upgrade header not to be set, from what I understand.

**Comment by george-zubrienko** [comment]
> [@george-zubrienko](https://github.com/george-zubrienko) does that work with Iceberg>=1.7? I looked through the Iceberg code but I don't see the HttpClient requests being set with a `Connection` header - it has to be set for the Upgrade header not to be set, from what I understand.

Yes, with Iceberg 1.8.1 `connection` is set to `keep alive,Upgrade` - that's how I found this. My code didn't work but Trino did. Since library version is included in headers I noticed that Trino used 5.4.2 and tested with it - bam fixed :)

**Comment by shantanu-dahiya** [comment]
@george-zubrienko I see [iceberg 1.8.1](https://github.com/apache/iceberg/blob/apache-iceberg-1.8.1/gradle/libs.versions.toml) imports httpcomponents version `5.4.1`, but the [upgrade header change](https://downloads.apache.org/httpcomponents/httpclient/RELEASE_NOTES-5.4.x.txt), as you said, is in version `5.4.2`. I haven't tried to get Trino working yet, but will do that tomorrow and report back here.

**Comment by shantanu-dahiya** [comment]
Well, Trino 473 does indeed seem to be working fine with Istio. Thanks for sharing @george-zubrienko

**Comment by shantanu-dahiya** [comment]
We tested iceberg-1.8.1 with Flink and it is still throwing the ForbiddenException. I'd venture to guess that Trino is implementing a fix that doesn't send the Upgrade headers, but iceberg itself is still sending them.

**Comment by george-zubrienko** [comment]
> We tested iceberg-1.8.1 with Flink and it is still throwing the ForbiddenException. I'd venture to guess that Trino is implementing a fix that doesn't send the Upgrade headers, but iceberg itself is still sending them.

You need to upgrade httpcomponents.client5 lib to 5.4.2. Iceberg 1.8.1 ships with 5.4.1.

**Comment by shantanu-dahiya** [comment]
Right, so a custom iceberg build is needed, or we wait for an iceberg release that upgrades httpcomponents.

**Comment by george-zubrienko** [comment]
> Right, so a custom iceberg build is needed, or we wait for an iceberg release that upgrades httpcomponents.

Yep, maybe this should be raised with them?
