### ISSUE TITLE
Flaky test `TestFlinkTableSink > testInsertFromSourceTable`

### ISSUE THREAD

**Issue by manuzhang** [apache/iceberg#11833]
### Apache Iceberg version

main (development)

### Query engine

Flink

### Please describe the bug 🐞

https://github.com/apache/iceberg/actions/runs/12419587376/job/34675216626

```
TestFlinkTableSink > testInsertFromSourceTable() > catalogName=testhadoop_basenamespace, baseNamespace=l0.l1, format=PARQUET, isStreaming=false, useV2Sink=true FAILED
    java.lang.RuntimeException: Failed to collect table result
        at org.apache.iceberg.flink.TestBase.sql(TestBase.java:105)
        at org.apache.iceberg.flink.TestFlinkTableSink.testInsertFromSourceTable(TestFlinkTableSink.java:152)

        Caused by:
        org.apache.flink.table.api.TableException: Failed to wait job finish
            at app//org.apache.flink.table.api.internal.InsertResultProvider.hasNext(InsertResultProvider.java:85)
            at app//org.apache.flink.table.api.internal.InsertResultProvider.access$200(InsertResultProvider.java:37)
            at app//org.apache.flink.table.api.internal.InsertResultProvider$Iterator.hasNext(InsertResultProvider.java:112)
            at app//org.apache.iceberg.relocated.com.google.common.collect.Iterators.addAll(Iterators.java:365)
            at app//org.apache.iceberg.relocated.com.google.common.collect.Lists.newArrayList(Lists.java:154)
            at app//org.apache.iceberg.flink.TestBase.sql(TestBase.java:103)
            ... 1 more

            Caused by:
            java.util.concurrent.ExecutionException: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
                at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
                at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2005)
                at org.apache.flink.table.api.internal.InsertResultProvider.hasNext(InsertResultProvider.java:83)
                ... 6 more

                Caused by:
                org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
                    at app//org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:144)
                            at org.apache.iceberg.hadoop.HadoopTableOperations.renameToFinal(HadoopTableOperations.java:363)
                            at org.apache.iceberg.hadoop.HadoopTableOperations.commit(HadoopTableOperations.java:162)
                            at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:433)
                            at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413)
                            at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219)
                            at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203)
                            at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
                            at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:405)
                            at org.apache.iceberg.flink.sink.IcebergCommitter.commitOperation(IcebergCommitter.java:293)
                            at org.apache.iceberg.flink.sink.IcebergCommitter.commitDeltaTxn(IcebergCommitter.java:248)
                            at org.apache.iceberg.flink.sink.IcebergCommitter.commitPendingResult(IcebergCommitter.java:200)
                            at org.apache.iceberg.flink.sink.IcebergCommitter.commitPendingRequests(IcebergCommitter.java:172)
                            at org.apache.iceberg.flink.sink.IcebergCommitter.commit(IcebergCommitter.java:133)
                            at org.apache.flink.streaming.runtime.operators.sink.committables.CheckpointCommittableManagerImpl.commit(CheckpointCommittableManagerImpl.java:134)
                            at org.apache.flink.streaming.runtime.operators.sink.CommitterOperator.commitAndEmit(CommitterOperator.java:190)
                            at org.apache.flink.streaming.runtime.operators.sink.CommitterOperator.commitAndEmitCheckpoints(CommitterOperator.java:174)
                            at org.apache.flink.streaming.runtime.operators.sink.CommitterOperator.notifyCheckpointComplete(CommitterOperator.java:164)
                            at org.apache.flink.streaming.runtime.operators.sink.CommitterOperator.endInput(CommitterOperator.java:151)
                            at org.apache.flink.streaming.runtime.tasks.StreamOperatorWrapper.endOperatorInput(StreamOperatorWrapper.java:96)
                            at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.endInput(RegularOperatorChain.java:97)
                            at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:68)
                            at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:579)
                            at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231)
                            at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:909)
                            at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:858)
                            at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958)
                            at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:937)
                            at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:751)
                            at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566)
                            at java.base/java.lang.Thread.run(Thread.java:829)
```

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [X] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

**Comment by ajantha-bhat** [comment]
Another flaky test from the same class
https://github.com/apache/iceberg/actions/runs/12701536583/job/35406205488?pr=11919


`TestFlinkTableSink > testReplacePartitions()` > catalogName=testhadoop_basenamespace, baseNamespace=l0.l1, format=AVRO, isStreaming=false, useV2Sink=true FAILED
    java.lang.RuntimeException: Failed to collect table result
        at org.apache.iceberg.flink.TestBase.sql(TestBase.java:105)
        at org.apache.iceberg.flink.TestFlinkTableSink.testReplacePartitions(TestFlinkTableSink.java:194)

        Caused by:
        org.apache.flink.table.api.TableException: Failed to wait job finish
            at app//org.apache.flink.table.api.internal.InsertResultProvider.hasNext(InsertResultProvider.java:85)
            at app//org.apache.flink.table.api.internal.InsertResultProvider.access$200(InsertResultProvider.java:37)
            at app//org.apache.flink.table.api.internal.InsertResultProvider$Iterator.hasNext(InsertResultProvider.java:112)
            at app//org.apache.iceberg.relocated.com.google.common.collect.Iterators.addAll(Iterators.java:367)
            at app//org.apache.iceberg.relocated.com.google.common.collect.Lists.newArrayList(Lists.java:156)
            at app//org.apache.iceberg.flink.TestBase.sql(TestBase.java:103)
            ... 1 more

            Caused by:
            java.util.concurrent.ExecutionException: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.

**Comment by manuzhang** [comment]
Same as above from https://github.com/apache/iceberg/actions/runs/13356805548/job/37300702080, but with more stacktraces.

```
TestFlinkTableSink > testReplacePartitions() > catalogName=testhadoop_basenamespace, baseNamespace=l0.l1, format=PARQUET, isStreaming=false, useV2Sink=true FAILED
    java.lang.RuntimeException: Failed to collect table result
        at org.apache.iceberg.flink.TestBase.sql(TestBase.java:105)
        at org.apache.iceberg.flink.TestFlinkTableSink.testReplacePartitions(TestFlinkTableSink.java:214)

        Caused by:
        org.apache.flink.table.api.TableException: Failed to wait job finish
            at app//org.apache.flink.table.api.internal.InsertResultProvider.hasNext(InsertResultProvider.java:85)
            at app//org.apache.flink.table.api.internal.InsertResultProvider.access$200(InsertResultProvider.java:37)
            at app//org.apache.flink.table.api.internal.InsertResultProvider$Iterator.hasNext(InsertResultProvider.java:112)
            at app//org.apache.iceberg.relocated.com.google.common.collect.Iterators.addAll(Iterators.java:367)
            at app//org.apache.iceberg.relocated.com.google.common.collect.Lists.newArrayList(Lists.java:156)
            at app//org.apache.iceberg.flink.TestBase.sql(TestBase.java:103)
            ... 1 more

            Caused by:
            java.util.concurrent.ExecutionException: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
                at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
                at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
                at org.apache.flink.table.api.internal.InsertResultProvider.hasNext(InsertResultProvider.java:83)
                ... 6 more

                Caused by:
                org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
                    at app//org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:144)
                    at app//org.apache.flink.runtime.minicluster.MiniClusterJobClient.lambda$getJobExecutionResult$3(MiniClusterJobClient.java:141)
                    at java.base@21.0.6/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
                    at java.base@21.0.6/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
                    at java.base@21.0.6/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
                    at org.apache.flink.runtime.rpc.pekko.PekkoInvocationHandler.lambda$invokeRpc$1(PekkoInvocationHandler.java:268)
                            at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
                            at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:433)
                            at org.apache.iceberg.BaseReplacePartitions.commit(BaseReplacePartitions.java:26)
                            at org.apache.iceberg.flink.sink.IcebergCommitter.commitOperation(IcebergCommitter.java:293)
                            at org.apache.iceberg.flink.sink.IcebergCommitter.replacePartitions(IcebergCommitter.java:227)
                            at org.apache.iceberg.flink.sink.IcebergCommitter.commitPendingResult(IcebergCommitter.java:198)
                            at org.apache.iceberg.flink.sink.IcebergCommitter.commitPendingRequests(IcebergCommitter.java:172)
                            at org.apache.iceberg.flink.sink.IcebergCommitter.commit(IcebergCommitter.java:133)
                            at org.apache.flink.streaming.runtime.operators.sink.committables.CheckpointCommittableManagerImpl.commit(CheckpointCommittableManagerImpl.java:134)
                            at org.apache.flink.streaming.runtime.operators.sink.CommitterOperator.commitAndEmit(CommitterOperator.java:190)
                            at org.apache.flink.streaming.runtime.operators.sink.CommitterOperator.commitAndEmitCheckpoints(CommitterOperator.java:174)
                            at org.apache.flink.streaming.runtime.operators.sink.CommitterOperator.notifyCheckpointComplete(CommitterOperator.java:164)
                            at org.apache.flink.streaming.runtime.operators.sink.CommitterOperator.endInput(CommitterOperator.java:151)
                            at org.apache.flink.streaming.runtime.tasks.StreamOperatorWrapper.endOperatorInput(StreamOperatorWrapper.java:96)
                            at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.endInput(RegularOperatorChain.java:97)
                            at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:68)
                            at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:579)
                            at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231)
                            at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:909)
                            at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:858)
                            at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958)
                            at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:937)
                            at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:751)
                            at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566)
                            at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by manuzhang** [comment]
@stevenzwu do you know about these failures?
