### ISSUE TITLE
`TestFlinkIcebergSinkDistributionMode#testRangeDistributionStatisticsMigration()` is failing

### ISSUE THREAD

**Issue by jbonofre** [apache/iceberg#11835]
### Apache Iceberg version

None

### Query engine

Flink

### Please describe the bug 🐞

When building iceberg-java `main`, `TestFlinkIcebergSinkDistributionMode#testRangeDistributionStatisticsMigration()` is failing:

```
TestFlinkIcebergSinkDistributionMode > testRangeDistributionStatisticsMigration() > parallelism = 2, partitioned = true FAILED
    java.lang.AssertionError: 
    Expecting actual:
      10999
    to be less than or equal to:
      500 
        at org.apache.iceberg.flink.sink.TestFlinkIcebergSinkDistributionMode.assertIdColumnStatsNoRangeOverlap(TestFlinkIcebergSinkDistributionMode.java:530)
        at org.apache.iceberg.flink.sink.TestFlinkIcebergSinkDistributionMode.testRangeDistributionStatisticsMigration(TestFlinkIcebergSinkDistributionMode.java:475)
```

I'm investigating the cause and I will provide a fix.

### Willingness to contribute

- [X] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

**Comment by manuzhang** [comment]
@jbonofre are you still working on this fix?

**Comment by manuzhang** [comment]
Same error in `TestFlinkIcebergSinkV2DistributionMode` cc @rodmeneses 

```
TestFlinkIcebergSinkV2DistributionMode > testRangeDistributionStatisticsMigration() > parallelism = 2, partitioned = true, writeParallelism = 2 FAILED
    java.lang.AssertionError: 
    Expecting actual:
      10999
    to be less than or equal to:
      500 
        at org.apache.iceberg.flink.sink.TestFlinkIcebergSinkV2DistributionMode.assertIdColumnStatsNoRangeOverlap(TestFlinkIcebergSinkV2DistributionMode.java:536)
        at org.apache.iceberg.flink.sink.TestFlinkIcebergSinkV2DistributionMode.testRangeDistributionStatisticsMigration(TestFlinkIcebergSinkV2DistributionMode.java:481)
```

**Comment by stevenzwu** [comment]
this should fixed with PR #13725
