### ISSUE TITLE
HadoopTableOperations might swallow IOException when doing commit

### ISSUE THREAD

**Issue by waterlx** [apache/iceberg#1349]
We met a condition that it failed to update version-hint.text when doing commit due to IOException, but the exception is swallowed.

The table is created by HadoopCatalog, by a user with proper permissions to access the directory, so the initial v1.metadata.json and version-hint.text are generated correctly.
After that, another job tries to update the table, with another user but without proper permissions. The subsequent v#.metadata.json could be generated correctly, but it fails to update version-hint.text so its content is always 1.

We noticed that failure by seeing no data when trying to read that Iceberg table and found the following exception in the log:
```
java.io.FileNotFoundException: xxxxx/version-hint.text (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.<init>(RawLocalFileSystem.java:222)
        at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.<init>(RawLocalFileSystem.java:209)
        at org.apache.hadoop.fs.RawLocalFileSystem.createOutputStreamWithMode(RawLocalFileSystem.java:307)
        at org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:295)
        at org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:328)
        at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSOutputSummer.<init>(ChecksumFileSystem.java:398)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:461)
        at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:440)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:911)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:892)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:789)
        at org.apache.iceberg.hadoop.HadoopTableOperations.writeVersionHint(HadoopTableOperations.java:273)
        at org.apache.iceberg.hadoop.HadoopTableOperations.commit(HadoopTableOperations.java:162)
        at org.apache.iceberg.BaseTransaction.lambda$commitSimpleTransaction$5(BaseTransaction.java:344)
        at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:403)
        at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:212)
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:188)
        at org.apache.iceberg.BaseTransaction.commitSimpleTransaction(BaseTransaction.java:329)
        at org.apache.iceberg.BaseTransaction.commitTransaction(BaseTransaction.java:220)
```

**Comment by waterlx** [comment]
The following code catches the IOException and only does the logging:
https://github.com/apache/iceberg/blob/3990daae506822dc6b85c7b6d8461be28ca5362e/core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java#L275

**Comment by waterlx** [comment]
@rdblue that code is brought in by the initial commit and never changed after that. 
Would you please share your idea why you perfer to swallow the exception here? 
Although the correct v#.metadata.json are generated, they are not considered if version-hint.text is not updated, as a result, the readers could not see that new data.

**Comment by RussellSpitzer** [comment]
@waterlx

Just to clarify, 
User 1 Has write and read permissions on the directory as well as unique status User2 doesn't have
User 2 Has write and read permissions on the directory but lacks authority to read files created by User1

User 1 Writes and Creates VersionHint + MetadataFile
User 2 Writes and Creates only Metadata file because they have permissions to do so but fails to write Version Hint because this would require overwriting User1's version hint

Then when reading User2 has issues because while they can read the Metadata they could never read the VersionHint from
User1?

**Comment by rdblue** [comment]
The version hint file is just that -- a hint. It is not guaranteed to be correct because we cannot guarantee that two different FS operations complete successfully (the rename to commit, and the version hint update).

To handle cases where the version hint is missing or incorrect, Iceberg should look for newer versions. If the version hint says the current version is 3, but v4.metadata.json exists, it should detect v4 and use that instead, and keep trying new version numbers until one does not exist.

So the main problem here is that you had an incorrect read when the version hint was out of date.

**Comment by waterlx** [comment]
@RussellSpitzer , yes, it is. But I realized that Iceberg is still able to read the correct data even with the wrong version-hint.

**Comment by waterlx** [comment]
@rdblue got your idea and I found the those logic in HadoopTableOperations#refresh().
So the version hint being out of date is not the root cause of incorrect read.

**Comment by aokolnychyi** [comment]
It seems correct to me to ignore exceptions that occur while writing the hint as that hint is optional.

@waterlx, how did you notice you read incorrect data? How did you load/write to the table? Did you cache the table instance?

**Comment by waterlx** [comment]
@aokolnychyi I used a Spark job to count the record after writing into the Iceberg table and it did not show the expected the number. By accident, I found that the version nuber in version-hint was not the same as the latest metadata json. 
A Flink job is used to write into Iceberg and I use MergeAppend and Transaction.commitTransaction() to do the commit. The table instance is not cached.

Sorry that I could not re-create it or recall all actions I made that day. I guess the incorrect read might be due to that ont only was version-hint not updated correctly, but at least one metadata json file is also not written correctly due to the improper permissions. 

Another thing I would like to mention (but might not relate to that incorrect read) is that "java.io.FileNotFoundException" in the description is the error made on purpose so as to trigger the error in house in my dev environment, the actual error on our production system is the following org.apache.hadoop.ipc.RemoteException (we enabled Ranger aganist Hadoop):
```
org.apache.hadoop.ipc.RemoteException(org.apache.ranger.authorization.hadoop.exceptions.RangerAccessControlException): Permission denied: user=u_teg_tdbank, access=WRITE, inode="/xxxx/version-hint.text"
	at org.apache.ranger.authorization.hadoop.RangerHdfsAuthorizer$RangerAccessControlEnforcer.checkPermission(RangerHdfsAuthorizer.java:442)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:190)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1663)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1647)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPathAccess(FSDirectory.java:1597)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.resolvePathForStartFile(FSDirWriteFileOp.java:305)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInt(FSNamesystem.java:2284)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFile(FSNamesystem.java:2227)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.createOriginal(NameNodeRpcServer.java:745)
	at org.apache.hadoop.hdfs.server.namenode.ProtectionManager.create(ProtectionManager.java:326)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.create(NameNodeRpcServer.java:715)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:421)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:447)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:866)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:809)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:2248)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2574)

	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1489)
	at org.apache.hadoop.ipc.Client.call(Client.java:1435)
	at org.apache.hadoop.ipc.Client.call(Client.java:1345)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
	at com.sun.proxy.$Proxy10.create(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.create(ClientNamenodeProtocolTranslatorPB.java:307)
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:409)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:163)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:155)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:346)
	at com.sun.proxy.$Proxy11.create(Unknown Source)
	at org.apache.hadoop.hdfs.DFSOutputStream.newStreamForCreate(DFSOutputStream.java:266)
	at org.apache.hadoop.hdfs.DFSClient.create(DFSClient.java:1308)
	at org.apache.hadoop.hdfs.DFSClient.create(DFSClient.java:1249)
	at org.apache.hadoop.hdfs.DistributedFileSystem$8.doCall(DistributedFileSystem.java:484)
	at org.apache.hadoop.hdfs.DistributedFileSystem$8.doCall(DistributedFileSystem.java:481)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.create(DistributedFileSystem.java:495)
	at org.apache.hadoop.hdfs.DistributedFileSystem.create(DistributedFileSystem.java:422)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:946)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:927)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:824)
	at org.apache.iceberg.hadoop.HadoopTableOperations.writeVersionHint(HadoopTableOperations.java:273)
	at org.apache.iceberg.hadoop.HadoopTableOperations.commit(HadoopTableOperations.java:162)
	at org.apache.iceberg.BaseTransaction.lambda$commitSimpleTransaction$5(BaseTransaction.java:344)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:403)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:212)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:188)
	at org.apache.iceberg.BaseTransaction.commitSimpleTransaction(BaseTransaction.java:329)
	at org.apache.iceberg.BaseTransaction.commitTransaction(BaseTransaction.java:220)
```

**Comment by waterlx** [comment]
ready to close this issue. Thanks for taking care of this.  @rdblue @RussellSpitzer @aokolnychyi
