### ISSUE TITLE
Occasional unit test failure from CI

### ISSUE THREAD

**Issue by chenjunjiedada** [apache/iceberg#1488]
I met following exceptions occasionally in our internal CI system. Do we have any fix about this recently?
```
org.apache.iceberg.TestRemoveSnapshots > dataFilesCleanupWithParallelTasks[0] FAILED
    java.lang.AssertionError: FILE_B should be deleted
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.apache.iceberg.TestRemoveSnapshots.dataFilesCleanupWithParallelTasks(TestRemoveSnapshots.java:828)
```

**Comment by kbendick** [comment]
I have found some flakey tests under some of the hive tests. I opened a PR for one that fails on my local (but doesn't fail on CI).

I also have this one that fails occasionally on my local

```
org.apache.iceberg.mr.hive.TestHiveIcebergStorageHandlerWithHiveCatalog > testScanTableORC FAILED
    java.lang.IllegalArgumentException: Failed to executeQuery Hive query SHOW TABLES: Error while compiling statement: FAILED: SemanticException org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe (Write failed)

        Caused by:
        org.apache.hive.service.cli.HiveSQLException: Error while compiling statement: FAILED: SemanticException org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe (Write failed)

            Caused by:
            org.apache.hadoop.hive.ql.parse.SemanticException: org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe (Write failed)

                Caused by:
                org.apache.hadoop.hive.ql.metadata.HiveException: org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe (Write failed)

                    Caused by:
                    org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe (Write failed)

                        Caused by:
                        java.net.SocketException: Broken pipe (Write failed)

    org.apache.hadoop.hive.ql.metadata.HiveException: org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe (Write failed)

        Caused by:
        org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe (Write failed)

            Caused by:
            java.net.SocketException: Broken pipe (Write failed)
```

**Comment by kbendick** [comment]
Here's the PR for the flakey test that fails on my local: https://github.com/apache/iceberg/pull/1579

**Comment by kbendick** [comment]
I got another one of those Broken Pipe ones in CI.

Here are the CI logs: https://travis-ci.org/github/apache/iceberg/builds/735138861

**Comment by chenjunjiedada** [comment]
Another one: https://travis-ci.org/github/apache/iceberg/jobs/735326468.

**Comment by pvary** [comment]
Are these tests after @marton-bod's last PR? #1585. That contained some memory upgrade for the tests

**Comment by chenjunjiedada** [comment]
It doesn't happen recently.
