### ISSUE TITLE
Spark reads the table created by flink  throws an exception

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/iceberg#1504]
I create iceberg table by flink, then insert data to the table , but when read the iceberg table by spark, throws a exception:
`
Caused by: java.lang.ClassCastException: org.apache.orc.TypeDescription cannot be cast to org.apache.iceberg.shaded.org.apache.orc.TypeDescription
`

**Comment by openinx** [comment]
Thanks for reporting this issue, mind to provide the full stacktrace ? I would love to take a look.

**Comment by zhangjun0x01** [comment]
hi, openinx :

my spark code is 

`spark.read().format("iceberg").load("iceberg_db.iceberg_001").show();`

but I can read the data by presto fine ,so I think the data is ok 

the full stacktrace is 

`Caused by: java.lang.ClassCastException: org.apache.orc.TypeDescription cannot be cast to org.apache.iceberg.shaded.org.apache.orc.TypeDescription
	at org.apache.iceberg.orc.OrcIterable.iterator(OrcIterable.java:108)
	at org.apache.iceberg.spark.source.RowDataReader.open(RowDataReader.java:106)
	at org.apache.iceberg.spark.source.BaseDataReader.next(BaseDataReader.java:73)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.hasNext(DataSourceRDD.scala:49)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:858)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:858)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by openinx** [comment]
I checked the case under my host , seems I did not encounter the problem you described: 

```bash
$ bin/spark-shell \
    --packages org.apache.iceberg:iceberg-spark-runtime:0.9.1 \
    --conf spark.sql.warehouse.dir=/Users/openinx/test/hive-warehouse \
    --conf spark.hadoop.hive.metastore.uris=thrift://localhost:9083

scala> spark.read.format("iceberg").load("iceberg_db.sample").show()
+---+----+                                                                      
| id|data|
+---+----+
|  1|   a|
+---+----+
```

**Comment by HeartSaVioR** [comment]
Describing all versions would be pretty much helpful. In this case, Spark version, Flink version, Iceberg version(s) if you used different version for Spark and Flink.

It would be even better if you don't mind sharing the table schema and how to create Iceberg table, and insert rows.

**Comment by zhangjun0x01** [comment]
my spark version is 2.4.5 ,and flink version is 1.11.0, but my hive version is 3.1.2 ,the hive-metastore version of iceberg is 2.3.6,if I use this version ,it will result in jar conflict。

So I modified the hive version of iceberg to 3.1.2, and re-compile the jar using the master branch. I don't know if it is caused by this problem. But in the same spark program, there is no problem reading the iceberg table created by java api 。

And Presto has no problem reading the tables created by spark and flink

I will test it carefully again.

**Comment by zhangjun0x01** [comment]
I read it with a program, there are some jar conflicts, after modify the reference, it's fine

I close it
