### ISSUE TITLE
flink module of master branch  unit test failed, TestIcebergFilesCommitter throws an exception

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/iceberg#1602]
The flink module of master branch  unit test failed, TestIcebergFilesCommitter throws an exception

`org.apache.iceberg.flink.sink.TestIcebergFilesCommitter > testOrderedEventsBetweenCheckpoints[format = parquet] FAILED
    org.apache.iceberg.exceptions.NoSuchTableException: Table does not exist at location: /var/folders/v8/q314pqp92q10pw_4v6513b800000gp/T/junit8719731320363441530/junit5241878040922380281/test
        at org.apache.iceberg.hadoop.HadoopTables.load(HadoopTables.java:86)
        at org.apache.iceberg.flink.TableLoader$HadoopTableLoader.loadTable(TableLoader.java:77)
        at org.apache.iceberg.flink.sink.IcebergFilesCommitter.initializeState(IcebergFilesCommitter.java:115)
        at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.initializeOperatorState(StreamOperatorStateHandler.java:106)
        at org.apache.flink.streaming.api.operators.AbstractStreamOperator.initializeState(AbstractStreamOperator.java:258)
        at org.apache.flink.streaming.util.AbstractStreamOperatorTestHarness.initializeState(AbstractStreamOperatorTestHarness.java:505)
        at org.apache.flink.streaming.util.AbstractStreamOperatorTestHarness.initializeState(AbstractStreamOperatorTestHarness.java:388)
        at org.apache.flink.streaming.util.AbstractStreamOperatorTestHarness.initializeEmptyState(AbstractStreamOperatorTestHarness.java:396)
        at org.apache.flink.streaming.util.AbstractStreamOperatorTestHarness.open(AbstractStreamOperatorTestHarness.java:575)
        at org.apache.iceberg.flink.sink.TestIcebergFilesCommitter.testOrderedEventsBetweenCheckpoints(TestIcebergFilesCommitter.java:167)`

**Comment by zhangjun0x01** [comment]
Local unit test needs to remove HADOOP_HOME
