### ISSUE TITLE
Flink iceberg hive catalog don't load  hive config

### ISSUE THREAD

**Issue by wg1026688210** [apache/iceberg#1605]
Caused by: java.lang.IllegalArgumentException: Can not create a Path from a null string
	at org.apache.hadoop.fs.Path.checkPathArg(Path.java:122) ~[hadoop-common-2.7.2.jar:?]
	at org.apache.hadoop.fs.Path.<init>(Path.java:134) ~[hadoop-common-2.7.2.jar:?]
	at org.apache.hadoop.fs.Path.<init>(Path.java:88) ~[hadoop-common-2.7.2.jar:?]
	at org.apache.iceberg.hive.HiveCatalog.convertToDatabase(HiveCatalog.java:460) ~[iceberg-flink-runtime-9d6318f.dirty.jar-1602570143989.jar:?]
	at org.apache.iceberg.hive.HiveCatalog.lambda$createNamespace$5(HiveCatalog.java:215) ~[iceberg-flink-runtime-9d6318f.dirty.jar-1602570143989.jar:?]
	at org.apache.iceberg.hive.ClientPool.run(ClientPool.java:54) ~[iceberg-flink-runtime-9d6318f.dirty.jar-1602570143989.jar:?]
	at org.apache.iceberg.hive.HiveCatalog.createNamespace(HiveCatalog.java:214) ~[iceberg-flink-runtime-9d6318f.dirty.jar-1602570143989.jar:?]
	at org.apache.iceberg.flink.FlinkCatalog.createDatabase(FlinkCatalog.java:197) ~[iceberg-flink-runtime-9d6318f.dirty.jar-1602570143989.jar:?]
	at org.apache.iceberg.flink.FlinkCatalog.open(FlinkCatalog.java:118) ~[iceberg-flink-runtime-9d6318f.dirty.jar-1602570143989.jar:?]
	at org.apache.flink.table.catalog.CatalogManager.registerCatalog(CatalogManager.java:191) ~[flink-table_2.11-1.11.2.jar:1.11.2]
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.createCatalog(TableEnvironmentImpl.java:1086) ~[flink-table_2.11-1.11.2.jar:1.11.2]
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeOperation(TableEnvironmentImpl.java:1019) ~[flink-table_2.11-1.11.2.jar:1.11.2]
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:690) ~[flink-table_2.11-1.11.2.jar:1.11.2]

**Comment by wg1026688210** [comment]
HiveCatalog will find the option  'hive.metastore.warehouse.dir'  which  should exist  in hive-site.xml config

**Comment by wg1026688210** [comment]
environment:
centos 7
jdk8
hadoop2.7



code 
```
tableEnvironment.executeSql("create catalog iceberg_catalog with ('type'='iceberg', 'catalog-type'='hive', 'uri'='xxx' ,'property-version'='1' ,'clients'='5')");
        tableEnvironment.executeSql("use catalog iceberg_catalog");
        tableEnvironment.executeSql(
                "CREATE TABLE iceberg_catalog.flink_origin_db.hive_1result_table (\n" +
                        "    id STRING COMMENT 'unique id',\n" +
                        "    data STRING\n" +
                        ")\n"
        );
```

**Comment by zhangjun0x01** [comment]
This is a known issue and I am working on it，You can follow https://github.com/apache/iceberg/pull/1558

**Comment by wg1026688210** [comment]
lgtm
