### ISSUE TITLE
class not found exception emr 6.1.0, iceberg-spark-0.9.1,iceberg-spark-runtime-0.9.1 java.lang.ClassNotFoundException: org.apache.spark.sql.sources.v2.DataSourceV2

### ISSUE THREAD

**Issue by jastisatya** [apache/iceberg#1622]
java.lang.ClassNotFoundException: org.apache.spark.sql.sources.v2.DataSourceV2
when I try to use iceberg-spark-0.9.1 in EMR 6.1.0 which comes with spark 3.0.
I don't see the DataSourceV2 present in java.lang.ClassNotFoundException: org.apache.spark.sql.sources.v2 package.
it is under 

java.lang.NoClassDefFoundError: org/apache/spark/sql/sources/v2/DataSourceV2
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  at java.lang.Class.forName0(Native Method)
  at java.lang.Class.forName(Class.java:348)
  at java.util.ServiceLoader$LazyIterator.nextService(ServiceL

**Comment by HeartSaVioR** [comment]
Could you please double check you're adding "iceberg-spark3-runtime" only for Iceberg?
