### ISSUE TITLE
Table refresh missing metadata file.

### ISSUE THREAD

**Issue by zhangdove** [apache/iceberg#1702]
### Use Case:

We have a Spark service on Zeppelin for others to look up Iceberg data online.

1. At time T1, query `prod.db.tb`.(Record version number)`(select * from prod.db.tb limit 1 )`
2. At time T2, the second query is made on `prod.db.tb`. 

The time between T1 and T2 may be a day or a month or more. During this time, we have an asynchronous operation to clear the small files of `prod.db.tb` table, including version file.

It has been some time since the last query, do one more metadata update on the current table (In fact,the cache of the MetaTable has already been invalidated).

```scala
spark.sql("refresh table prod.db.tb")
```

### Phenomenon:
```bash
spark.sql("refresh table prod.db.tb")
org.apache.iceberg.exceptions.ValidationException: Metadata file for version 3175 is missing
  at org.apache.iceberg.hadoop.HadoopTableOperations.refresh(HadoopTableOperations.java:100)
  at org.apache.iceberg.BaseTable.refresh(BaseTable.java:49)
  at org.apache.iceberg.spark.SparkCatalog.invalidateTable(SparkCatalog.java:255)
  at org.apache.spark.sql.execution.datasources.v2.RefreshTableExec.run(RefreshTableExec.scala:28)
  at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:39)
  at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:39)
  at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:45)
  at org.apache.spark.sql.Dataset.$anonfun$logicalPlan$1(Dataset.scala:229)
  at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3616)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:100)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:160)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:87)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:763)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3614)
  at org.apache.spark.sql.Dataset.<init>(Dataset.scala:229)
  at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:100)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:763)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
  at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:606)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:763)
  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:601)
```

**Comment by zhangdove** [comment]
I will try to add a PR to fix this issue

**Comment by rdblue** [comment]
@zhangdove, from the description, it looks like the current metadata file for the table was deleted, is that right? If so, then the table was corrupted and this should result in the exception that was thrown. Reading an old metadata file instead of the current one would be incorrect and would roll back changes in the missing metadata file.

**Comment by zhangdove** [comment]
@rdblue Yes, just as you described.

There is a parameter `write.metadata.previous-versions-max` control the number of metadata, when another process using `actions.RemoveOrphanFiles()` to clean orphan files, the older of metadata files will be deleted, and SparkSession still old cache metadata file information.

**Comment by rdblue** [comment]
Are you saying that the version that was deleted wasn't the current version? This failed because a session was kept open for a long time?

If so, why didn't refresh on its own work?

**Comment by zhangdove** [comment]
We have a Spark service on Zeppelin, it's a long service SparkSession.

When a table that has already been queried is re-queried after some time, it will throw out that the manifestfiles do not exist.

So, we executor `spark.sql("refresh table prod.db.tb")`.However, when do refresh, because the old version value is kept in`HadoopTableOperations`, the metadata file is searched using the old version number. The older version of the metadata file has been cleared by another process with `actions.RemoveOrphanFiles()`.

https://github.com/apache/iceberg/blob/4f2b82e53aca0b5d4bee50353396e53a3f55cd10/core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java#L98

Finally, the exception is as originally described:

`
org.apache.iceberg.exceptions.ValidationException: Metadata file for version 3175 is missing
`

**Comment by rdblue** [comment]
Okay, if I understand correctly, you keep a table around for several days. It starts on some version, like 3175. Then when you call refresh, it tries to look up the next version and fails because both 3175 and 3176 have been deleted already. So it tries to use 3175 and fails.

It seems to me that the problem is keeping a table reference around for that long. Why not drop the cached reference and reload it? You could turn off caching in your catalog.

**Comment by zhangdove** [comment]
Right! We can disable the cache of the catalog by using the `cache-enabled` parameter, but we still want to use the cache to ensure the consistency of the results before and after the data analysis in a short time.

In addition, I'm not sure whether agree with the modified of the #1703  from the community's point of view. At least in the current case it will not work.

**Comment by rdblue** [comment]
The fix in #1703 doesn't seem like the right one to me because it will hide problems with broken tables, where the current metadata file is actually missing. For your use case, maybe you should clear out the cache every so often to avoid having this happen, or refresh all of the tables in the cache periodically. Refreshing periodically would make sense to me.

**Comment by zhangdove** [comment]
Are there any relevant parameters to refresh periodically(If it exists)? Or, we need to manually trigger Refresh all of the Table on a regular basis?

**Comment by rdblue** [comment]
That's not a feature that's been implemented.

**Comment by zhangdove** [comment]
Thanks for your reply!
