### ISSUE TITLE
Query by `day` doesn't work

### ISSUE THREAD

**Issue by dmgcodevil** [apache/iceberg#1713]
I have two partitions created using transformation functions: `day` and `bucket`. 

Schema: 

```
(
    security_id varchar,
    frontdoor_timestamp timestamp(3) with time zone
 )
 WITH (
    format = 'PARQUET',
    partitioning = ARRAY['day(frontdoor_timestamp)','bucket(security_id, 10)']
 )
```

i.e. `struct: struct<1000: frontdoor_timestamp_day: optional date, 1001: security_id_bucket: optional int>`

I'd like to query by day:

```
val tasks = scan.filter(Expressions.equal(Expressions.day[String]("frontdoor_timestamp"), "2020-10-20"))
      .select("security_id")
      .planTasks().toList
````

Getting the following error: 

```
Exception in thread "main" org.apache.iceberg.exceptions.ValidationException: Cannot find field 'day' in struct: struct<1000: frontdoor_timestamp_day: optional date, 1001: security_id_bucket: optional int>
	at org.apache.iceberg.exceptions.ValidationException.check(ValidationException.java:42)
	at org.apache.iceberg.expressions.NamedReference.bind(NamedReference.java:46)
	at org.apache.iceberg.expressions.NamedReference.bind(NamedReference.java:27)
	at org.apache.iceberg.expressions.UnboundPredicate.bind(UnboundPredicate.java:105)
	at org.apache.iceberg.expressions.Binder$BindVisitor.predicate(Binder.java:145)
	at org.apache.iceberg.expressions.Binder$BindVisitor.predicate(Binder.java:104)
	at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:283)
	at org.apache.iceberg.expressions.Binder.bind(Binder.java:62)
	at org.apache.iceberg.expressions.ManifestEvaluator.<init>(ManifestEvaluator.java:65)
	at org.apache.iceberg.expressions.ManifestEvaluator.forPartitionFilter(ManifestEvaluator.java:60)
	at org.apache.iceberg.ManifestGroup.lambda$entries$7(ManifestGroup.java:189)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache$UnboundedLocalLoadingCache.lambda$new$0(UnboundedLocalCache.java:928)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:237)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:233)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:111)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:66)
	at org.apache.iceberg.ManifestGroup.lambda$entries$8(ManifestGroup.java:197)
	at org.apache.iceberg.relocated.com.google.common.collect.Iterators$5.computeNext(Iterators.java:637)
	at org.apache.iceberg.relocated.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at org.apache.iceberg.relocated.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at org.apache.iceberg.relocated.com.google.common.collect.Iterators$5.computeNext(Iterators.java:635)
	at org.apache.iceberg.relocated.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at org.apache.iceberg.relocated.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at org.apache.iceberg.relocated.com.google.common.collect.Iterators$5.computeNext(Iterators.java:635)
	at org.apache.iceberg.relocated.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at org.apache.iceberg.relocated.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at org.apache.iceberg.relocated.com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
	at org.apache.iceberg.relocated.com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
	at org.apache.iceberg.util.ParallelIterable$ParallelIterator.submitNextTask(ParallelIterable.java:113)
	at org.apache.iceberg.util.ParallelIterable$ParallelIterator.checkTasks(ParallelIterable.java:101)
	at org.apache.iceberg.util.ParallelIterable$ParallelIterator.hasNext(ParallelIterable.java:138)
	at org.apache.iceberg.relocated.com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
	at org.apache.iceberg.relocated.com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
	at org.apache.iceberg.relocated.com.google.common.collect.Iterators$ConcatenatedIterator.getTopMetaIterator(Iterators.java:1309)
	at org.apache.iceberg.relocated.com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1325)
	at org.apache.iceberg.io.CloseableIterator$1.hasNext(CloseableIterator.java:48)
	at org.apache.iceberg.util.BinPacking$PackingIterator.hasNext(BinPacking.java:106)
	at org.apache.iceberg.io.CloseableIterator$1.hasNext(CloseableIterator.java:48)
	at org.apache.iceberg.io.CloseableIterable$3$1.hasNext(CloseableIterable.java:104)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:43)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:184)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
	at scala.collection.TraversableLike.to(TraversableLike.scala:725)
	at scala.collection.TraversableLike.to$(TraversableLike.scala:722)
	at scala.collection.AbstractTraversable.to(Traversable.scala:108)
	at scala.collection.TraversableOnce.toList(TraversableOnce.scala:332)
	at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:332)
	at scala.collection.AbstractTraversable.toList(Traversable.scala:108)
	at IcebergQueryApp$.main(IcebergQueryApp.scala:50)
	at IcebergQueryApp.main(IcebergQueryApp.scala)

Process finished with exit code 1
```

What am I doing wrong?

Also tried: `scan.filter(Expressions.equal(Expressions.day[Int]("frontdoor_timestamp"), 20))`, same problem

**Comment by zhangdove** [comment]
As the data type of your `frontdoor_timestamp` field is timestamp, you can express `frontdoor_timestamp = '2020-10-20'` by using the following method

```
val tasks = scan
      .filter(Expressions.greaterThanOrEqual("frontdoor_timestamp", Timestamp.valueOf("2020-10-20").getTime * 1000))
      .filter(Expressions.lessThan("frontdoor_timestamp", Timestamp.valueOf("2020-10-21").getTime * 1000))
```

Maybe there's a better way to write it, and hopefully that helps you.

**Comment by dmgcodevil** [comment]
@zhangdove thanks for the reply, so it's not possible to use a transformation function on queried fields, am I getting this right?
Also, I've noticed that I need to multiply my timestamp by 1000 otherwise I'm getting wrong results. Why do we need to do that?
For example in iceberg parquet file frontdoor_timestamp = 1603411200404000, however Timestamp.valueOf("2020-10-20").getTime = 1603411200404

**Comment by zhangdove** [comment]
I can't guarantee I can explain the cleanup, so I suggest you take a look at the test case here
https://github.com/apache/iceberg/blob/master/api/src/test/java/org/apache/iceberg/transforms/TestTimestampsProjection.java

**Comment by HeartSaVioR** [comment]
https://iceberg.apache.org/spec/#primitive-types

Once you're dealing with Iceberg core API directly, you need to understand the Iceberg types. According to spec, Iceberg stores timestamp via microsecond precision, which is different than java.sql.Timestamp (probably you meant this) which getTime would provide millisecond precision.

**Comment by HeartSaVioR** [comment]
Also the one of major advantages in Iceberg is that you really don't need to specify the partition explicitly. You can apply filter on origin column, and Iceberg will automatically prune the partitions based on the condition.

I don't know whether Iceberg supports explicit partition filtering, but the automatic pruning really works well.

**Comment by dmgcodevil** [comment]
@zhangdove  thanks for the link

@HeartSaVioR I thought if `Expressions` has `day` function I can do `filter(Expressions.equal(Expressions.day[String]("frontdoor_timestamp"), "2020-10-20"))` instead of `between`

closing this issue
