### ISSUE TITLE
  Hive client cannot read the datetime type of Hadoop table in MapReduce phase

### ISSUE THREAD

**Issue by liudi1184** [apache/iceberg#1838]
When I use the table created by haoop catalog and read it with hive client, the data can be read without MapReduce. Once MapReduce occurs, the data cannot be read.

Here's the exception：

Error: java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row 
        at org.apache.hadoop.hive.ql.exec.mr.ExecMapper.map(ExecMapper.java:163)
        at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:54)
        at org.apache.hadoop.hive.ql.exec.mr.ExecMapRunner.run(ExecMapRunner.java:37)
        at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:465)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:349)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:174)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:168)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row 
        at org.apache.hadoop.hive.ql.exec.vector.VectorMapOperator.process(VectorMapOperator.java:973)
        at org.apache.hadoop.hive.ql.exec.mr.ExecMapper.map(ExecMapper.java:154)
        ... 9 more
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: copyToStandardObject failed: java.lang.ClassCastException: java.time.OffsetDateTime cannot be cast to org.apache.hadoop.hive.common.type.Timestamp
        at org.apache.hadoop.hive.ql.exec.vector.VectorMapOperator.process(VectorMapOperator.java:954)
        ... 10 more

**Comment by pvary** [comment]
@liudi1184: Thanks for reporting this!
@lcspinter found the issue and fixed it. See: Hive: Fix casting bugs in Tez joins (#1740)

You might want to build your own Iceberg until we can release a version which contains the fix 😢

**Comment by liudi1184** [comment]
> @liudi1184: Thanks for reporting this!
> @lcspinter found the issue and fixed it. See: Hive: Fix casting bugs in Tez joins (#1740)
> 
> You might want to build your own Iceberg until we can release a version which contains the fix 😢

Thank you. It's done
