### ISSUE TITLE
Exception using Actions

### ISSUE THREAD

**Issue by liudi1184** [apache/iceberg#2008]
When I use the following API

                  `Actions
                            .forTable(table)
                            .rewriteDataFiles()
                            .execute();`
my Flink task always has the following exception

java.lang.IllegalStateException: MiniCluster is not yet running or has already been shut down.
	at org.apache.flink.util.Preconditions.checkState(Preconditions.java:195)
	at org.apache.flink.runtime.minicluster.MiniCluster.getDispatcherGatewayFuture(MiniCluster.java:707)
	at org.apache.flink.runtime.minicluster.MiniCluster.runDispatcherCommand(MiniCluster.java:621)
	at org.apache.flink.runtime.minicluster.MiniCluster.getJobStatus(MiniCluster.java:587)
	at org.apache.flink.client.program.PerJobMiniClusterFactory$PerJobMiniClusterJobClient.getJobStatus(PerJobMiniClusterFactory.java:159)
	at org.apache.flink.streaming.api.operators.collect.CollectResultFetcher.isJobTerminated(CollectResultFetcher.java:202)
	at org.apache.flink.streaming.api.operators.collect.CollectResultFetcher.next(CollectResultFetcher.java:125)
	at org.apache.flink.streaming.api.operators.collect.CollectResultIterator.nextResultFromFetcher(CollectResultIterator.java:89)
	at org.apache.flink.streaming.api.operators.collect.CollectResultIterator.hasNext(CollectResultIterator.java:63)
	at org.apache.iceberg.relocated.com.google.common.collect.Iterators.addAll(Iterators.java:355)
	at org.apache.iceberg.relocated.com.google.common.collect.Lists.newArrayList(Lists.java:143)
	at org.apache.iceberg.flink.source.RowDataRewriter.rewriteDataForTasks(RowDataRewriter.java:89)
	at org.apache.iceberg.flink.actions.RewriteDataFilesAction.rewriteDataForTasks(RewriteDataFilesAction.java:55)
	at org.apache.iceberg.actions.BaseRewriteDataFilesAction.execute(BaseRewriteDataFilesAction.java:231)

**Comment by zhangjun0x01** [comment]
check  it whether other flink programs are started on your computer, such as  started by executing the main method or `start-cluster.sh`, close them, and try to execute the Actions again. I guess it maybe some conflicts  .

**Comment by liudi1184** [comment]
> check it whether other flink programs are started on your computer, such as started by executing the main method or `start-cluster.sh`, close them, and try to execute the Actions again. I guess it maybe some conflicts .

My Flink task runs in the yarn cluster

**Comment by zhangjun0x01** [comment]
use the Actions like this;
```
StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
Actions.forTable(env,table)
              .rewriteDataFiles()
              .execute();
```

**Comment by liudi1184** [comment]
> 
> 
> use the Actions like this;
> 
> ```
> StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
> Actions.forTable(env,table)
>               .rewriteDataFiles()
>               .execute();
> ```

I tried to use it like this, but the following exception occurred


`Caused by: java.io.IOException: Failed to deserialize an element from the source. If you are using user-defined serialization (Value and Writable types), check the serialization functions.
Serializer is org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer@1af6329f
        at org.apache.flink.streaming.api.functions.source.FromElementsFunction.run(FromElementsFunction.java:158) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:201) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException
Serialization trace:
columnSizes (org.apache.iceberg.GenericDeleteFile)
deletes (org.apache.iceberg.BaseFileScanTask)
fileScanTask (org.apache.iceberg.BaseFileScanTask$SplitScanTask)
tasks (org.apache.iceberg.BaseCombinedScanTask)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:378) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:289) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:378) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:289) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer.deserialize(KryoSerializer.java:346) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at org.apache.flink.streaming.api.functions.source.FromElementsFunction.run(FromElementsFunction.java:155) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63) ~[flink-dist_2.11-1.11.1.jar:1.11.1]
        at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:201) ~[flink-dist_2.11-1.11.1.jar:1.11.1]`

**Comment by zhangjun0x01** [comment]
there are some data cannot be serialized, please check  whether it meets the requirements of flink serialization

https://ci.apache.org/projects/flink/flink-docs-stable/dev/types_serialization.html
