### ISSUE TITLE
Hive: query failed when iceberg table has upper case column

### ISSUE THREAD

**Issue by dixingxing0** [apache/iceberg#2045]
When iceberg table has upper case column, query in hive will cause an error, I can reproduce this error after i change iceberg schema from 'first_name' to 'First_name' in TestHiveIcebergStorageHandler, i try to add this code but still can not work.

```java
 shell.executeStatement("SET iceberg.mr.case.sensitive=false");
```
Is this a bug? If it's a bug, i would look into it ,and try to fix it. 

This is the exception info:
```java
java.lang.RuntimeException: cannot find field first_name from [org.apache.iceberg.mr.hive.serde.objectinspector.IcebergRecordObjectInspector$IcebergRecordStructField@582733be, org.apache.iceberg.mr.hive.serde.objectinspector.IcebergRecordObjectInspector$IcebergRecordStructField@cb12aaa, org.apache.iceberg.mr.hive.serde.objectinspector.IcebergRecordObjectInspector$IcebergRecordStructField@d6dde550]
	at org.apache.hadoop.hive.serde2.objectinspector.ObjectInspectorUtils.getStandardStructFieldRef(ObjectInspectorUtils.java:538) ~[hive-serde-3.1.2.jar:3.1.2]
	at org.apache.iceberg.mr.hive.serde.objectinspector.IcebergRecordObjectInspector.getStructFieldRef(IcebergRecordObjectInspector.java:73) ~[iceberg-mr-613327b.dirty.jar:?]
	at org.apache.hadoop.hive.ql.exec.ExprNodeColumnEvaluator.initialize(ExprNodeColumnEvaluator.java:56) ~[hive-exec-3.1.2-core.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.Operator.initEvaluators(Operator.java:1130) ~[hive-exec-3.1.2-core.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.Operator.initEvaluatorsAndReturnStruct(Operator.java:1156) ~[hive-exec-3.1.2-core.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.SelectOperator.initializeOp(SelectOperator.java:75) ~[hive-exec-3.1.2-core.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.Operator.initialize(Operator.java:376) ~[hive-exec-3.1.2-core.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.Operator.initialize(Operator.java:573) ~[hive-exec-3.1.2-core.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.Operator.initializeChildren(Operator.java:525) ~[hive-exec-3.1.2-core.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.Operator.initialize(Operator.java:386) ~[hive-exec-3.1.2-core.jar:3.1.2]
	at org.apache.hadoop.hive.ql.exec.FetchTask.initialize(FetchTask.java:87) [hive-exec-3.1.2-core.jar:3.1.2]
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:689) [hive-exec-3.1.2-core.jar:3.1.2]
	at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1826) [hive-exec-3.1.2-core.jar:3.1.2]
	at org.apache.hadoop.hive.ql.Driver.compileAndRespond(Driver.java:1773) [hive-exec-3.1.2-core.jar:3.1.2]
	at org.apache.hadoop.hive.ql.Driver.compileAndRespond(Driver.java:1768) [hive-exec-3.1.2-core.jar:3.1.2]
	at org.apache.hadoop.hive.ql.reexec.ReExecDriver.compileAndRespond(ReExecDriver.java:126) [hive-exec-3.1.2-core.jar:3.1.2]
	at org.apache.hive.service.cli.operation.SQLOperation.prepare(SQLOperation.java:197) [hive-service-3.1.2.jar:3.1.2]
	at org.apache.hive.service.cli.operation.SQLOperation.runInternal(SQLOperation.java:260) [hive-service-3.1.2.jar:3.1.2]
	at org.apache.hive.service.cli.operation.Operation.run(Operation.java:247) [hive-service-3.1.2.jar:3.1.2]
	at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementInternal(HiveSessionImpl.java:541) [hive-service-3.1.2.jar:3.1.2]
	at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatement(HiveSessionImpl.java:510) [hive-service-3.1.2.jar:3.1.2]
	at org.apache.hive.service.cli.CLIService.executeStatement(CLIService.java:267) [hive-service-3.1.2.jar:3.1.2]
	at org.apache.iceberg.mr.hive.TestHiveShell.executeStatement(TestHiveShell.java:133) [test/:?]
	at org.apache.iceberg.mr.hive.TestHiveIcebergStorageHandler.testScanTable(TestHiveIcebergStorageHandler.java:242) [test/:?]

````

**Comment by pvary** [comment]
@dixingxing0: Thanks for reporting this!
We definitely want to make this work.

One thing to consider is that for Hive the uppercase and the lowercase names should mean the same, so we have to find a way to ignore the case for these tables.

**Comment by dixingxing0** [comment]
I would like to have a try and make a pr

**Comment by pvary** [comment]
@dixingxing0: Ping me to review! Thanks for taking care of this!

**Comment by dixingxing0** [comment]
> @dixingxing0: Ping me to review! Thanks for taking care of this!
Thanks, i'll 

> @dixingxing0: Ping me to review! Thanks for taking care of this!

https://github.com/apache/iceberg/pull/2053
