### ISSUE TITLE
Meet an error when create hive catalog using flink sql client

### ISSUE THREAD

**Issue by zhengqiangtan** [apache/iceberg#2057]
when i using flink sql client to create hive catalog is failed ,reason as follows,what should i do ?
flink version: v1.11.2
hive version: v2.1.1
java version:openjdk version "1.8.0_252"

I'm using flink standalone to open the shell client like this:

```shell
./bin/sql-client.sh embedded \
    -j /data/flink-1.11.2/lib/iceberg-flink-runtime-0.10.0.jar \
    -j /data/flink-1.11.2/lib/flink-sql-connector-hive-2.2.0_2.11-1.11.2.jar \
    shell
```

```
Flink SQL> CREATE CATALOG hive_catalog WITH (
>   'type'='iceberg',
>   'catalog-type'='hive',
>   'uri'='thrift://uat03:9083',
>   'clients'='3',
>   'property-version'='1',
>   'warehouse'='hdfs://nameservice1/user/hive/warehouse/ods.db'
> );


Exception in thread "main" org.apache.flink.table.client.SqlClientException: Unexpected exception. This is a bug. Please consider filing an issue.
    at org.apache.flink.table.client.SqlClient.main(SqlClient.java:213)
Caused by: java.lang.VerifyError: Stack map does not match the one at exception handler 69
Exception Details:
  Location:
    org/apache/iceberg/hive/HiveCatalog.loadNamespaceMetadata(Lorg/apache/iceberg/catalog/Namespace;)Ljava/util/Map; @69: astore_2
  Reason:
    Type 'org/apache/hadoop/hive/metastore/api/NoSuchObjectException' (current frame, stack[0]) is not assignable to 'org/apache/thrift/TException' (stack map, stack[0])
  Current Frame:
    bci: @26
    flags: { }
    locals: { 'org/apache/iceberg/hive/HiveCatalog', 'org/apache/iceberg/catalog/Namespace' }
    stack: { 'org/apache/hadoop/hive/metastore/api/NoSuchObjectException' }
  Stackmap Frame:
    bci: @69
    flags: { }
    locals: { 'org/apache/iceberg/hive/HiveCatalog', 'org/apache/iceberg/catalog/Namespace' }
    stack: { 'org/apache/thrift/TException' }
  Bytecode:
    0x0000000: 2a2b b700 759a 0015 bb00 c759 12c9 04bd
    0x0000010: 00cb 5903 2b53 b700 cebf 2ab4 0038 2bba
    0x0000020: 0236 0000 b600 9ac0 0238 4d2a 2cb7 023c
    0x0000030: 4eb2 00bd 1302 3e2b 2db9 0204 0100 b900
    0x0000040: c504 002d b04d bb00 c759 2c12 c904 bd00
    0x0000050: cb59 032b 53b7 0229 bf4d bb00 d059 bb00
    0x0000060: d259 b700 d313 022b b600 d92b b600 dc13
    0x0000070: 01a4 b600 d9b6 00e0 2cb7 00e3 bf4d b800
    0x0000080: 40b6 00e6 bb00 d059 bb00 d259 b700 d313
    0x0000090: 022d b600 d92b b600 dc13 01a4 b600 d9b6
    0x00000a0: 00e0 2cb7 00e3 bf
  Exception Handler Table:
    bci [26, 68] => handler: 69
    bci [26, 68] => handler: 69
    bci [26, 68] => handler: 89
    bci [26, 68] => handler: 125
  Stackmap Table:
    same_frame(@26)
    same_locals_1_stack_item_frame(@69,Object[#111])
    same_locals_1_stack_item_frame(@89,Object[#111])
    same_locals_1_stack_item_frame(@125,Object[#113])

    at org.apache.iceberg.flink.CatalogLoader$HiveCatalogLoader.loadCatalog(CatalogLoader.java:95)
    at org.apache.iceberg.flink.FlinkCatalog.<init>(FlinkCatalog.java:104)
    at org.apache.iceberg.flink.FlinkCatalogFactory.createCatalog(FlinkCatalogFactory.java:132)
    at org.apache.iceberg.flink.FlinkCatalogFactory.createCatalog(FlinkCatalogFactory.java:122)
    at org.apache.flink.table.api.internal.TableEnvironmentImpl.createCatalog(TableEnvironmentImpl.java:1085)
    at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeOperation(TableEnvironmentImpl.java:1019)
    at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:690)
    at org.apache.flink.table.client.gateway.local.LocalExecutor.lambda$executeSql$7(LocalExecutor.java:360)
    at org.apache.flink.table.client.gateway.local.ExecutionContext.wrapClassLoader(ExecutionContext.java:255)
    at org.apache.flink.table.client.gateway.local.LocalExecutor.executeSql(LocalExecutor.java:360)
    at org.apache.flink.table.client.cli.CliClient.callDdl(CliClient.java:642)
    at org.apache.flink.table.client.cli.CliClient.callDdl(CliClient.java:637)
    at org.apache.flink.table.client.cli.CliClient.callCommand(CliClient.java:357)
    at java.util.Optional.ifPresent(Optional.java:159)
    at org.apache.flink.table.client.cli.CliClient.open(CliClient.java:212)
    at org.apache.flink.table.client.SqlClient.openCli(SqlClient.java:142)
    at org.apache.flink.table.client.SqlClient.start(SqlClient.java:114)
    at org.apache.flink.table.client.SqlClient.main(SqlClient.java:201)
```

**Comment by zhangjun0x01** [comment]
I think maybe jar conflict，could you describe your environment  more detail? For example,  the flink cluster is yarn session or standalone? Have you put iceberg-flink-runtime-xxx.jar and flink-sql-connector-hive-xxx.jar on the classpath? Currently the hive version integrated by iceberg is 2.3.6. Can you test whether there is a problem with this version?

**Comment by dixingxing0** [comment]
Maybe you can check your JDK version, we use HotSpot 1.8.0_202 which works fine.

**Comment by pvary** [comment]
I see: `org/apache/hadoop/hive/metastore/api/NoSuchObjectException` in the logs. Is it possible that the db is not created?

**Comment by zhengqiangtan** [comment]
> I think maybe jar conflict，could you describe your environment more detail? For example, the flink cluster is yarn session or standalone? Have you put iceberg-flink-runtime-xxx.jar and flink-sql-connector-hive-xxx.jar on the classpath? Currently the hive version integrated by iceberg is 2.3.6. Can you test whether there is a problem with this version?

thanks a lot, there is have two jars（iceberg-flink-runtime-0.10.0.jar，iceberg-hive-0.9.1.jar） in the flink lib directory，when i move  the iceberg-hive-0.9.1.jar  out and run `bin/sql-client.sh embedded shell` that is ok for me , hive catalog can be created success as follow :
```shell
Flink SQL> CREATE CATALOG hive_catalog WITH (
>   'type'='iceberg',
>   'catalog-type'='hive',
>   'uri'='thrift://zmbd-uat03:9083',
>   'clients'='3',
>   'property-version'='1',
>   'warehouse'='hdfs://nameservice1/user/hive/warehouse'
> );
2021-01-12 14:26:56,009 WARN  org.apache.hadoop.hive.conf.HiveConf                         [] - HiveConf of name hive.vectorized.use.checked.expressions does not exist
2021-01-12 14:26:56,009 WARN  org.apache.hadoop.hive.conf.HiveConf                         [] - HiveConf of name hive.strict.checks.no.partition.filter does not exist
2021-01-12 14:26:56,010 WARN  org.apache.hadoop.hive.conf.HiveConf                         [] - HiveConf of name hive.strict.checks.orderby.no.limit does not exist
2021-01-12 14:26:56,010 WARN  org.apache.hadoop.hive.conf.HiveConf                         [] - HiveConf of name hive.vectorized.input.format.excludes does not exist
2021-01-12 14:26:56,010 WARN  org.apache.hadoop.hive.conf.HiveConf                         [] - HiveConf of name hive.strict.checks.bucketing does not exist
[INFO] Catalog has been created.
```

**Comment by zhengqiangtan** [comment]
> Maybe you can check your JDK version, we use HotSpot 1.8.0_202 which works fine.

thanks~，The reason is JAR conflict, as described above
