### ISSUE TITLE
Iceberg + Flink + Hive NoSuchMethodError

### ISSUE THREAD

**Issue by deadwind4** [apache/iceberg#2071]
following is POM and error message. 

` <flink.version>1.11.3</flink.version>
    <scala.version>2.12</scala.version>
    <hive.version>2.3.6</hive.version>
    <iceberg.version>0.10.0</iceberg.version>   

     <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-sql-connector-hive-${hive.version}_${scala.version}</artifactId>
            <version>${flink.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.iceberg</groupId>
            <artifactId>iceberg-flink</artifactId>
            <version>${iceberg.version}</version>
        </dependency>`   

`java.lang.NoSuchMethodError: org.apache.parquet.schema.Types$PrimitiveBuilder.as(Lorg/apache/parquet/schema/LogicalTypeAnnotation;)Lorg/apache/parquet/schema/Types$Builder;
	at org.apache.iceberg.parquet.TypeToMessageType.primitive(TypeToMessageType.java:145) ~[iceberg-parquet-0.10.0.jar:na]
	at org.apache.iceberg.parquet.TypeToMessageType.field(TypeToMessageType.java:88) ~[iceberg-parquet-0.10.0.jar:na]
	at org.apache.iceberg.parquet.TypeToMessageType.convert(TypeToMessageType.java:65) ~[iceberg-parquet-0.10.0.jar:na]
	at org.apache.iceberg.parquet.ParquetSchemaUtil.convert(ParquetSchemaUtil.java:43) ~[iceberg-parquet-0.10.0.jar:na]
	at org.apache.iceberg.parquet.Parquet$WriteBuilder.build(Parquet.java:228) ~[iceberg-parquet-0.10.0.jar:na]
	at org.apache.iceberg.flink.sink.RowDataTaskWriterFactory$FlinkFileAppenderFactory.newAppender(RowDataTaskWriterFactory.java:161) ~[iceberg-flink-0.10.0.jar:na]
	at org.apache.iceberg.io.BaseTaskWriter$RollingFileWriter.openCurrent(BaseTaskWriter.java:103) ~[iceberg-core-0.10.0.jar:na]
	at org.apache.iceberg.io.BaseTaskWriter$RollingFileWriter.<init>(BaseTaskWriter.java:82) ~[iceberg-core-0.10.0.jar:na]
	at org.apache.iceberg.io.UnpartitionedWriter.<init>(UnpartitionedWriter.java:33) ~[iceberg-core-0.10.0.jar:na]
	at org.apache.iceberg.flink.sink.RowDataTaskWriterFactory.create(RowDataTaskWriterFactory.java:95) ~[iceberg-flink-0.10.0.jar:na]
	at org.apache.iceberg.flink.sink.IcebergStreamWriter.open(IcebergStreamWriter.java:59) ~[iceberg-flink-0.10.0.jar:na]
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:291) ~[flink-streaming-java_2.12-1.11.3.jar:1.11.3]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$1(StreamTask.java:506) ~[flink-streaming-java_2.12-1.11.3.jar:1.11.3]
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:92) ~[flink-streaming-java_2.12-1.11.3.jar:1.11.3]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:475) ~[flink-streaming-java_2.12-1.11.3.jar:1.11.3]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:526) ~[flink-streaming-java_2.12-1.11.3.jar:1.11.3]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:721) [flink-runtime_2.12-1.11.3.jar:1.11.3]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:546) [flink-runtime_2.12-1.11.3.jar:1.11.3]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_251]`

**Comment by pvary** [comment]
Little bit afraid that I am stating the obvious, but seems like a problem with the parquet library version to me. What version or versions of parquet is on your classparh?

Thanks, Peter

**Comment by deadwind4** [comment]
After I import flink-parquet_${scala.version}, this happen a new problem.

`java.lang.NoClassDefFoundError: org/apache/parquet/schema/LogicalTypeAnnotation
	at org.apache.iceberg.parquet.ParquetSchemaUtil.convert(ParquetSchemaUtil.java:43) ~[iceberg-parquet-0.10.0.jar:na]
Caused by: java.lang.ClassNotFoundException: org.apache.parquet.schema.LogicalTypeAnnotation
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_251]`

It is invalid for manually importing parquet-format(version is 2.8.0) dependency.

**Comment by deadwind4** [comment]
![image](https://user-images.githubusercontent.com/12015546/104287423-64cdea00-54f1-11eb-85bc-88237abe9dae.png)
my parquet version

**Comment by zhangjun0x01** [comment]
I think maybe version conflict

**Comment by deadwind4** [comment]
I resolved this problem. This reason is the conflict between iceberg-parquet and flink-sql-connector-hive-${hive.version}_${scala.version}.
