### ISSUE TITLE
Hadoop catalog missing no-arg constructor

### ISSUE THREAD

**Issue by ismailsimsek** [apache/iceberg#2144]
Hadoop catalog missing no-arg constructor, CatalogUtil.loadCatalog code giving following error meesage

```
icebergCatalog = CatalogUtil.loadCatalog(catalogImpl, "iceberg", icebergProperties, hadoopConf);
```

```
Caused by: java.lang.IllegalArgumentException: Cannot initialize Catalog, missing no-arg constructor: hadoop
	at org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:157)
	at io.debezium.server.iceberg.IcebergChangeConsumer.connect(IcebergChangeConsumer.java:102)
```

**Comment by ismailsimsek** [comment]
my bad, 

i wasn't using it right, `catalogImpl` should be class name instead of `hadoop`

```
icebergCatalog = CatalogUtil.loadCatalog("org.apache.iceberg.hadoop.HadoopCatalog", "iceberg", icebergProperties, hadoopConf);
```
