### ISSUE TITLE
Unable to query Iceberg data from Spark on EMR

### ISSUE THREAD

**Issue by bkahloon** [apache/iceberg#2202]
I seem to be having some difficulties with integrating AWS Glue catalog and Flink. If I try to register an Iceberg catalog, databases or tables from the Flink SQL client the appropriate names show up in Glue catalog but the location field is not updated (preventing me from querying it using some other query engine). 

To provide some more details this was my workflow:

1. create an iceberg catalog, database and table from the sql client.
2.  Submit a flink datastream api job to write to this iceberg table, I just provide the table reference (also load the catalog) with the database.tablename reference (couldn't use SQL because CDC wasn't supported, see issue #2172)
3. Flink is able to write to the appropriate s3 bucket and the metadata files are getting updated as well.
4. When I look in the AWS Glue catalog UI, even though the table name shows up the table location, schema is not picked up in Glue. 

The create catalog, database and table DDL queries I issued via the SQL client

```
CREATE CATALOG iceberg_catalog WITH (
  'type'='iceberg',
  'catalog-type'='iceberg',
  'catalog-impl'='org.apache.iceberg.aws.glue.GlueCatalog',
  'lock-impl'='org.apache.iceberg.aws.glue.DynamoLockManager',
  'lock.table'='icebergGlueLockTable',
  'warehouse'='s3://iceberg-flink'
);

create database iceberg_catalog.iceberg_temp;

CREATE TABLE iceberg_catalog.iceberg_temp.shipments_temp(
  shipment_id INT,
  origin STRING,
  is_arrived BOOLEAN,
  order_date DATE
)PARTITIONED BY  (order_date);
```

<img width="984" alt="Screen Shot 2021-02-02 at 10 32 45 PM 1" src="https://user-images.githubusercontent.com/42993708/106703571-b70da280-65a7-11eb-956f-ffd5f4351ca7.png">
 
<img width="1037" alt="Screen Shot 2021-02-02 at 11 00 03 PM" src="https://user-images.githubusercontent.com/42993708/106705167-af033200-65aa-11eb-86af-d013cd7820a5.png">

<img width="1049" alt="Screen Shot 2021-02-02 at 11 00 14 PM" src="https://user-images.githubusercontent.com/42993708/106705175-b296b900-65aa-11eb-8a36-a39089120e0b.png">

<img width="577" alt="Screen Shot 2021-02-02 at 11 01 01 PM" src="https://user-images.githubusercontent.com/42993708/106705183-ba565d80-65aa-11eb-9530-9d4f4cbc693a.png">

<img width="877" alt="Screen Shot 2021-02-02 at 11 01 17 PM" src="https://user-images.githubusercontent.com/42993708/106705192-bf1b1180-65aa-11eb-87aa-a751c27fb613.png">

**Comment by bkahloon** [comment]
@jackye1995 would you maybe have any ideas ?

**Comment by jackye1995** [comment]
We see there are some issues with the Glue UI for displaying Iceberg tables, can you first check through AWS CLI to see if the table information is actually updated properly?

```
aws glue get-table --database-name db --name table
```

**Comment by bkahloon** [comment]
This was the output I got
```
aws glue get-table --database-name iceberg_warehouse  --name iceberg_dummy_table
{
    "Table": {
        "UpdateTime": 1612385097.0,
        "Name": "iceberg_dummy_table",
        "Parameters": {
            "table_type": "ICEBERG",
            "previous_metadata_location": "s3://iceberg-warehouse/iceberg_warehouse.db/iceberg_dummy_table/metadata/00039-5b28310e-6767-4eff-9ff9-8827c010870f.metadata.json",
            "metadata_location": "s3://iceberg_warehouse.db/iceberg_dummy_table/metadata/00040-d3069356-5ae6-4e76-9d33-63bfccfc04c8.metadata.json"
        },
        "CreateTime": 1612243846.0,
        "CreatedBy": "arn:aws:sts::1234456:assumed-role/dev01InstanceProfile/i-0513",
        "DatabaseName": "iceberg_warehouse",
        "IsRegisteredWithLakeFormation": false,
        "TableType": "EXTERNAL_TABLE",
        "Retention": 0
    }
} 
```

**Comment by bkahloon** [comment]
attempt at a hive query:

```
 hive> show tables;
OK
iceberg_dummy_table
Time taken: 0.367 seconds, Fetched: 1 row(s)
hive> select count(*) from iceberg_dummy_table;
FAILED: SemanticException Unable to fetch table iceberg_dummy_table. StorageDescriptor cannot be null for table: iceberg_dummy_table (Service: null; Status Code: 0; Error Code: null; Request ID: null; Proxy: null) 
```

**Comment by jackye1995** [comment]
```
        "Parameters": {
            "table_type": "ICEBERG",
            "previous_metadata_location": "s3://iceberg-warehouse/iceberg_warehouse.db/iceberg_dummy_table/metadata/00039-5b28310e-6767-4eff-9ff9-8827c010870f.metadata.json",
            "metadata_location": "s3://iceberg_warehouse.db/iceberg_dummy_table/metadata/00040-d3069356-5ae6-4e76-9d33-63bfccfc04c8.metadata.json"
        },
```
This looks correct to me. In the title you said "table location not updated", is this the updated location or not?

For the schema issue, yes Glue UI currently does not support displaying Iceberg table schema, it is expected behavior, the shcema is stored in Iceberg's table metadata in S3.

For Hive, AWS module is not tested and added to Hive runtime jar yet, I do not know if Hive supports loading dynamic catalog yet.

**Comment by bkahloon** [comment]
Ahh I see, thanks a lot @jackye1995.

>  In the title you said "table location not updated", is this the updated location or not?

Yea, that's the updated location. I think the problem I was facing was just a UI issue.

**Comment by tracycarley** [comment]
> ```
>         "Parameters": {
>             "table_type": "ICEBERG",
>             "previous_metadata_location": "s3://iceberg-warehouse/iceberg_warehouse.db/iceberg_dummy_table/metadata/00039-5b28310e-6767-4eff-9ff9-8827c010870f.metadata.json",
>             "metadata_location": "s3://iceberg_warehouse.db/iceberg_dummy_table/metadata/00040-d3069356-5ae6-4e76-9d33-63bfccfc04c8.metadata.json"
>         },
> ```
> 
> This looks correct to me. In the title you said "table location not updated", is this the updated location or not?
> 
> For the schema issue, yes Glue UI currently does not support displaying Iceberg table schema, it is expected behavior, the shcema is stored in Iceberg's table metadata in S3.
> 
> For Hive, AWS module is not tested and added to Hive runtime jar yet, I do not know if Hive supports loading dynamic catalog yet. Currently Hive is still considered an experimental engine, that's why we have not added support yet.

@jackye1995 Any idea on when will the support be added for Glue (AWS) and Hive?

**Comment by jackye1995** [comment]
I don't have an ETA for Glue side UI change yet, will reply when I have it.
For Hive, it is probably worth trying to add the AWS module in Hive runtime, let me have a try in the next few days.

**Comment by bkahloon** [comment]
I see in the docs that currently Iceberg only supports Hive 2.x. So I tried querying the table from Spark. Here is the stack trace I got. Which is similar to the trace I got for Hive (attached in thread above).

I can however, query the table just fine from Flink SQL. 

I'd also like to point out that all of this testing was done from a different EMR cluster than the one that wrote out the original data (Flink streaming job). Indicating I'm able to connect to Glue to get the relevant metadata, but for some reason Spark and Hive can't (Hive I understand that I should be testing with version 2.x)    

```
Flink SQL> select * from iceberg.iceberg_warehouse.iceberg_dummy_table;
[INFO] Result retrieval cancelled.
```

Spark-sql shell error:
```
spark-sql> select * from iceberg_dummy_table;
Error in query: org.apache.hadoop.hive.ql.metadata.HiveException: Unable to fetch table iceberg_dummy_table. StorageDescriptor cannot be null for table: iceberg_dummy_table (Service: null; Status Code: 0; Error Code: null; Request ID: null; Proxy: null);
org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: Unable to fetch table iceberg_dummy_table. StorageDescriptor cannot be null for table: iceberg_dummy_table (Service: null; Status Code: 0; Error Code: null; Request ID: null; Proxy: null);
	at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:113)
	at org.apache.spark.sql.hive.HiveExternalCatalog.tableExists(HiveExternalCatalog.scala:855)
	at org.apache.spark.sql.catalyst.catalog.ExternalCatalogWithListener.tableExists(ExternalCatalogWithListener.scala:146)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalog.tableExists(SessionCatalog.scala:432)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalog.requireTableExists(SessionCatalog.scala:185)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalog.getTableMetadata(SessionCatalog.scala:445)
	at org.apache.spark.sql.execution.datasources.v2.V2SessionCatalog.loadTable(V2SessionCatalog.scala:66)
	at org.apache.spark.sql.connector.catalog.CatalogV2Util$.loadTable(CatalogV2Util.scala:283)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.loaded$lzycompute$1(Analyzer.scala:1010)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.loaded$1(Analyzer.scala:1010)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.$anonfun$lookupRelation$3(Analyzer.scala:1022)
	at scala.Option.orElse(Option.scala:447)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.org$apache$spark$sql$catalyst$analysis$Analyzer$ResolveRelations$$lookupRelation(Analyzer.scala:1021)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$$anonfun$apply$9.applyOrElse(Analyzer.scala:977)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$$anonfun$apply$9.applyOrElse(Analyzer.scala:962)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$3(AnalysisHelper.scala:90)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:72)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$1(AnalysisHelper.scala:90)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:194)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp(AnalysisHelper.scala:86)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp$(AnalysisHelper.scala:84)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUp(LogicalPlan.scala:29)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$2(AnalysisHelper.scala:87)
	at org.apache.spark.sql.catalyst.trees.TreeNode.applyFunctionIfChanged$1(TreeNode.scala:380)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:416)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:248)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:414)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:362)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$1(AnalysisHelper.scala:87)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:194)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp(AnalysisHelper.scala:86)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp$(AnalysisHelper.scala:84)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUp(LogicalPlan.scala:29)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.apply(Analyzer.scala:962)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.apply(Analyzer.scala:934)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:149)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:146)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:138)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:138)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:176)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:170)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:130)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:116)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:104)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:116)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:154)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:201)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:153)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:68)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:149)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:153)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:153)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:68)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:66)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:58)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:100)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:98)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:607)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:602)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:650)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLDriver.run(SparkSQLDriver.scala:63)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processCmd(SparkSQLCLIDriver.scala:377)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.$anonfun$processLine$1(SparkSQLCLIDriver.scala:496)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processLine(SparkSQLCLIDriver.scala:490)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:282)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:936)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1015)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1024)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Unable to fetch table iceberg_dummy_table. StorageDescriptor cannot be null for table: iceberg_dummy_table (Service: null; Status Code: 0; Error Code: null; Request ID: null; Proxy: null)
	at org.apache.hadoop.hive.ql.metadata.Hive.getTable(Hive.java:1296)
	at org.apache.spark.sql.hive.client.HiveClientImpl.getRawTableOption(HiveClientImpl.scala:397)
	at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$tableExists$1(HiveClientImpl.scala:411)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$withHiveState$1(HiveClientImpl.scala:294)
	at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:227)
	at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:226)
	at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:276)
	at org.apache.spark.sql.hive.client.HiveClientImpl.tableExists(HiveClientImpl.scala:411)
	at org.apache.spark.sql.hive.HiveExternalCatalog.$anonfun$tableExists$1(HiveExternalCatalog.scala:855)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:103)
	... 90 more
Caused by: InvalidObjectException(message:StorageDescriptor cannot be null for table: iceberg_dummy_table (Service: null; Status Code: 0; Error Code: null; Request ID: null; Proxy: null))
	at com.amazonaws.glue.catalog.converters.BaseCatalogToHiveConverter$5.get(BaseCatalogToHiveConverter.java:51)
	at com.amazonaws.glue.catalog.converters.BaseCatalogToHiveConverter.getHiveException(BaseCatalogToHiveConverter.java:90)
	at com.amazonaws.glue.catalog.converters.BaseCatalogToHiveConverter.wrapInHiveException(BaseCatalogToHiveConverter.java:81)
	at com.amazonaws.glue.catalog.metastore.GlueMetastoreClientDelegate.getTable(GlueMetastoreClientDelegate.java:430)
	at com.amazonaws.glue.catalog.metastore.AWSCatalogMetastoreClient.getTable(AWSCatalogMetastoreClient.java:1008)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient$SynchronizedHandler.invoke(HiveMetaStoreClient.java:2364)
	at com.sun.proxy.$Proxy37.getTable(Unknown Source)
	at org.apache.hadoop.hive.ql.metadata.Hive.getTable(Hive.java:1288)
	... 101 more
```

**Comment by bkahloon** [comment]
@RussellSpitzer was able to help me resolve this.  I was issuing the spark sql query incorrectly.

```
SELECT * FROM my_catalog.iceberg_warehouse.iceberg_dummy_table
```

**Comment by RussellSpitzer** [comment]
For future users, the issue here was that the spark catalog was configured as "my_catalog" but the tables were being referred to in the session catalog which was not replaced with the Iceberg Spark SessionCatalog class.

There are two solutions

using the tripart identifier "catalogname.namespace.table"

or telling spark to use your catalog (whatever it's name is) by default

"use my_catalog"
