### ISSUE TITLE
Basemetastore Name StackOverflow

### ISSUE THREAD

**Issue by johnclara** [apache/iceberg#2318]
Catalog's default name() calls toString:
https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/catalog/Catalog.java#L44

BaseMetastoreCatalog's toString calls name:
https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java#L149

Without overrides, results in:
```
        java.lang.StackOverflowError
            at org.apache.iceberg.BaseMetastoreCatalog.toString(BaseMetastoreCatalog.java:149)
            at org.apache.iceberg.catalog.Catalog.name(Catalog.java:44)
            at org.apache.iceberg.BaseMetastoreCatalog.toString(BaseMetastoreCatalog.java:149)
            at org.apache.iceberg.catalog.Catalog.name(Catalog.java:44)
```

Is this expected?

**Comment by openinx** [comment]
@johnclara  Thanks for reporting this,  I think it's a bug need to be fixed.  Would you like to prepare a PR for this ?  Thanks.
