### ISSUE TITLE
CodePointCharStream not found while using the latest snapshot version

### ISSUE THREAD

**Issue by hseagle** [apache/iceberg#2383]
Failed to call any procedure defined in spark3-extension during the related antlr class not found.  I'm using the latest dev version. 

Here is the detail error messages
```bash
scala> sql("CALL hive_prod.system.expire_snapshots('default.sample_ice_tbl00')")
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.parser.UpperCaseCharStream.<init>(Lorg/apache/iceberg/shaded/org/antlr/v4/runtime/CodePointCharStream;)V
  at org.apache.spark.sql.catalyst.parser.extensions.IcebergSparkSqlExtensionsParser.parse(IcebergSparkSqlExtensionsParser.scala:124)
  at org.apache.spark.sql.catalyst.parser.extensions.IcebergSparkSqlExtensionsParser.parsePlan(IcebergSparkSqlExtensionsParser.scala:105)
  at org.apache.spark.sql.SparkSession.$anonfun$sql$2(SparkSession.scala:605)
  at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
  at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:605)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:602)
  ... 47 elided

scala> 
```

**Comment by pan3793** [comment]
Temporary solution is revert #2331, see #2382
