### ISSUE TITLE
Commit failed due to Internal error processing lock in metastore DB

### ISSUE THREAD

**Issue by flyrain** [apache/iceberg#2387]
I hit this issue, and got it resolved. It should only happen when you connect a postgres Hive metastore DB. Open this issue in case somebody else hit it. It is similar to issue #798, the root case should be different though. 
Here is the client side stack.
```
scala> spark.sql("CREATE TABLE testdb.student (id INT, name STRING, age INT) USING ADT PARTITIONED by(age) LOCATION 'file:/tmp/testdb/student'").show
java.lang.RuntimeException: Metastore operation failed for testdb.student
  at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:204)
  at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:107)
...
Caused by: org.apache.thrift.TApplicationException: Internal error processing lock
  at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
  at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
  at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_lock(ThriftHiveMetastore.java:3910)
  at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.lock(ThriftHiveMetastore.java:3897)
  at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.lock(HiveMetaStoreClient.java:1955)
  at org.apache.iceberg.hive.HiveTableOperations.lambda$acquireLock$8(HiveTableOperations.java:277)
  at org.apache.iceberg.hive.ClientPool.run(ClientPool.java:54)
  at org.apache.iceberg.hive.HiveTableOperations.acquireLock(HiveTableOperations.java:277)
  at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:145)
  ... 72 more
```
Server side stack
```
2021-03-26 18:47:03,240 ERROR thrift.ProcessFunction (ProcessFunction.java:process(41)) - Internal error processing lock
MetaException(message:Unable to update transaction database org.postgresql.util.PSQLException: ERROR: index "hl_txnid_index" contains unexpected zero page at block 0
  Hint: Please REINDEX it.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
        at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:246)
        at com.jolbox.bonecp.StatementHandle.executeUpdate(StatementHandle.java:497)
        at org.apache.hadoop.hive.metastore.txn.TxnHandler.lock(TxnHandler.java:1428)
        at org.apache.hadoop.hive.metastore.txn.TxnHandler.lock(TxnHandler.java:422)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.lock(HiveMetaStore.java:5527)
```
To fix it, we need to reindex hl_txnid_index. Here is a command example.
```
psql -U hive -d metastore --no-password -h localhost --command "REINDEX INDEX hl_txnid_index"
```

**Comment by flyrain** [comment]
@hililiwei not sure if there is another solution, it is more a Hive issue. To get a better answer, you may ping the Hive community. cc Hive expert, @szehon-ho

**Comment by szehon-ho** [comment]
Thanks :). Yea it looks like postgres DB issue, instead of Hive, looks corrupted.

**Comment by michTalebzadeh** [comment]
I have the same error with Hive 4.01 and Oracle 12g as the hive metastore. I am getting error
```
0: jdbc:hive2://rhes75:10099/default> CREATE VIEW alayer.joint_accounts_view AS SELECT * FROM ilayer.joint_accounts;

ERROR : FAILED: Error in acquiring locks: Error communicating with the metastore
org.apache.hadoop.hive.ql.lockmgr.LockException: Error communicating with the metastore
        at org.apache.hadoop.hive.ql.lockmgr.DbLockManager.lock(DbLockManager.java:183)
        at org.apache.hadoop.hive.ql.lockmgr.DbTxnManager.acquireLocks(DbTxnManager.java:475)
        at org.apache.hadoop.hive.ql.lockmgr.DbTxnManager.acquireLocksWithHeartbeatDelay(DbTxnManager.java:509)
        at org.apache.hadoop.hive.ql.lockmgr.DbTxnManager.acquireLocks(DbTxnManager.java:296)
        at org.apache.hadoop.hive.ql.lockmgr.HiveTxnManagerImpl.acquireLocks(HiveTxnManagerImpl.java:81)
        at org.apache.hadoop.hive.ql.lockmgr.DbTxnManager.acquireLocks(DbTxnManager.java:101)
        at org.apache.hadoop.hive.ql.DriverTxnHandler.acquireLocksInternal(DriverTxnHandler.java:328)
        at org.apache.hadoop.hive.ql.DriverTxnHandler.acquireLocks(DriverTxnHandler.java:232)
        at org.apache.hadoop.hive.ql.DriverTxnHandler.acquireLocksIfNeeded(DriverTxnHandler.java:144)
        at org.apache.hadoop.hive.ql.Driver.lockAndRespond(Driver.java:356)
        at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:197)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:154)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:149)
        at org.apache.hadoop.hive.ql.reexec.ReExecDriver.run(ReExecDriver.java:185)
        at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:236)
        at org.apache.hive.service.cli.operation.SQLOperation.access$500(SQLOperation.java:90)
        at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork$1.run(SQLOperation.java:336)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1953)
        at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork.run(SQLOperation.java:356)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.TApplicationException: Internal error processing lock
```
rebuilding index HL_TXNID_INDEX did not help. Appreciate any thoughts.
