### ISSUE TITLE
NPE when reading metadata for manifests.

### ISSUE THREAD

**Issue by chenjunjiedada** [apache/iceberg#2405]
When using Spark3SQL to read manifests, it throws NPE exception. The stack is：
Caused by: java.lang.NullPointerException
	at org.apache.iceberg.spark.source.StructInternalRow.getBoolean(StructInternalRow.java:109)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.iceberg.common.DynMethods$UnboundMethod.invokeChecked(DynMethods.java:65)
	at org.apache.iceberg.common.DynMethods$UnboundMethod.invoke(DynMethods.java:77)
	at org.apache.iceberg.common.DynMethods$BoundMethod.invoke(DynMethods.java:180)
	at org.apache.iceberg.spark.source.RowDataReader.lambda$newDataIterable$3(RowDataReader.java:197)
	at org.apache.iceberg.io.CloseableIterable$4$1.next(CloseableIterable.java:114)
	at org.apache.iceberg.io.FilterIterator.advance(FilterIterator.java:66)
	at org.apache.iceberg.io.FilterIterator.hasNext(FilterIterator.java:50)
	at org.apache.iceberg.spark.source.BaseDataReader.next(BaseDataReader.java:87)
	at org.apache.spark.sql.execution.datasources.v2.PartitionIterator.hasNext(DataSourceRDD.scala:79)
	at org.apache.spark.sql.execution.datasources.v2.MetricsIterator.hasNext(DataSourceRDD.scala:112)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:221)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1371)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1298)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1362)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1186)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:360)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:311)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1391)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	... 3 more

**Comment by RussellSpitzer** [comment]
Do you have any more info on the repo for this?

**Comment by chenjunjiedada** [comment]
Thanks @RussellSpitzer to take care! It happens at the customer's table. I opened the issue to remind myself as I was busy. Let me inspect what's happened!

**Comment by chenjunjiedada** [comment]
I thought it is caused by the `ManifestFileUtil` bug. But we had fixed that issue internally.  After digging more, we found this is caused by our internal flink iceberg sink which appends manifest without partition summary.

**Comment by chenjunjiedada** [comment]
Still hit this problem.  Now I know how to reproduce this.

1. Write the iceberg table with the 0.10.0 version.
2. Read the iceberg table manifests with the 0.11.1 version.

The following code could fix the issue:
```
--- a/core/src/main/java/org/apache/iceberg/GenericPartitionFieldSummary.java
+++ b/core/src/main/java/org/apache/iceberg/GenericPartitionFieldSummary.java
@@ -121,7 +121,7 @@ public class GenericPartitionFieldSummary
 
   @Override
   public Boolean containsNaN() {
-    return containsNaN;
+    return containsNaN == null || containsNull;
   }
```

@RussellSpitzer @yyanyy, We may need to re-consider this with #2492 again.

**Comment by RussellSpitzer** [comment]
I think I have this fixed in #2495

**Comment by yyanyy** [comment]
I think it's expected that `summary.containsNaN()` could return null? looking from the code it seems that `StaticDataTask.Row` should also be able to handle null? when does the issue occur?

**Comment by chenjunjiedada** [comment]
@RussellSpitzer, `summary.containsNaN()` is called in two places, #2495 fixes one place. Another place is in #2509.

@yyanyy , I thought return boxed value in `summary.containsNaN()` may fix the problem for all places, while I don't want to break the original assumption. There is also a unit test for the null value. This issue happens when reading manifests as a table.

> ManifestTable.partitionSummarirsToRows puts summary.containsNaN(), which is null, to the spark row that will be parsed to Boolean class and show out.

**Comment by chenjunjiedada** [comment]
@yyanyy Looks like `StaticDataTask.Row` doesn't handle the null case. Do you think we should fix in that?

**Comment by RussellSpitzer** [comment]
@chenjunjiedada Good catch, we should definitely fix that, I also was a little worried about keeping the boxed boolean as the return value in containsNaN since we usually treat the parameter as a primitive, but I'm ok with just fixing the other occurrence for now, wdyt?

**Comment by RussellSpitzer** [comment]
I think if we make the changes @chenjunjiedada suggests (which I think are a good idea too), we should probably just change the signature to be a primitive and not the Boxed bool.

**Comment by RussellSpitzer** [comment]
I think for the StaticDataRow error we should be changing the Schema of Manifests table to mark containsNan as Optional

**Comment by yyanyy** [comment]
I think the `required` keyword in manifests table @RussellSpitzer pointed out is the culprit, I think `StaticDataTask.Row` should be able to handle null but since we marked `containsNan` as required in manifests table, it then throws the exception. And I agree with Russell that at least for showing manifest table, we probably don't want to mark `containsNan` as true if originally it's null/missing as it could be misleading.

If we indeed want to make `containsNan` a primitive everywhere, there would be other places to change including a [public facing interface](https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/ManifestFile.java#L209-L211) that are introduced in #1872 and [a case](https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/expressions/ManifestEvaluator.java#L164) that will produce less accurate result. However we haven't specify if we want `contains_nan` to be nullable or not [in spec](https://iceberg.apache.org/spec/#manifest-lists) so this decision might still be revertible.

I'll submit a PR to fix `required` field in manifests table and a separate PR to update spec so that we can have a wider audience and make a decision there. Meanwhile @RussellSpitzer @chenjunjiedada please let me know if you have further comments/concerns, and sorry for causing the issue!

**Comment by RussellSpitzer** [comment]
@yyanyy np :) It's a team effort. I think i'm pro just changing required -> Optional and in the future i'm going to be very strict about anyone using boxed primitives :P

**Comment by yyanyy** [comment]
Apologies for the delay, #2521 contains the two changes I planned to include as mentioned earlier, please take a look when you have time @RussellSpitzer @chenjunjiedada Thank you!
