### ISSUE TITLE
errors when creating catalog and tables

### ISSUE THREAD

**Issue by junsionzhang** [apache/iceberg#2422]
I. versions:
 hadoop(cluster): 2.9.2
 hive:2.3.6
 flink(standalone cluster): 1.12.2
II.steps
1.add jars to flink and hive
apache-hive-2.3.6-bin/lib/iceberg-hive-runtime-0.11.1.jar
flink-1.12.2/lib/iceberg-flink-runtime-0.11.1.jar

add variables to bin/config.sh
export HADOOP_CLASSPATH=$(/opt/hadoop/bin/hadoop classpath)
export HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop

2.run ./bin/sql-client.sh embedded 
2.1 CREATE CATALOG hadoop_catalog WITH (
 'type'='iceberg',
 'catalog-type'='hadoop',
  'clients'='5',
  'warehouse'='hdfs://NN:9000/iceberg/hadoop'
);
2.2 use catalog hadoop_catalog
2.3 create table sample_hive (
    id BIGINT COMMENT 'unique id',
    data STRING
);
**error**
Exception in thread "main" org.apache.flink.table.client.SqlClientException: Unexpected exception. This is a bug. Please consider filing an issue.
	at org.apache.flink.table.client.SqlClient.main(SqlClient.java:215)
Caused by: java.lang.NoSuchMethodError: org.apache.flink.table.api.TableColumn.isGenerated()Z
	at org.apache.iceberg.flink.FlinkCatalog.lambda$validateFlinkTable$2(FlinkCatalog.java:459)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.apache.iceberg.flink.FlinkCatalog.validateFlinkTable(FlinkCatalog.java:458)
	at org.apache.iceberg.flink.FlinkCatalog.createTable(FlinkCatalog.java:360)
	at org.apache.flink.table.catalog.CatalogManager.lambda$createTable$10(CatalogManager.java:633)
	at org.apache.flink.table.catalog.CatalogManager.execute(CatalogManager.java:790)
	at org.apache.flink.table.catalog.CatalogManager.createTable(CatalogManager.java:632)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeOperation(TableEnvironmentImpl.java:776)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:666)
	at org.apache.flink.table.client.gateway.local.LocalExecutor.lambda$executeSql$1(LocalExecutor.java:315)
	at org.apache.flink.table.client.gateway.local.ExecutionContext.wrapClassLoader(ExecutionContext.java:256)
	at org.apache.flink.table.client.gateway.local.LocalExecutor.executeSql(LocalExecutor.java:315)
	at org.apache.flink.table.client.cli.CliClient.callDdl(CliClient.java:739)
	at org.apache.flink.table.client.cli.CliClient.callDdl(CliClient.java:734)
	at org.apache.flink.table.client.cli.CliClient.callCommand(CliClient.java:330)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.apache.flink.table.client.cli.CliClient.open(CliClient.java:214)
	at org.apache.flink.table.client.SqlClient.openCli(SqlClient.java:144)
	at org.apache.flink.table.client.SqlClient.start(SqlClient.java:115)
	at org.apache.flink.table.client.SqlClient.main(SqlClient.java:201)

Shutting down the session...
done.
Exception in thread "Thread-5" java.lang.IllegalStateException: Trying to access closed classloader. Please check if you store classloaders directly or indirectly in static fields. If the stacktrace suggests that the leak occurs in a third party library and cannot be fixed immediately, you can disable this check with the configuration 'classloader.check-leaked-classloader'.
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$SafetyNetWrapperClassLoader.ensureInner(FlinkUserCodeClassLoaders.java:164)
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$SafetyNetWrapperClassLoader.getResource(FlinkUserCodeClassLoaders.java:183)
	at org.apache.hadoop.conf.Configuration.getResource(Configuration.java:2537)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2750)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2725)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2605)
	at org.apache.hadoop.conf.Configuration.get(Configuration.java:1103)

3.run ./bin/sql-client.sh embedded 
3.1 CREATE CATALOG hive_catalog WITH (
  'type'='iceberg',
  'catalog-type'='hive',
  'uri'='thrift://NODE1:9083',
  'clients'='5',
  'property-version'='1',
  'warehouse'='hdfs://NN:9000/iceberg/hive'
);

use catalog hive_catalog;

create table sample_hive (
    id BIGINT COMMENT 'unique id',
    data STRING
);

**error**
Exception in thread "main" org.apache.flink.table.client.SqlClientException: Unexpected exception. This is a bug. Please consider filing an issue.
	at org.apache.flink.table.client.SqlClient.main(SqlClient.java:215)
Caused by: java.lang.NoSuchMethodError: org.apache.flink.table.api.TableColumn.isGenerated()Z
	at org.apache.iceberg.flink.FlinkCatalog.lambda$validateFlinkTable$2(FlinkCatalog.java:459)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.apache.iceberg.flink.FlinkCatalog.validateFlinkTable(FlinkCatalog.java:458)
	at org.apache.iceberg.flink.FlinkCatalog.createTable(FlinkCatalog.java:360)
	at org.apache.flink.table.catalog.CatalogManager.lambda$createTable$10(CatalogManager.java:633)
	at org.apache.flink.table.catalog.CatalogManager.execute(CatalogManager.java:790)
	at org.apache.flink.table.catalog.CatalogManager.createTable(CatalogManager.java:632)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeOperation(TableEnvironmentImpl.java:776)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:666)
	at org.apache.flink.table.client.gateway.local.LocalExecutor.lambda$executeSql$1(LocalExecutor.java:315)
	at org.apache.flink.table.client.gateway.local.ExecutionContext.wrapClassLoader(ExecutionContext.java:256)
	at org.apache.flink.table.client.gateway.local.LocalExecutor.executeSql(LocalExecutor.java:315)
	at org.apache.flink.table.client.cli.CliClient.callDdl(CliClient.java:739)
	at org.apache.flink.table.client.cli.CliClient.callDdl(CliClient.java:734)
	at org.apache.flink.table.client.cli.CliClient.callCommand(CliClient.java:330)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.apache.flink.table.client.cli.CliClient.open(CliClient.java:214)
	at org.apache.flink.table.client.SqlClient.openCli(SqlClient.java:144)
	at org.apache.flink.table.client.SqlClient.start(SqlClient.java:115)
	at org.apache.flink.table.client.SqlClient.main(SqlClient.java:201)

**Comment by openinx** [comment]
> Caused by: java.lang.NoSuchMethodError: org.apache.flink.table.api.TableColumn.isGenerated()Z

This is because we are using the jar that was compiled in flink 1.11.x to run in flink 1.12 cluster.  I will suggest building a new  iceberg-flink-runtime jar from apache iceberg master branch to submit your flink jobs (Because we've upgraded the flink version in iceberg master branch, pls see [here](https://github.com/apache/iceberg/pull/1956/files#diff-0ae3022739b9b55183c9aa972fadb7cdb9cb3956468f14559b3c57c5900f3953L459))

**Comment by junsionzhang** [comment]
> here

hey，@openinx  thank you ,I will try it now.
