### ISSUE TITLE
Class not found error when use sink

### ISSUE THREAD

**Issue by ashwini-tgam** [apache/iceberg#2455]
While building in local I am trying to build sink data from kinesis to iceberg table till the stream is working fine while sink I see this error as class not found in scala flink job:

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/flink/table/runtime/typeutils/RowDataTypeInfo
	at io.sophi.platform.realtime.snowplow.enrich.bad.archiver.Job$.main(Job.scala:129)
	at io.sophi.platform.realtime.snowplow.enrich.bad.archiver.Job.main(Job.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.flink.table.runtime.typeutils.RowDataTypeInfo
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

How to resolve this?

**Comment by openinx** [comment]
@ashwini-tgam   The `RowDataTypeInfo` is a class that comes from flink 1.11,  in flink 1.12 the class was refactored to `InternalTypeInfo` (See https://github.com/apache/iceberg/pull/1956/files#diff-752b41f006e879a05750f3723df689214cdd629d8d9f48af76ed9f99c38d49b2R38).  So I think you are using flink-runtime jar that was compiled from flink 1.11 and then run the flink streaming job under flink 1.12 cluster ?   Pls check you flink-runtime jar version and flink cluster version.

**Comment by xianhaohihi** [comment]
hi, i've met the same problem with flink 1.12 when trying sink data to iceberg, have you already solve the problem?

**Comment by ashwini-tgam** [comment]
> @ashwini-tgam The `RowDataTypeInfo` is a class that comes from flink 1.11, in flink 1.12 the class was refactored to `InternalTypeInfo` (See https://github.com/apache/iceberg/pull/1956/files#diff-752b41f006e879a05750f3723df689214cdd629d8d9f48af76ed9f99c38d49b2R38). So I think you are using flink-runtime jar that was compiled from flink 1.11 and then run the flink streaming job under flink 1.12 cluster ? Pls check you flink-runtime jar version and flink cluster version.

I am using flink 1.11 in production which did not solve my issue

**Comment by ashwini-tgam** [comment]
> hi, i've met the same problem with flink 1.12 when trying sink data to iceberg, have you already solve the problem?

No I am not able to solve it but in production server it worked but never worked on my local
