### ISSUE TITLE
Hive aggregate query iceberg tables is failing with ArrayIndexOutOfBound exception using Hive Catalog

### ISSUE THREAD

**Issue by rakeshsayini** [apache/iceberg#2601]
Added this property in beeline: hive.vectorized.execution.enabled=false

The query  "select date_time,count(*) from db.tablename a group by date_time" is failing with below error. Same query works fine from spark.sql. If we select all columns it would work fine.

**Error:**
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
        at org.apache.iceberg.data.GenericRecord.get(GenericRecord.java:114)
        at org.apache.iceberg.mr.hive.serde.objectinspector.IcebergRecordObjectInspector.getStructFieldData(IcebergRecordObjectInspector.java:75)
        at org.apache.hadoop.hive.ql.exec.ExprNodeColumnEvaluator._evaluate(ExprNodeColumnEvaluator.java:95)
        at org.apache.hadoop.hive.ql.exec.ExprNodeEvaluator.evaluate(ExprNodeEvaluator.java:80)
        at org.apache.hadoop.hive.ql.exec.ExprNodeEvaluator.evaluate(ExprNodeEvaluator.java:68)
        at org.apache.hadoop.hive.ql.exec.SelectOperator.process(SelectOperator.java:88)

**Comment by pvary** [comment]
@rakeshsayini: Which version of Hive, Iceberg are you using?
Also, are you using MR or Tez as the execution engine?

The issue seems like #2171 which should be fixed by TEZ-4248.

CC: @marton-bod 

Thanks,
Peter

**Comment by rakeshsayini** [comment]
@pvary : Thanks @pvary . Following are the versions we had and seems there is no other work arounds till TEZ issue is fixed.
Hive 3.1
Spark 3.0.2 
IceBerg 0.11.1

**Comment by pvary** [comment]
You may want to try out upgrading the tez jar to a newer version. Tez 0.9.3 supposed to have this fix. Since it is only a minor version change from the Tez 0.9.1 originally contained in Hive 3.1.2, upgrading might be possible.

**Comment by rakeshsayini** [comment]
Thanks @pvary : Tez did not officially release 0.9.3 yet. They released  0.10.1,but it did not have the fix related to TEZ-4248 by that time.

**Comment by pvary** [comment]
That is sad 😢 
Is it possible for you to create and try out a patched build?
