### ISSUE TITLE
An error occurred when I started running Iceberg

### ISSUE THREAD

**Issue by Aload** [apache/iceberg#2669]
sql-client.sh embedded -j lib/iceberg-flink-runtime-0.11.1.jar -j lib/flink-sql-connector-hive-2.3.6_2.12-1.11.3.jar shell

Flink SQL> CREATE CATALOG h_catalog WITH (
>   'type'='iceberg',
>   'catalog-type'='hive',
>   'uri'='thrift://node1:9083',
>   'clients'='2',
>   'property-version'='1',
>   'warehouse'='hdfs://node1:8020/user/hive/warehouse'
> );

Exception in thread "main" org.apache.flink.table.client.SqlClientException: Unexpected exception. This is a bug. Please consider filing an issue.
        at org.apache.flink.table.client.SqlClient.main(SqlClient.java:213)
Caused by: java.lang.ExceptionInInitializerError
        at org.apache.iceberg.hive.HiveCatalog.initialize(HiveCatalog.java:154)
        at org.apache.iceberg.hive.HiveCatalog.<init>(HiveCatalog.java:147)
        at org.apache.iceberg.flink.CatalogLoader$HiveCatalogLoader.loadCatalog(CatalogLoader.java:112)
        at org.apache.iceberg.flink.FlinkCatalog.<init>(FlinkCatalog.java:111)
        at org.apache.iceberg.flink.FlinkCatalogFactory.createCatalog(FlinkCatalogFactory.java:127)
        at org.apache.iceberg.flink.FlinkCatalogFactory.createCatalog(FlinkCatalogFactory.java:117)
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.createCatalog(TableEnvironmentImpl.java:1087)
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeOperation(TableEnvironmentImpl.java:1021)
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:691)
        at org.apache.flink.table.client.gateway.local.LocalExecutor.lambda$executeSql$7(LocalExecutor.java:360)
        at org.apache.flink.table.client.gateway.local.ExecutionContext.wrapClassLoader(ExecutionContext.java:255)
        at org.apache.flink.table.client.gateway.local.LocalExecutor.executeSql(LocalExecutor.java:360)
        at org.apache.flink.table.client.cli.CliClient.callDdl(CliClient.java:642)
        at org.apache.flink.table.client.cli.CliClient.callDdl(CliClient.java:637)
        at org.apache.flink.table.client.cli.CliClient.callCommand(CliClient.java:357)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.apache.flink.table.client.cli.CliClient.open(CliClient.java:212)
        at org.apache.flink.table.client.SqlClient.openCli(SqlClient.java:142)
        at org.apache.flink.table.client.SqlClient.start(SqlClient.java:114)
        at org.apache.flink.table.client.SqlClient.main(SqlClient.java:201)
Caused by: java.lang.IllegalArgumentException: Unrecognized Hadoop major version number: 3.0.0-cdh6.3.2
        at org.apache.hadoop.hive.shims.ShimLoader.getMajorVersion(ShimLoader.java:174)
        at org.apache.hadoop.hive.shims.ShimLoader.loadShims(ShimLoader.java:139)
        at org.apache.hadoop.hive.shims.ShimLoader.getHadoopShims(ShimLoader.java:100)
        at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<clinit>(HiveConf.java:371)
        ... 20 more

**Comment by silvermissile** [comment]
`Caused by: java.lang.IllegalArgumentException: Unrecognized Hadoop major version number: 3.0.0-cdh6.3.2`  .
this link shows  support hadoop version 
https://github.com/apache/iceberg/blob/11562e38255e968079a6f5c8f6a0ce14b06825af/versions.props#L5
