### ISSUE TITLE
error when run flink-sql with iceberg table that has identifierFieldIds

### ISSUE THREAD

**Issue by moon-fall** [apache/iceberg#2679]
error like this 
Exception in thread "main" org.apache.flink.table.api.ValidationException: Could not create a PRIMARY KEY '17bb7db3-e030-4639-ba8a-ff74f78649f6'. Column 'id' is nullable.
	at org.apache.flink.table.api.TableSchema.validatePrimaryKey(TableSchema.java:468)
	at org.apache.flink.table.api.TableSchema.access$200(TableSchema.java:59)
	at org.apache.flink.table.api.TableSchema$Builder.build(TableSchema.java:698)
	at org.apache.iceberg.flink.FlinkSchemaUtil.toSchema(FlinkSchemaUtil.java:173)
	at org.apache.iceberg.flink.FlinkCatalog.toCatalogTable(FlinkCatalog.java:535)
	at org.apache.iceberg.flink.FlinkCatalog.getTable(FlinkCatalog.java:311)
	at org.apache.iceberg.flink.FlinkCatalog.getTable(FlinkCatalog.java:90)
	at org.apache.flink.table.catalog.CatalogManager.getPermanentTable(CatalogManager.java:412)
	at org.apache.flink.table.catalog.CatalogManager.getTable(CatalogManager.java:378)
	at org.apache.flink.table.planner.delegation.PlannerBase.getTableSink(PlannerBase.scala:335)
	at org.apache.flink.table.planner.delegation.PlannerBase.translateToRel(PlannerBase.scala:220)
	at org.apache.flink.table.planner.delegation.PlannerBase$$anonfun$1.apply(PlannerBase.scala:164)
	at org.apache.flink.table.planner.delegation.PlannerBase$$anonfun$1.apply(PlannerBase.scala:164)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.flink.table.planner.delegation.PlannerBase.translate(PlannerBase.scala:164)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.translate(TableEnvironmentImpl.java:1329)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:676)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeOperation(TableEnvironmentImpl.java:767)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:666)
	at CdcToIceberg.main(CdcToIceberg.java:89)

i think it should set the identifierFieldIds not null when convert iceberg schema to flink table schema?

**Comment by jackye1995** [comment]
I think this is because the Iceberg identifier field can be null, but Flink does not allow null primary key column. Is it the case for you? What is the type of `id` column in your Iceberg schema?

**Comment by jackye1995** [comment]
Sorry when I say type I was trying to ask if you have set your `id` column to be optional or not in Iceberg schema. If your `id` column is optional, I think this is expected behavior.

**Comment by moon-fall** [comment]
> Sorry when I say type I was trying to ask if you have set your `id` column to be optional or not in Iceberg schema. If your `id` column is optional, I think this is expected behavior.

I do set the `id` column  to be optional，and I set it to required  then it runs no error any more，thanks for your  response.
