### ISSUE TITLE
Read Iceberg Table via Hive: Hadoop Tables Succeed. Hive Catalog Failed. Anyone met the errors before?

### ISSUE THREAD

**Issue by aimenglin** [apache/iceberg#2686]
```
$hive
Hive Session ID = dbb0e1e7-041e-4664-bc7a-496e6c4bbf0c

Logging initialized using configuration in file:/etc/hive/conf.dist/hive-log4j2.properties Async: true
Hive Session ID = d3edbd13-c374-46ee-b392-290486cf07d0
hive> add jar /home/shenme_google_com/iceberg-hive-runtime.jar;
Added [/home/shenme_google_com/iceberg-hive-runtime.jar] to class path
Added resources: [/home/shenme_google_com/iceberg-hive-runtime.jar]
hive> set iceberg.engine.hive.enabled=true;
hive> set engine.hive.enabled=true;
hive> set iceberg.mr.catalog=hive;
hive> set hive.vectorized.execution.enabled=false;
hive> describe example3;
OK
id                      int                                         
name                    string                                      
major                   string                                      
grade                   string                                      
Time taken: 1.074 seconds, Fetched: 4 row(s)
hive> select * from example3;
Query ID = shenme_google_com_20210609213922_236d670a-a2eb-4772-947d-05c13a1ed13d
Total jobs = 1
Launching Job 1 out of 1
----------------------------------------------------------------------------------------------
        VERTICES      MODE        STATUS  TOTAL  COMPLETED  RUNNING  PENDING  FAILED  KILLED  
----------------------------------------------------------------------------------------------
Map 1            container  INITIALIZING     -1          0        0       -1       0       0  
----------------------------------------------------------------------------------------------
VERTICES: 00/01  [>>--------------------------] 0%    ELAPSED TIME: 0.68 s     
----------------------------------------------------------------------------------------------
Status: Failed
Vertex failed, vertexName=Map 1, vertexId=vertex_1622522135523_0068_1_00, diagnostics=[Vertex vertex_1622522135523_0068_1_00 [Map 1] killed/
failed due to:ROOT_INPUT_INIT_FAILURE, Vertex Input: example3 initializer failed, vertex=vertex_1622522135523_0068_1_00 [Map 1], java.io.IOE
xception: Cannot create an instance of InputFormat class org.apache.hadoop.mapred.FileInputFormat as specified in mapredWork!
        at org.apache.hadoop.hive.ql.io.HiveInputFormat.getInputFormatFromCache(HiveInputFormat.java:366)
        at org.apache.hadoop.hive.ql.io.HiveInputFormat.getSplits(HiveInputFormat.java:766)
        at org.apache.hadoop.hive.ql.exec.tez.HiveSplitGenerator.initialize(HiveSplitGenerator.java:243)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable$1.run(RootInputInitializerManager.java:279)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable$1.run(RootInputInitializerManager.java:270)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1762)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable.call(RootInputInitializerManager.java:270)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable.call(RootInputInitializerManager.java:254)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFu
tureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.InstantiationException
        at org.apache.hive.common.util.ReflectionUtil.newInstance(ReflectionUtil.java:85)
        at org.apache.hadoop.hive.ql.io.HiveInputFormat.getInputFormatFromCache(HiveInputFormat.java:358)
        ... 15 more
Caused by: java.lang.InstantiationException
        at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hive.common.util.ReflectionUtil.newInstance(ReflectionUtil.java:83)
        ... 16 more
]
DAG did not succeed due to VERTEX_FAILURE. failedVertices:1 killedVertices:0
FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.tez.TezTask. Vertex failed, vertexName=Map 1, vertexId=vertex_162
2522135523_0068_1_00, diagnostics=[Vertex vertex_1622522135523_0068_1_00 [Map 1] killed/failed due to:ROOT_INPUT_INIT_FAILURE, Vertex Input:
 example3 initializer failed, vertex=vertex_1622522135523_0068_1_00 [Map 1], java.io.IOException: Cannot create an instance of InputFormat c
lass org.apache.hadoop.mapred.FileInputFormat as specified in mapredWork!
        at org.apache.hadoop.hive.ql.io.HiveInputFormat.getInputFormatFromCache(HiveInputFormat.java:366)
        at org.apache.hadoop.hive.ql.io.HiveInputFormat.getSplits(HiveInputFormat.java:766)
        at org.apache.hadoop.hive.ql.exec.tez.HiveSplitGenerator.initialize(HiveSplitGenerator.java:243)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable$1.run(RootInputInitializerManager.java:279)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable$1.run(RootInputInitializerManager.java:270)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1762)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable.call(RootInputInitializerManager.java:270)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable.call(RootInputInitializerManager.java:254)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFu
tureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.InstantiationException
        at org.apache.hive.common.util.ReflectionUtil.newInstance(ReflectionUtil.java:85)
        at org.apache.hadoop.hive.ql.io.HiveInputFormat.getInputFormatFromCache(HiveInputFormat.java:358)
        ... 15 more
Caused by: java.lang.InstantiationException
        at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hive.common.util.ReflectionUtil.newInstance(ReflectionUtil.java:83)
        ... 16 more
]DAG did not succeed due to VERTEX_FAILURE. failedVertices:1 killedVertices:0
```

**Comment by aimenglin** [comment]
<friendly ping> Appreciate your help!

**Comment by marton-bod** [comment]
This looks like the table is missing the right storage handler and serde. My assumption would be that the "iceberg.hive.engine.enabled=true" property was missing from the config when the table was created - please check this section: https://github.com/apache/iceberg/blob/master/site/docs/hive.md#enabling-support. Can you send the `describe formatted testhive` output for this table to double check? Thanks!

**Comment by aimenglin** [comment]
@marton-bod Thanks for the response! Below are the queries and results:
```
$ hive
Hive Session ID = 01b4eccd-aae9-4cef-ae72-c1949f69a785
Logging initialized using configuration in file:/etc/hive/conf.dist/hive-log4j2.properties Async: true
Hive Session ID = b0f1c211-25a6-4ebd-85db-28c73431263f
hive> add jar /home/shenme_google_com/iceberg-hive-runtime.jar;
Added [/home/shenme_google_com/iceberg-hive-runtime.jar] to class path
Added resources: [/home/shenme_google_com/iceberg-hive-runtime.jar]
hive> set iceberg.engine.hive.enabled=true;
hive> set engine.hive.enabled=true;
hive> set iceberg.mr.catalog=hive;
hive> describe formatted testhive;
OK
# col_name              data_type               comment             
id                      int                                         
                 
# Detailed Table Information             
Database:               default                  
OwnerType:              USER                     
Owner:                  shenme_google_com        
CreateTime:             Sun Jun 06 23:13:31 UTC 2021     
LastAccessTime:         Fri Dec 26 11:39:34 UTC 1969     
Retention:              2147483647               
Location:               gs://gcs-bucket-shenme-test-service-7f1dbd01-5cc9-4393-a54a-e9c2b9c9/hive-warehouse/testhive     
Table Type:             EXTERNAL_TABLE           
Table Parameters:                
        EXTERNAL                TRUE                
        metadata_location       gs://gcs-bucket-shenme-test-service-7f1dbd01-5cc9-4393-a54a-e9c2b9c9/hive-warehouse/testhive/
metadata/00001-88fe51b7-ff5b-45ab-80e6-57ef3defef20.metadata.json
        numFiles                1                   
        previous_metadata_location      gs://gcs-bucket-shenme-test-service-7f1dbd01-5cc9-4393-a54a-e9c2b9c9/hive-warehouse/t
esthive/metadata/00000-145b061d-8bc7-4ea0-b997-05bd1c21fa92.metadata.json
        table_type              ICEBERG             
        totalSize               956                 
        transient_lastDdlTime   1623021211          
                 
# Storage Information            
SerDe Library:          org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe       
InputFormat:            org.apache.hadoop.mapred.FileInputFormat         
OutputFormat:           org.apache.hadoop.mapred.FileOutputFormat        
Compressed:             No                       
Num Buckets:            0                        
Bucket Columns:         []                       
Sort Columns:           []                       
Time taken: 1.068 seconds, Fetched: 29 row(s)
```

**Comment by aimenglin** [comment]
Update the queries and errors:
```
----------------------------------------------------------------------------------------------
        VERTICES      MODE        STATUS  TOTAL  COMPLETED  RUNNING  PENDING  FAILED  KILLED  
----------------------------------------------------------------------------------------------
Map 1            container  INITIALIZING     -1          0        0       -1       0       0  
----------------------------------------------------------------------------------------------
VERTICES: 00/01  [>>--------------------------] 0%    ELAPSED TIME: 0.68 s     
----------------------------------------------------------------------------------------------
Status: Failed
Vertex failed, vertexName=Map 1, vertexId=vertex_1622522135523_0068_1_00, diagnostics=[Vertex vertex_1622522135523_0068_1_00 [Map 1] killed/
failed due to:ROOT_INPUT_INIT_FAILURE, Vertex Input: example3 initializer failed, vertex=vertex_1622522135523_0068_1_00 [Map 1], java.io.IOE
xception: Cannot create an instance of InputFormat class org.apache.hadoop.mapred.FileInputFormat as specified in mapredWork!
        at org.apache.hadoop.hive.ql.io.HiveInputFormat.getInputFormatFromCache(HiveInputFormat.java:366)
        at org.apache.hadoop.hive.ql.io.HiveInputFormat.getSplits(HiveInputFormat.java:766)
        at org.apache.hadoop.hive.ql.exec.tez.HiveSplitGenerator.initialize(HiveSplitGenerator.java:243)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable$1.run(RootInputInitializerManager.java:279)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable$1.run(RootInputInitializerManager.java:270)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1762)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable.call(RootInputInitializerManager.java:270)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable.call(RootInputInitializerManager.java:254)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFu
tureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.InstantiationException
        at org.apache.hive.common.util.ReflectionUtil.newInstance(ReflectionUtil.java:85)
        at org.apache.hadoop.hive.ql.io.HiveInputFormat.getInputFormatFromCache(HiveInputFormat.java:358)
        ... 15 more
Caused by: java.lang.InstantiationException
        at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hive.common.util.ReflectionUtil.newInstance(ReflectionUtil.java:83)
        ... 16 more
]
DAG did not succeed due to VERTEX_FAILURE. failedVertices:1 killedVertices:0
FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.tez.TezTask. Vertex failed, vertexName=Map 1, vertexId=vertex_162
2522135523_0068_1_00, diagnostics=[Vertex vertex_1622522135523_0068_1_00 [Map 1] killed/failed due to:ROOT_INPUT_INIT_FAILURE, Vertex Input:
 example3 initializer failed, vertex=vertex_1622522135523_0068_1_00 [Map 1], java.io.IOException: Cannot create an instance of InputFormat c
lass org.apache.hadoop.mapred.FileInputFormat as specified in mapredWork!
        at org.apache.hadoop.hive.ql.io.HiveInputFormat.getInputFormatFromCache(HiveInputFormat.java:366)
        at org.apache.hadoop.hive.ql.io.HiveInputFormat.getSplits(HiveInputFormat.java:766)
        at org.apache.hadoop.hive.ql.exec.tez.HiveSplitGenerator.initialize(HiveSplitGenerator.java:243)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable$1.run(RootInputInitializerManager.java:279)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable$1.run(RootInputInitializerManager.java:270)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1762)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable.call(RootInputInitializerManager.java:270)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable.call(RootInputInitializerManager.java:254)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFu
tureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.InstantiationException
        at org.apache.hive.common.util.ReflectionUtil.newInstance(ReflectionUtil.java:85)
        at org.apache.hadoop.hive.ql.io.HiveInputFormat.getInputFormatFromCache(HiveInputFormat.java:358)
        ... 15 more
Caused by: java.lang.InstantiationException
        at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hive.common.util.ReflectionUtil.newInstance(ReflectionUtil.java:83)
        ... 16 more
]DAG did not succeed due to VERTEX_FAILURE. failedVertices:1 killedVertices:0
```

**Comment by marton-bod** [comment]
Can you please append the `engine.hive.enabled=true` to the table properties, via:
`ALTER TABLE tbl_name SET TBLPROPERTIES ('engine.hive.enabled'='true');`
Afterwards, the read queries should work fine.

**Comment by aimenglin** [comment]
@marton-bod I'm following your instruction when I created the table on Spark. But when I **inserted data on Hive**, it still cannot be read. Do I misunderstand anything here?

**Comment by aimenglin** [comment]
@marton-bod Solved the problem! Thank you so much!

**Comment by pvary** [comment]
@aimenglin: Could you please help us by describing how the problem was solved, so we can help others in the same situation?

Thanks,
Peter

**Comment by aimenglin** [comment]
@pvary I add ```table.updateProperties().set("engine.hive.enabled", "true").commit()``` when I created the table on Spark.

**Comment by jhsenjaliya** [comment]
@aimenglin , once you add engine.hive.enabled to table properties ( as @marton-bod suggested) it works for me, i was having same issue before. ( I also had to disable vectorized execution as suggested by the iceberg docs, or u can follow the warning. ) - good luck.

**Comment by pvary** [comment]
Thanks for the info @aimenglin  and @jhsenjaliya! Hope this will help the next users facing the issue.

I will close this issue as we have a solution.

Peter

**Comment by HamaWhiteGG** [comment]
@marton-bod thanks,  add  'engine.hive.enabled' = 'true'   can solved the problem.

  execute("CREATE TABLE IF NOT EXISTS  flink_iceberg_table ( " +
                "       id                  BIGINT                          ," +
                "       data                STRING                           " +
                ") WITH ( " +
                "       'connector' = 'iceberg'                             ," +
                "       'catalog-name' = 'iceberg'                          ," +
                "       'catalog-type' = 'hive'                             ," +
                "       'catalog-database' = 'flink_demo'                   ," +
                "       'catalog-table' = 'iceberg_table'                   ," +
                "       'uri' = 'thrift://192.168.90.150:9083'              ," +
                "       'engine.hive.enabled' = 'true'                      ," +
                "       'warehouse' = '" + WAREHOUSE + "'                    " +
                ")"
        );

**Comment by 0xffmeta** [comment]
Seems when I created the table, I didn't sepcify `engine.hive.enabled=true` in the table properties. But this seems to be required duirng the table creation, otherwise it will not work with `ALTER TABLE xx set TBLPROPERTIES`.
Is there any workaround for this? Or I need to re-create the table.

**Comment by luoyuxia** [comment]
@0xffmeta 
Does the following command work?
```sql
ALTER TABLE flink_local_nohive SET SERDEPROPERTIES (
    'storage_handler' = 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler',
);
ALTER TABLE flink_local_nohive SET FILEFORMAT
    INPUTFORMAT 'org.apache.iceberg.mr.hive.HiveIcebergInputFormat'
    OUTPUTFORMAT 'org.apache.iceberg.mr.hive.HiveIcebergOutputFormat'
    SERDE 'org.apache.iceberg.mr.hive.HiveIcebergSerDe';
```
There is pr #3539 is for such case, you can refer it for more details.

**Comment by 0xffmeta** [comment]
Thanks @luoyuxia. It's working now.
