### ISSUE TITLE
Encounter UnsupportedOperationException  when describing the spark table schema after we dropped the partitioned fields

### ISSUE THREAD

**Issue by openinx** [apache/iceberg#2710]
There's an original iceberg table in my aliyun cloud: 

```sql
ss_sold_time_sk	bigint	
ss_item_sk	bigint	
ss_customer_sk	bigint	
ss_cdemo_sk	bigint	
ss_hdemo_sk	bigint	
ss_addr_sk	bigint	
ss_store_sk	bigint	
ss_promo_sk	bigint	
ss_ticket_number	bigint	
ss_quantity	int	
ss_wholesale_cost	decimal(7,2)	
ss_list_price	decimal(7,2)	
ss_sales_price	decimal(7,2)	
ss_ext_discount_amt	decimal(7,2)	
ss_ext_sales_price	decimal(7,2)	
ss_ext_wholesale_cost	decimal(7,2)	
ss_ext_list_price	decimal(7,2)	
ss_ext_tax	decimal(7,2)	
ss_coupon_amt	decimal(7,2)	
ss_net_paid	decimal(7,2)	
ss_net_paid_inc_tax	decimal(7,2)	
ss_net_profit	decimal(7,2)	
ss_sold_date_sk	bigint	
		
# Partitioning		
Part 0	bucket(200, ss_sold_date_sk)	
Time taken: 0.19 seconds, Fetched 26 row(s)
```

After we dropped the partitioned fields `ss_sold_date_sk` by the following SQL: 

```sql
ALTER TABLE emr_dlf_catalog.emr_dlf_db.store_sales DROP PARTITION FIELD bucket(200, ss_sold_date_sk);
```

And we are trying to describe the iceberg table schema we will encounter the exception: 

```
spark-sql> describe emr_dlf_catalog.emr_dlf_db.store_sales
         > ;
21/06/18 12:09:53 INFO [main] BaseMetastoreTableOperations: Refreshing table metadata from new version: oss://emr-iceberg/warehouse/emr_dlf_db.db/store_sales/metadata/00003-7cdf5364-3110-4779-b1ef-23d871fa4cab.metadata.json
21/06/18 12:09:53 ERROR [main] SparkSQLDriver: Failed in [describe emr_dlf_catalog.emr_dlf_db.store_sales]
java.lang.UnsupportedOperationException: Void transform is not supported
	at org.apache.iceberg.transforms.PartitionSpecVisitor.alwaysNull(PartitionSpecVisitor.java:86)
	at org.apache.iceberg.transforms.PartitionSpecVisitor.visit(PartitionSpecVisitor.java:148)
	at org.apache.iceberg.transforms.PartitionSpecVisitor.visit(PartitionSpecVisitor.java:120)
	at org.apache.iceberg.transforms.PartitionSpecVisitor.visit(PartitionSpecVisitor.java:102)
	at org.apache.iceberg.spark.Spark3Util.toTransforms(Spark3Util.java:258)
	at org.apache.iceberg.spark.source.SparkTable.partitioning(SparkTable.java:130)
	at org.apache.spark.sql.execution.datasources.v2.DescribeTableExec.addPartitioning(DescribeTableExec.scala:78)
	at org.apache.spark.sql.execution.datasources.v2.DescribeTableExec.run(DescribeTableExec.scala:41)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:39)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:39)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:45)
	at org.apache.spark.sql.Dataset.$anonfun$logicalPlan$1(Dataset.scala:229)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3618)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:100)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:160)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:87)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3616)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:229)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:100)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:607)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:602)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:650)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLDriver.run(SparkSQLDriver.scala:63)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processCmd(SparkSQLCLIDriver.scala:377)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.$anonfun$processLine$1(SparkSQLCLIDriver.scala:496)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processLine(SparkSQLCLIDriver.scala:490)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:282)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
java.lang.UnsupportedOperationException: Void transform is not supported
	at org.apache.iceberg.transforms.PartitionSpecVisitor.alwaysNull(PartitionSpecVisitor.java:86)
	at org.apache.iceberg.transforms.PartitionSpecVisitor.visit(PartitionSpecVisitor.java:148)
	at org.apache.iceberg.transforms.PartitionSpecVisitor.visit(PartitionSpecVisitor.java:120)
	at org.apache.iceberg.transforms.PartitionSpecVisitor.visit(PartitionSpecVisitor.java:102)
	at org.apache.iceberg.spark.Spark3Util.toTransforms(Spark3Util.java:258)
	at org.apache.iceberg.spark.source.SparkTable.partitioning(SparkTable.java:130)
	at org.apache.spark.sql.execution.datasources.v2.DescribeTableExec.addPartitioning(DescribeTableExec.scala:78)
	at org.apache.spark.sql.execution.datasources.v2.DescribeTableExec.run(DescribeTableExec.scala:41)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:39)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:39)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:45)
	at org.apache.spark.sql.Dataset.$anonfun$logicalPlan$1(Dataset.scala:229)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3618)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:100)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:160)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:87)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3616)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:229)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:100)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:607)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:602)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:650)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLDriver.run(SparkSQLDriver.scala:63)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processCmd(SparkSQLCLIDriver.scala:377)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.$anonfun$processLine$1(SparkSQLCLIDriver.scala:496)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processLine(SparkSQLCLIDriver.scala:490)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:282)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

I think it's a critial bug that we should fixed in our apache iceberg (still not dig into this bug), will publish a PR to fix this if it's true.

**Comment by openinx** [comment]
The current table metadata json file for this testing table is: 

```json
{
  "format-version" : 1,
  "table-uuid" : "e38f4202-f28f-4ae9-b2d1-21af112db2cc",
  "location" : "oss://emr-iceberg/warehouse/emr_dlf_db.db/store_sales",
  "last-updated-ms" : 1623988963494,
  "last-column-id" : 23,
  "schema" : {
    "type" : "struct",
    "schema-id" : 0,
    "fields" : [ {
      "id" : 1,
      "name" : "ss_sold_time_sk",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 2,
      "name" : "ss_item_sk",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 3,
      "name" : "ss_customer_sk",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 4,
      "name" : "ss_cdemo_sk",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 5,
      "name" : "ss_hdemo_sk",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 6,
      "name" : "ss_addr_sk",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 7,
      "name" : "ss_store_sk",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 8,
      "name" : "ss_promo_sk",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 9,
      "name" : "ss_ticket_number",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 10,
      "name" : "ss_quantity",
      "required" : false,
      "type" : "int"
    }, {
      "id" : 11,
      "name" : "ss_wholesale_cost",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 12,
      "name" : "ss_list_price",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 13,
      "name" : "ss_sales_price",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 14,
      "name" : "ss_ext_discount_amt",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 15,
      "name" : "ss_ext_sales_price",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 16,
      "name" : "ss_ext_wholesale_cost",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 17,
      "name" : "ss_ext_list_price",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 18,
      "name" : "ss_ext_tax",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 19,
      "name" : "ss_coupon_amt",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 20,
      "name" : "ss_net_paid",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 21,
      "name" : "ss_net_paid_inc_tax",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 22,
      "name" : "ss_net_profit",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 23,
      "name" : "ss_sold_date_sk",
      "required" : false,
      "type" : "long"
    } ]
  },
  "current-schema-id" : 0,
  "schemas" : [ {
    "type" : "struct",
    "schema-id" : 0,
    "fields" : [ {
      "id" : 1,
      "name" : "ss_sold_time_sk",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 2,
      "name" : "ss_item_sk",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 3,
      "name" : "ss_customer_sk",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 4,
      "name" : "ss_cdemo_sk",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 5,
      "name" : "ss_hdemo_sk",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 6,
      "name" : "ss_addr_sk",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 7,
      "name" : "ss_store_sk",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 8,
      "name" : "ss_promo_sk",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 9,
      "name" : "ss_ticket_number",
      "required" : false,
      "type" : "long"
    }, {
      "id" : 10,
      "name" : "ss_quantity",
      "required" : false,
      "type" : "int"
    }, {
      "id" : 11,
      "name" : "ss_wholesale_cost",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 12,
      "name" : "ss_list_price",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 13,
      "name" : "ss_sales_price",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 14,
      "name" : "ss_ext_discount_amt",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 15,
      "name" : "ss_ext_sales_price",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 16,
      "name" : "ss_ext_wholesale_cost",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 17,
      "name" : "ss_ext_list_price",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 18,
      "name" : "ss_ext_tax",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 19,
      "name" : "ss_coupon_amt",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 20,
      "name" : "ss_net_paid",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 21,
      "name" : "ss_net_paid_inc_tax",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 22,
      "name" : "ss_net_profit",
      "required" : false,
      "type" : "decimal(7, 2)"
    }, {
      "id" : 23,
      "name" : "ss_sold_date_sk",
      "required" : false,
      "type" : "long"
    } ]
  } ],
  "partition-spec" : [ {
    "name" : "ss_sold_date_sk_bucket",
    "transform" : "void",
    "source-id" : 23,
    "field-id" : 1000
  } ],
  "default-spec-id" : 1,
  "partition-specs" : [ {
    "spec-id" : 0,
    "fields" : [ {
      "name" : "ss_sold_date_sk_bucket",
      "transform" : "bucket[200]",
      "source-id" : 23,
      "field-id" : 1000
    } ]
  }, {
    "spec-id" : 1,
    "fields" : [ {
      "name" : "ss_sold_date_sk_bucket",
      "transform" : "void",
      "source-id" : 23,
      "field-id" : 1000
    } ]
  } ],
  "last-partition-id" : 1000,
  "default-sort-order-id" : 0,
  "sort-orders" : [ {
    "order-id" : 0,
    "fields" : [ ]
  } ],
  "properties" : {
    "owner" : "root"
  },
  "current-snapshot-id" : 6150124945094061685,
  "snapshots" : [ {
    "snapshot-id" : 1616121965204544780,
    "timestamp-ms" : 1623912758210,
    "summary" : {
      "operation" : "append",
      "spark.app.id" : "application_1623232753519_0011",
      "added-data-files" : "1",
      "added-records" : "10",
      "added-files-size" : "7764",
      "changed-partition-count" : "1",
      "total-records" : "10",
      "total-files-size" : "7764",
      "total-data-files" : "1",
      "total-delete-files" : "0",
      "total-position-deletes" : "0",
      "total-equality-deletes" : "0"
    },
    "manifest-list" : "oss://emr-iceberg/warehouse/emr_dlf_db.db/store_sales/metadata/snap-1616121965204544780-1-0892fb81-c77d-4653-9ad0-e48b4245a2fe.avro"
  }, {
    "snapshot-id" : 6150124945094061685,
    "parent-snapshot-id" : 1616121965204544780,
    "timestamp-ms" : 1623973911363,
    "summary" : {
      "operation" : "append",
      "spark.app.id" : "application_1623232753519_0011",
      "added-data-files" : "16261",
      "added-records" : "28800426268",
      "added-files-size" : "1123112440679",
      "changed-partition-count" : "201",
      "total-records" : "28800426278",
      "total-files-size" : "1123112448443",
      "total-data-files" : "16262",
      "total-delete-files" : "0",
      "total-position-deletes" : "0",
      "total-equality-deletes" : "0"
    },
    "manifest-list" : "oss://emr-iceberg/warehouse/emr_dlf_db.db/store_sales/metadata/snap-6150124945094061685-1-86dbe856-c57b-4f5b-aea3-84fd34471329.avro"
  } ],
  "snapshot-log" : [ {
    "timestamp-ms" : 1623912758210,
    "snapshot-id" : 1616121965204544780
  }, {
    "timestamp-ms" : 1623973911363,
    "snapshot-id" : 6150124945094061685
  } ],
  "metadata-log" : [ {
    "timestamp-ms" : 1623233762317,
    "metadata-file" : "oss://emr-iceberg/warehouse/emr_dlf_db.db/store_sales/metadata/00000-585dbe4e-c573-490b-841b-e909e898923a.metadata.json"
  }, {
    "timestamp-ms" : 1623912758210,
    "metadata-file" : "oss://emr-iceberg/warehouse/emr_dlf_db.db/store_sales/metadata/00001-2d30ab82-9026-425c-bdd3-31a29048a723.metadata.json"
  }, {
    "timestamp-ms" : 1623973911363,
    "metadata-file" : "oss://emr-iceberg/warehouse/emr_dlf_db.db/store_sales/metadata/00002-aa0facf2-75a5-422e-971e-c53ac88d7f3d.metadata.json"
  } ]
}
```

**Comment by openinx** [comment]
Okay,  we apache master branch had a fixed for  this https://github.com/apache/iceberg/pull/2454.  Close this issue now.
