### ISSUE TITLE
org.apache.flink.table.api.TableException: Required context of factory

### ISSUE THREAD

**Issue by yunfeng79** [apache/iceberg#2814]
flink-1.13.1
CREATE CATALOG hive_catalog WITH (
'type'='iceberg',
'catalog-type'='hive',
'uri'='thrift://localhost:9083',
'clients'='5',
'property-version'='1',
'warehouse'='hdfs://localhost:9000/user/hive/warehouse'
);

[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.table.api.TableException: Required context of factory 'org.apache.flink.table.catalog.hive.factories.HiveCatalogFactory' must not be null.

**Comment by windylcx** [comment]
flink-1.16.3  the  same issue

org.apache.flink.table.client.gateway.SqlExecutionException: Could not execute SQL statement.
	at org.apache.flink.table.client.gateway.local.LocalExecutor.executeOperation(LocalExecutor.java:208) ~[flink-sql-client-1.16.3.jar:1.16.3]
	at org.apache.flink.table.client.cli.CliClient.executeOperation(CliClient.java:639) ~[flink-sql-client-1.16.3.jar:1.16.3]
	at org.apache.flink.table.client.cli.CliClient.callOperation(CliClient.java:473) [flink-sql-client-1.16.3.jar:1.16.3]
	at org.apache.flink.table.client.cli.CliClient.executeOperation(CliClient.java:372) [flink-sql-client-1.16.3.jar:1.16.3]
	at org.apache.flink.table.client.cli.CliClient.getAndExecuteStatements(CliClient.java:329) [flink-sql-client-1.16.3.jar:1.16.3]
	at org.apache.flink.table.client.cli.CliClient.executeInteractive(CliClient.java:280) [flink-sql-client-1.16.3.jar:1.16.3]
	at org.apache.flink.table.client.cli.CliClient.executeInInteractiveMode(CliClient.java:228) [flink-sql-client-1.16.3.jar:1.16.3]
	at org.apache.flink.table.client.SqlClient.openCli(SqlClient.java:151) [flink-sql-client-1.16.3.jar:1.16.3]
	at org.apache.flink.table.client.SqlClient.start(SqlClient.java:95) [flink-sql-client-1.16.3.jar:1.16.3]
	at org.apache.flink.table.client.SqlClient.startClient(SqlClient.java:187) [flink-sql-client-1.16.3.jar:1.16.3]
	at org.apache.flink.table.client.SqlClient.main(SqlClient.java:161) [flink-sql-client-1.16.3.jar:1.16.3]
Caused by: org.apache.flink.table.api.TableException: Required context of factory 'org.apache.flink.table.catalog.hive.factories.HiveCatalogFactory' must not be null.
	at org.apache.flink.table.factories.TableFactoryService.normalizeContext(TableFactoryService.java:353) ~[flink-table-api-java-uber-1.16.3.jar:1.16.3]
	at org.apache.flink.table.factories.TableFactoryService.filterByContext(TableFactoryService.java:248) ~[flink-table-api-java-uber-1.16.3.jar:1.16.3]
	at org.apache.flink.table.factories.TableFactoryService.filter(TableFactoryService.java:191) ~[flink-table-api-java-uber-1.16.3.jar:1.16.3]
	at org.apache.flink.table.factories.TableFactoryService.findSingleInternal(TableFactoryService.java:152) ~[flink-table-api-java-uber-1.16.3.jar:1.16.3]
	at org.apache.flink.table.factories.TableFactoryService.find(TableFactoryService.java:121) ~[flink-table-api-java-uber-1.16.3.jar:1.16.3]
	at org.apache.flink.table.factories.FactoryUtil.createCatalog(FactoryUtil.java:413) ~[flink-table-api-java-uber-1.16.3.jar:1.16.3]
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.createCatalog(TableEnvironmentImpl.java:1426) ~[flink-table-api-java-uber-1.16.3.jar:1.16.3]
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1172) ~[flink-table-api-java-uber-1.16.3.jar:1.16.3]
	at org.apache.flink.table.client.gateway.local.LocalExecutor.executeOperation(LocalExecutor.java:206) ~[flink-sql-client-1.16.3.jar:1.16.3]
	... 10 more
