### ISSUE TITLE
Parquet 1.11.1 causes regressions while reading iceberg data written with v1.11.0

### ISSUE THREAD

**Issue by prodeezy** [apache/iceberg#2962]
As part of https://github.com/apache/iceberg/issues/1441 Parquet version was updated from 1.11.0 to 1.11.1. After rebasing our internal version with latest changes from master  we found that certain fields written with iceberg using Parquet v1.11.0 are not readable with iceberg built against Parquet  v1.11.1

**Error:**
```
java.lang.IllegalArgumentException: [segmentMembership, map, key] required binary key (STRING) = 9 is not in the store: [[identityMap, map, key] required binary key (STRING) = 3, [identityMap, map, value, list, element, id] optional binary id (STRING) = 7, [identityMap, map, value, list, element, authenticatedState] optional binary authenticatedState (STRING) = 6, [identityMap, map, value, list, element, primary] optional boolean primary = 8] 4
	at org.apache.iceberg.shaded.org.apache.parquet.hadoop.ColumnChunkPageReadStore.getPageReader(ColumnChunkPageReadStore.java:231)
	at org.apache.iceberg.parquet.ParquetValueReaders$PrimitiveReader.setPageSource(ParquetValueReaders.java:185)
	at org.apache.iceberg.parquet.ParquetValueReaders$RepeatedKeyValueReader.setPageSource(ParquetValueReaders.java:529)
	at org.apache.iceberg.parquet.ParquetValueReaders$StructReader.setPageSource(ParquetValueReaders.java:685)
	at org.apache.iceberg.parquet.ParquetReader$FileIterator.advance(ParquetReader.java:142)
	at org.apache.iceberg.parquet.ParquetReader$FileIterator.next(ParquetReader.java:112)
	at org.apache.iceberg.io.FilterIterator.advance(FilterIterator.java:66)
	at org.apache.iceberg.io.FilterIterator.hasNext(FilterIterator.java:50)
	at org.apache.iceberg.spark.source.BaseDataReader.next(BaseDataReader.java:87)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.hasNext(DataSourceRDD.scala:49)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:640)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:117)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:116)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1560)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:146)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:67)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:66)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:139)
	at org.apache.spark.scheduler.Task.run(Task.scala:112)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$13.apply(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1526)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:503)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Field in question is of this form:

```
 |-- segmentMembership: map (nullable = true)
 |    |-- key: string
 |    |-- value: map (valueContainsNull = true)
 |    |    |-- key: string
 |    |    |-- value: struct (valueContainsNull = true)
 |    |    |    |-- payload: struct (nullable = true)
 |    |    |    |    |-- boolA: boolean (nullable = true)
 |    |    |    |    |-- doubleValueA: double (nullable = true)
 |    |    |    |    |-- doubleValueB: double (nullable = true)
 |    |    |    |    |-- stringValueA: string (nullable = true)
 |    |    |    |    |-- stringValueB: string (nullable = true)
 |    |    |    |-- status: string (nullable = true)
 |    |    |    |-- lastQualificationTime: timestamp (nullable = true)
```

**Comment by prodeezy** [comment]
Will create a gist to repro this issue. Wondering if others are facing this as well.

**Comment by prodeezy** [comment]
changes in 1.11.1 since 1.11.0 

https://github.com/apache/parquet-mr/blob/apache-parquet-1.11.1/CHANGES.md

**Comment by julienledem** [comment]
I don't have much insight in this change but this looks suspicious:
https://github.com/apache/parquet-mr/commit/32e9578894506df07d65bbeb012a44ec7746ddcb
From: 
https://github.com/apache/parquet-mr/compare/apache-parquet-1.11.0...apache-parquet-1.11.1

**Comment by prodeezy** [comment]
Sample data written using Iceberg v0.9.0 (with parquet 1.11.0) : https://drive.google.com/drive/folders/1GckUAYZpOYJQtkTFtavKzpqxKzXkCbqy?usp=sharing

Fails when reading using code from tag: apache-iceberg-0.10.0

```
spark-shell --jars spark-runtime/build/libs/iceberg-spark-runtime-0.10.0.jar

 > spark.read.format("iceberg").load("iceberg_issue_2962_parquet_1_11_0").show(false)

[Stage 0:>   (0 + 1) / 1]2021-08-12 17:58:28 ERROR Executor:91 - Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.IllegalArgumentException: [segmentMembership, map, key] required binary key (STRING) = 2 is not in the store: [] 8
```


If i switch to parquet 1.11.0 and rebuild, it starts reading just fine.
```
scala> spark.read.format("iceberg").load("/tools/iceberg_issue_2962_parquet_1_11_0").show(false)
+------------------------------------------------------------------------------------------------+
|segmentMembership                                                                               |
+------------------------------------------------------------------------------------------------+
|[AEPSegmentMatch -> []]                                                                         |
|[AEPSegmentMatch -> []]                                                                         |
|[AEPSegmentMatch -> []]                                                                         |
|[AEPSegmentMatch -> []]                                                                         |
|[AEPSegmentMatch -> [cea3dda5-5604-4548-a031-148867e425b5 -> [, existing, 2021-04-28 03:34:36]]]|
|[AEPSegmentMatch -> [cea3dda5-5604-4548-a031-148867e425b5 -> [, existing, 2021-04-28 03:34:36]]]|
|[AEPSegmentMatch -> [cea3dda5-5604-4548-a031-148867e425b5 -> [, existing, 2021-04-28 03:34:37]]]|
|[AEPSegmentMatch -> [cea3dda5-5604-4548-a031-148867e425b5 -> [, existing, 2021-04-28 03:34:37]]]|
+------------------------------------------------------------------------------------------------+
```

**Comment by rdblue** [comment]
I agree with Julien that https://github.com/apache/parquet-mr/commit/32e9578894506df07d65bbeb012a44ec7746ddcb looks suspicious. That changed "map" to "key_value" so we see that the data used the old version. @prodeezy, can you debug to fine where that exception is being created to see what's going on?

**Comment by hankfanchiu** [comment]
We've also encountered this issue, after updating our internal fork from 0.9.0 to 0.12.0.

Comparing the Parquet schemas of the outputs written with Iceberg 0.9.0 and with Iceberg 0.12.0, we see that only the name of the middle level was changed from `map` (Iceberg 0.9.0, Parquet 1.11.0) to `key_value` (Iceberg 0.12.0, Parquet 1.12.0), e.g.:

```diff
@@ -1,6 +1,6 @@
   optional group my_optional_map (MAP) = 9 {
-    repeated group map {
+    repeated group key_value {
       required binary key (STRING) = 13;
       required group value = 14 {
         optional group values (LIST) = 15 {
```

As a temporary workaround, while still on Iceberg 0.12.0, we've downgraded the version of Parquet from 1.12.0 back to 1.11.0.

**Comment by kbendick** [comment]
Hi @prodeezy @hankfanchiu , sorry for the delay in getting back to you on this. I was looking into a different parquet issue,[ PARQUET-2078](https://issues.apache.org/jira/browse/PARQUET-2078) so my apologies for overlooking this one.

I'm also able to reproduce this using Spark 3.1.2 with Iceberg 0.9.0 (compile only paquet@1.11.0) to Iceberg 0.11.0 (compile only parquet@1.11.1).

I get the same error
```
java.lang.IllegalArgumentException: [mapCol, key_value, key] required binary key (STRING) = 2 is not in the store: [] 12
	at org.apache.iceberg.shaded.org.apache.parquet.hadoop.ColumnChunkPageReadStore.getPageReader(ColumnChunkPageReadStore.java:231)
	at org.apache.iceberg.parquet.ParquetValueReaders$PrimitiveReader.setPageSource(ParquetValueReaders.java:154)
	at org.apache.iceberg.parquet.ParquetValueReaders$RepeatedKeyValueReader.setPageSource(ParquetValueReaders.java:487)
	at org.apache.iceberg.parquet.ParquetValueReaders$StructReader.setPageSource(ParquetValueReaders.java:643)
	at org.apache.iceberg.parquet.ParquetReader$FileIterator.advance(ParquetReader.java:139)
	at org.apache.iceberg.parquet.ParquetReader$FileIterator.next(ParquetReader.java:110)
	at org.apache.iceberg.spark.source.BaseDataReader.next(BaseDataReader.java:69)
	at org.apache.spark.sql.execution.datasources.v2.PartitionIterator.hasNext(DataSourceRDD.scala:79)
	at org.apache.spark.sql.execution.datasources.v2.MetricsIterator.hasNext(DataSourceRDD.scala:112)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Here's my minimal reproduction:

I downloaded the Spark tarball for 3.1.2 from https://archive.apache.org/dist/spark/spark-3.1.2/spark-3.1.2-bin-hadoop2.7.tgz, untarred it, and created a test table similar to yours.

**Notice that by default, it's parquet-1.10.1, so I removed the parquet jars from /opt/spark/jars**
```bash
# Note that this is parquet 1.10.1 using Apache Spark 3.1.2.
root@spark:/opt/spark# ls -la jars | grep parquet
parquet-column-1.10.1.jar  parquet-common-1.10.1.jar  parquet-encoding-1.10.1.jar  parquet-format-2.4.0.jar  parquet-hadoop-1.10.1.jar  parquet-jackson-1.10.1.jar

root@spark:/opt/spark# rm -f jars/parquet-*

root@spark-box:/opt/spark# ./bin/spark-shell     --packages org.apache.iceberg:iceberg-spark3-runtime:0.9.0    --driver-memory 2g     --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog     --conf spark.sql.catalog.spark_catalog.type=hive      --conf spark.hadoop.hive.metastore.uris=thrift://hive:9083
```

```scala
scala>  import spark.implicits._
import spark.implicits._

scala> import org.apache.spark.sql._
import org.apache.spark.sql._

scala> import org.apache.spark.sql.functions._
import org.apache.spark.sql.functions._

scala> import org.apache.spark.sql.expressions._
import org.apache.spark.sql.expressions._

scala>  spark.sql("CREATE TABLE IF NOT EXISTS test_parquet_map_regression_iceberg_090(mapCol MAP<STRING, STRUCT<payload: STRUCT<bool: BOOLEAN, dbl: DOUBLE, str: STRING>, str: STRING>>) USING ICEBERG TBLPROPERTIES('type'='hive')")

scala> :paste
// Entering paste mode (ctrl-D to finish)

    var df = spark.range(NUM_ROWS)
      .withColumnRenamed("id", "longCol")
      .withColumn("intCol", expr("CAST(longCol AS INT)"))
      .withColumn("dbl", expr("CAST(longCol AS DOUBLE)"))
      .withColumn("str", expr("CAST(longCol AS STRING)"))
      .withColumn("bool", expr("IF(intCol % 2 = 0, true, false)"))
      .withColumn("payload", struct($"bool", $"dbl", $"str"))
      .withColumn("value", struct($"payload", $"str"))
      .withColumn("mapCol", map($"str", $"value"))
      .select("mapCol")

// Exiting paste mode, now interpreting.

df: org.apache.spark.sql.DataFrame = [mapCol: map<string,struct<payload:struct<bool:boolean,dbl:double,str:string>,str:string>>]

scala> df.writeTo("default.test_parquet_map_regression_iceberg_090").append

scala>  spark.table("default.test_parquet_map_regression_iceberg_090").show(false)
+-------------------------------+
|mapCol                         |
+-------------------------------+
|{0 -> {{true, 0.0, 0}, 0}}     |
|{1 -> {{false, 1.0, 1}, 1}}    |
|{2 -> {{true, 2.0, 2}, 2}}     |
|{3 -> {{false, 3.0, 3}, 3}}    |
|{4 -> {{true, 4.0, 4}, 4}}     |
|{5 -> {{false, 5.0, 5}, 5}}    |
|{6 -> {{true, 6.0, 6}, 6}}     |
|{7 -> {{false, 7.0, 7}, 7}}    |
|{8 -> {{true, 8.0, 8}, 8}}     |
|{9 -> {{false, 9.0, 9}, 9}}    |
|{10 -> {{true, 10.0, 10}, 10}} |
|{11 -> {{false, 11.0, 11}, 11}}|
|{12 -> {{true, 12.0, 12}, 12}} |
|{13 -> {{false, 13.0, 13}, 13}}|
|{14 -> {{true, 14.0, 14}, 14}} |
|{15 -> {{false, 15.0, 15}, 15}}|
|{16 -> {{true, 16.0, 16}, 16}} |
|{17 -> {{false, 17.0, 17}, 17}}|
|{18 -> {{true, 18.0, 18}, 18}} |
|{19 -> {{false, 19.0, 19}, 19}}|
+-------------------------------+
only showing top 20 rows

scala> :quit
```

I then upgraded from Iceberg 0.9.0 (compiled against Parquet 0.11.0) to Iceberg 0.10.0 (compiled against Parquet 0.11.1)

First, I tried writing a new table (to ensure that data is working when using the new format).
```bash
root@spark-box:/opt/spark#  ./bin/spark-shell     --packages org.apache.iceberg:iceberg-spark3-runtime:0.10.0    --driver-memory 2g     --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog     --conf spark.sql.catalog.spark_catalog.type=hive      --conf spark.hadoop.hive.metastore.uris=thrift://hive-box:9083
```

First, I tried writing a new table (to ensure that data is working when using the new format).
```scala
scala>  spark.sql("CREATE TABLE IF NOT EXISTS test_parquet_map_regression_iceberg_010(mapCol MAP<STRING, STRUCT<payload: STRUCT<bool: BOOLEAN, dbl: DOUBLE, str: STRING>, str: STRING>>) USING ICEBERG TBLPROPERTIES('type'='hive')")

... create df as above ....

scala> spark.table("default.test_parquet_map_regression_iceberg_010").show(false)
+-------------------------------+
|mapCol                         |
+-------------------------------+
|{0 -> {{true, 0.0, 0}, 0}}     |
|{1 -> {{false, 1.0, 1}, 1}}    |
|{2 -> {{true, 2.0, 2}, 2}}     |
|{3 -> {{false, 3.0, 3}, 3}}    |
|{4 -> {{true, 4.0, 4}, 4}}     |
|{5 -> {{false, 5.0, 5}, 5}}    |
|{6 -> {{true, 6.0, 6}, 6}}     |
|{7 -> {{false, 7.0, 7}, 7}}    |
|{8 -> {{true, 8.0, 8}, 8}}     |
|{9 -> {{false, 9.0, 9}, 9}}    |
|{10 -> {{true, 10.0, 10}, 10}} |
|{11 -> {{false, 11.0, 11}, 11}}|
|{12 -> {{true, 12.0, 12}, 12}} |
|{13 -> {{false, 13.0, 13}, 13}}|
|{14 -> {{true, 14.0, 14}, 14}} |
|{15 -> {{false, 15.0, 15}, 15}}|
|{16 -> {{true, 16.0, 16}, 16}} |
|{17 -> {{false, 17.0, 17}, 17}}|
|{18 -> {{true, 18.0, 18}, 18}} |
|{19 -> {{false, 19.0, 19}, 19}}|
+-------------------------------+
only showing top 20 rows
```

So Parquet 1.11.1 data can be written and then read.

However, the older data written with Parquet 1.11.0 cannot be read on the newer Iceberg version.

```scala
scala> spark.table("default.test_parquet_map_regression_iceberg_090").show(false)
21/09/22 21:49:24 ERROR executor.Executor: Exception in task 0.0 in stage 2.0 (TID 2)
java.lang.IllegalArgumentException: [mapCol, map, key] required binary key (STRING) = 2 is not in the store: [] 12
	at org.apache.iceberg.shaded.org.apache.parquet.hadoop.ColumnChunkPageReadStore.getPageReader(ColumnChunkPageReadStore.java:231)
	at org.apache.iceberg.parquet.ParquetValueReaders$PrimitiveReader.setPageSource(ParquetValueReaders.java:185)
	at org.apache.iceberg.parquet.ParquetValueReaders$RepeatedKeyValueReader.setPageSource(ParquetValueReaders.java:529)
	at org.apache.iceberg.parquet.ParquetValueReaders$StructReader.setPageSource(ParquetValueReaders.java:685)
	at org.apache.iceberg.parquet.ParquetReader$FileIterator.advance(ParquetReader.java:142)
	at org.apache.iceberg.parquet.ParquetReader$FileIterator.next(ParquetReader.java:112)
	at org.apache.iceberg.spark.source.BaseDataReader.next(BaseDataReader.java:81)
	at org.apache.spark.sql.execution.datasources.v2.PartitionIterator.hasNext(DataSourceRDD.scala:79)
	at org.apache.spark.sql.execution.datasources.v2.MetricsIterator.hasNext(DataSourceRDD.scala:112)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

So this issue has actually been present for this particular map data since Iceberg 0.9.0 -> Iceberg 0.10.0 Upgrade (which is when we went from Parquet 1.11.0 -> Parquet 1.11.1).

I also tried with Iceberg 0.12.0, and as expected, the data written from Iceberg 0.10.0 is readable, but the data from Iceberg 0.9.0 (Parquet 1.11.0) is not readable.

We should investigate if there's a fix in upcoming Parquet 1.12.1.

I'm also going to check to see if this issue affects OSS Spark and not just Iceberg (I suspect that it does but will double check).

cc @rdblue

**Comment by kbendick** [comment]
For what it's worth, the reason I think this didn't come up sooner, is that the jars that come packaged with Spark still work for reading both.

When I move the parquet-1.10.2 jars that came with the OSS distribution back to `/opt/spark/jars`, I'm able to read both tables.

**Comment by kbendick** [comment]
When moving the original parquet-1.10.2 jars that came with OSS Spark 3.1.2 back, as you can see the data generated with Iceberg 0.9.0 and Iceberg 0.10.0 (and even generated with Iceberg 0.12.0) are all readable.

```
root@spark:/opt/spark# ls jars | grep parquet
parquet-column-1.10.1.jar
parquet-common-1.10.1.jar
parquet-encoding-1.10.1.jar
parquet-format-2.4.0.jar
parquet-hadoop-1.10.1.jar
parquet-jackson-1.10.1.jar
root@spark:/opt/spark# ./bin/spark-shell     --packages org.apache.iceberg:iceberg-spark3-runtime:0.12.0    --driver-memory 2g     --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog     --conf spark.sql.catalog.spark_catalog.type=hive      --conf spark.hadoop.hive.metastore.uris=thrift://hive:9083
:: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /root/.ivy2/cache
The jars for the packages stored in: /root/.ivy2/jars
org.apache.iceberg#iceberg-spark3-runtime added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-7a1b923a-77d9-455b-b946-72100bf36f6c;1.0
	confs: [default]
	found org.apache.iceberg#iceberg-spark3-runtime;0.12.0 in central
:: resolution report :: resolve 144ms :: artifacts dl 2ms
	:: modules in use:
	org.apache.iceberg#iceberg-spark3-runtime;0.12.0 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   1   |   0   |   0   |   0   ||   1   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-7a1b923a-77d9-455b-b946-72100bf36f6c
	confs: [default]
	0 artifacts copied, 1 already retrieved (0kB/5ms)
21/09/22 21:55:17 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Spark context Web UI available at http://spark-box:4040
Spark context available as 'sc' (master = local[*], app id = local-1632347722175).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.1.2
      /_/

Using Scala version 2.12.10 (OpenJDK 64-Bit Server VM, Java 1.8.0_292)
Type in expressions to have them evaluated.
Type :help for more information.

scala>

scala>

scala> spark.table("default.test_parquet_map_regression_iceberg_010").show(false)
+-------------------------------+
|mapCol                         |
+-------------------------------+
|{0 -> {{true, 0.0, 0}, 0}}     |
|{1 -> {{false, 1.0, 1}, 1}}    |
|{2 -> {{true, 2.0, 2}, 2}}     |
|{3 -> {{false, 3.0, 3}, 3}}    |
|{4 -> {{true, 4.0, 4}, 4}}     |
|{5 -> {{false, 5.0, 5}, 5}}    |
|{6 -> {{true, 6.0, 6}, 6}}     |
|{7 -> {{false, 7.0, 7}, 7}}    |
|{8 -> {{true, 8.0, 8}, 8}}     |
|{9 -> {{false, 9.0, 9}, 9}}    |
|{10 -> {{true, 10.0, 10}, 10}} |
|{11 -> {{false, 11.0, 11}, 11}}|
|{12 -> {{true, 12.0, 12}, 12}} |
|{13 -> {{false, 13.0, 13}, 13}}|
|{14 -> {{true, 14.0, 14}, 14}} |
|{15 -> {{false, 15.0, 15}, 15}}|
|{16 -> {{true, 16.0, 16}, 16}} |
|{17 -> {{false, 17.0, 17}, 17}}|
|{18 -> {{true, 18.0, 18}, 18}} |
|{19 -> {{false, 19.0, 19}, 19}}|
+-------------------------------+
only showing top 20 rows


scala> spark.table("default.test_parquet_map_regression_iceberg_090").show(false)
+-------------------------------+
|mapCol                         |
+-------------------------------+
|{0 -> {{true, 0.0, 0}, 0}}     |
|{1 -> {{false, 1.0, 1}, 1}}    |
|{2 -> {{true, 2.0, 2}, 2}}     |
|{3 -> {{false, 3.0, 3}, 3}}    |
|{4 -> {{true, 4.0, 4}, 4}}     |
|{5 -> {{false, 5.0, 5}, 5}}    |
|{6 -> {{true, 6.0, 6}, 6}}     |
|{7 -> {{false, 7.0, 7}, 7}}    |
|{8 -> {{true, 8.0, 8}, 8}}     |
|{9 -> {{false, 9.0, 9}, 9}}    |
|{10 -> {{true, 10.0, 10}, 10}} |
|{11 -> {{false, 11.0, 11}, 11}}|
|{12 -> {{true, 12.0, 12}, 12}} |
|{13 -> {{false, 13.0, 13}, 13}}|
|{14 -> {{true, 14.0, 14}, 14}} |
|{15 -> {{false, 15.0, 15}, 15}}|
|{16 -> {{true, 16.0, 16}, 16}} |
|{17 -> {{false, 17.0, 17}, 17}}|
|{18 -> {{true, 18.0, 18}, 18}} |
|{19 -> {{false, 19.0, 19}, 19}}|
+-------------------------------+
only showing top 20 rows
```

**Comment by kbendick** [comment]
So I'm not sure how urgent of an issue this is presently, given that we don't officially support Spark 3.2 yet and given that the issue has existed since Iceberg 0.10.0 was released (so data from Iceberg 0.9.1 and prior would be affected, depending on how your class path is set up).

It's an issue for sure, but it seems it only affects you if you compile Spark with different versions of the parquet jars on the class path. If using OSS Iceberg, there's not a currently released OSS Spark version that this is affected by.

`iceberg-parquet` itself has parquet as a `compileOnly` dependency. The only `compile` dependency we have is on `parquet-avro`.

**Comment by kbendick** [comment]
I looked at the parquet meta of one of the underlying files from both Iceberg 0.9.0 and Iceberg 0.10.0.

The difference does seem to be in the change in the MAP type definition.

```
File path:  file_iceberg_010.parquet
Created by: parquet-mr version 1.11.1 (build 765bd5cd7fdef2af1cecd0755000694b992bfadd)
Properties:
  iceberg.schema: {"type":"struct","fields":[{"id":1,"name":"mapCol","required":true,"type":{"type":"map","key-id":2,"key":"string","value-id":3,"value":{"type":"struct","fields":[{"id":4,"name":"payload","required":true,"type":{"type":"struct","fields":[{"id":6,"name":"bool","required":true,"type":"boolean"},{"id":7,"name":"dbl","required":true,"type":"double"},{"id":8,"name":"str","required":true,"type":"string"}]}},{"id":5,"name":"str","required":true,"type":"string"}]},"value-required":true}}]}
Schema:
message table {
  required group mapCol (MAP) = 1 {
    repeated group key_value {
      required binary key (STRING) = 2;
      required group value = 3 {
        required group payload = 4 {
          required boolean bool = 6;
          required double dbl = 7;
          required binary str (STRING) = 8;
        }
        required binary str (STRING) = 5;
      }
    }
  }
}


Row group 0:  count: 12  32.33 B records  start: 4  total: 388 B
--------------------------------------------------------------------------------
                                     type      encodings count     avg size   nulls   min / max
mapCol.key_value.key                 BINARY    G   _     12        6.92 B     0       "0" / "9"
mapCol.key_value.value.payload.bool  BOOLEAN   G   _     12        4.50 B     0       "false" / "true"
mapCol.key_value.value.payload.dbl   DOUBLE    G   _     12        7.08 B     0       "-0.0" / "11.0"
mapCol.key_value.value.payload.str   BINARY    G   _     12        6.92 B     0       "0" / "9"
mapCol.key_value.value.str           BINARY    G   _     12        6.92 B     0       "0" / "9"
```

Here's the meta from one of the files in the Iceberg 0.9.0 table

```
File path:  file_090.parquet
Created by: parquet-mr version 1.11.0 (build 18519eb8e059865652eee3ff0e8593f126701da4)
Properties:
  iceberg.schema: {"type":"struct","fields":[{"id":1,"name":"mapCol","required":true,"type":{"type":"map","key-id":2,"key":"string","value-id":3,"value":{"type":"struct","fields":[{"id":4,"name":"payload","required":true,"type":{"type":"struct","fields":[{"id":6,"name":"bool","required":true,"type":"boolean"},{"id":7,"name":"dbl","required":true,"type":"double"},{"id":8,"name":"str","required":true,"type":"string"}]}},{"id":5,"name":"str","required":true,"type":"string"}]},"value-required":true}}]}
Schema:
message table {
  required group mapCol (MAP) = 1 {
    repeated group map {
      required binary key (STRING) = 2;
      required group value = 3 {
        required group payload = 4 {
          required boolean bool = 6;
          required double dbl = 7;
          required binary str (STRING) = 8;
        }
        required binary str (STRING) = 5;
      }
    }
  }
}


Row group 0:  count: 12  32.33 B records  start: 4  total: 388 B
--------------------------------------------------------------------------------
                               type      encodings count     avg size   nulls   min / max
mapCol.map.key                 BINARY    G   _     12        6.92 B     0       "0" / "9"
mapCol.map.value.payload.bool  BOOLEAN   G   _     12        4.50 B     0       "false" / "true"
mapCol.map.value.payload.dbl   DOUBLE    G   _     12        7.08 B     0       "-0.0" / "11.0"
mapCol.map.value.payload.str   BINARY    G   _     12        6.92 B     0       "0" / "9"
mapCol.map.value.str           BINARY    G   _     12        6.92 B     0       "0" / "9"
```

However, as mentioned, I _am_ able to read both tables with Iceberg 0.12.0.  @hankfanchiu You said your internal fork doesn't work with Iceberg 0.12.0? Can you possibly try with OSS?

**Comment by kbendick** [comment]
@edgarRd From my investigation, the issue seems to have come up from Parquet version 1.11.0 -> 1.11.1 (which is where the map key_value type change occurred).

Since you're importing tables, can you run parquet-cli meta on the files that are imported and see what parquet version they are? Or try upgrading to Parquet 1.11.1 and see if the issue occurs (using Iceberg 0.12.0 should be fine). I believe the issue will occur for you on Parquet 1.11.1 based on what you're saying.

We are looking into the issue further, but I don't believe Iceberg 0.12.0 is the issue. The issue seems to stem from going from Iceberg 0.9.1 or lower to Iceberg 0.10.0 or higher (where the parquet upgrade from 1.11.0 -> 1.11.1 occurred).

**Comment by kbendick** [comment]
> The solution is to rebuild the map structure to exactly match the incoming file schema rather than relying on Parquet to produce the same thing across versions. I'll open a PR.

Thank you @rdblue! It will be good to have this solution in place that doesn't rely on parquet producing the same thing across versions. Great find.
