### ISSUE TITLE
ClassCastException on wide tables with Spark 3.1.x

### ISSUE THREAD

**Issue by huadongliu** [apache/iceberg#2976]
ClassCastException is seen with Spark 3.1.x on a wide table (100+ columns). Spark 3.0.x works fine. I tried the Iceberg 0.12.0rc build (that fixes https://github.com/apache/iceberg/issues/2335), it didn't help. The error is gone by selecting a subset of the columns. I have tried different subsets to rule out possible data column issues. Note that selecting columns[1:89] is good, but not columns[2:90], which make it look more related to total length than number of columns.
 
```
ds = spark.read().format("iceberg").load(table);
ds.filter("dtype=abc").limit(1000).show();

java.lang.ClassCastException: org.apache.spark.sql.catalyst.expressions.GenericInternalRow cannot be cast to org.apache.spark.sql.catalyst.expressions.UnsafeRow
	at org.apache.spark.sql.execution.UnsafeRowSerializerInstance$$anon$1.writeValue(UnsafeRowSerializer.scala:64)
	at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:249)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:158)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dev-lpq** [comment]
We have the same issue. ClassCastException is seen with Spark 3.1.x on a wide table. The error occurs in iceberg overwritePartitions. I checked the table schemas is right. I  retry Spark 3.0.x, and work failed. Not all tables have the issue, only a few tables have problems. Please help check the issue, thanks.

 `
 java.lang.ClassCastException: org.apache.spark.sql.catalyst.expressions.GenericInternalRow cannot be cast to org.apache.spark.sql.catalyst.expressions.UnsafeRow
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.sort(UnsafeExternalRowSorter.java:226)
	at org.apache.spark.sql.execution.SortExec.$anonfun$doExecute$1(SortExec.scala:119)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by gustavoatt** [comment]
I'm seeing something similar only with Spark 3.1.x (it works fine on Spark 2.4.x and Spark 3.2.x) from my tests. Here is a repro I was able to create:

```sql
CREATE TABLE test_table (
    `meta_data` STRUCT<`event_schema`: STRING, `id`: STRING, `tiers`: ARRAY<STRUCT<`id`: STRING, `type`: STRING, `hostname`: STRING, `ip_address`: STRING, `timestamp`: BIGINT, `sequences`: ARRAY<STRUCT<`key`: ARRAY<STRING>, `value`: BIGINT, `bytes_sent`: BIGINT>>>>, `kafka_metadata`: STRUCT<`topic`: STRING, `partition`: INT, `offset`: BIGINT>, `properties`: MAP<STRING, STRING>, `message_type`: STRING>,
    `schema_version` STRING,
    `context_user_id` BIGINT,
    `context_visitor_id` STRING,
    `schema` STRING,
    `event_name` STRING,
    `context` STRUCT<`timestamp`: BIGINT, `source`: STRING, `platform`: STRING, `user_agent`: STRING, `version`: STRING, `bev`: STRING, `user_id`: BIGINT, `hash_user_id`: STRING, `language`: STRING, `locale`: STRING, `campaign`: STRING, `affiliate_id`: STRING, `screen_width`: BIGINT, `screen_height`: BIGINT, `web`: STRUCT<`controller`: STRING, `page`: STRING, `action`: STRING, `rendered_on`: STRING, `viewport`: STRING, `req_uuid`: STRING, `page_uri`: STRING, `page_referrer`: STRING, `canonical_url`: STRING, `shardset`: STRING, `local_time`: STRING, `queued`: BOOLEAN, `canonical_host`: STRING, `app`: STRING, `section_id`: STRING>, `monorail`: STRUCT<`controller`: STRING, `action`: STRING, `api_client_id`: STRING, `api_device_id`: STRING, `api_client_name`: STRING, `api_protocol`: STRING, `api_version`: STRING, `api_resource`: STRING, `api_format`: STRING, `api_intents`: STRING>, `mobile`: STRUCT<`device_type`: STRING, `device_id`: STRING, `version_code`: BIGINT, `screen_orientation`: STRING, `network_type`: STRING, `carrier_name`: STRING, `carrier_country`: STRING, `build_type`: STRING, `view_class_name`: STRING, `native_mode`: STRING, `module_name`: STRING>, `extra_data`: MAP<STRING, STRING>, `client_session_id`: STRING, `bev_expiry`: STRING, `service_context`: STRUCT<`service_name`: STRING, `local_request_id`: STRING, `http_method_type`: STRING, `endpoint_name`: STRING, `global_request_chain_id`: STRING>, `page_name`: STRING, `amp_id`: STRING, `req_remote_host`: STRING, `amp_client_session_id`: STRING, `previous_page_name`: STRING, `visitor_id`: STRING, `impression_uuid`: STRING, `api_request_id`: STRING, `max_deferred_minutes`: BIGINT, `environment`: STRING, `device`: STRUCT<`device_year_class`: STRING>, `traffic_type`: STRING, `context_api_client_id`: STRING>,
    `experiment` STRING,
    `treatment` STRING,
    `subject_type` STRING,
    `subject_id` STRING,
    `client` STRING,
    `client_version` STRING,
    `user_id` STRING,
    `visitor_id` STRING,
    `misa_id` STRING,
    `listing_id` STRING,
    `extra_data` MAP<STRING, STRING>,
    `ds` STRING,
    `hr` STRING
)
USING iceberg
PARTITIONED BY (ds, hr);

-- Insert only nulls (but error happens even with non-null columns)
INSERT INTO test_table (
    meta_data,
    schema_version,
    context_user_id,
    context_visitor_id,
    schema,
    event_name,
    context,
    experiment,
    treatment,
    subject_type,
    subject_id,
    client,
    client_version,
    user_id,
    visitor_id,
    misa_id,
    listing_id,
    extra_data,
    ds,
    hr
)
VALUES (
    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2022-01-01', '10'
);

-- If we select everything we have no issue whatsoever.
SELECT *
FROM test_table;

-- However, if we try to filter based on any column we get a class cast exception, even though the results should be the
-- same.
SELECT *
FROM test_table
WHERE hr = '10';

-- The same query above works if we select fewer columns. In this case selecting < 14 columns works correctly
select
    meta_data,
    schema_version,
    context_user_id,
    context_visitor_id,
    schema,
    event_name,
    context,
    experiment,
    treatment,
    subject_type,
    subject_id,
    client,
    client_version,
    user_id,
    hr
from test_table
WHERE hr = '10';
```

**Comment by kbendick** [comment]
Which version(s) of Iceberg have people tried this with, and have _any_ been successful?

**Comment by gustavoatt** [comment]
@kbendick so far this is failing on Iceberg 0.12.x and on current master (as of yesterday). Let me test it out on 0.11 to verify whether it also happens on that version.

**Comment by edgarRd** [comment]
I don't think Iceberg `0.11` was compatible with `3.1.x` but it may be worth checking if `3.0.x` also works with `0.11` as it does with `0.12`.

**Comment by gustavoatt** [comment]
That's correct, iceberg `0.11` doesn't have support for Spark `3.1.x`. I'v tested iceberg `0.11` with Spark `3.0.x` and it works correctly.

I also tested with plain Spark and there are no issues. I can only reproduce the error with Spark `3.1.x`  from Iceberg `>= 0.12`.

Here is a test I ran from within the Iceberg repo that reproduces the issue:

```diff
diff --git a/spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestIcebergExpressions.java b/spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spar
index ce88814c..e2f37f59 100644
--- a/spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestIcebergExpressions.java
+++ b/spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestIcebergExpressions.java
@@ -28,6 +28,7 @@ import org.apache.spark.sql.Row;
 import org.apache.spark.sql.catalyst.expressions.IcebergTruncateTransform;
 import org.junit.After;
 import org.junit.Test;
+import org.junit.Assert;

 public class TestIcebergExpressions extends SparkExtensionsTestBase {

@@ -67,4 +68,64 @@ public class TestIcebergExpressions extends SparkExtensionsTestBase {
         ImmutableList.of(row(100, 10000L, new BigDecimal("10.50"), "10", "12")),
         sql("SELECT int_c, long_c, dec_c, str_c, CAST(binary_c AS STRING) FROM v"));
   }
+
+  @Test
+  public void testSelectAndFilterWithManyRows() {
+    sql("DROP TABLE IF EXISTS %s", tableName);
+    sql("CREATE TABLE %s (\n" +
+            "  `meta_data` STRUCT<`event_schema`: STRING, `id`: STRING, `tiers`: ARRAY<STRUCT<`id`: STRING, `type`: STRING, `hostname`: STRING, `ip_address`: STRING, `timestamp`: BIGINT
+            "  `schema_version` STRING,\n" +
+            "  `context_user_id` BIGINT,\n" +
+            "  `context_visitor_id` STRING,\n" +
+            "  `schema` STRING,\n" +
+            "  `event_name` STRING,\n" +
+            "  `context` STRUCT<`timestamp`: BIGINT, `source`: STRING, `platform`: STRING, `user_agent`: STRING, `version`: STRING, `bev`: STRING, `user_id`: BIGINT, `hash_user_id`: STR
+            "  `experiment` STRING,\n" +
+            "  `treatment` STRING,\n" +
+            "  `subject_type` STRING,\n" +
+            "  `subject_id` STRING,\n" +
+            "  `client` STRING,\n" +
+            "  `client_version` STRING,\n" +
+            "  `user_id` STRING,\n" +
+            "  `visitor_id` STRING,\n" +
+            "  `misa_id` STRING,\n" +
+            "  `listing_id` STRING,\n" +
+            "  `extra_data` MAP<STRING, STRING>,\n" +
+            "  `ds` STRING,\n" +
+            "  `hr` STRING)\n" +
+            "USING iceberg\n" +
+            "PARTITIONED BY (ds, hr)\n", tableName);
+
+    sql(
+        "INSERT INTO %s (\n"
+            + "    meta_data,\n"
+            + "    schema_version,\n"
+            + "    context_user_id,\n"
+            + "    context_visitor_id,\n"
+            + "    schema,\n"
+            + "    event_name,\n"
+            + "    context,\n"
+            + "    experiment,\n"
+            + "    treatment,\n"
+            + "    subject_type,\n"
+            + "    subject_id,\n"
+            + "    client,\n"
+            + "    client_version,\n"
+            + "    user_id,\n"
+            + "    visitor_id,\n"
+            + "    misa_id,\n"
+            + "    listing_id,\n"
+            + "    extra_data,\n"
+            + "    ds,\n"
+            + "    hr\n"
+            + ")\n"
+            + "VALUES (\n"
+            + "    null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2022-01-01', '10'         \n"
+            + ")",
+        tableName);
+
+    Assert.assertEquals(1, sql("SELECT * FROM %s", tableName).size());
+
+    Assert.assertEquals(1, sql("SELECT * FROM %s WHERE hr = '10'", tableName).size());
+  }
 }
```

**Comment by dev-lpq** [comment]
@gustavoatt I have solved this issue. please check the jira, I think the case can solve the issue. 
https://issues.apache.org/jira/browse/SPARK-37621
And suggest you can update the spark version to 3.2.0
https://issues.apache.org/jira/browse/SPARK-35287

**Comment by gustavoatt** [comment]
That's great @dev-lpq, thank you! Will try upgrading to Spark 3.2.0
