### ISSUE TITLE
AvroSchemaUtil.buildAvroProjection produces duplicate "rnull" record schemas for optional fields

### ISSUE THREAD

**Issue by tweise** [apache/iceberg#3005]
Optional columns are added as union types `["null",{"type":"record","name":"rnull","fields":[...]}]` and in case of multiple such additions, the resulting schema will be invalid due to repetition of the nested record schema with name `"rnull"` and namespace `null`.  

Projected schema is invalid and fails toString conversion with:

```
Exception: org.apache.avro.SchemaParseException: Can't redefine: rnull
	at org.apache.avro.Schema$Names.put(Schema.java:1547)
	at org.apache.avro.Schema$NamedSchema.writeNameRef(Schema.java:810)
	at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:972)
	at org.apache.avro.Schema$UnionSchema.toJson(Schema.java:1239)
	at org.apache.avro.Schema$RecordSchema.fieldsToJson(Schema.java:1000)
	at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:984)
	at org.apache.avro.Schema.toString(Schema.java:424)
	at org.apache.avro.Schema.toString(Schema.java:396)
	at org.apache.avro.Schema.toString(Schema.java:387)
```

I was able to work around the issue by setting a unique name space for these schemas.

**Comment by tweise** [comment]
```
createRecord:217, Schema (org.apache.avro)
struct:114, TypeToSchema (org.apache.iceberg.avro)
struct:34, TypeToSchema (org.apache.iceberg.avro)
visit:364, TypeUtil (org.apache.iceberg.types)
convert:77, AvroSchemaUtil (org.apache.iceberg.avro)
convert:69, AvroSchemaUtil (org.apache.iceberg.avro)
record:105, BuildAvroProjection (org.apache.iceberg.avro)
record:42, BuildAvroProjection (org.apache.iceberg.avro)
visit:51, AvroCustomOrderSchemaVisitor (org.apache.iceberg.avro)
buildAvroProjection:105, AvroSchemaUtil (org.apache.iceberg.avro)
```

https://github.com/apache/iceberg/blob/apache-iceberg-0.12.0/core/src/main/java/org/apache/iceberg/avro/TypeToSchema.java#L114
