### ISSUE TITLE
Flink:  Decouple the iceberg integration work from hadoop libraries

### ISSUE THREAD

**Issue by openinx** [apache/iceberg#3117]
Thanks for working on this. I wanted to draw attention to the issue mentioned above (Update FlinkCatalogFactory to implement the new Factory interface). I closed it as basically a duplicate of this one though.

The reason I opened that issue is that several users have reported difficulties in using Iceberg with Flink, specifically in configuring Hadoop.

In some environments, users might not have access to setup the class path properly for including Hadoop. The new [Context interface that provides access to the ClassLoader ](https://github.com/apache/flink/commit/4497e96b96724aee6637f19f64ffc8ba47a9b0ac#diff-d4dda8460ab068327897de5487517f43186faced18d3a121981e70f6ad9f827aR85) might help with that.

The ultimate goal is to decouple the need for hadoop to be in the environment when it's not actually needed (for example, when using `S3FileIO`). The thought was that upgrading to 1.13 (and the new FlinkCatalogFactory interface) will be helpful to provide the easier access to the ClassLoader.

In environments where hadoop `Configuration` isn't used, such as Ververica Platform or AWS Kinesis Data Analytics with `S3FileIO`, the hope is to remove the need for the Hadoop `Configuration` entirely.

For Ververica, users have reported a workaround but in Kinesis Data Analytics, it's a bit more difficult (as far as has been reported).

More information on the Hadoop `Configurable` concern can be found in this issue: https://github.com/apache/iceberg/issues/3044

Thanks again @zhangjun0x01!

_Originally posted by @kbendick in https://github.com/apache/iceberg/issues/2558#issuecomment-908597980_

**Comment by xinbinhuang** [comment]
@openinx  I would like to work on this. Can you assign it to me?

**Comment by openinx** [comment]
Of course, assigned to you @xinbinhuang !  Pls enjoy.

**Comment by rdblue** [comment]
@openinx, @xinbinhuang, there's no need to assign issues to specific people. Assigning issues almost always prevents work from getting done instead of deconflicting. It is far more likely that someone has an issue assigned and then doesn't have time to work on it, compared to having two people work on an issue at the same time. If you want to work on something, just mention that you plan to do it or link to a PR, rather than waiting to be assigned.

**Comment by xinbinhuang** [comment]
Makes sense! thanks for the info!

**Comment by fi-ecavc** [comment]
Yes, the storage we use is exactly Minio (S3 compatible). More and more are adopting hive-metastore +S3. It feels weird to have to deploy Hadoop.

**Comment by bhanuunrivalled** [comment]
please let us know if  this is wokring .

in KDA we have the problem .

HI @kainoa21 ,

we create catlog like this

tableEnv.executeSql("CREATE CATALOG iceberg WITH (\n" +
" 'type'='iceberg',\n" +
" 'warehouse'='s3://ka-app-code/icebergst/',\n" +
" 'catalog-impl'='org.apache.iceberg.aws.glue.GlueCatalog',\n" +
" 'io-impl'='org.apache.iceberg.aws.s3.S3FileIO'\n" +
")");

we are using flink 1.13.2 and

<dependency>
			<groupId>org.apache.iceberg</groupId>
			<artifactId>iceberg-flink-runtime-1.13</artifactId>
			<version>0.13.1</version>
		</dependency>

		
		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>bundle</artifactId>
			<version>2.15.40</version>
		</dependency>

		
		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>url-connection-client</artifactId>
			<version>2.15.40</version>
		</dependency>
but we still get this error

java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
	at org.apache.iceberg.flink.FlinkCatalogFactory.clusterHadoopConf(FlinkCatalogFactory.java:160)
	at org.apache.iceberg.flink.FlinkCatalogFactory.createCatalog(FlinkCatalogFactory.java:126)
	at org.apache.flink.table.factories.FactoryUtil.createCatalog(FactoryUtil.java:267)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.createCatalog(TableEnvironmentImpl.java:1292)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1122)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:742)
	at basic.application.StreamingJob.main(StreamingJob.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
	at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
	at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
this method is still called

public static Configuration clusterHadoopConf() {
   return HadoopUtils.getHadoopConfiguration(GlobalConfiguration.loadConfiguration());
 }
please advice

**Comment by xinbinhuang** [comment]
@bhanuunrivalled @fi-ecavc I've created a draft PR #4768 to decouple `Configuration` from the path. Will appreciate if you're convenient to help test it. 

(I'm still finding a way to properly test this change)

**Comment by bhanuunrivalled** [comment]
@xinbinhuang  Thanks , I think this will work for us as I see

  ```
public static Configuration clusterHadoopConf() {
    return HadoopUtils.getHadoopConfiguration(GlobalConfiguration.loadConfiguration());
```

is removed

**Comment by canopenerda** [comment]
@xinbinhuang a tricky case would be flink on k8s creating/writing/reading iceberg table in hadoop catalog. How hadoop dependencies should be resolved in this case?

**Comment by xinbinhuang** [comment]
> @xinbinhuang a tricky case would be flink on k8s creating/writing/reading iceberg table in hadoop catalog. How hadoop dependencies should be resolved in this case?

As long as Hadoop is on the classpath, it should just work. The change simply try to defer the loading of Hadoop dependencies so that catalog that doesn't require Hadoop (i.e. Glue catalog) doesn't need the Hadoop jar on the classpath

**Comment by canopenerda** [comment]
Since the case I

> > @xinbinhuang a tricky case would be flink on k8s creating/writing/reading iceberg table in hadoop catalog. How hadoop dependencies should be resolved in this case?
> 
> As long as Hadoop is on the classpath, it should just work. The change simply try to defer the loading of Hadoop dependencies so that catalog that doesn't require Hadoop (i.e. Glue catalog) doesn't need the Hadoop jar on the classpath

@xinbinhuang Since the case I mentioned is flink on k8s, it's not likely there would be hadoop on classpath in flink image.

**Comment by xinbinhuang** [comment]
> Since the case I
> 
> > > @xinbinhuang a tricky case would be flink on k8s creating/writing/reading iceberg table in hadoop catalog. How hadoop dependencies should be resolved in this case?
> > 
> > 
> > As long as Hadoop is on the classpath, it should just work. The change simply try to defer the loading of Hadoop dependencies so that catalog that doesn't require Hadoop (i.e. Glue catalog) doesn't need the Hadoop jar on the classpath
> 
> @xinbinhuang Since the case I mentioned is flink on k8s, it's not likely there would be hadoop on classpath in flink image.

Ah I see. If you're using Hadoop catalog with k8s, this PR has nothing to do with it. Since you're using Hadoop catalog, you'll need to supply hadoop classes regardless. I'm not sure if bundle `hadoop-common` in your fat jar is good enough. You may also need to specify [`HADOOP_CLASSPATH`](https://nightlies.apache.org/flink/flink-docs-release-1.11/ops/deployment/hadoop.html#providing-hadoop-classes) when you [build the image](https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/deployment/resource-providers/native_kubernetes/#flink-on-kubernetes-reference)

**Comment by jeff1evesque** [comment]
I plan on using Apache Iceberg with AWS Kinesis Data Analytics. I contacted AWS support last evening to determine what I need, and I was told it's not supported yet. Specifically, the support engineer stated its pending this pull request. While I keep this issue/pull under radar, could someone provide me information regarding what kind of configuration I need to define to use Apache Icerberg with PyFlink on KDA. Would I need to provide my own JAR file in my deployment package, as well as adding some additional configuration in the `application_properties.json`?

**Comment by rdblue** [comment]
@jeff1evesque, the PR is mostly pending because we haven't had a chance to validate it. Would you like to try with it and we can help out? If you can verify it works, we'll get the PR in the next release.

**Comment by attzy** [comment]
As a workaround for KDA, I was able to deploy an application that writes Parquet files to S3, and associated metadata to Glue using Flink SQL (likely will work fine for Table API as well) by packaging and relocating the Hadoop dependencies within an Uber JAR.

This might have some other side effects but in the context of building datasets in AWS using KDA with checkpointing/snapshots everything seems to be working as it should.

```
dependencies {

    (...)

    implementation 'com.amazonaws:aws-kinesisanalytics-runtime:1.2.0'
    implementation 'org.apache.iceberg:iceberg-flink-runtime-1.15:1.1.0'
    
    implementation 'org.apache.hadoop:hadoop-common:2.10.2'
    implementation 'org.apache.hadoop:hadoop-hdfs:2.10.2'
    implementation 'org.apache.flink:flink-hadoop-fs:1.15.2'

    implementation 'software.amazon.awssdk:glue:2.17.257'
    implementation 'software.amazon.awssdk:s3:2.17.257'
    implementation 'software.amazon.awssdk:sts:2.17.257'
    implementation 'software.amazon.awssdk:dynamodb:2.17.257'
    implementation 'software.amazon.awssdk:kms:2.17.257'
    implementation 'software.amazon.awssdk:url-connection-client:2.17.257'
}

shadowJar {
    mergeServiceFiles()
    zip64 true
    relocate 'org.apache.hadoop', 'shadow.org.apache.hadoop'
    relocate 'org.apache.flink.runtime.util.HadoopUtils', 'shadow.org.apache.flink.runtime.util.HadoopUtils'
}
```
I was then able to create a Catalog pointing to Glue with a table inside, stream some data and query back with Athena.
```
      CREATE CATALOG glue WITH (
        'type'='iceberg',
        'warehouse'='s3://<S3 bucket>',
        'catalog-impl'='org.apache.iceberg.aws.glue.GlueCatalog',
        'io-impl'='org.apache.iceberg.aws.s3.S3FileIO',
        'format'='parquet',
        'format-version'='2'
      )"
```

**Comment by Fokko** [comment]
I have a draft over here: https://github.com/apache/iceberg/pull/7369 but it breaks quite a few APIs.

**Comment by vbabenkoru** [comment]
I just hit this issue when trying to create a basic Flink app with an Iceberg catalog, and there is no straightforward workaround, apparently. The repro is very easy: run Flink docker image, upload a jar that tries to initialize an Iceberg catalog via SQL, and you're going to hit this error.
This issue basically makes onboarding with Flink and Iceberg very difficult, and there is no plan to solve it or an easy workaround.

**Comment by dyrnq** [comment]
stare
