### ISSUE TITLE
Spark: Add_files throws IllegalArgumentException when adding Avro files

### ISSUE THREAD

**Issue by szehon-ho** [apache/iceberg#3263]
Reproduces on master branch:

```
CALL catalog.system.add_files(table, '`avro`.`avro_path`')
```
Leads to:

```
Caused by: java.lang.IllegalArgumentException: Record count is required
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at org.apache.iceberg.DataFiles$Builder.build(DataFiles.java:288)
	at org.apache.iceberg.data.TableMigrationUtil.lambda$listAvroPartition$2(TableMigrationUtil.java:106)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.apache.iceberg.data.TableMigrationUtil.listAvroPartition(TableMigrationUtil.java:108)
	at org.apache.iceberg.data.TableMigrationUtil.listPartition(TableMigrationUtil.java:76)
	at org.apache.iceberg.spark.SparkTableUtil.listPartition(SparkTableUtil.java:303)
	at org.apache.iceberg.spark.SparkTableUtil.lambda$importSparkPartitions$f46fdb10$1(SparkTableUtil.java:520)
	at org.apache.spark.sql.Dataset.$anonfun$flatMap$2(Dataset.scala:2876)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
```

Looks like a bit similar to discussion : https://github.com/apache/iceberg/pull/2494#discussion_r616607521. , but now it seems like not just Metrics problem, but DataFile needs a recordCount.

**Comment by szehon-ho** [comment]
I was thinking to explicitly set it to -1 when constructing the DataFile in listAvroPartitions, but I feel its wrong metadata (though it is set to -1 for Metrics..)

Doesn't seem like Avro file has any metadata to quickly get recordCount, I wonder if making a Spark job to read the rows is overkill?  Any thoughts @RussellSpitzer and @aokolnychyi ?

**Comment by RussellSpitzer** [comment]
https://github.com/apache/iceberg/issues/2161 -- Another Report of this issue
https://github.com/apache/iceberg/issues/2360 -- Our initial problem with running tests for AVRO and ORC
