### ISSUE TITLE
Can spark operates iceberg table created by hive?

### ISSUE THREAD

**Issue by yujiantao** [apache/iceberg#3295]

**Comment by 1ambda** [comment]
Hi, 

I am trying to read a PrestoDB (0.266 w/ Iceberg 0.12) created iceberg table in Spark (3.2.0 w/ Iceberg 0.13 SNAPSHOT).
- Presto can read Spark created iceberg tables without any errors
- However, Spark throw an error when trying to read Presto created iceberg tables

```scala
// Spark SQL
spark.sql("SELECT * FROM hive_prod.test_db.test_table LIMIT 10").printSchema().show()

// ERROR
Caused by: java.lang.ClassCastException: [B cannot be cast to org.apache.spark.unsafe.types.UTF8String
  at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.getUTF8String(rows.scala:46)
  at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.getUTF8String$(rows.scala:46)
  at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.getUTF8String(rows.scala:195)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
```

Here is DDL and DML for creating iceberg tables used in Presto and inserting data into the table.

```sql
CREATE TABLE iceberg.test_db.test_table (
    col_a bigint comment '...' ,
    col_b varchar comment '...',
    p_ymd varchar
)
WITH (
    format = 'PARQUET',
    partitioning = ARRAY['p_ymd'],
    location = 's3://...'
)
 
INSERT INTO CREATE TABLE iceberg.test_db.test_table
SELECT col_a, col_b, '20211201' as p_ymd
FROM existing_table
```

@RussellSpitzer Could different version of iceberg library used in each computing engine have affect on the read query?

**Comment by RussellSpitzer** [comment]
That is possible, since a snapshot build isn't necessarily production ready yet. Although we should have no problem with pretty much any released Iceberg version reading Iceberg tables unless they are Iceberg V2 Tables since the spec had not finalized until recently. In this case it looks like somewhere it is returning a Byte value where it expects a string.

**Comment by 1ambda** [comment]
Thanks for the quick answer! Will try iceberg 0.12 in Spark too.

**Comment by 1ambda** [comment]
Tested in Spark 3.1.2 (Iceberg runtime 0.12.1), But still got same error. 

```
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.1.2
      /_/

Using Scala version 2.12.10 (OpenJDK 64-Bit Server VM, Java 1.8.0_242)
Type in expressions to have them evaluated.
Type :help for more information.

scala> spark.sql("SELECT * FROM hive_prod.test_db.test_table ...").show()
res0: org.apache.spark.sql.DataFrame = [placeno: col_a, col_b: string ... 1 more field]

scala> spark.sql("SELECT * FROM hive_prod.test_db.test_table ...").show()
21/12/08 09:42:22 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)/ 1]
java.lang.ClassCastException: [B cannot be cast to org.apache.spark.unsafe.types.UTF8String
        at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.getUTF8String(rows.scala:46)
        at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.getUTF8String$(rows.scala:46)
        at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.getUTF8String(rows.scala:195)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
21/12/08 09:42:22 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) (hive-metastore-2-66d6c89cf-jxbcg executor driver): java.lang.ClassCastException: [B cannot be cast to org.apache.spark.unsafe.types.UTF8String

```

**Comment by 1ambda** [comment]
Still having the same problem with Spark 3.2.1 / Iceberg 0.13.1 (table created from PrestoDB 0.270 Iceberg 0.12)

```python

Py4JJavaError: An error occurred while calling o191.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 3.0 failed 4 times, most recent failure: Lost task 0.3 in stage 3.0 (TID 13) (10.3.38.211 executor 1): java.lang.ClassCastException: [B cannot be cast to org.apache.spark.unsafe.types.UTF8String
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.getUTF8String(rows.scala:46)
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.getUTF8String$(rows.scala:46)
	at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.getUTF8String(rows.scala:195)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:349)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
