### ISSUE TITLE
Unable to create table in local environment

### ISSUE THREAD

**Issue by cvasani** [apache/iceberg#3346]
Hi Team,

I have tried to setup a iceberg on my local instance. Spark is local to my machine and tried executing given commands. Now command is throwing errors. Could you please advise ? 

Commands : 
```shell
spark-sql --packages org.apache.iceberg:iceberg-spark3-runtime:0.12.0\
    --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions \
    --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog \
    --conf spark.sql.catalog.spark_catalog.type=hive \
    --conf spark.sql.catalog.local=org.apache.iceberg.spark.SparkCatalog \
    --conf spark.sql.catalog.local.type=hadoop \
    --conf spark.sql.catalog.local.warehouse=$PWD/warehouse

CREATE TABLE local.db.table (id bigint, data string) USING iceberg;
```

Error : 
```shell
spark-sql> CREATE TABLE local.db.table (id bigint, data string) USING iceberg;
21/10/22 01:59:22 ERROR SparkSQLDriver: Failed in [CREATE TABLE local.db.table (id bigint, data string) USING iceberg]
java.lang.IncompatibleClassChangeError: class org.apache.spark.sql.catalyst.plans.logical.DynamicFileFilterWithCardinalityCheck has interface org.apache.spark.sql.catalyst.plans.logical.BinaryNode as super class
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions.$anonfun$apply$8(IcebergSparkSessionExtensions.scala:50)

```

For NameSpace.
```shell
spark-sql> CREATE NAMESPACE IF NOT EXISTS db;
21/10/22 02:02:59 ERROR SparkSQLDriver: Failed in [CREATE NAMESPACE IF NOT EXISTS db]
java.lang.IncompatibleClassChangeError: class org.apache.spark.sql.catalyst.plans.logical.DynamicFileFilterWithCardinalityCheck has interface org.apache.spark.sql.catalyst.plans.logical.BinaryNode as super class
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)

```

**Comment by RussellSpitzer** [comment]
What version of spark are you running. We test with spark 3.0, 3.1, and 2.4.7￼ (different runtime jar) 

3.2 is in progress

**Comment by cvasani** [comment]
> What version of spark are you running. We test with spark 3.0, 3.1, and 2.4.7￼ (different runtime jar)
> 
> 3.2 is in progress

I am using spark 3.2. Thank you . let me test with 3.1. Could you please help me find documentation link for certification matrix.
