### ISSUE TITLE
select .files and rewrite data files failed after remove partition field

### ISSUE THREAD

**Issue by jinchengchenghh** [apache/iceberg#3374]
if update the spec, remove the partition field, then cannot query files, and rewrite data files, expire snapshots will also raise exception

### _Case_
```
create table iceberg_catalog.db.bucket2(a string, b string, c string) using iceberg partitioned by (bucket(2, b), bucket(2, c)) location "/Users/jcc/hive/bucket2";
insert into db.bucket2 values("1", "cc", "bb");
insert into db.bucket2 values("1", "cc", "bb");
alter table iceberg_catalog.db.bucket2 drop partition field bucket(2, c);
insert into db.bucket2 values("1", "cc", "bb");
insert into db.bucket2 values("1", "cc", "bb");
select * from iceberg_catalog.db.bucket2.files;
```
### _Exception is_
```
Caused by: java.lang.IllegalArgumentException: Wrong class, java.lang.CharSequence, for object: 1
        at org.apache.iceberg.PartitionData.get(PartitionData.java:120)
        at org.apache.iceberg.spark.source.StructInternalRow.getUTF8StringInternal(StructInternalRow.java:175)
        at org.apache.iceberg.spark.source.StructInternalRow.getUTF8String(StructInternalRow.java:171)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:340)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by mbabic** [comment]
Hey everyone, just commenting to say we’re running into this issue on `0.13.0`. It unfortunately prevents us from using Spark actions for maintenance tasks (e.g. snapshot expiration) on tables for which we’ve removed a partition field.

If there’s any more work that needs to be done on https://github.com/apache/iceberg/pull/3411 or if there's any more info I can provide I’m happy to do it. :slightly_smiling_face: Thanks!

**Comment by RussellSpitzer** [comment]
Took another look at #3411, sorry for the delay. I was a little confused on the issue but now I see the problem and have a workaround to try for folks dealing with this now.

From what I can tell, the issues is primarily with V1 Iceberg tables where a column has a transform applied to it that changes its type, and then is dropped.

For example `bucket(10, stringColumn)` has a type "int" but when dropped in v1 is replaced with a `VoidTransform` which always returns null but has a type of "string". Reading the partition data with "string" when the actual data is "Int" causes problems.

I think 3411 has the right fix and I just have a few minor comments on it. I do think as a workaround converting a table to a V2 table should fix the issue.
