### ISSUE TITLE
While I tring to select table1 join  table2，if fields of table2 was choosed, error like "java.lang.ArrayIndexOutOfBoundsException: 6"  occurred

### ISSUE THREAD

**Issue by xigua88-66** [apache/iceberg#3395]
**flink : v1.12.1
iceberg : v0.12
iceberg table version: v2**

I have 2 iceberg tables , table01 and table02。
Fields of table01 are a, b, c ;
Fields of table02 are d, e, f ;

SQL like:
SELECT   t2.*   FROM    table01   AS   t1   JOIN   table02   AS  t2   ON  t1.a= t2.d;
or
SELECT  t2.d  FROM   table01   AS   t1   JOIN   table02   AS  t2   ON  t1.a= t2.d;
or
SELECT  t1.c,  t2.d  FROM   table01   AS   t1   JOIN   table02   AS  t2   ON  t1.a= t2.d;

and so on. **exactly, if fields of table02 was choosed, error like "java.lang.ArrayIndexOutOfBoundsException: 6 " will happened.**

![image](https://user-images.githubusercontent.com/54090607/139057414-7fb657c4-4dc2-43fb-b70d-242938508d9b.png)

It seems that there is a problem here：
flink-table-planner-blink_2.11-1.12.1.jar   org.apache.flink.table.planner.plan.utils.KeySelectorUtil

**Seems to always be [0, 6]**

![image](https://user-images.githubusercontent.com/54090607/139056747-b4ba59aa-f004-4099-8e87-36991fdd89e8.png)

**### Stacktrace:**

2021-10-27 18:17:14,057 INFO  org.apache.flink.contrib.streaming.state.RocksDBStateBackend [] - Using default options factory: DefaultConfigurableOptionsFactory{configuredOptions={}}.
2021-10-27 18:17:14,082 WARN  org.apache.flink.table.client.cli.CliClient                  [] - Could not execute SQL statement.
org.apache.flink.table.client.gateway.SqlExecutionException: Invalid SQL query.
        at org.apache.flink.table.client.gateway.local.LocalExecutor.executeQueryInternal(LocalExecutor.java:548) ~[flink-sql-client_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.gateway.local.LocalExecutor.executeQuery(LocalExecutor.java:374) ~[flink-sql-client_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.cli.CliClient.callSelect(CliClient.java:648) ~[flink-sql-client_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.cli.CliClient.callCommand(CliClient.java:323) ~[flink-sql-client_2.11-1.12.1.jar:1.12.1]
        at java.util.Optional.ifPresent(Optional.java:159) [?:1.8.0_211]
        at org.apache.flink.table.client.cli.CliClient.open(CliClient.java:214) [flink-sql-client_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.SqlClient.openCli(SqlClient.java:144) [flink-sql-client_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.SqlClient.start(SqlClient.java:115) [flink-sql-client_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.SqlClient.main(SqlClient.java:201) [flink-sql-client_2.11-1.12.1.jar:1.12.1]
Caused by: java.lang.RuntimeException: Error while applying rule StreamExecJoinRule, args [rel#1171:FlinkLogicalJoin.LOGICAL.any.None: 0.[NONE].[NONE](left=RelSubset#1169,right=RelSubset#1170,condition==($2, $0),joinType=full), rel#1144:FlinkLogicalTableSourceScan.LOGICAL.any.None: 0.[NONE].[NONE](table=[SWJCXT16337493441451360674258538498, udf_test, cs_device_mine_info_CGK, project=[sensor_type, unit]],fields=sensor_type, unit), rel#1146:FlinkLogicalTableSourceScan.LOGICAL.any.None: 0.[NONE].[NONE](table=[SWJCXT16337493441451120848483762178, udf_test, hg_t_types_dict, project=[hg_type_code]],fields=hg_type_code)]
        at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:256) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.plan.volcano.IterativeRuleDriver.drive(IterativeRuleDriver.java:58) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.plan.volcano.VolcanoPlanner.findBestExp(VolcanoPlanner.java:510) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.tools.Programs$RuleSetProgram.run(Programs.java:312) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.program.FlinkVolcanoProgram.optimize(FlinkVolcanoProgram.scala:64) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.program.FlinkChainedProgram$$anonfun$optimize$1.apply(FlinkChainedProgram.scala:62) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.program.FlinkChainedProgram$$anonfun$optimize$1.apply(FlinkChainedProgram.scala:58) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.Iterator$class.foreach(Iterator.scala:891) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.program.FlinkChainedProgram.optimize(FlinkChainedProgram.scala:57) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.StreamCommonSubGraphBasedOptimizer.optimizeTree(StreamCommonSubGraphBasedOptimizer.scala:163) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.StreamCommonSubGraphBasedOptimizer.doOptimize(StreamCommonSubGraphBasedOptimizer.scala:79) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.CommonSubGraphBasedOptimizer.optimize(CommonSubGraphBasedOptimizer.scala:77) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.delegation.PlannerBase.optimize(PlannerBase.scala:286) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.delegation.PlannerBase.translate(PlannerBase.scala:165) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.translate(TableEnvironmentImpl.java:1329) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.translateAndClearBuffer(TableEnvironmentImpl.java:1321) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.api.bridge.java.internal.StreamTableEnvironmentImpl.getPipeline(StreamTableEnvironmentImpl.java:328) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.gateway.local.ExecutionContext.lambda$createPipeline$1(ExecutionContext.java:287) ~[flink-sql-client_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.gateway.local.ExecutionContext.wrapClassLoader(ExecutionContext.java:256) ~[flink-sql-client_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.gateway.local.ExecutionContext.createPipeline(ExecutionContext.java:282) ~[flink-sql-client_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.gateway.local.LocalExecutor.executeQueryInternal(LocalExecutor.java:542) ~[flink-sql-client_2.11-1.12.1.jar:1.12.1]
        ... 8 more
Caused by: java.lang.RuntimeException: Error occurred while applying rule StreamExecJoinRule
        at org.apache.calcite.plan.volcano.VolcanoRuleCall.transformTo(VolcanoRuleCall.java:161) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.plan.RelOptRuleCall.transformTo(RelOptRuleCall.java:268) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.plan.RelOptRuleCall.transformTo(RelOptRuleCall.java:283) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.rules.physical.stream.StreamExecJoinRule.onMatch(StreamExecJoinRule.scala:133) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:229) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.plan.volcano.IterativeRuleDriver.drive(IterativeRuleDriver.java:58) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.plan.volcano.VolcanoPlanner.findBestExp(VolcanoPlanner.java:510) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.tools.Programs$RuleSetProgram.run(Programs.java:312) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.program.FlinkVolcanoProgram.optimize(FlinkVolcanoProgram.scala:64) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.program.FlinkChainedProgram$$anonfun$optimize$1.apply(FlinkChainedProgram.scala:62) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.program.FlinkChainedProgram$$anonfun$optimize$1.apply(FlinkChainedProgram.scala:58) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.Iterator$class.foreach(Iterator.scala:891) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.program.FlinkChainedProgram.optimize(FlinkChainedProgram.scala:57) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.StreamCommonSubGraphBasedOptimizer.optimizeTree(StreamCommonSubGraphBasedOptimizer.scala:163) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.StreamCommonSubGraphBasedOptimizer.doOptimize(StreamCommonSubGraphBasedOptimizer.scala:79) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.CommonSubGraphBasedOptimizer.optimize(CommonSubGraphBasedOptimizer.scala:77) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.delegation.PlannerBase.optimize(PlannerBase.scala:286) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.delegation.PlannerBase.translate(PlannerBase.scala:165) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.translate(TableEnvironmentImpl.java:1329) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.translateAndClearBuffer(TableEnvironmentImpl.java:1321) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.api.bridge.java.internal.StreamTableEnvironmentImpl.getPipeline(StreamTableEnvironmentImpl.java:328) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.gateway.local.ExecutionContext.lambda$createPipeline$1(ExecutionContext.java:287) ~[flink-sql-client_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.gateway.local.ExecutionContext.wrapClassLoader(ExecutionContext.java:256) ~[flink-sql-client_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.gateway.local.ExecutionContext.createPipeline(ExecutionContext.java:282) ~[flink-sql-client_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.gateway.local.LocalExecutor.executeQueryInternal(LocalExecutor.java:542) ~[flink-sql-client_2.11-1.12.1.jar:1.12.1]
        ... 8 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 6
        at org.apache.flink.table.planner.plan.utils.KeySelectorUtil.getRowDataSelector(KeySelectorUtil.java:51) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecJoin.analyzeJoinInput(StreamExecJoin.scala:230) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecJoin.explainTerms(StreamExecJoin.scala:110) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.rel.AbstractRelNode.getDigestItems(AbstractRelNode.java:409) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.rel.AbstractRelNode.deepHashCode(AbstractRelNode.java:391) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.rel.AbstractRelNode$InnerRelDigest.hashCode(AbstractRelNode.java:443) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at java.util.HashMap.hash(HashMap.java:339) ~[?:1.8.0_211]
        at java.util.HashMap.get(HashMap.java:557) ~[?:1.8.0_211]
        at org.apache.calcite.plan.volcano.VolcanoPlanner.registerImpl(VolcanoPlanner.java:1150) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.plan.volcano.VolcanoPlanner.register(VolcanoPlanner.java:589) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.plan.volcano.VolcanoPlanner.ensureRegistered(VolcanoPlanner.java:604) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.plan.volcano.VolcanoRuleCall.transformTo(VolcanoRuleCall.java:148) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.plan.RelOptRuleCall.transformTo(RelOptRuleCall.java:268) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.plan.RelOptRuleCall.transformTo(RelOptRuleCall.java:283) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.rules.physical.stream.StreamExecJoinRule.onMatch(StreamExecJoinRule.scala:133) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:229) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.plan.volcano.IterativeRuleDriver.drive(IterativeRuleDriver.java:58) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.plan.volcano.VolcanoPlanner.findBestExp(VolcanoPlanner.java:510) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.calcite.tools.Programs$RuleSetProgram.run(Programs.java:312) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.program.FlinkVolcanoProgram.optimize(FlinkVolcanoProgram.scala:64) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.program.FlinkChainedProgram$$anonfun$optimize$1.apply(FlinkChainedProgram.scala:62) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.program.FlinkChainedProgram$$anonfun$optimize$1.apply(FlinkChainedProgram.scala:58) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.Iterator$class.foreach(Iterator.scala:891) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104) ~[flink-dist_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.program.FlinkChainedProgram.optimize(FlinkChainedProgram.scala:57) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.StreamCommonSubGraphBasedOptimizer.optimizeTree(StreamCommonSubGraphBasedOptimizer.scala:163) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.StreamCommonSubGraphBasedOptimizer.doOptimize(StreamCommonSubGraphBasedOptimizer.scala:79) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.plan.optimize.CommonSubGraphBasedOptimizer.optimize(CommonSubGraphBasedOptimizer.scala:77) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.delegation.PlannerBase.optimize(PlannerBase.scala:286) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.planner.delegation.PlannerBase.translate(PlannerBase.scala:165) ~[flink-table-blink_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.translate(TableEnvironmentImpl.java:1329) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.translateAndClearBuffer(TableEnvironmentImpl.java:1321) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.api.bridge.java.internal.StreamTableEnvironmentImpl.getPipeline(StreamTableEnvironmentImpl.java:328) ~[flink-table_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.gateway.local.ExecutionContext.lambda$createPipeline$1(ExecutionContext.java:287) ~[flink-sql-client_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.gateway.local.ExecutionContext.wrapClassLoader(ExecutionContext.java:256) ~[flink-sql-client_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.gateway.local.ExecutionContext.createPipeline(ExecutionContext.java:282) ~[flink-sql-client_2.11-1.12.1.jar:1.12.1]
        at org.apache.flink.table.client.gateway.local.LocalExecutor.executeQueryInternal(LocalExecutor.java:542) ~[flink-sql-client_2.11-1.12.1.jar:1.12.1]
        ... 8 more

**Comment by luoyuxia** [comment]
It should be fixed by latest Flink.
