### ISSUE TITLE
Spark 3.2 benchmark failed with netty.buffer issue

### ISSUE THREAD

**Issue by flyrain** [apache/iceberg#3405]
It may be related to an older netty version in the classpath. Spark 3.2 updated netty from 4.1.51 to 4.1.63 by https://github.com/apache/spark/pull/32227, due a security problem.
```
java.lang.NoSuchMethodError: 'void io.netty.buffer.PooledByteBufAllocator.<init>(boolean, int, int, int, int, int, int, boolean)'
        at org.apache.spark.network.util.NettyUtils.createPooledByteBufAllocator(NettyUtils.java:171)
        at org.apache.spark.network.util.NettyUtils.getSharedPooledByteBufAllocator(NettyUtils.java:142)
        at org.apache.spark.network.client.TransportClientFactory.<init>(TransportClientFactory.java:111)
        at org.apache.spark.network.TransportContext.createClientFactory(TransportContext.java:142)
        at org.apache.spark.rpc.netty.NettyRpcEnv.<init>(NettyRpcEnv.scala:77)
        at org.apache.spark.rpc.netty.NettyRpcEnvFactory.create(NettyRpcEnv.scala:493)
        at org.apache.spark.rpc.RpcEnv$.create(RpcEnv.scala:57)
        at org.apache.spark.SparkEnv$.create(SparkEnv.scala:268)
        at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:191)
        at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:277)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:460)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2690)
        at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:949)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:943)
        at org.apache.iceberg.spark.source.IcebergSourceBenchmark.setupSpark(IcebergSourceBenchmark.java:118)
        at org.apache.iceberg.spark.source.IcebergSourceBenchmark.setupSpark(IcebergSourceBenchmark.java:124)
        at org.apache.iceberg.spark.source.parquet.IcebergSourceFlatParquetDataDeleteBenchmark.setupBenchmark(IcebergSourceFlatParquetDataDeleteBenchmark.java:71)
        at org.apache.iceberg.spark.source.parquet.jmh_generated.IcebergSourceFlatParquetDataDeleteBenchmark_readIceberg_jmhTest._jmh_tryInit_f_icebergsourceflatparquetdatadeletebenchmark0_G(IcebergSourceFlatParquetDataDeleteBenchmark_readIceberg_jmhTest.java:442)
        at org.apache.iceberg.spark.source.parquet.jmh_generated.IcebergSourceFlatParquetDataDeleteBenchmark_readIceberg_jmhTest.readIceberg_SingleShotTime(IcebergSourceFlatParquetDataDeleteBenchmark_readIceberg_jmhTest.java:363)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:470)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
cc @aokolnychyi @RussellSpitzer

**Comment by Zhu-wenlong** [comment]
what should I do for solve this problem

**Comment by flyrain** [comment]
@Zhu-wenlong, the issue has been fixed by https://github.com/apache/iceberg/pull/3420. You don't have to do anything.

**Comment by Rajashekhar-meesala** [comment]
Hi We are getting the same issue with spark 3.2.1 version and unable to resolve. can anyone please guide us.

**Comment by flyrain** [comment]
Hi @Rajashekhar-meesala, is the error message exactly the same? If it is, you need to check all your dependencies including the transitive dependencies to make sure there is no old version(< 4.1.63.Final) of netty buffer get into your Spark runtime.
