### ISSUE TITLE
Flink: Get KryoException when starting a flink job.

### ISSUE THREAD

**Issue by Reo-LEI** [apache/iceberg#3551]
Currently I encounter a `KryoException` when I submit a flink job to flink 1.12.x. 
```
2021-11-12 18:07:03,976 WARN  org.apache.flink.runtime.taskmanager.Task                    dw_rt_ods.ods_mysql_cdc_hive_exec_job-IcebergStreamWriter (1/1)#0 [] - database.table-IcebergStreamWriter (1/1)#0 (2377289ed0fedccf9d510099ec769e24) switched from RUNNING to FAILED.
java.lang.RuntimeException: Exception occurred while setting the current key context.
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.setCurrentKey(StreamOperatorStateHandler.java:322) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.setCurrentKey(AbstractStreamOperator.java:532) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.setKeyContextElement(AbstractStreamOperator.java:527) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.setKeyContextElement1(AbstractStreamOperator.java:514) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:190) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.processElement(StreamTaskNetworkInput.java:204) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.emitNext(StreamTaskNetworkInput.java:174) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:396) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:191) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:617) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:581) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:755) [flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:570) [flink-dist_2.12-1.12.1.jar:1.12.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
Serialization trace:
getters (org.apache.iceberg.flink.RowDataWrapper)
struct (org.apache.iceberg.util.StructProjection)
struct (org.apache.iceberg.util.StructLikeWrapper)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:82) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:523) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:61) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:523) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:61) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:599) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer.serialize(KryoSerializer.java:316) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.contrib.streaming.state.RocksDBSerializedCompositeKeyBuilder.serializeKeyGroupAndKey(RocksDBSerializedCompositeKeyBuilder.java:157) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.contrib.streaming.state.RocksDBSerializedCompositeKeyBuilder.setKeyAndKeyGroup(RocksDBSerializedCompositeKeyBuilder.java:93) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.contrib.streaming.state.RocksDBKeyedStateBackend.setCurrentKey(RocksDBKeyedStateBackend.java:386) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.setCurrentKey(StreamOperatorStateHandler.java:320) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	... 14 more
Caused by: java.lang.NullPointerException
	at com.esotericsoftware.kryo.Kryo.getSerializer(Kryo.java:476) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:345) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:289) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:523) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:61) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:523) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:61) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:523) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:61) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:599) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer.serialize(KryoSerializer.java:316) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.contrib.streaming.state.RocksDBSerializedCompositeKeyBuilder.serializeKeyGroupAndKey(RocksDBSerializedCompositeKeyBuilder.java:157) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.contrib.streaming.state.RocksDBSerializedCompositeKeyBuilder.setKeyAndKeyGroup(RocksDBSerializedCompositeKeyBuilder.java:93) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.contrib.streaming.state.RocksDBKeyedStateBackend.setCurrentKey(RocksDBKeyedStateBackend.java:386) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.setCurrentKey(StreamOperatorStateHandler.java:320) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	... 14 more
```

**Comment by openinx** [comment]
Looks like we are trying to serialize the `RowDataWrapper` (which we don't guarantee the serialization ability) in some paths.  If we can locate the path,  then we can use the similar approach the PartitionKeySelector used to avoid the kryo serialization issues. https://github.com/apache/iceberg/blob/1d8164383baf0e343ade13b21ed0e4d4d02c56cd/flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/sink/PartitionKeySelector.java#L52

**Comment by Reo-LEI** [comment]
> Looks like we are trying to serialize the `RowDataWrapper` (which we don't guarantee the serialization ability) in some paths. 

Thanks @openinx for step in. I think I encounter this problem on #2898 when flink try to extract the equality fields to distribute the messages. But In #2898 I have been load the RowDataWrapper lazily and still encounter the kryo serialization issues. Maybe there has other reason, but I will trying to reproduce this problem in unittest later.
https://github.com/apache/iceberg/blob/709e0d3501257d1331cb8633ea25c8029da6f5ad/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java#L73

**Comment by Reo-LEI** [comment]
OK, I think I figure it out this problem. In #2898  of [EqualityFieldKeySelector](https://github.com/apache/iceberg/blob/14af007c7e6fa206cc44dbfde7546feb33718277/flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java#L73) return the `RowDataWrapper` as key directly. When we use RocksDB as flink state backend and distribute record through network, flink `StreamTaskNetworkOutput` will set key context by `StreamOperatorStateHandler` and RocksDB state backend will serialize the key by kryo. But kryo does not directly support serialized lamda functions, and finally we will got this error.
