### ISSUE TITLE
Broken dependency resolution in 0.13.0-SNAPSHOT and Spark 3.2

### ISSUE THREAD

**Issue by racevedoo** [apache/iceberg#3620]
Hi all!

I'm trying to use iceberg's snapshot release (to make use of the better spark 3.2 support), but I'm getting the following error when running spark-shell (full log [here](https://gist.github.com/racevedoo/3530bce04364629f81217e78dea66071))
```
spark-shell --repositories https://repository.apache.org/content/repositories/snapshots \
 --packages org.apache.iceberg:iceberg-spark-3.2-runtime:0.13.0-SNAPSHOT,org.postgresql:postgresql:42.2.10,software.amazon.awssdk:url-connection-client:2.17.68,software.amazon.awssdk:sts:2.17.68,software.amazon.awssdk:s3:2.17.68,software.amazon.awssdk:dynamodb:2.17.68,software.amazon.awssdk:glue:2.17.68


:: problems summary ::
:::: WARNINGS
                module not found: org.slf4j#slf4j-api;working@mymachine

        ==== local-m2-cache: tried

          file:/home/rafael.acevedo/.m2/repository/org/slf4j/slf4j-api/working@mymachine/slf4j-api-working@mymachine.pom

          -- artifact org.slf4j#slf4j-api;working@mymachine!slf4j-api.jar:

          file:/home/rafael.acevedo/.m2/repository/org/slf4j/slf4j-api/working@mymachine/slf4j-api-working@mymachine.jar

        ==== local-ivy-cache: tried

          /home/rafael.acevedo/.ivy2/local/org.slf4j/slf4j-api/working@mymachine/ivys/ivy.xml

          -- artifact org.slf4j#slf4j-api;working@mymachine!slf4j-api.jar:

          /home/rafael.acevedo/.ivy2/local/org.slf4j/slf4j-api/working@mymachine/jars/slf4j-api.jar

        ==== central: tried

          https://repo1.maven.org/maven2/org/slf4j/slf4j-api/working@mymachine/slf4j-api-working@mymachine.pom

          -- artifact org.slf4j#slf4j-api;working@mymachine!slf4j-api.jar:

          https://repo1.maven.org/maven2/org/slf4j/slf4j-api/working@mymachine/slf4j-api-working@mymachine.jar

        ==== spark-packages: tried

          https://repos.spark-packages.org/org/slf4j/slf4j-api/working@mymachine/slf4j-api-working@mymachine.pom

          -- artifact org.slf4j#slf4j-api;working@mymachine!slf4j-api.jar:

          https://repos.spark-packages.org/org/slf4j/slf4j-api/working@mymachine/slf4j-api-working@mymachine.jar

        ==== repo-1: tried

          https://repository.apache.org/content/repositories/snapshots/org/slf4j/slf4j-api/working@mymachine/slf4j-api-working@mymachine.pom

          -- artifact org.slf4j#slf4j-api;working@mymachine!slf4j-api.jar:

          https://repository.apache.org/content/repositories/snapshots/org/slf4j/slf4j-api/working@mymachine/slf4j-api-working@mymachine.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: org.slf4j#slf4j-api;working@mymachine: not found

                ::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
        unknown resolver null

        unknown resolver null

        unknown resolver public

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver sbt-chain

        unknown resolver null

        unknown resolver sbt-chain

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null

        unknown resolver null


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.slf4j#slf4j-api;working@mymachine: not found]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1447)
        at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:898)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

Running with iceberg 0.12.1 works fine:
```
spark-shell --repositories https://repository.apache.org/content/repositories/snapshots --packages org.apache.iceberg:iceberg-spark3-runtime:0.12.1,org.postgresql:postgresql:42.2.10,software.amazon.awssdk:url-connection-client:2.17.68,software.amazon.awssdk:sts:2.17.68,software.amazon.awssdk:s3:2.17.68,software.amazon.awssdk:dynamodb:2.17.68,software.amazon.awssdk:glue:2.17.68
```

From my investigation, slf4j is now a runtime dependency (should be included with spark) since #3335 (https://github.com/apache/iceberg/blob/master/spark/v3.2/build.gradle#L181). In my case, dependency resolution is failing for some reason

**Comment by kbendick** [comment]
I'm not sure why it's trying to resolve to `working@mymachine`.

For example, when it tries this webpage: https://repo1.maven.org/maven2/org/slf4j/slf4j-api/

It tries https://repo1.maven.org/maven2/org/slf4j/slf4j-api/working@mymachine.

But going to that webpage, they're all a list of versions, such as https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.10/

So what I'm most confused about is how it has resolved the slf4j dependency as `working@mymachine`.

**Comment by racevedoo** [comment]
I'm really confused about the `working@mymachine` too, but couldn't find the root cause. Were you able to reproduce @kbendick ?

**Comment by kbendick** [comment]
Oh. On further inspection, it looks like it resolves to both 1.7.25 and 1.7.30 for slf4j-core, which is causing the issue.

https://gist.github.com/racevedoo/3530bce04364629f81217e78dea66071#file-spark-shell-log-L371-L375

The `working@mymachine` seems to come from your local classpath of slf4j.

```
        :: evicted modules:
        org.slf4j#slf4j-api;1.7.25 by [org.slf4j#slf4j-api;working@mymachine] in [default]
        org.slf4j#slf4j-api;working@mymachine by [org.slf4j#slf4j-api;1.7.30] in [default]
        com.fasterxml.jackson.core#jackson-core;2.11.3 by [com.fasterxml.jackson.core#jackson-core;2.11.4] in [default]
        com.fasterxml.jackson.core#jackson-databind;2.11.3 by [com.fasterxml.jackson.core#jackson-databind;2.11.4] in [default]
```

**Comment by kbendick** [comment]
I get a similar issue, though the path is `working@Kyles-Computer`.

Let's try removing some of the glue deps etc and see if maybe that's what's causing the issue?

**Comment by racevedoo** [comment]
I got the same issue with no dependencies other than `iceberg-spark-3.2-runtime`
```
spark-shell --repositories https://repository.apache.org/content/repositories/snapshots \
 --packages org.apache.iceberg:iceberg-spark-3.2-runtime:0.13.0-SNAPSHOT
```

**Comment by kbendick** [comment]
Yeah I did as well. I admittedly havne't used the snapshot dependency pulling it from the snapshot repo.

cc @nastra who setup the SNAPSHOT release process. Wondering if you can reproduce an issue with trying to start a Spark 3.2 shell with iceberg 0.13.0-SNAPSHOT.

```
# Assuming spark-shell is linked to Spark 3.2.0.
spark-shell --repositories https://repository.apache.org/content/repositories/snapshots --packages org.apache.iceberg:iceberg-spark3-runtime:0.12.1
```

**Comment by nastra** [comment]
I can reproduce the issue and I don't understand why it is trying to pull a dependency where it contains the local hostname. Also I don't understand why the dependency pattern is `working@hostname`

**Comment by racevedoo** [comment]
Apparently Ant defaults to `working@hostname` when the version of a dependency is not specified: https://www.mail-archive.com/ivy-user@ant.apache.org/msg06013.html

**Comment by racevedoo** [comment]
Looking at `iceberg-spark-3.2-runtime`'s POM, I found that there is no version specified for `slf4j-api`: https://repository.apache.org/content/repositories/snapshots/org/apache/iceberg/iceberg-spark-3.2-runtime/0.13.0-SNAPSHOT/iceberg-spark-3.2-runtime-0.13.0-20211130.000831-33.pom

At the same time, it's a `runtime` dependency, so I'm not sure if it should make a difference

**Comment by kbendick** [comment]
Well that solves the name look up thing.

For the record, I'm able to reproduce the issue with just the repository and the package as well.

But the primary issue of why it's not able to resolve an slf4j version isn't solved.

From the logs it looks like it is coming up with multiple dependency versions declared, or maybe conflicting versions declared in different dependencies.

I wonder if we've recently added any dependencies that aren't excluding slf4j in a way that they should.

I'm going to run some of the Gradle dependency resolution tools over the current master branch and see if something comes up.

**Comment by kbendick** [comment]
> Looking at `iceberg-spark-3.2-runtime`'s POM, I found that there is no version specified for `slf4j-api`: https://repository.apache.org/content/repositories/snapshots/org/apache/iceberg/iceberg-spark-3.2-runtime/0.13.0-SNAPSHOT/iceberg-spark-3.2-runtime-0.13.0-20211130.000831-33.pom
> 
> At the same time, it's a `runtime` dependency, so I'm not sure if it should make a difference

Yeah we typically expect it to be pulled from a transitive dependency. That's why I'm thinking maybe we have recently added something that isn't excluding it properly.

**Comment by racevedoo** [comment]
I may have found a solution (maybe just a workaround). Looking at the `iceberg-spark-3.2` POM, there is a version specification for `slf4j-api` (1.7.30, got from [here](https://repository.apache.org/content/repositories/snapshots/org/apache/iceberg/iceberg-spark-3.2/0.13.0-SNAPSHOT/iceberg-spark-3.2-0.13.0-20211130.000831-33.pom)). With that, we do not need slf4j-api at all in the spark `runtime` modules, as they include the respective `iceberg-spark` module.

Applying the following patch and publishing a custom version to local maven makes `spark-shell` able to start:

```patch
diff --git a/build.gradle b/build.gradle
index 38388747..b1645a01 100644
--- a/build.gradle
+++ b/build.gradle
@@ -111,7 +111,6 @@ subprojects {
   targetCompatibility = '1.8'
 
   dependencies {
-    implementation 'org.slf4j:slf4j-api'
     implementation 'com.github.stephenc.findbugs:findbugs-annotations'
 
     testImplementation 'org.junit.vintage:junit-vintage-engine'
@@ -147,6 +146,12 @@ subprojects {
   }
 }
 
+configure(subprojects.findAll{!(it.name.contains("spark") && it.name.contains("runtime")) }) {
+  dependencies {
+    implementation 'org.slf4j:slf4j-api'
+  }
+}
+
 project(':iceberg-bundled-guava') {
   apply plugin: 'com.github.johnrengelman.shadow'
 

```

If this makes enough sense, I'd be happy open a PR

**Comment by racevedoo** [comment]
Another option is to exclude log4j from the nebula dependency management plugin config (apparently it does not work well with POMs - check [here](https://github.com/nebula-plugins/nebula-dependency-recommender-plugin#8-notes-on-poms-generated-by-gradle-maven-publish)). This is probably a simpler solution that solves the issue as well:

```patch
diff --git a/build.gradle b/build.gradle
index 38388747..5103cdd5 100644
--- a/build.gradle
+++ b/build.gradle
@@ -111,13 +111,13 @@ subprojects {
   targetCompatibility = '1.8'
 
   dependencies {
-    implementation 'org.slf4j:slf4j-api'
+    implementation 'org.slf4j:slf4j-api:1.7.30'
     implementation 'com.github.stephenc.findbugs:findbugs-annotations'
 
     testImplementation 'org.junit.vintage:junit-vintage-engine'
     testImplementation 'org.junit.jupiter:junit-jupiter-engine'
     testImplementation 'org.junit.jupiter:junit-jupiter'
-    testImplementation 'org.slf4j:slf4j-simple'
+    testImplementation 'org.slf4j:slf4j-simple:1.7.30'
     testImplementation 'org.mockito:mockito-core'
     testImplementation 'org.assertj:assertj-core'
   }
diff --git a/spark/v3.0/build.gradle b/spark/v3.0/build.gradle
index 2ad0fb00..f1edc5e1 100644
--- a/spark/v3.0/build.gradle
+++ b/spark/v3.0/build.gradle
@@ -203,7 +203,7 @@ project(':iceberg-spark:iceberg-spark3-runtime') {
 
     integrationImplementation "org.apache.spark:spark-hive_2.12:${sparkVersion}"
     integrationImplementation 'org.junit.vintage:junit-vintage-engine'
-    integrationImplementation 'org.slf4j:slf4j-simple'
+    integrationImplementation 'org.slf4j:slf4j-simple:1.7.30'
     integrationImplementation project(path: ':iceberg-api', configuration: 'testArtifacts')
     integrationImplementation project(path: ':iceberg-hive-metastore', configuration: 'testArtifacts')
     integrationImplementation project(path: ':iceberg-spark:iceberg-spark3', configuration: 'testArtifacts')
diff --git a/spark/v3.1/build.gradle b/spark/v3.1/build.gradle
index 55e76942..9d4030b9 100644
--- a/spark/v3.1/build.gradle
+++ b/spark/v3.1/build.gradle
@@ -203,7 +203,7 @@ project(':iceberg-spark:iceberg-spark-3.1-runtime_2.12') {
 
     integrationImplementation "org.apache.spark:spark-hive_2.12:${sparkVersion}"
     integrationImplementation 'org.junit.vintage:junit-vintage-engine'
-    integrationImplementation 'org.slf4j:slf4j-simple'
+    integrationImplementation 'org.slf4j:slf4j-simple:1.7.30'
     integrationImplementation project(path: ':iceberg-api', configuration: 'testArtifacts')
     integrationImplementation project(path: ':iceberg-hive-metastore', configuration: 'testArtifacts')
     integrationImplementation project(path: ':iceberg-spark:iceberg-spark-3.1_2.12', configuration: 'testArtifacts')
diff --git a/spark/v3.2/build.gradle b/spark/v3.2/build.gradle
index c85c0fde..dcb8f20b 100644
--- a/spark/v3.2/build.gradle
+++ b/spark/v3.2/build.gradle
@@ -205,7 +205,7 @@ project(':iceberg-spark:iceberg-spark-3.2-runtime_2.12') {
 
     integrationImplementation "org.apache.spark:spark-hive_2.12:${sparkVersion}"
     integrationImplementation 'org.junit.vintage:junit-vintage-engine'
-    integrationImplementation 'org.slf4j:slf4j-simple'
+    integrationImplementation 'org.slf4j:slf4j-simple:1.7.30'
     integrationImplementation project(path: ':iceberg-api', configuration: 'testArtifacts')
     integrationImplementation project(path: ':iceberg-hive-metastore', configuration: 'testArtifacts')
     integrationImplementation project(path: ':iceberg-spark:iceberg-spark-3.2_2.12', configuration: 'testArtifacts')
diff --git a/versions.props b/versions.props
index abe0f80c..65b6a7a7 100644
--- a/versions.props
+++ b/versions.props
@@ -1,4 +1,3 @@
-org.slf4j:* = 1.7.25
 org.apache.avro:avro = 1.10.1
 org.apache.calcite:* = 1.10.0
 org.apache.flink:* = 1.12.5


```

Took the liberty to change the slf4j version to 1.7.30 (that was the version that was being resolved to anyway)
