### ISSUE TITLE
throw exception : InvalidOperationException(message:The following columns have types incompatible with the existing columns in their respective positions : idd1) when add column

### ISSUE THREAD

**Issue by fennuzhichui** [apache/iceberg#3747]
when add column use sql :  alter table test.czm33 add columns idd1bigint comment 'test2' after age;
it will throw exception.
java.lang.RuntimeException: InvalidOperationException(message:The following columns have types incompatible with the existing columns in their respective positions :
idd)
	at org.apache.iceberg.relocated.com.google.common.base.Throwables.propagate(Throwables.java:241)
	at org.apache.iceberg.common.DynMethods$UnboundMethod.invoke(DynMethods.java:80)
	at org.apache.iceberg.hive.HiveTableOperations.lambda$persistTable$1(HiveTableOperations.java:220)
	at org.apache.iceberg.hive.ClientPool.run(ClientPool.java:55)
	at org.apache.iceberg.hive.HiveTableOperations.persistTable(HiveTableOperations.java:216)
	at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:191)
	at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:118)
	at org.apache.iceberg.BaseTransaction.lambda$commitSimpleTransaction$5(BaseTransaction.java:360)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:213)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:197)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:189)
	at org.apache.iceberg.BaseTransaction.commitSimpleTransaction(BaseTrans
can reproduce follow this:
use icebergtest.test;
create table czm33(id int ,age bigint, idd bigint, name string, udt string) using iceberg partitioned by (udt);
alter table test.czm33 add columns idd2 bigint comment 'test2' after age;

**Comment by sanchitkashyap** [comment]
Looks duplicate of https://github.com/apache/iceberg/issues/1092. Can you try this https://github.com/apache/iceberg/issues/1092#issuecomment-638432848.

**Comment by szehon-ho** [comment]
Unfortuantely it's a server-side Hive configuration and metastore needs to be restarted with this config set.

**Comment by pawankukreja01** [comment]
Based on the error message you provided, it seems like the column idd has an incompatible type with the existing columns in their respective positions.

To add a column to an existing table, you can use the `ALTER TABLE` statement. Here’s an example of how to add a column to a table:

`ALTER TABLE table_name ADD column_name datatype;`

In your case, you can try running the following SQL command to add a new column named `idd1` of type `bigint` with a comment of `test2` after the `age` column:

`ALTER TABLE test.czm33 ADD COLUMN idd1 BIGINT COMMENT 'test2' AFTER age;`
