### ISSUE TITLE
Deadlock when using CachingCatalog with Iceberg 0.13.0-SNAPSHOT

### ISSUE THREAD

**Issue by racevedoo** [apache/iceberg#3791]
Hi all!

When running maintenance procedures with spark sql, namely `expire_snapshots, rewrite_data_files, rewrite_manifests and remove_orphan_files`, I'm getting a deadlock within the caffeine cache in CachingCatalog. This does not happen for every run, but happens for most of them (specifically when running the `rewrite_data_files` procedure).

The blocked threads and their traces are below:
```

"ForkJoinPool.commonPool-worker-13" #1103 daemon prio=5 os_prio=0 cpu=7.93ms elapsed=674.73s tid=0x000055c8bb5e9000 nid=0x5a0 waiting for monitor entry  [0x00007f0291ee4000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.util.concurrent.ConcurrentHashMap.computeIfPresent(java.base@11.0.12/ConcurrentHashMap.java:1814)
        - waiting to lock <0x00000006c9b9fca0> (a java.util.concurrent.ConcurrentHashMap$Node)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.remove(BoundedLocalCache.java:2102)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCache.invalidateAll(LocalCache.java:121)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.invalidateAll(LocalManualCache.java:145)
        at org.apache.iceberg.CachingCatalog$MetadataTableInvalidatingCacheWriter.delete(CachingCatalog.java:101)
        at org.apache.iceberg.CachingCatalog$MetadataTableInvalidatingCacheWriter.delete(CachingCatalog.java:92)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$evictEntry$2(BoundedLocalCache.java:937)
        - locked <0x00000006c7576498> (a org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.PDA)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$4879/0x0000000801e49440.apply(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.computeIfPresent(java.base@11.0.12/ConcurrentHashMap.java:1822)
        - locked <0x00000006cf86f1c8> (a java.util.concurrent.ConcurrentHashMap$Node)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.evictEntry(BoundedLocalCache.java:905)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.expireAfterAccessEntries(BoundedLocalCache.java:818)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.expireAfterAccessEntries(BoundedLocalCache.java:802)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.expireEntries(BoundedLocalCache.java:782)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.maintenance(BoundedLocalCache.java:1479)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:1448)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.run(BoundedLocalCache.java:3293)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.exec(BoundedLocalCache.java:3280)
        at java.util.concurrent.ForkJoinTask.doExec(java.base@11.0.12/ForkJoinTask.java:290)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@11.0.12/ForkJoinPool.java:1020)
        at java.util.concurrent.ForkJoinPool.scan(java.base@11.0.12/ForkJoinPool.java:1656)
        at java.util.concurrent.ForkJoinPool.runWorker(java.base@11.0.12/ForkJoinPool.java:1594)
        at java.util.concurrent.ForkJoinWorkerThread.run(java.base@11.0.12/ForkJoinWorkerThread.java:183)

   Locked ownable synchronizers:
        - <0x00000006c5103038> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

"HiveServer2-Background-Pool: Thread-1682" #1682 prio=5 os_prio=0 cpu=13.77ms elapsed=412.87s tid=0x00007f02a8034800 nid=0x845 waiting for monitor entry  [0x00007f01ed9ee000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.util.concurrent.ConcurrentHashMap.computeIfPresent(java.base@11.0.12/ConcurrentHashMap.java:1814)
        - waiting to lock <0x00000006cf86f1c8> (a java.util.concurrent.ConcurrentHashMap$Node)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.remove(BoundedLocalCache.java:2102)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCache.invalidateAll(LocalCache.java:121)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.invalidateAll(LocalManualCache.java:145)
        at org.apache.iceberg.CachingCatalog$MetadataTableInvalidatingCacheWriter.delete(CachingCatalog.java:101)
        at org.apache.iceberg.CachingCatalog$MetadataTableInvalidatingCacheWriter.delete(CachingCatalog.java:92)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2368)
        - locked <0x00000006c9a0f0d8> (a org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.PDA)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$2256/0x00000008014aac40.apply(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.compute(java.base@11.0.12/ConcurrentHashMap.java:1932)
        - locked <0x00000006c9b9fca0> (a java.util.concurrent.ConcurrentHashMap$Node)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2342)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2325)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
        at org.apache.iceberg.CachingCatalog.loadTable(CachingCatalog.java:168)
        at org.apache.iceberg.spark.SparkCatalog.load(SparkCatalog.java:490)
        at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:135)
        at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:92)
        at org.apache.iceberg.spark.procedures.BaseProcedure.loadSparkTable(BaseProcedure.java:115)
        at org.apache.iceberg.spark.procedures.BaseProcedure.execute(BaseProcedure.java:82)
        at org.apache.iceberg.spark.procedures.BaseProcedure.modifyIcebergTable(BaseProcedure.java:74)
        at org.apache.iceberg.spark.procedures.RewriteDataFilesProcedure.call(RewriteDataFilesProcedure.java:94)
        at org.apache.spark.sql.execution.datasources.v2.CallExec.run(CallExec.scala:33)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
        - locked <0x00000006d8f18c68> (a org.apache.spark.sql.execution.datasources.v2.CallExec)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:110)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1$$Lambda$1933/0x00000008012b3840.apply(Unknown Source)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$$$Lambda$1941/0x00000008012b7440.apply(Unknown Source)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.execution.SQLExecution$$$Lambda$1934/0x00000008012b3c40.apply(Unknown Source)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:110)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:106)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$Lambda$1923/0x00000008012ad840.apply(Unknown Source)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
        at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:106)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:93)
        - locked <0x00000006d8f18ea8> (a org.apache.spark.sql.execution.QueryExecution)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:91)
        at org.apache.spark.sql.Dataset.<init>(Dataset.scala:219)
        at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
        at org.apache.spark.sql.Dataset$$$Lambda$1551/0x0000000800f6cc40.apply(Unknown Source)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
        at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
        at org.apache.spark.sql.SparkSession$$Lambda$1471/0x0000000800f28840.apply(Unknown Source)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
        at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:651)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:291)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.$anonfun$run$2(SparkExecuteStatementOperation.scala:230)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3$$Lambda$2166/0x00000008013e5440.apply$mcV$sp(Unknown Source)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.sql.hive.thriftserver.SparkOperation.withLocalProperties(SparkOperation.scala:79)
        at org.apache.spark.sql.hive.thriftserver.SparkOperation.withLocalProperties$(SparkOperation.scala:63)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.withLocalProperties(SparkExecuteStatementOperation.scala:43)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:230)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:225)
        at java.security.AccessController.doPrivileged(java.base@11.0.12/Native Method)
        at javax.security.auth.Subject.doAs(java.base@11.0.12/Subject.java:423)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2.run(SparkExecuteStatementOperation.scala:239)
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.12/Executors.java:515)
        at java.util.concurrent.FutureTask.run(java.base@11.0.12/FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.12/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.12/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.12/Thread.java:829)

   Locked ownable synchronizers:
        - <0x00000006d8f19118> (a java.util.concurrent.ThreadPoolExecutor$Worker)

```

Full thread dump available [here](https://gist.github.com/racevedoo/e90a23ffdad3534522773501f47efb04)

From what I'm seeing, this happens when running multiple procedure calls in a row (sequentially) and for multiple tables. Running a single `rewrite_data_files` works fine (probably because the cache has not expired yet).

The workaround on my end was to disable caching.

Environment details: Spark 3.2 and Iceberg 0.13.0-SNAPSHOT

**Comment by racevedoo** [comment]
I investigated this a little, and found that in 9c3e340c we added `MetadataTableInvalidatingCacheWriter`. From my understanding, I think it introduces additional writes to the cache in the `tableCache.get` trace called by `loadTable`. This probably violates an assumption made by caffeine's `Cache` class (that `get` calls do not change additional entries) - see javadoc (https://github.com/ben-manes/caffeine/blob/v2.8.4/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Cache.java#L55-L68)

This causes the a deadlock between 2 threads: the procedure call thread (`HiveServer2-Background-Pool: Thread-1682` in the trace) trying to invalidate cache entries while caffeine's `PerformCleanupTask` (`ForkJoinPool.commonPool-worker-13` in the trace) is trying to cleanup the cache due to ttl expiration.

**Comment by racevedoo** [comment]
cc @kbendick could you take a look at this and tell me if it makes sense? 

This is probably related to the cache expiration option we introduced recently

**Comment by racevedoo** [comment]
also cc @igorcalabria who helped me investigate this

**Comment by kbendick** [comment]
> cc @kbendick could you take a look at this and tell me if it makes sense?
> 
> This is probably related to the cache expiration option we introduced recently

Thanks for the detailed report. I will take a look more closely at this this afternoon. The procedures make heavy use of the metadata tables.

For now, if you set `cache.expiration-interval-ms` to -1 on the catalog’s configuration, you’ll get the old behavior if you’d like to continue using the SNAPSHOT to investigate other things.

If you’d like to investigate further, as it might take me a day or two to get a reliable reproduction, you can try raising the value of `cache.expiration-interval-ms` to see if that reduces the likelihood of hitting the issue.

Though it sounds like in your case it might be better to leave expiration off when calling the procedures.

Thanks again for the detailed report.

**Comment by kbendick** [comment]
Question: we’re you running those procedures sequentially on one table, or on multiple tables?

**Comment by racevedoo** [comment]
> Question: we’re you running those procedures sequentially on one table, or on multiple tables?

Multiple tables (4 of them)

**Comment by kbendick** [comment]
Ok. And can you describe the tables (are they partitioned, how big are they) and also, how youv'e configured the procedure calls (do they have a filter, do they group commits or do they use the default behavior of committing all at the end)?

I think this can be solved. I've just started researching more, and I am still working on a reproduction case. If you have one you can send or create a gist for, that would be awesome.

But I'm seeing a few options. We can pass a `scheduler` in to [make the expiration more synchronous](https://github.com/ben-manes/caffeine/wiki/Compute#synchronous-listeners), and then alternatively we can also consider trying to set both `refreshAfter` and `expireAfter`, as `refreshAfter` will mark the entry for removal, and then on the next round, it will return the [old value and then evict the entry (so the next get will return right away)](https://github.com/ben-manes/caffeine/issues/204#issuecomment-345312109).

**Comment by ben-manes** [comment]
Java's ConcurrentHashMap does not allow for computations to modify the hash map. This may livelock, deadlock, or may throw an exception (Java 9+).

A `CacheWriter` performs its actions under a map computation to be atomic. This has since been deprecated and removed in 3.0. Your use-case of responding to evictions is either served by an `evictionListener` (atomic; notified within the `computeIfPresent` removing the entry) or `removalListener` (async; notified after the computation). Since your callback is removing more entries, it looks like an async removal listener might work better here.

The `refreshAfterWrite` feature will proactively reload an entry if accessed after the threshold period. This can combined with expiration so that active content is kept fresh and inactive fades away. If only expiration is used then one may periodically see a latency spike when a popular item expires and the callers block waiting for it to be loaded. If both expiration and refresh are set to the same threshold then the entry is discarded, as one setting says it stale and the other that it is unusable. 

The scheduler is helpful when application logic relies on timely removal of an expired entry. For example to close a websocket after the client times out due to inactivity. As the cache itself does not start any background threads, by default it relies on other activity (reads, writes) to trigger a maintenance cycle when it will sweep away expired entries.

As an aside, I would recommend against using soft references as they have long been a problematic Java feature. The usual reason is a lack of knowledge of a good maximum size, but delegating to the GC can cause high pause times and churn. Instead improving instrumentation and setting a size threshold allows for more predictable latencies, avoids GC death spirals / OOME, and allows for use of a better eviction algorithm.

hope that helps a little.

**Comment by racevedoo** [comment]
Thanks for the detailed explanation @ben-manes! This helps a lot.

> I think this can be solved. I've just started researching more, and I am still working on a reproduction case. If you have one you can send or create a gist for, that would be awesome.

I can try to create a failing test reproducing the two threads. It's quite difficult to reproduce this (as it normally is with deadlocks).

**Comment by racevedoo** [comment]
> Ok. And can you describe the tables (are they partitioned, how big are they) and also, how youv'e configured the procedure calls (do they have a filter, do they group commits or do they use the default behavior of committing all at the end)?

The tables are quite small (~500MB). They are not partitioned.
The procedures are just using the default behavior (except for the file size in `rewrite_data_files`):
```sql
CALL prod.system.expire_snapshots(table => 'my_db.table');
CALL prod.system.rewrite_data_files(table => 'my_db.table', options => map('target-file-size-bytes','26214400')); --25MB
CALL prod.system.rewrite_manifests(table => 'my_db.table');
CALL prod.system.remove_orphan_files(table => 'my_db.table');
```

**Comment by racevedoo** [comment]
I have a failing test and a fix. I will open the PRs soon

**Comment by racevedoo** [comment]
Opened #3798 (failing test) and #3801 (fix)
