### ISSUE TITLE
How do I make Iceberg ignore corrupt (parquet, ORC, avro) file?

### ISSUE THREAD

**Issue by dubeme** [apache/iceberg#4051]
In our datalake, it is posible to corrupt files to exists in the same directory of a hive table. We've been using the Iceber `add_files` procedure to migrate those tables to Iceberg. Unfortunately, Iceberg will fail when it encounters a corrupt (_a file that doesn't match the file type Iceberg is looking for_) file. Below is a sample exception. **So, is it possible to tell Iceberg to ignore those files?** This is possible in Spark, setting `spark.sql.files.ignoreCorruptFiles=true`.

```
Error: Job aborted due to stage failure: Task 34 in stage 1.0 failed 4 times, most recent failure: Lost task 34.3 in stage 1.0 (TID 222) (vm-f1668438 executor 19): java.lang.RuntimeException: <REDACTED PATH> is not a Parquet file (length is too low: 0)
	at org.apache.iceberg.shaded.org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:539)
	at org.apache.iceberg.shaded.org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:776)
	at org.apache.iceberg.shaded.org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:645)
	at org.apache.iceberg.parquet.ParquetUtil.fileMetrics(ParquetUtil.java:78)
	at org.apache.iceberg.data.TableMigrationUtil.getParquetMerics(TableMigrationUtil.java:145)
	at org.apache.iceberg.data.TableMigrationUtil.lambda$listPartition$3(TableMigrationUtil.java:113)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190)
	at org.apache.iceberg.data.TableMigrationUtil.listPartition(TableMigrationUtil.java:112)
	at org.apache.iceberg.data.TableMigrationUtil.listPartition(TableMigrationUtil.java:80)
	at org.apache.iceberg.spark.SparkTableUtil.listPartition(SparkTableUtil.java:304)
	at org.apache.iceberg.spark.SparkTableUtil.lambda$importSparkPartitions$f46fdb10$1(SparkTableUtil.java:531)
	at org.apache.spark.sql.Dataset.$anonfun$flatMap$2(Dataset.scala:2876)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.sort(UnsafeExternalRowSorter.java:300)
	at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$.$anonfun$prepareShuffleDependency$10(ShuffleExchangeExec.scala:349)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2263)
org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2212)
org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2211)
scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2211)
org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1082)
org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1082)
scala.Option.foreach(Option.scala:407)
org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1082)
org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2450)
org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2392)
org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2381)
org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:869)
org.apache.spark.SparkContext.runJob(SparkContext.scala:2243)
org.apache.spark.SparkContext.runJob(SparkContext.scala:2264)
org.apache.spark.SparkContext.runJob(SparkContext.scala:2283)
org.apache.spark.SparkContext.runJob(SparkContext.scala:2308)
org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1030)
org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
org.apache.spark.rdd.RDD.collect(RDD.scala:1029)
org.apache.spark.RangePartitioner$.sketch(Partitioner.scala:304)
org.apache.spark.RangePartitioner.<init>(Partitioner.scala:171)
org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$.prepareShuffleDependency(ShuffleExchangeExec.scala:273)
org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.shuffleDependency$lzycompute(ShuffleExchangeExec.scala:155)
org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.shuffleDependency(ShuffleExchangeExec.scala:149)
org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.$anonfun$doExecute$1(ShuffleExchangeExec.scala:172)
org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:52)
org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.doExecute(ShuffleExchangeExec.scala:163)
org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:218)
org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:256)
org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:253)
org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:214)
org.apache.spark.sql.execution.InputAdapter.inputRDD(WholeStageCodegenExec.scala:525)
org.apache.spark.sql.execution.InputRDDCodegen.inputRDDs(WholeStageCodegenExec.scala:453)
org.apache.spark.sql.execution.InputRDDCodegen.inputRDDs$(WholeStageCodegenExec.scala:452)
org.apache.spark.sql.execution.InputAdapter.inputRDDs(WholeStageCodegenExec.scala:496)
org.apache.spark.sql.execution.SortExec.inputRDDs(SortExec.scala:155)
org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:746)
org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:218)
org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:256)
org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:253)
org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:214)
org.apache.spark.sql.execution.DeserializeToObjectExec.doExecute(objects.scala:96)
org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:218)
org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:256)
org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:253)
org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:214)
org.apache.spark.sql.execution.MapPartitionsExec.doExecute(objects.scala:192)
org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:218)
org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:256)
org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:253)
org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:214)
org.apache.spark.sql.execution.InputAdapter.inputRDD(WholeStageCodegenExec.scala:525)
org.apache.spark.sql.execution.InputRDDCodegen.inputRDDs(WholeStageCodegenExec.scala:453)
org.apache.spark.sql.execution.InputRDDCodegen.inputRDDs$(WholeStageCodegenExec.scala:452)
org.apache.spark.sql.execution.InputAdapter.inputRDDs(WholeStageCodegenExec.scala:496)
org.apache.spark.sql.execution.SerializeFromObjectExec.inputRDDs(objects.scala:117)
org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:746)
org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:218)
org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:256)
org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:253)
org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:214)
org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:359)
org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:425)
org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3696)
org.apache.spark.sql.Dataset.$anonfun$collectAsList$1(Dataset.scala:2977)
org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3687)
org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:112)
org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:176)
org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:94)
org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:67)
org.apache.spark.sql.Dataset.withAction(Dataset.scala:3685)
org.apache.spark.sql.Dataset.collectAsList(Dataset.scala:2976)
org.apache.iceberg.spark.SparkTableUtil.importSparkPartitions(SparkTableUtil.java:573)
org.apache.iceberg.spark.procedures.AddFilesProcedure.importPartitions(AddFilesProcedure.java:194)
org.apache.iceberg.spark.procedures.AddFilesProcedure.importFileTable(AddFilesProcedure.java:179)
org.apache.iceberg.spark.procedures.AddFilesProcedure.lambda$importToIceberg$1(AddFilesProcedure.java:138)
org.apache.iceberg.spark.procedures.BaseProcedure.execute(BaseProcedure.java:85)
org.apache.iceberg.spark.procedures.BaseProcedure.modifyIcebergTable(BaseProcedure.java:74)
org.apache.iceberg.spark.procedures.AddFilesProcedure.importToIceberg(AddFilesProcedure.java:130)
org.apache.iceberg.spark.procedures.AddFilesProcedure.call(AddFilesProcedure.java:116)
org.apache.spark.sql.execution.datasources.v2.CallExec.run(CallExec.scala:33)
org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:40)
org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:40)
org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:46)
org.apache.spark.sql.Dataset.$anonfun$logicalPlan$1(Dataset.scala:228)
org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3687)
org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:112)
org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:176)
org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:94)
org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:67)
org.apache.spark.sql.Dataset.withAction(Dataset.scala:3685)
org.apache.spark.sql.Dataset.<init>(Dataset.scala:228)
org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
org.apache.livy.repl.SQLInterpreter.execute(SQLInterpreter.scala:128)
org.apache.livy.repl.Session.$anonfun$executeCode$1(Session.scala:330)
scala.Option.map(Option.scala:230)
org.apache.livy.repl.Session.executeCode(Session.scala:328)
org.apache.livy.repl.Session.$anonfun$execute$2(Session.scala:202)
org.apache.livy.repl.Session.withRealtimeOutputSupport(Session.scala:451)
org.apache.livy.repl.Session.$anonfun$execute$1(Session.scala:202)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
scala.util.Success.$anonfun$map$1(Try.scala:255)
scala.util.Success.map(Try.scala:213)
scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

**Comment by RussellSpitzer** [comment]
No, at the moment that isn't possible and I don't think we would want to add this capability. I think if you have records you are sure can be removed safely you should use the Iceberg Java API to delete those files so they are officially removed from the table. 

One thing we could do is add some filters in `addFiles` to skip invalid files or something like that?

**Comment by RussellSpitzer** [comment]
Ah I misread you are looking for such an option. That we could do, I think it wouldn't be that hard to put a try catch in add-files that is only used if a flag "skip-corrupt-files" or something is set.

**Comment by dubeme** [comment]
> Ah I misread you are looking for such an option. That we could do, I think it wouldn't be that hard to put a try catch in add-files that is only used if a flag "skip-corrupt-files" or something is set.

I see you read things like I do 😂 Yes, I want to Ignore corrupt files during Table import via _add_files_. Ideally controlled with a flag. 

I've been looking at the code path, and it seems `TableMigrationUtil.listPartition` (https://github.com/apache/iceberg/blob/2208b24617f2c64bb02f1a7aec79f3bbaabdc1cc/data/src/main/java/org/apache/iceberg/data/TableMigrationUtil.java#L106) is the place to start?

**Comment by RussellSpitzer** [comment]
Yes, Take a look at the Tasks API and you should see we have the option to put a flag on "Suppress Exceptions", I think we also have a "handleException" method. I would basically just use one of those

**Comment by dubeme** [comment]
Ah, that makes it easier... BTW, I want to add breakpoints to the code sections and inspect executions, but haven't figured out how to setup my environment to do so. Do you have any recomendations?

**Comment by RussellSpitzer** [comment]
I use IntelliJ idea and the iceberg project works for me out of the box. The only additional config is for check style which has config notes in our docs

**Comment by hililiwei** [comment]
hi, guys, i have raised a PR for this. If you have available, could you please help to review? thx.
