### ISSUE TITLE
FLINK:I meet this error when i use DataStream to read hive_catalogTable?

### ISSUE THREAD

**Issue by gongjinzz** [apache/iceberg#4389]
i want to know whether hive_catalog table can be read by DataStream?

Exception in thread "main" java.lang.IllegalArgumentException: Cannot initialize Catalog implementation org.apache.iceberg.hive.HiveCatalog: Cannot find constructor for interface org.apache.iceberg.catalog.Catalog
	Missing org.apache.iceberg.hive.HiveCatalog [java.lang.NoClassDefFoundError: org/apache/hadoop/hive/metastore/api/UnknownDBException]
	at org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:176)
	at org.apache.iceberg.flink.CatalogLoader$HiveCatalogLoader.loadCatalog(CatalogLoader.java:112)
	at org.apache.iceberg.flink.TableLoader$CatalogTableLoader.open(TableLoader.java:108)
	at org.apache.iceberg.flink.source.FlinkSource$Builder.buildFormat(FlinkSource.java:178)
	at org.apache.iceberg.flink.source.FlinkSource$Builder.build(FlinkSource.java:204)
	at HadoopDemo2$.main(HadoopDemo2.scala:50)
	at HadoopDemo2.main(HadoopDemo2.scala)
Caused by: java.lang.NoSuchMethodException: Cannot find constructor for interface org.apache.iceberg.catalog.Catalog
	Missing org.apache.iceberg.hive.HiveCatalog [java.lang.NoClassDefFoundError: org/apache/hadoop/hive/metastore/api/UnknownDBException]
	at org.apache.iceberg.common.DynConstructors$Builder.buildChecked(DynConstructors.java:227)
	at org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:174)
	... 6 more

Process finished with exit code 1

**Comment by molsionmo** [comment]
You may be missing package hive-metastore-2.3.8.jar(or other version), check hadoop Settings or put the package in the $flink_home/lib directory

**Comment by gongjinzz** [comment]
You are right,thank you!

**Comment by gongjinzz** [comment]
> You may be missing package hive-metastore-2.3.8.jar(or other version), check hadoop Settings or put the package in the $flink_home/lib directory

You are right,thank you!
