### ISSUE TITLE
On iceberg11 getting s3 connection reset error

### ISSUE THREAD

**Issue by yeshvantbhavnasi** [apache/iceberg#4457]
Started getting connection reset error on s3 reader stacktrace : 

Can anyone navigate to me what could be the issue here? 
`22/03/31 22:32:16 WARN TaskSetManager: Lost task 100.0 in stage 0.0 (TID 100, ip-10-26-20-170.prod.dp.box.net, executor 35): org.apache.iceberg.exceptions.RuntimeIOException: javax.net.ssl.SSLException: Connection reset
	at org.apache.iceberg.parquet.ParquetReader$FileIterator.advance(ParquetReader.java:135)
	at org.apache.iceberg.parquet.ParquetReader$FileIterator.next(ParquetReader.java:112)
	at org.apache.iceberg.spark.source.BaseDataReader.next(BaseDataReader.java:88)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.hasNext(DataSourceRDD.scala:49)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:462)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:117)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:116)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1439)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:146)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:67)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:66)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1405)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: javax.net.ssl.SSLException: Connection reset
	at sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:138)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1363)
	at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:73)
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:957)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:197)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:198)
	at org.apache.http.impl.io.ContentLengthInputStream.close(ContentLengthInputStream.java:101)
	at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:142)
	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at software.amazon.awssdk.services.s3.checksums.ChecksumValidatingInputStream.close(ChecksumValidatingInputStream.java:162)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at software.amazon.awssdk.core.io.SdkFilterInputStream.close(SdkFilterInputStream.java:83)
	at org.apache.iceberg.aws.s3.S3InputStream.closeStream(S3InputStream.java:149)
	at org.apache.iceberg.aws.s3.S3InputStream.openStream(S3InputStream.java:143)
	at org.apache.iceberg.aws.s3.S3InputStream.positionStream(S3InputStream.java:132)
	at org.apache.iceberg.aws.s3.S3InputStream.read(S3InputStream.java:80)
	at com.box.dataplatform.iceberg.encryption.crypto.TruncatedInputStream.read(TruncatedInputStream.java:25)
	at java.io.InputStream.read(InputStream.java:170)
	at java.io.InputStream.read(InputStream.java:101)
	at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:121)
	at javax.crypto.CipherInputStream.read(CipherInputStream.java:199)
	at com.box.dataplatform.iceberg.encryption.crypto.DecryptingSeekableInputStream.read(DecryptingSeekableInputStream.java:53)
	at java.io.InputStream.read(InputStream.java:170)
	at org.apache.iceberg.shaded.org.apache.parquet.io.DelegatingSeekableInputStream.readFully(DelegatingSeekableInputStream.java:102)
	at org.apache.iceberg.shaded.org.apache.parquet.io.DelegatingSeekableInputStream.readFullyHeapBuffer(DelegatingSeekableInputStream.java:127)
	at org.apache.iceberg.shaded.org.apache.parquet.io.DelegatingSeekableInputStream.readFully(DelegatingSeekableInputStream.java:91)
	at org.apache.iceberg.shaded.org.apache.parquet.hadoop.ParquetFileReader$ConsecutivePartList.readAll(ParquetFileReader.java:1464)
	at org.apache.iceberg.shaded.org.apache.parquet.hadoop.ParquetFileReader.readNextRowGroup(ParquetFileReader.java:853)
	at org.apache.iceberg.parquet.ParquetReader$FileIterator.advance(ParquetReader.java:133)
	... 21 more
	Suppressed: java.net.SocketException: Broken pipe (Write failed)
		at java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
		at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
		at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:355)
		... 57 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:464)
	at sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:237)
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:190)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109)
	... 54 more`

**Comment by rajarshisarkar** [comment]
Hi, Can you please help me with the issue reproduction steps?

**Comment by yeshvantbhavnasi** [comment]
I guess this is becuase of hadoop s3 connector not trying to reconnect. 
This is on a simple IcebergRead causing an exception

**Comment by yeshvantbhavnasi** [comment]
Problem was the number of partition on the dataframe was large, causing s3 read to fail. 
- Did a `df.repartition(df.rdd.numberOfPartition*10)` and it started working

**Comment by javrasya** [comment]
I am using Flink to consume from a table which gets upserts and I am getting this error too. Tried tweaking http client socket timeouts and stuff but nothing has worked so for for me. How did reducing the number of partitions with Spark helped here? Was it maybe S3 in your case which was closing the socket 🤔 ?

**Comment by anirbanroyeasygo** [comment]
I am getting a similar issue consuming from kinesis and merging into an iceberg table. My spark structured streaming code works when its inserting the data into a new file but whenever it tries to access an older partition(not caused by s3 eventual consistency issue), it fails with the following issue:
```

2025-01-29 00:36:30,223 ERROR [Executor task launch worker for task 16177.0 in stage 31.0 (TID 68551)]
 
source.BaseDataReader (BaseDataReader.java:next(120)): Error reading file: s3://path/00198-11348490-64a86129-f447-4497-8898-5bbaf58d64f4-00001.parquetorg.apache.iceberg.exceptions.RuntimeIOException: javax.net.ssl.SSLException: Connection reset	at 

org.apache.iceberg.parquet.VectorizedParquetReader$FileIterator.advance(VectorizedParquetReader.java:165) ~[iceberg-spark-runtime-3.3_2.12-1.0.0.jar:?]	
at org.apache.iceberg.parquet.VectorizedParquetReader$FileIterator.next(VectorizedParquetReader.java:141) ~[iceberg-spark-runtime-3.3_2.12-1.0.0.jar:?]	at org.apache.iceberg.spark.source.BaseDataReader.next(BaseDataReader.java:107) ~[iceberg-spark-runtime-3.3_2.12-1.0.0.jar:?]	
at org.apache.spark.sql.execution.datasources.v2.PartitionIterator.hasNext(DataSourceRDD.scala:119) ~[spark-sql_2.12-3.3.0-amzn-1.j

```
