### ISSUE TITLE
Spark: SparkSQL call procedures blocking(expire_snapshots and delete orphan files)

### ISSUE THREAD

**Issue by eric666666** [apache/iceberg#4471]
Spark version: 3.2.1 or 3.1.2
Spark SQL statements:
` CALL hive_prod.system.expire_snapshots(table => 'test.iceberg_test_col_data_with_dt_02', older_than => timestamp '2022-05-18 19:02:00.595',retain_last => 1); 
`
`CALL hive_prod.system.remove_orphan_files(table => 'test.iceberg_test_col_data_with_dt_02', dry_run => true);`
Execute statement may occour spark task blocking(last task of collectAsList operator)

**Comment by eric666666** [comment]
When we use upon spark sql statements ,we found that Spark job will block on the last task of stage.
![image](https://user-images.githubusercontent.com/51162281/161371008-38f2a2a2-63bd-4bcb-bd1f-4e18156d90c5.png)

We printed full thread information about locks.
`"main" #1 prio=5 os_prio=0 tid=0x0000000002f79800 nid=0x1bd4 waiting on condition [0x0000000002f1c000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000004c7b1bf38> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$getFinalPhysicalPlan$1(AdaptiveSparkPlanExec.scala:273)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec$$Lambda$2268/608590206.apply(Unknown Source)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.getFinalPhysicalPlan(AdaptiveSparkPlanExec.scala:226)
        - locked <0x00000004c7fa0240> (a java.lang.Object)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.withFinalPlanUpdate(AdaptiveSparkPlanExec.scala:365)
        at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.executeCollect(AdaptiveSparkPlanExec.scala:338)
        at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3715)
        at org.apache.spark.sql.Dataset.$anonfun$collectAsList$1(Dataset.scala:2983)
        at org.apache.spark.sql.Dataset$$Lambda$1843/857865061.apply(Unknown Source)
        at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3706)
        at org.apache.spark.sql.Dataset$$Lambda$1844/1920110923.apply(Unknown Source)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$$$Lambda$1289/993347235.apply(Unknown Source)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.execution.SQLExecution$$$Lambda$1282/2074109190.apply(Unknown Source)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3704)
        at org.apache.spark.sql.Dataset.collectAsList(Dataset.scala:2982)
        at org.apache.iceberg.spark.actions.BaseExpireSnapshotsSparkAction.doExecute(BaseExpireSnapshotsSparkAction.java:219)
        at org.apache.iceberg.spark.actions.BaseExpireSnapshotsSparkAction$$Lambda$1503/1268892066.get(Unknown Source)
        at org.apache.iceberg.spark.actions.BaseSparkAction.withJobGroupInfo(BaseSparkAction.java:98)
        at org.apache.iceberg.spark.actions.BaseExpireSnapshotsSparkAction.execute(BaseExpireSnapshotsSparkAction.java:188)
        at org.apache.iceberg.spark.actions.BaseExpireSnapshotsSparkAction.execute(BaseExpireSnapshotsSparkAction.java:68)
        at org.apache.iceberg.spark.procedures.ExpireSnapshotsProcedure.lambda$call$0(ExpireSnapshotsProcedure.java:110)
        at org.apache.iceberg.spark.procedures.ExpireSnapshotsProcedure$$Lambda$1488/961628534.apply(Unknown Source)
        at org.apache.iceberg.spark.procedures.BaseProcedure.execute(BaseProcedure.java:85)
        at org.apache.iceberg.spark.procedures.BaseProcedure.modifyIcebergTable(BaseProcedure.java:74)
        at org.apache.iceberg.spark.procedures.ExpireSnapshotsProcedure.call(ExpireSnapshotsProcedure.java:95)
        at org.apache.spark.sql.execution.datasources.v2.CallExec.run(CallExec.scala:33)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
        - locked <0x00000004c48c0cc0> (a org.apache.spark.sql.execution.datasources.v2.CallExec)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:110)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1$$Lambda$1281/1519216494.apply(Unknown Source)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$$$Lambda$1289/993347235.apply(Unknown Source)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.execution.SQLExecution$$$Lambda$1282/2074109190.apply(Unknown Source)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:110)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:106)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$Lambda$1002/771715205.apply(Unknown Source)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan
.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
        at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:106)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:93)
        - locked <0x00000004c4646e88> (a org.apache.spark.sql.execution.QueryExecution)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:91)
        at org.apache.spark.sql.Dataset.<init>(Dataset.scala:219)
        at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
        at org.apache.spark.sql.Dataset$$$Lambda$828/2128310218.apply(Unknown Source)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
        at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
        at org.apache.spark.sql.SparkSession$$Lambda$716/1165568071.apply(Unknown Source)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
        at com.eric.icebergspark.CallCommand.ExpireSnapshot$.$anonfun$main$1(ExpireSnapshot.scala:71)
        at com.eric.icebergspark.CallCommand.ExpireSnapshot$.$anonfun$main$1$adapted(ExpireSnapshot.scala:72)
        at com.eric.icebergspark.CallCommand.ExpireSnapshot$$$Lambda$715/903064416.apply(Unknown Source)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at com.eric.icebergspark.call.ExpireSnapshot$.main(ExpireSnapshot.scala:72)
        at com.eric.icebergspark.call.ExpireSnapshot.main(ExpireSnapshot.scala)
`

**Comment by eric666666** [comment]
As we can see from lock info, The main cause in org.apache.iceberg.spark.actions.BaseExpireSnapshotsSparkAction.doExecute(BaseExpireSnapshotsSparkAction.java:219) 
![image](https://user-images.githubusercontent.com/51162281/161371162-88d0a9f8-8c84-45de-b022-3692d3ece544.png)
we can align that DataSet's action operator(#collectAsList) cannot do the last task.

**Comment by eric666666** [comment]
> Spark version: 3.2.1 or 3.1.2 Spark SQL statements: `CALL hive_prod.system.expire_snapshots(table => 'test.iceberg_test_col_data_with_dt_02', older_than => timestamp '2022-05-18 19:02:00.595',retain_last => 1); ` `CALL hive_prod.system.remove_orphan_files(table => 'test.iceberg_test_col_data_with_dt_02', dry_run => true);` Execute statement may occour spark task blocking(last task of collectAsList operator)

The iceberg version is 0.13.1

**Comment by RussellSpitzer** [comment]
What is the issue here? This is the expected behavior of the default action. We want to block until we have the results of which files to remove, then we remove them.

There are proposal to execute deletes in the executors themselves, but we would still block until all the work is complete.

**Comment by peterxiong13** [comment]
我也碰到此问题了，快照过期和删除孤儿文件都卡在最后一步，10个小时都没反应

**Comment by peterxiong13** [comment]
用table方式对表做快照过期则不会卡住，但很多文件都没有删除掉，包括数据文件和元数据文件。

**Comment by peterxiong13** [comment]
用table方式对快照过期则不会卡住，但很多文件都没有被删除掉，导致小文件一大堆

**Comment by peterxiong13** [comment]
用表方式对快照过期则不会卡住，但很多文件都没有被删除掉，导致小文件一大堆

**Comment by peterxiong13** [comment]
The blocking occurred in a kerberos-certified Hadoop environment, possibly due to other processes in the program that acquired files on the Hadoop file system, but failed to access the HDFS file system without passing the Kerberos authentication information from the main program in the past, resulting in a failure to obtain a list of files. Is there a solution? Whether there is an option to specify a list of HDFS file systems in the main program so that Kerberos authentication information can be used correctly to access the HDFS file system, which may compromise some of the parallel processing performance, but is better than being blocked and unable to run this function. Thank you!
@RussellSpitzer @eric666666

**Comment by eric666666** [comment]
> 我也这个问题了，过渡和删除孤儿文件都在最后一个，10小时反应

我解决掉了这个问题，用local模式跑会阻塞，spark on yarn是正常的
如果本地模式要解决阻塞有两种方式，1种改spark源码，1种改iceberg的源码，改spark源码的方式比较通用解决这个阻塞问题
改一下org.apache.spark.scheduler.TaskSetManager#addPendingTask这个方法，把spark task任务优先级这段注释一下就可以了
![image](https://user-images.githubusercontent.com/51162281/173723217-bdeca447-7c39-4a5a-a92e-4a6499b06b37.png)

**Comment by peterxiong13** [comment]
@eric666666
改了下确实可以，local模式不会阻塞了。另外有个问题请教下，我在合并小文件时，对于分区表老是有些等值删除文件没有清理掉，导致小文件很多。如果对表做一次比较重的数据文件重写（比如设定的条件能覆盖到所有分区的所有数据文件）有可能就清理掉了，但这么做代价太高了。难道也是local模式下才会这样？on yarn或on k8s能正常清理掉？

**Comment by eric666666** [comment]
> @eric666666 改了下确实可以，local模式不会阻塞了。另外有个问题请教下，我在合并小文件时，对于分区表老是有些等值删除文件没有清理掉，导致小文件很多。如果对表做一次比较重的数据文件重写（比如设定的条件能覆盖到所有分区的所有数据文件）有可能就清理掉了，但这么做代价太高了。难道也是local模式下才会这样？on yarn或on k8s能正常清理掉？

我们可以加下好友交流下，eq-delete file和pos-delete file，重写后，过期快照不删除的问题，我一直再尝试修，目前还没有能解决

**Comment by peterxiong13** [comment]
> > @eric666666 改了下确实可以，local模式不会阻塞了。另外有个问题请教下，我在合并小文件时，对于分区表老是有些等值删除文件没有清理掉，导致小文件很多。如果对表做一次比较重的数据文件重写（比如设定的条件能覆盖到所有分区的所有数据文件）有可能就清理掉了，但这么做代价太高了。难道也是local模式下才会这样？on yarn或on k8s能正常清理掉？
> 
> 我们可以加下好友交流下，eq-delete file和pos-delete file，重写后，过期快照不删除的问题，我一直再尝试修，目前还没有能解决

好啊，qq：4612815
我想我已经找到原因了，qq上详聊

**Comment by peterxiong13** [comment]
> > > @eric666666 改了下确实可以，local模式不会阻塞了。另外有个问题请教下，我在合并小文件时，对于分区表老是有些等值删除文件没有清理掉，导致小文件很多。如果对表做一次比较重的数据文件重写（比如设定的条件能覆盖到所有分区的所有数据文件）有可能就清理掉了，但这么做代价太高了。难道也是local模式下才会这样？on yarn或on k8s能正常清理掉？
> > 
> > 
> > 我们可以加下好友交流下，eq-delete file和pos-delete file，重写后，过期快照不删除的问题，我一直再尝试修，目前还没有能解决
> 
> 好啊，qq：4612815 我想我已经找到原因了，qq上详聊

我测了下 [https://github.com/apache/iceberg/pull/3990](url)，貌似能解决分区表快照过期，删除文件未清理掉的问题

**Comment by eric666666** [comment]
> 

我加你啦，之前我排查了好像和delete file的manifest在重写和快照过期的时候，sequence number小于最新分区data file的sequence number也没有去删除，这个PR我也看了，有个大佬说这个PR改动比较大，你这边patch后有持续跑一段时间吗？
