### ISSUE TITLE
Spark overwrite issue when partition changes

### ISSUE THREAD

**Issue by itaise** [apache/iceberg#4510]
Hi, 
we are writing to iceberg using spark, and when renaming the partition field name, we are getting a validation error: 
```
org.apache.iceberg.exceptions.ValidationException: Cannot find source column for partition field: 1000: some_date: void(1)
```

It seems like iceberg is referring to the existing table partition field name, which is irrelevant anymore - as there is a new partition field, and the write mode is "overwrite". 

Can you please assist? 
Thank you!

Here is a minimal reproducible example:

1. create the original table with partition field "some_date":
```
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType ,StructField, StringType
dataDF = [('1991-04-01',)]
schema = StructType([
        StructField('some_date',StringType(), True)])

spark = SparkSession.builder.master('local[1]').appName('example') \
    .getOrCreate()

df = spark.createDataFrame(data = dataDF, schema = schema)
spark.sql(f"use iprod")  # catalog
spark.sql(f"CREATE SCHEMA IF NOT EXISTS iprod.test_schema")
df.write.mode("overwrite").format("parquet").partitionBy('some_date').saveAsTable("iprod.test_schema.example")
## added this based on advice in this issue
spark.sql(f"""ALTER TABLE iprod.test_schema.example SET TBLPROPERTIES ('format-version' = '2')""")
```

2. Try to overwrite the table with the same code, but the partition field renamed to ```some_date_2```
```
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType ,StructField, StringType
dataDF = [('1991-04-01',)]
schema = StructType([
        StructField('some_date_2',StringType(), True)])

spark = SparkSession.builder.master('local[1]').appName('example') \
    .getOrCreate()

df = spark.createDataFrame(data = dataDF, schema = schema)
spark.sql(f"use iprod")  # catalog
spark.sql(f"CREATE SCHEMA IF NOT EXISTS iprod.test_schema")

df.write.mode("overwrite").format("parquet").partitionBy('some_date_2').saveAsTable("iprod.test_schema.example")
```

Full trace: 
```
: org.apache.iceberg.exceptions.ValidationException: Cannot find source column for partition field: 1000: some_date: void(1)
	at org.apache.iceberg.exceptions.ValidationException.check(ValidationException.java:46)
	at org.apache.iceberg.PartitionSpec.checkCompatibility(PartitionSpec.java:511)
	at org.apache.iceberg.PartitionSpec$Builder.build(PartitionSpec.java:503)
	at org.apache.iceberg.TableMetadata.reassignPartitionIds(TableMetadata.java:768)
	at org.apache.iceberg.TableMetadata.buildReplacement(TableMetadata.java:790)
	at org.apache.iceberg.BaseMetastoreCatalog$BaseMetastoreCatalogTableBuilder.newReplaceTableTransaction(BaseMetastoreCatalog.java:256)
	at org.apache.iceberg.BaseMetastoreCatalog$BaseMetastoreCatalogTableBuilder.createOrReplaceTransaction(BaseMetastoreCatalog.java:244)
	at org.apache.iceberg.CachingCatalog$CachingTableBuilder.createOrReplaceTransaction(CachingCatalog.java:244)
	at org.apache.iceberg.spark.SparkCatalog.stageCreateOrReplace(SparkCatalog.java:190)
	at org.apache.spark.sql.execution.datasources.v2.AtomicReplaceTableAsSelectExec.run(WriteToDataSourceV2Exec.scala:197)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:40)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:40)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.doExecute(V2CommandExec.scala:55)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:194)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:190)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:134)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:133)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:232)
	at org.apache.spark.sql.execution.SQLExecution$.executeQuery$1(SQLExecution.scala:110)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:135)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:232)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:135)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:253)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:134)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:68)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:686)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:619)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by rajarshisarkar** [comment]
I can't find the table being altered to introduce the new partition field `some_date_2`. Am I missing something?

**Comment by itaise** [comment]
@rajarshisarkar  the first part is creating the first version, and the second part tries to overwrite it. 
Maybe you should change the catalog name to your catalog?

**Comment by itaise** [comment]
This happens also when using the DataFrameWriter V2, for example: 

`df.writeTo("iprod.test_schema.example").partitionedBy(partition_column).createOrReplace()`

and also with: 
`df.writeTo("iprod.test_schema.example").partitionedBy(partition_column).replace()`

**Comment by romibuzi** [comment]
Hi @itaise, 
you need to change the partition specs of your table before writing the data with the new partition:

```
spark.sql("ALTER TABLE my_iceberg_catalog.db.vaccinations DROP PARTITION FIELD some_date")
spark.sql("ALTER TABLE my_iceberg_catalog.db.vaccinations ADD PARTITION FIELD some_date_2")
```

This will not drop `some_date` from your data but only metadata

**Comment by rdblue** [comment]
I think the problem is that this is a v1 table. In v1, the `some_date` partition field is not actually dropped, it is replaced with a null / void transform. So you still need the original column ref. If you update your table to v2 and then try the write it should work.

**Comment by itaise** [comment]
@romibuzi  thanks i will try it out and update!

@rdblue thanks a lot! What do you mean by updating the table to V2?

**Comment by rdblue** [comment]
@itaise, by default tables use the v1 format, which didn't use unique IDs for partition fields in metadata. That was fixed in v2. So when you upgrade a table to v2, (set the `table-format` property to 2) your changes will actually remove the unnecessary field that references the old column, rather than keeping a placeholder partition field around for it.

**Comment by itaise** [comment]
thank you so much @rdblue!

**Comment by itaise** [comment]
Hi :) any update regarding that?
