### ISSUE TITLE
Read metadata table failed due to illegal character

### ISSUE THREAD

**Issue by ConeyLiu** [apache/iceberg#4576]
Reproduce code:
```scala
case class Data(id: Long)
case class Item(id: Long, data: Data)

spark.sql("create table local.db.test_table(id long, data struct<id: long>) using iceberg partitioned by (identity(id))").show()
spark.range(10).map(i => Item(i, Data(i))).writeTo("local.db.test_table").append()
spark.sql("alter table local.db.test_table add partition field identity(data.id)").show()
spark.range(10).map(i => Item(i, Data(i))).writeTo("local.db.test_table").append()
spark.sql("select * from local.db.test_table.files").show()
```

Exception stack:
```
Caused by: org.apache.iceberg.shaded.org.apache.avro.SchemaParseException: Illegal character in: data.id_r1001
  at org.apache.iceberg.shaded.org.apache.avro.Schema.validateName(Schema.java:1561)
  at org.apache.iceberg.shaded.org.apache.avro.Schema.access$400(Schema.java:87)
  at org.apache.iceberg.shaded.org.apache.avro.Schema$Field.<init>(Schema.java:541)
  at org.apache.iceberg.shaded.org.apache.avro.Schema$Field.<init>(Schema.java:580)
  at org.apache.iceberg.avro.BuildAvroProjection.record(BuildAvroProjection.java:111)
  at org.apache.iceberg.avro.BuildAvroProjection.record(BuildAvroProjection.java:43)
  at org.apache.iceberg.avro.AvroCustomOrderSchemaVisitor.visit(AvroCustomOrderSchemaVisitor.java:51)
  at org.apache.iceberg.avro.AvroCustomOrderSchemaVisitor$VisitFuture.get(AvroCustomOrderSchemaVisitor.java:109)
  at org.apache.iceberg.avro.BuildAvroProjection.field(BuildAvroProjection.java:140)
  at org.apache.iceberg.avro.BuildAvroProjection.field(BuildAvroProjection.java:43)
  at org.apache.iceberg.avro.AvroCustomOrderSchemaVisitor$VisitFieldFuture.get(AvroCustomOrderSchemaVisitor.java:124)
  at org.apache.iceberg.relocated.com.google.common.collect.Iterators$6.transform(Iterators.java:826)
  at org.apache.iceberg.relocated.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52)
  at org.apache.iceberg.relocated.com.google.common.collect.Iterators.addAll(Iterators.java:367)
  at org.apache.iceberg.relocated.com.google.common.collect.Lists.newArrayList(Lists.java:147)
  at org.apache.iceberg.relocated.com.google.common.collect.Lists.newArrayList(Lists.java:133)
  at org.apache.iceberg.avro.BuildAvroProjection.record(BuildAvroProjection.java:68)
  at org.apache.iceberg.avro.BuildAvroProjection.record(BuildAvroProjection.java:43)
  at org.apache.iceberg.avro.AvroCustomOrderSchemaVisitor.visit(AvroCustomOrderSchemaVisitor.java:51)
  at org.apache.iceberg.avro.AvroCustomOrderSchemaVisitor$VisitFuture.get(AvroCustomOrderSchemaVisitor.java:109)
  at org.apache.iceberg.avro.BuildAvroProjection.field(BuildAvroProjection.java:140)
  at org.apache.iceberg.avro.BuildAvroProjection.field(BuildAvroProjection.java:43)
  at org.apache.iceberg.avro.AvroCustomOrderSchemaVisitor$VisitFieldFuture.get(AvroCustomOrderSchemaVisitor.java:124)
  at org.apache.iceberg.relocated.com.google.common.collect.Iterators$6.transform(Iterators.java:826)
  at org.apache.iceberg.relocated.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52)
  at org.apache.iceberg.relocated.com.google.common.collect.Iterators.addAll(Iterators.java:367)
  at org.apache.iceberg.relocated.com.google.common.collect.Lists.newArrayList(Lists.java:147)
  at org.apache.iceberg.relocated.com.google.common.collect.Lists.newArrayList(Lists.java:133)
  at org.apache.iceberg.avro.BuildAvroProjection.record(BuildAvroProjection.java:68)
  at org.apache.iceberg.avro.BuildAvroProjection.record(BuildAvroProjection.java:43)
  at org.apache.iceberg.avro.AvroCustomOrderSchemaVisitor.visit(AvroCustomOrderSchemaVisitor.java:51)
  at org.apache.iceberg.avro.AvroSchemaUtil.buildAvroProjection(AvroSchemaUtil.java:124)
  at org.apache.iceberg.avro.ProjectionDatumReader.setSchema(ProjectionDatumReader.java:68)
  at org.apache.iceberg.shaded.org.apache.avro.file.DataFileStream.initialize(DataFileStream.java:133)
  at org.apache.iceberg.shaded.org.apache.avro.file.DataFileReader.<init>(DataFileReader.java:130)
  at org.apache.iceberg.shaded.org.apache.avro.file.DataFileReader.<init>(DataFileReader.java:122)
  at org.apache.iceberg.shaded.org.apache.avro.file.DataFileReader.openReader(DataFileReader.java:66)
  at org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:100)
  at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:77)
  at org.apache.iceberg.io.CloseableIterable$4$1.<init>(CloseableIterable.java:99)
  at org.apache.iceberg.io.CloseableIterable$4.iterator(CloseableIterable.java:98)
  at org.apache.iceberg.io.CloseableIterable.lambda$filter$0(CloseableIterable.java:79)
  at org.apache.iceberg.io.CloseableIterable$2.iterator(CloseableIterable.java:73)
  at org.apache.iceberg.io.CloseableIterable$4$1.<init>(CloseableIterable.java:99)
  at org.apache.iceberg.io.CloseableIterable$4.iterator(CloseableIterable.java:98)
  at org.apache.iceberg.ManifestReader.iterator(ManifestReader.java:247)
  at org.apache.iceberg.io.CloseableIterable$4$1.<init>(CloseableIterable.java:99)
  at org.apache.iceberg.io.CloseableIterable$4.iterator(CloseableIterable.java:98)
  at org.apache.iceberg.io.CloseableIterable$4$1.<init>(CloseableIterable.java:99)
  at org.apache.iceberg.io.CloseableIterable$4.iterator(CloseableIterable.java:98)
  at org.apache.iceberg.io.CloseableIterable$4.iterator(CloseableIterable.java:90)
  at org.apache.iceberg.util.Filter.lambda$filter$0(Filter.java:35)
  at org.apache.iceberg.io.CloseableIterable$2.iterator(CloseableIterable.java:73)
  at org.apache.iceberg.spark.source.RowDataReader.open(RowDataReader.java:77)
  at org.apache.iceberg.spark.source.BaseDataReader.next(BaseDataReader.java:103)
  at org.apache.spark.sql.execution.datasources.v2.PartitionIterator.hasNext(DataSourceRDD.scala:79)
  at org.apache.spark.sql.execution.datasources.v2.MetricsIterator.hasNext(DataSourceRDD.scala:112)
  at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
  at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
  at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
  at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
  at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
  at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
  at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
  at org.apache.spark.scheduler.Task.run(Task.scala:131)
  at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
  at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
```

**Comment by ConeyLiu** [comment]
@rdblue @nastra Would you mind taking a look at this issue? This is true should be a bug.
