### ISSUE TITLE
missing SetWriteDistributionAndOrdering class for spark sql plan 

### ISSUE THREAD

**Issue by scaladevspark** [apache/iceberg#4628]
Trying to run Scala Spark Structured Streaming app with iceberg via Spark operator on Spark 3.1.1.

Spark submit fails on Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/plans/logical/SetWriteDistributionAndOrdering

I am unable to find a jar to include to get this class. There seems to be a context with this name, but not the class itself https://iceberg.apache.org/javadoc/0.12.1/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsParser.SetWriteDistributionAndOrderingContext.html

my dependencies
  "org.apache.spark" %% "spark-core" % "3.1.1" % Provided,
  "org.apache.spark" %% "spark-sql" % "3.1.1" % Provided,
  "org.apache.hadoop" % "hadoop-aws" % "3.2.0",
  "org.apache.hadoop" % "hadoop-common" % "3.2.0",
  "org.apache.hadoop" % "hadoop-client" % "3.2.0",
  "org.apache.hadoop" % "hadoop-mapreduce-client-core" % "3.2.0",
  "org.apache.hadoop" % "hadoop-minikdc" % "3.2.0",
  "com.amazonaws" % "aws-java-sdk-bundle" % "1.11.375",
  "com.typesafe" % "config" % "1.3.1"
  , "joda-time" % "joda-time" % "2.9.9"
  , "org.apache.iceberg" % "iceberg-spark3-extensions" % "0.13.1"
  , "org.apache.iceberg" % "iceberg-common" % "0.13.1"
  , "org.apache.iceberg" % "iceberg-spark3-runtime" % "0.13.1"

Thanks for any help! Full stacktrace:
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/plans/logical/SetWriteDistributionAndOrdering
	at org.apache.spark.sql.execution.datasources.v2.ExtendedDataSourceV2Strategy.apply(ExtendedDataSourceV2Strategy.scala:77)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$1(QueryPlanner.scala:63)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:489)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
	at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:67)
	at org.apache.spark.sql.execution.QueryExecution$.createSparkPlan(QueryExecution.scala:391)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$sparkPlan$1(QueryExecution.scala:104)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:143)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:143)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:104)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:97)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executedPlan$1(QueryExecution.scala:117)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:143)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:143)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:117)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:110)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$simpleString$2(QueryExecution.scala:161)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$explainString(QueryExecution.scala:206)
	at org.apache.spark.sql.execution.QueryExecution.explainString(QueryExecution.scala:175)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:98)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3685)

**Comment by RussellSpitzer** [comment]
You should only be including the Spark-Runtime jar and in particular this version icberg-spark-runtime-3.1

https://mvnrepository.com/artifact/org.apache.iceberg/iceberg-spark-runtime-3.1_2.12/0.13.1

Then if you are launching your application via Spark-Submit or something like that you must include this jar as a runtime dependency either with --packages or by bundling it into your application code.

https://iceberg.apache.org/docs/latest/getting-started/#using-iceberg-in-spark-3

**Comment by scaladevspark** [comment]
@RussellSpitzer thanks, used only   , "org.apache.iceberg" % "iceberg-spark-runtime-3.1_2.12" % "0.13.1", but getting another error bellow - are there any other jars required?

java.lang.ClassNotFoundException: Failed to find data source: iceberg. Please find packages at http://spark.apache.org/third-party-projects.html
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:689)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:743)
	at org.apache.spark.sql.DataFrameWriter.lookupV2Provider(DataFrameWriter.scala:993)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:615)
	at pipelines.EbmL1ToL2$.processAndOutputSessionInfo$1(EbmL1ToL2.scala:148)
	at pipelines.EbmL1ToL2$.$anonfun$apply$1(EbmL1ToL2.scala:89)
	at pipelines.EbmL1ToL2$.$anonfun$apply$1$adapted(EbmL1ToL2.scala:89)
	at org.apache.spark.sql.execution.streaming.sources.ForeachBatchSink.addBatch(ForeachBatchSink.scala:35)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runBatch$16(MicroBatchExecution.scala:586)

**Comment by RussellSpitzer** [comment]
Did you include --packages at runtime? Or include the jar in a your application with a FatJar pluigin?

**Comment by RussellSpitzer** [comment]
If you are running scala, try printing this out
```scala
println(classOf[org.apache.iceberg.spark.source.IcebergSource])
```
It that throws an error your jar is not shaded correctly

**Comment by RussellSpitzer** [comment]
What exactly are you trying to run?

**Comment by RussellSpitzer** [comment]
In general you should be using the DSV2 Catalog api which wouldn't use "format" at all, but the class I asked you to print out has the DataSourceRegister which when loaded onto the classpath registers "iceberg" as a format. Now whether that supports structured streaming is a different question. I know we only have limited support for that in the Table api itself and i'm not sure it was added to the IcebergSource

**Comment by scaladevspark** [comment]
this page seems to be using it with Structured Streaming https://iceberg.apache.org/docs/latest/spark-structured-streaming/

btw thanks a lot for your help and the time you are taking w me.

**Comment by RussellSpitzer** [comment]
Yes I know we have the support there, i'm just not sure if the Source flow was compatible, but you aren't using it in an actual streaming context. That code above should trigger the standard write pathway. You can pass in the full classpath for the `IcebergSource` there, although if that works it means something has gone pretty wrong in the classloader :/

**Comment by scaladevspark** [comment]
could the catalog settings be an issue then? Have this currently:
"spark.sql.catalogImplementation": "hive"
    "spark.sql.catalog.iceberg_catalog.type": "hive"
    "spark.sql.catalog.iceberg_catalog.uri": "thrift://hms-service.default.svc.cluster.local:9083"
    "spark.sql.catalog.iceberg_catalog": "org.apache.iceberg.spark.SparkCatalog"
    "spark.sql.catalog.iceberg_catalog.warehouse": "s3a://spark/warehouse/"
    "spark.sql.extensions": "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
    "spark.hadoop.hive.metastore.uris": "thrift://hms-service.default.svc.cluster.local:9083"

**Comment by scaladevspark** [comment]
ok, switching to writeTo helped, this now runs:
      allocDfToWrite
        .orderBy(TIME_KEY_COL)
        .coalesce(1)
        .writeTo(s"iceberg_catalog.$db.$table")
        .partitionedBy(col(TIME_KEY_COL))
        .createOrReplace()

However, the api changed a lot. It does not seem possible anymore to directly write to a partitioned table with an external location and create it if not exists. So basically:
df
.write
.mode(SaveMode.Append)
.format(writeFormat)
.partitionBy(TIME_KEY_COL)
.option("path", path)
.saveAsTable(s"$db.$table")

is not possible with the new API anymore, as you need to create the table first and then write to it? Or is there a way?

Thanks a lot again for all your help.

**Comment by scaladevspark** [comment]
thanks, this approach works, you just have to move the partitionedBy to the create part, otherwise you cannot continue with append. So this works:

` val df = dfToWrite
    .orderBy(TIME_KEY_COL)
    .coalesce(1)
     .writeTo(s"iceberg_catalog.$db.$table")
try {
  df
    .partitionedBy(col(TIME_KEY_COL))
    .tableProperty("location", "somewhere").create()
} catchTableExists {
  df.append()
}`

thanks again for helping me.

**Comment by scaladevspark** [comment]
btw @RussellSpitzer do you happen to know if you can bucket via the writeTo api? It seems possible with iceberg via spark sql CREATE TABLE prod.db.sample (
    id bigint,
    data string,
    category string,
    ts timestamp)
USING iceberg
PARTITIONED BY (bucket(16, id), days(ts), category)

but have not found any way to do it via writeTo. Thanks again!
