### ISSUE TITLE
A problem occurs when updating/deleting with spark-sql after loading data with iceberg Java api

### ISSUE THREAD

**Issue by bbasosuho** [apache/iceberg#4639]
A problem occurs when updating/deleting with spark-sql after loading data with iceberg Java api

**Iceberg Version : iceberg-spark-runtime-3.1_2.12-0.13.1.jar
Spark Version : 3.1.2**

First, load 3 rows of data with iceberg Java api
![image](https://user-images.githubusercontent.com/20290980/165416371-f17c0f97-6529-4523-8452-25cdcf5ddd36.png)

And load 1 rows of data with iceberg Java api ( id = 4 ) 
![image](https://user-images.githubusercontent.com/20290980/165416365-3ae32cb1-417b-434e-8b5c-336dc9458dcf.png)

Delete 1 row data with iceberg Java api ( id = 2 )
![image](https://user-images.githubusercontent.com/20290980/165416210-cc7ffec4-9f41-4e06-ad87-17a59bef3dad.png)

**And Retrieve data from spark-sql
**Rows with IDs 1, 3, 4 are retrieved. (  Normal ) . id = 2 is deleted**** 

**[Issue]**

**case1 )  - Normal** 
UPDATE iceberg.testdb.testtb SET memo='new-value' WHERE id = **1** ; 

And Retrieve data from spark-sql
Rows with IDs 1, 3, 4 are retrieved. **(  Normal )** 
![image](https://user-images.githubusercontent.com/20290980/165433081-74e36afc-ccbb-4bec-b021-4a75d6fdfef4.png)

- If the Id column is a numeric type, the same problem occurs as in case2.

**case2 ) - Abnormal**
UPDATE iceberg.testdb.testtb SET memo='new' WHERE id = **'1'** ; 

And Retrieve data from spark-sql
**Rows with IDs 1, 2, 3, 4 are retrieved. (  Abnormal ). id=2 is back** 
![image](https://user-images.githubusercontent.com/20290980/165416770-58d5ce73-0e8b-431e-a3d9-4d3ac9315811.png)

**case3 ) - Normal** 
DELETE FROM iceberg.testdb.testtb WHERE id = **1** ; 
And Retrieve data from spark-sql
Rows with IDs  3, 4 are retrieved. **(  Normal )** 
![image](https://user-images.githubusercontent.com/20290980/165433598-9d11d487-2ebd-40ef-83d5-a24fe8d3fe9d.png)

If the Id column is a numeric type, the same problem occurs as in case4.

**case4) - Abnormal**
DELETE FROM iceberg.testdb.testtb WHERE id = **'1'** ; 
And Retrieve data from spark-sql
Rows with IDs  2, 3, 4 are retrieved. **(  Abnormal). id=2 is back** 
![image](https://user-images.githubusercontent.com/20290980/165433624-1761c701-3401-48e5-a3a9-be7f22de7f0f.png)

**Is there any problem when using the iceberg API and spark-sql crossover?
It seems that the existing delete file information is lost when performing Update/Delete statements in Spark-sql.**

Iceberg API is used as below.
(Writer is implemented by inheriting BaseEqualityDeltaWriter.)

...
WriteResult files = writer.complete();
RowDelta newRowDelta = icebergTable.newRowDelta();
Arrays.stream(files.dataFiles()).forEach(newRowDelta::addRows);
Arrays.stream(files.deleteFiles()).forEach(newRowDelta::addDeletes);
....

**Comment by ajantha-bhat** [comment]
It is looking like Java API has used the row-level-delete (merge-on-read deletes from V2 spec) by creating a new delete file.

But in spark 3.1, from SQL, only copy-on-write update/delete is supported. So, it doesn't understand the delete files.

**workaround:**
1. So, In java API we need to use copy-on-write (v1 spec) delete for spark 3.1 to understand it.
2. Or, use spark 3.2 which can understand the merge-on-read deletes by configuring a table property.

**Comment by bbasosuho** [comment]
**Thank you for answer. But the same thing happens.**

I have added content to my original post.
**In the case of a character column, it is strange that it is normally processed without ''. ( case1 , case3 )**

I upgraded to version 3.2
Iceberg Version : iceberg-spark-runtime-3.2_2.12-0.13.1.jar
Spark Version : 3.2.1

**I have added table properties. 'write.merge.mode'='merge-on-read'
But the same thing happens.
It does not recognize the delete file and is created again.**





**I searched for settings and found more similar settings and tried to put them in.**
write.update.mode=merge-on-read
write.delete.mode=merge-on-read

And I tried again.
It was confirmed that Delect Action(case3 and case4) were handled normally.

But, I saw an error message saying that Update Action( case1 and case2) are not supported.
![image](https://user-images.githubusercontent.com/20290980/165436765-cd3529ab-c34b-4cee-bb17-e0db7cf452f5.png)

**Comment by ajantha-bhat** [comment]
> But, I saw an error message saying that Update Action( case1 and case2) are not supported.

**Could you provide a complete call stack for this error message ?**

And if we are doing update operation with merge on read, we need to set **write.update.mode**.
Similarly for delete operation, **write.delete.mode** and for merge sql we need to use **write.merge.mode**. AS you are using only delete and update, last one is no need to set.

**Comment by kbendick** [comment]
Seems @ajantha-bhat is helping, but reminder that you likely need to call `.refresh()` on the table (or use `REFRESH TABLE` syntax.

The Spark writer will refresh a table automatically after a write, but if you’re mixing the Java API you likely need to call refresh yourself (or disable the caching catalog entirely).

**Comment by kbendick** [comment]
Also +1 to the complete stack trace beyond “delta updates are not supported”. That will tell likely tell us the issue.

**Comment by bbasosuho** [comment]
Write additional content.

**1. TBLPROPERTIES**

....
TBLPROPERTIES (
  'metadata_location'='.......', 
  'previous_metadata_location'='.......', 
  'table_type'='ICEBERG', 
  'transient_lastDdlTime'='1651038945', 
  'uuid'='a9ecab95-4dff-49ff-8860-663262c6aa14', 
  'write.delete.mode'='merge-on-read', 
  'write.format.default'='parquet', 
  'write.merge.mode'='merge-on-read', 
  'write.update.mode'='merge-on-read')
.....

**After adding the 'write.delete.mode'='merge-on-read' setting, the problem in case4 does not occur.**


**2. Spark-sql Cache**

The cache option is set to false .
spark.sql.catalog.iceberg.cache-enabled=false

**3. Correct TBLPROPERTIES**

Which of the options below should be set to only use simple update/delete?
------------------------
write.delete.mode
write.merge.mode
write.update.mode
------------------------

**4. Stack trace**

Error: org.apache.hive.service.cli.HiveSQLException: Error running query: org.apache.spark.sql.AnalysisException: Delta updates are currently not supported
	at org.apache.spark.sql.hive.thriftserver.HiveThriftServerErrors$.runningQueryError(HiveThriftServerErrors.scala:43)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:325)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.$anonfun$run$2(SparkExecuteStatementOperation.scala:230)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.hive.thriftserver.SparkOperation.withLocalProperties(SparkOperation.scala:79)
	at org.apache.spark.sql.hive.thriftserver.SparkOperation.withLocalProperties$(SparkOperation.scala:63)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.withLocalProperties(SparkExecuteStatementOperation.scala:43)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:230)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:225)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2.run(SparkExecuteStatementOperation.scala:239)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.sql.AnalysisException: Delta updates are currently not supported
	at org.apache.spark.sql.catalyst.analysis.RewriteUpdateTable$$anonfun$apply$1.applyOrElse(RewriteUpdateTable.scala:62)
	at org.apache.spark.sql.catalyst.analysis.RewriteUpdateTable$$anonfun$apply$1.applyOrElse(RewriteUpdateTable.scala:53)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$2(AnalysisHelper.scala:170)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$1(AnalysisHelper.scala:170)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:323)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning(AnalysisHelper.scala:168)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning$(AnalysisHelper.scala:164)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning(AnalysisHelper.scala:99)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning$(AnalysisHelper.scala:96)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperators(AnalysisHelper.scala:76)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperators$(AnalysisHelper.scala:75)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperators(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.analysis.RewriteUpdateTable$.apply(RewriteUpdateTable.scala:53)
	at org.apache.spark.sql.catalyst.analysis.RewriteUpdateTable$.apply(RewriteUpdateTable.scala:51)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:211)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:208)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:200)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:200)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:222)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$execute$1(Analyzer.scala:218)
	at org.apache.spark.sql.catalyst.analysis.AnalysisContext$.withNewAnalysisContext(Analyzer.scala:167)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:218)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:182)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:179)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:88)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:179)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:203)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:330)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:202)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:88)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:196)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:196)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:88)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:86)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:78)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:98)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:651)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:291)
	... 16 more (state=,code=0)

**Comment by bbasosuho** [comment]
@ajantha-bhat 
 So, In java API we need to use copy-on-write (v1 spec) delete for spark 3.1 to understand it.
=> **Where is the v1 spec java API example? I can't find it, so I'm asking.**

**Comment by ajantha-bhat** [comment]
> So, In java API we need to use copy-on-write (v1 spec) delete for spark 3.1 to understand it.
=> Where is the v1 spec java API example? I can't find it, so I'm asking.

I too couldn't find it. I expected it to be there. I think it is manual scan with filter and append new file and delete old file operation. I am only familiar with SQL. 

Let's wait for @aokolnychyi view point on this issue and callstack.
