### ISSUE TITLE
flink1.14.4+iceberg0.14.0 java.lang.NoClassDefFoundError: org/apache/iceberg/shaded/org/apache/parquet/hadoop/ParquetInputFormat

### ISSUE THREAD

**Issue by chenJz1012** [apache/iceberg#4884]
flink 1.14.4
iceberg 0.14.0

flink-sql on yarn-session commands like this:

./bin/yarn-session.sh -s 2 -jm 1024 -tm 2048 -nm flink-sql-client -d

./bin/sql-client.sh embedded -j ./jars/iceberg-flink-runtime-1.14-0.14.0.jar -s flink-sql-client

```sql
CREATE CATALOG hadoop_catalog WITH (
  'type'='iceberg',
  'catalog-type'='hadoop',
  'warehouse'='hdfs://xxx/iceberg/category',
  'property-version'='1'
);
use CATALOG hadoop_catalog;

CREATE DATABASE iceberg_db;

USE iceberg_db;

CREATE TABLE t_iceberg_sample (
    id BIGINT COMMENT 'unique id',
    data STRING
)WITH (
  'type'='iceberg',
  'catalog-type'='hadoop',
  'warehouse'='hdfs://xxx/iceberg/iceberg_db/t_iceberg_sample',
  'property-version'='1'
);

insert into t_iceberg_sample values(1,'a');

select * from t_iceberg_sample;
```

get error

```
java.lang.NoClassDefFoundError: org/apache/iceberg/shaded/org/apache/parquet/hadoop/ParquetInputFormat
	at org.apache.iceberg.shaded.org.apache.parquet.HadoopReadOptions$Builder.<init>(HadoopReadOptions.java:112)
	at org.apache.iceberg.shaded.org.apache.parquet.HadoopReadOptions$Builder.<init>(HadoopReadOptions.java:97)
	at org.apache.iceberg.shaded.org.apache.parquet.HadoopReadOptions.builder(HadoopReadOptions.java:85)
	at org.apache.iceberg.parquet.Parquet$ReadBuilder.build(Parquet.java:851)
	at org.apache.iceberg.flink.source.RowDataFileScanTaskReader.newParquetIterable(RowDataFileScanTaskReader.java:146)
	at org.apache.iceberg.flink.source.RowDataFileScanTaskReader.newIterable(RowDataFileScanTaskReader.java:97)
	at org.apache.iceberg.flink.source.RowDataFileScanTaskReader.open(RowDataFileScanTaskReader.java:76)
	at org.apache.iceberg.flink.source.DataIterator.openTaskIterator(DataIterator.java:136)
	at org.apache.iceberg.flink.source.DataIterator.updateCurrentIterator(DataIterator.java:126)
	at org.apache.iceberg.flink.source.DataIterator.hasNext(DataIterator.java:103)
	at org.apache.iceberg.flink.source.FlinkInputFormat.reachedEnd(FlinkInputFormat.java:111)
	at org.apache.flink.streaming.api.functions.source.InputFormatSourceFunction.run(InputFormatSourceFunction.java:89)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:323)
```

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/11772351/170695164-b8ef14bf-a18b-4b3d-ad53-d62842b49ee5.png">

help!!!

**Comment by chenJz1012** [comment]
first error
```
java.lang.NoClassDefFoundError: org/apache/hadoop/mapreduce/lib/input/FileInputFormat
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:71)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.iceberg.shaded.org.apache.parquet.HadoopReadOptions$Builder.<init>(HadoopReadOptions.java:112)
	at org.apache.iceberg.shaded.org.apache.parquet.HadoopReadOptions$Builder.<init>(HadoopReadOptions.java:97)
	at org.apache.iceberg.shaded.org.apache.parquet.HadoopReadOptions.builder(HadoopReadOptions.java:85)
	at org.apache.iceberg.parquet.Parquet$ReadBuilder.build(Parquet.java:851)
	at org.apache.iceberg.flink.source.RowDataFileScanTaskReader.newParquetIterable(RowDataFileScanTaskReader.java:146)
	at org.apache.iceberg.flink.source.RowDataFileScanTaskReader.newIterable(RowDataFileScanTaskReader.java:97)
	at org.apache.iceberg.flink.source.RowDataFileScanTaskReader.open(RowDataFileScanTaskReader.java:76)
	at org.apache.iceberg.flink.source.DataIterator.openTaskIterator(DataIterator.java:136)
	at org.apache.iceberg.flink.source.DataIterator.updateCurrentIterator(DataIterator.java:126)
	at org.apache.iceberg.flink.source.DataIterator.hasNext(DataIterator.java:103)
	at org.apache.iceberg.flink.source.FlinkInputFormat.reachedEnd(FlinkInputFormat.java:111)
	at org.apache.flink.streaming.api.functions.source.InputFormatSourceFunction.run(InputFormatSourceFunction.java:89)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:323)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.mapreduce.lib.input.FileInputFormat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:64)
	at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:65)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 27 more
```

**Comment by chenJz1012** [comment]
run sql-client with hadoop-mapreduce-client-core.jar solve the problem!
