### ISSUE TITLE
Flink import debezium cdc record(delete type) to iceberg(0.13.2+) got IndexOutOfBoundsException

### ISSUE THREAD

**Issue by eric666666** [apache/iceberg#5043]
When i use iceberg 0.13.1 or iceberg current master branch(until 06-04)  with flink 1.13+, write cdc record(specific delete type) to iceberg got IndexOutOfBoundsException.
There is a trace log 
_
2022-06-13 14:25:39
java.lang.IndexOutOfBoundsException: pos: 1140850704, length: 15639, index: 1140850688, offset: 0
	at org.apache.flink.core.memory.MemorySegment.get(MemorySegment.java:453)
	at org.apache.flink.table.data.binary.BinarySegmentUtils.getBytes(BinarySegmentUtils.java:292)
	at org.apache.flink.table.data.binary.BinaryStringData.toBytes(BinaryStringData.java:112)
	at org.apache.iceberg.flink.data.FlinkParquetWriters$StringDataWriter.write(FlinkParquetWriters.java:238)
	at org.apache.iceberg.flink.data.FlinkParquetWriters$StringDataWriter.write(FlinkParquetWriters.java:231)
	at org.apache.iceberg.parquet.ParquetValueWriters$StructWriter.write(ParquetValueWriters.java:562)
	at org.apache.iceberg.parquet.ParquetWriter.add(ParquetWriter.java:130)
	at org.apache.iceberg.deletes.EqualityDeleteWriter.delete(EqualityDeleteWriter.java:82)
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.write(BaseTaskWriter.java:357)
	at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.write(BaseTaskWriter.java:340)
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.write(BaseTaskWriter.java:254)
	at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.delete(BaseTaskWriter.java:166)
	at org.apache.iceberg.flink.sink.BaseDeltaTaskWriter.write(BaseDeltaTaskWriter.java:95)
	at org.apache.iceberg.flink.sink.BaseDeltaTaskWriter.write(BaseDeltaTaskWriter.java:41)
	at org.apache.iceberg.flink.sink.IcebergStreamWriter.processElement(IcebergStreamWriter.java:72)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:233)
	at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.processElement(AbstractStreamTaskNetworkInput.java:134)
	at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.emitNext(AbstractStreamTaskNetworkInput.java:105)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:519)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:203)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:804)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:753)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:948)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:741)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:563)
	at java.lang.Thread.run(Thread.java:748)
_

**Comment by kingwind94** [comment]
got same problem, have any fixs now?

**Comment by kingwind94** [comment]
I fixed it! You must have -D (delete rowkind) rowdata in your cdc datastream. Check your BaseDeltaTaskWriter, fix your write(RowData row)  method as below
`
      case DELETE:
        if (upsert) {
          writer.deleteKey(keyProjection.wrap(row));
        } else {
          writer.delete(row);
        }
        break;
`

**Comment by eric666666** [comment]
> 

I have solved this. Here is my code
`
            case DELETE:
                writer.deleteKey(keyProjection.wrap(row), schema);
                break;
`
`writer.delete(row);  ` is unnecessary because eq-delete file only record v2 table's key fields.

**Comment by zinking** [comment]
incorrect data type mapping between mysql and iceberg could also lead to this. for example tinyint -> boolean
