### ISSUE TITLE
TestS3OutputStream#testAbortAfterFailedPartUpload fails occassionally on CI

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#5387]
```
> Task :iceberg-aws:test FAILED

org.apache.iceberg.aws.s3.TestS3OutputStream > testAbortAfterFailedPartUpload FAILED
    java.lang.AssertionError: 
    Expecting throwable message:
      "java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/s3fileio-test-4474512894306655287/s3fileio-7517579648971065210.tmp"
    to contain:
      "mock uploadPart failure"
    but did not.

    Throwable that failed the check:

    java.util.concurrent.CompletionException: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/s3fileio-test-4474512894306655287/s3fileio-7517579648971065[210](https://github.com/apache/iceberg/runs/7575406305?check_suite_focus=true#step:6:211).tmp
    	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
    	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
    	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:750)
    Caused by: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/s3fileio-test-4474512894306655287/s3fileio-7517579648971065210.tmp
    	at software.amazon.awssdk.utils.FunctionalUtils.asRuntimeException(FunctionalUtils.java:180)
    	at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeSupplier$4(FunctionalUtils.java:110)
    	at software.amazon.awssdk.utils.FunctionalUtils.invokeSafely(FunctionalUtils.java:136)
    	at software.amazon.awssdk.core.sync.RequestBody.fromFile(RequestBody.java:100)
    	at software.amazon.awssdk.core.sync.RequestBody.fromFile(RequestBody.java:111)
    	at org.apache.iceberg.aws.s3.S3OutputStream.lambda$null$2(S3OutputStream.java:324)
    	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
    	... 3 more
    Caused by: java.nio.file.NoSuchFileException: /tmp/s3fileio-test-4474512894306655287/s3fileio-7517579648971065210.tmp
    	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
    	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
    	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
    	at java.nio.file.Files.readAttributes(Files.java:1737)
    	at java.nio.file.Files.size(Files.java:[233](https://github.com/apache/iceberg/runs/7575406305?check_suite_focus=true#step:6:234)2)
    	at software.amazon.awssdk.core.sync.RequestBody.lambda$fromFile$0(RequestBody.java:100)
    	at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeSupplier$4(FunctionalUtils.java:108)
    	... 8 more
        at org.apache.iceberg.aws.s3.TestS3OutputStream.testAbortAfterFailedPartUpload(TestS3OutputStream.java:137)
```

**Comment by nastra** [comment]
Looks like this test was modified with #5317. @abmo-x is this something you could potentially look at?

**Comment by singhpk234** [comment]
fixed via :
- https://github.com/apache/iceberg/pull/5366

cc @nastra

**Comment by nastra** [comment]
thanks for fixing this @singhpk234
