### ISSUE TITLE
Failed to start the Flink task (write iceberg)

### ISSUE THREAD

**Issue by 95liu** [apache/iceberg#5630]
### Please describe the bug 🐞

use iceberg-flink-runtime:jar:0.12.1 

`Caused by: java.lang.IllegalStateException: org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.SI
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:101)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3357)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3353)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:995)
        at org.apache.iceberg.SchemaParser.<clinit>(SchemaParser.java:272)
        ... 29 more
Caused by: java.lang.NoSuchMethodException: org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.SI.<init>(org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.Caffeine, org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.CacheLoader, boolean)
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.getDeclaredConstructor(Class.java:2178)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:96)
        ... 33 more`

**Comment by Fokko** [comment]
Hey @95liu, thanks for opening a ticket. Which version of Flink are you using? Please note that you're using a rather old version of Iceberg, I would recommend updating that as well 👍🏻

**Comment by msb1** [comment]
If you are using gradle and creating shadow jar; do not use minimize()... Was doing build with 
      shadowJar {
          minimize()
          zip64 true
      }
in build.gradle. Had identical error message to what is shown in first post above.

Changed to 
      shadowJar {
          zip64 true
      }
in build.gradle and error is gone. Appears that minimize() was removing shaded caffeine from fat jar.  Could probably have problem if using maven shaded plugin as well.
