### ISSUE TITLE
jmh benchmarks under org.apache.iceberg.spark.data.parquet package are failing

### ISSUE THREAD

**Issue by sumeetgajjar** [apache/iceberg#5634]
### Apache Iceberg version

0.14.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

The jmh benchmarks under `org.apache.iceberg.spark.data.parquet` package are failing due to `IllegalArgumentException`.

The `ParquetToSparkSchemaConverter` class in Spark3.3 expects `SQLConf.CASE_SENSITIVE` in the `Configuration`. 
However, the above config is not specified while instantiating the `ReadBuilder` and `WriteBuilder` thereby resulting in the following exception.

https://github.com/apache/spark/blob/branch-3.3/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetSchemaConverter.scala#L66

```java
java.lang.IllegalArgumentException: For input string: "null"
	at scala.collection.immutable.StringLike.parseBoolean(StringLike.scala:330)
	at scala.collection.immutable.StringLike.toBoolean(StringLike.scala:289)
	at scala.collection.immutable.StringLike.toBoolean$(StringLike.scala:289)
	at scala.collection.immutable.StringOps.toBoolean(StringOps.scala:33)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetToSparkSchemaConverter.<init>(ParquetSchemaConverter.scala:66)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetReadSupport.prepareForRead(ParquetReadSupport.scala:108)
	at org.apache.iceberg.parquet.ParquetReadSupport.prepareForRead(ParquetReadSupport.java:119)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.initialize(InternalParquetRecordReader.java:190)
	at org.apache.parquet.hadoop.ParquetReader.initReader(ParquetReader.java:166)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:135)
	at org.apache.iceberg.parquet.ParquetIterable$ParquetIterator.advance(ParquetIterable.java:80)
	at org.apache.iceberg.parquet.ParquetIterable$ParquetIterator.<init>(ParquetIterable.java:55)
	at org.apache.iceberg.parquet.ParquetIterable.iterator(ParquetIterable.java:41)
	at org.apache.iceberg.spark.data.parquet.SparkParquetReadersFlatDataBenchmark.readWithProjectionUsingSparkReader(SparkParquetReadersFlatDataBenchmark.java:219)
	at org.apache.iceberg.spark.data.parquet.jmh_generated.SparkParquetReadersFlatDataBenchmark_readWithProjectionUsingSparkReader_jmhTest.readWithProjectionUsingSparkReader_ss_jmhStub(SparkParquetReadersFlatDataBenchmark_readWithProjectionUsingSparkReader_jmhTest.java:416)
	at org.apache.iceberg.spark.data.parquet.jmh_generated.SparkParquetReadersFlatDataBenchmark_readWithProjectionUsingSparkReader_jmhTest.readWithProjectionUsingSparkReader_SingleShotTime(SparkParquetReadersFlatDataBenchmark_readWithProjectionUsingSparkReader_jmhTest.java:371)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

## Fix 
Add `spark.sql.caseSensitive=false` to `ReadBuilder` and `WriteBuilder` properties to avoid the exception.

**Comment by sumeetgajjar** [comment]
I'm working on the fix, will publish a PR soon.
