### ISSUE TITLE
Vectorized Read

### ISSUE THREAD

**Issue by asheeshgarg** [apache/iceberg#6003]
### Query engine

Java API

### Question

I am trying to create a API that need to return data using Apache Arrow. The data is stored as Iceberg table I want to filter the data using the Java api to avoid any  heavy compute job. I am able to load and run scan

val namespace = Namespace.of("Test")
catalog.listTables(namespace)
val tableIdentifier = TableIdentifier.of("Test", "Temp")
val table = catalog.loadTable(tableIdentifier)
val scan = table.newScan();
val filteredScan = scan.filter(Expressions.and(Expressions.equal("date", "20220810"),Expressions.equal("class", "test")))

 val resultsItr= filteredScan.planTasks().iterator()
  while(resultsItr.hasNext()){
    val task = resultsItr.next();
    val dataFile = task.files().iterator().next().file();
    println(dataFile);
  }
this gives me datafile

Now I want to read the parquet file using the 
val itr = new VectorizedTableScanIterable(filteredScan).iterator()
it always giving me nullpointer exception any idea what is wrong?

**Comment by asheeshgarg** [comment]
scala>  itr.next().createVectorSchemaRootFromVectors().getRowCount()
java.lang.NullPointerException
  at org.apache.iceberg.arrow.vectorized.GenericArrowVectorAccessorFactory.getPlainVectorAccessor(GenericArrowVectorAccessorFactory.java:199)
  at org.apache.iceberg.arrow.vectorized.GenericArrowVectorAccessorFactory.getVectorAccessor(GenericArrowVectorAccessorFactory.java:99)
  at org.apache.iceberg.arrow.vectorized.ArrowVectorAccessors.getVectorAccessor(ArrowVectorAccessors.java:52)
  at org.apache.iceberg.arrow.vectorized.ColumnVector.getVectorAccessor(ColumnVector.java:116)
  at org.apache.iceberg.arrow.vectorized.ColumnVector.<init>(ColumnVector.java:55)
  at org.apache.iceberg.arrow.vectorized.ArrowBatchReader.read(ArrowBatchReader.java:53)
  at org.apache.iceberg.arrow.vectorized.ArrowBatchReader.read(ArrowBatchReader.java:30)
  at org.apache.iceberg.parquet.VectorizedParquetReader$FileIterator.next(VectorizedParquetReader.java:136)
  at org.apache.iceberg.arrow.vectorized.ArrowReader$VectorizedCombinedScanIterator.next(ArrowReader.java:312)
  at org.apache.iceberg.arrow.vectorized.ArrowReader$VectorizedCombinedScanIterator.next(ArrowReader.java:198)
  ... 48 elided

**Comment by nastra** [comment]
@asheeshgarg any chance that you could reproduce that issue in the `ArrowReaderTest` maybe?

**Comment by nastra** [comment]
The spark runtime jar relocates the arrow-related classes to `org.apache.iceberg.shaded.org.apache.arrow`. You probably need to change `org.apache.arrow.vector.VectorSchemaRoot` to `org.apache.iceberg.shaded.org.apache.arrow.vector.VectorSchemaRoot` to pick up the shaded arrow classes

**Comment by asheeshgarg** [comment]
@nastra 
Thanks for the inputs one thing I see when I call getVector and do a println below code the columns are already deseralized in the print statement I was assuming the vector should be serialized format while reading. The underlying storage is parquet for these files 
    import util.control.Breaks._
      val columns = table.schema().columns()
      val itr = new VectorizedTableScanIterable(filteredScan, 2, false).iterator()
      while (itr.hasNext()) {
        breakable {
          val columnarBatch = itr.next();
          val schemaRoot = columnarBatch.createVectorSchemaRootFromVectors
          columns.forEach {
            case (column) => {
              println(column.name(), schemaRoot.getVector(column.name()))
            }
          }
        }
        break
      }

**Comment by nastra** [comment]
Can you be a bit more specifc when you say you're expecting them to be in the serialized format? It's difficult to tell what this prints. It might also help looking at the `ArrowReaderTest` to see how values are being extracted and such

**Comment by asheeshgarg** [comment]
@nastra 
I have removed the spark dependency and just added raw 
    <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-common</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-core</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-data</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-hive-metastore</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-parquet</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-arrow</artifactId>
      <version>1.0.0</version>
    </dependency>

    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-common</artifactId>
      <version>3.3.1</version>
    </dependency>


I am getting java.lang.NoClassDefFoundError: org/apache/thrift/TException Do we have list of depedency that we need to set in order to read the datafiles from iceberg in Pure Java API without any processing Engine.

**Comment by asheeshgarg** [comment]
@nastra 
  <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-common</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-core</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-data</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-arrow</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-hive-runtime</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-common</artifactId>
      <version>3.3.1</version>
    </dependency>

still getting 
java.lang.NoClassDefFoundError: org/apache/thrift/TException

**Comment by nastra** [comment]
NoClassDefFoundError generally means that this dependency existed at compilation time but doesn't exist at runtime, so you're missing the right dependency for that. 
Can you provide a full stack trace and all dependencies that you're using? Or is the above list complete?
Or do you have a direct link to this project where this issue happens?

**Comment by asheeshgarg** [comment]
@nastra is there a complete list of dependency that I can use for Pure Java API program
above list is complete I have added     <dependency>
      <groupId>org.apache.thrift</groupId>
      <artifactId>libthrift</artifactId>
      <version>0.16.0</version>
    </dependency>
Now getting java.lang.ClassNotFoundException: org.apache.hadoop.hive.metastore.api.UnknownDBException

**Comment by asheeshgarg** [comment]
After could of jar iteration able to read the catalog now for reading the data I am getting
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.apache.arrow.memory.ArrowBuf.setZero(ArrowBuf.java:1161)
        at org.apache.arrow.vector.BaseVariableWidthVector.initOffsetBuffer(BaseVariableWidthVector.java:242)
        at org.apache.arrow.vector.BaseVariableWidthVector.allocateBytes(BaseVariableWidthVector.java:467)
        at org.apache.arrow.vector.BaseVariableWidthVector.allocateNew(BaseVariableWidthVector.java:419)
        at org.apache.arrow.vector.BaseVariableWidthVector.allocateNewSafe(BaseVariableWidthVector.java:393)
        at org.apache.iceberg.arrow.vectorized.VectorizedArrowReader.allocateVectorBasedOnOriginalType(VectorizedArrowReader.java:247)
        at org.apache.iceberg.arrow.vectorized.VectorizedArrowReader.allocateFieldVector(VectorizedArrowReader.java:218)
        at org.apache.iceberg.arrow.vectorized.VectorizedArrowReader.read(VectorizedArrowReader.java:132)
        at org.apache.iceberg.arrow.vectorized.ArrowBatchReader.read(ArrowBatchReader.java:46)
        at org.apache.iceberg.arrow.vectorized.ArrowBatchReader.read(ArrowBatchReader.java:29)
        at org.apache.iceberg.parquet.VectorizedParquetReader$FileIterator.next(VectorizedParquetReader.java:149)
        at org.apache.iceberg.arrow.vectorized.ArrowReader$VectorizedCombinedScanIterator.next(ArrowReader.java:313)
        at org.apache.iceberg.arrow.vectorized.ArrowReader$VectorizedCombinedScanIterator.next(ArrowReader.java:189)
        at com.jpmorgan.Test.readContent(Test.java:62)
        at com.jpmorgan.Test.main(Test.java:72)
Caused by: java.lang.RuntimeException: Failed to initialize MemoryUtil.
        at org.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:136)
        ... 15 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @3fb875d8
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at org.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:84)

**Comment by nastra** [comment]
This problem is specific to Arrow itself when running with JDK9+, because Arrow's `MemoryUtil` requires access to the mentioned Java module. See https://arrow.apache.org/docs/java/install.html#java-compatibility / https://github.com/apache/arrow/commit/0310add1776054a67aacfb1a7bc0f569a19c7628#diff-23f1adfa46ef0fe69d6902b25cd417114b089d692d0c313d3a9a2c8ceff7cd3d on how to resolve this

**Comment by asheeshgarg** [comment]
@nastra thanks for the details able to read the data

**Comment by nastra** [comment]
@asheeshgarg great that it eventually worked out. Do you maybe want to share how you fixed it so that potentially other users that navigate to this issue know what to do?

**Comment by asheeshgarg** [comment]
Adding combination of Jars and Command
`    <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-common</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-core</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-data</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-arrow</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-hive-runtime</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.iceberg</groupId>
      <artifactId>iceberg-hive-metastore</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.hive</groupId>
      <artifactId>hive-metastore</artifactId>
      <version>3.1.3</version>
    </dependency>
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-common</artifactId>
      <version>3.3.1</version>
    </dependency>
    <dependency>
      <groupId>org.apache.hive</groupId>
      <artifactId>hive-common</artifactId>
      <version>2.3.9</version>
    </dependency>
    <dependency>
      <groupId>org.apache.hive</groupId>
      <artifactId>hive-storage-api</artifactId>
      <version>2.8.1</version>
    </dependency>
    <dependency>
      <groupId>org.apache.thrift</groupId>
      <artifactId>libthrift</artifactId>
      <version>0.13.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-mapreduce-client-core</artifactId>
      <version>3.3.4</version>
   </dependency>
   <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-aws</artifactId>
      <version>3.3.1</version>
    </dependency>
   <dependency>
      <groupId>org.apache.arrow</groupId>
      <artifactId>arrow-vector</artifactId>
      <version>9.0.0</version>
    </dependency>
   <dependency>
      <groupId>org.apache.arrow</groupId>
      <artifactId>arrow-memory-netty</artifactId>
      <version>9.0.0</version>
    </dependency>`

_JAVA_OPTIONS="--add-opens=java.base/java.nio=ALL-UNNAMED" mvn exec:java -Dexec.mainClass=com.icebergread.Test

With the above options and dependency able to query the data directly from iceberg Java API without any processing engine. With catalog store in hive and storage in s3.

**Comment by asheeshgarg** [comment]
@nastra added my configuration above
