### ISSUE TITLE
ORC:ORC VectorizedRowBatch NoSuchMethodError

### ISSUE THREAD

**Issue by V-yg** [apache/iceberg#6181]
### Apache Iceberg version

1.0.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

I run test org.apache.iceberg.spark.extensions.TestDelete#testExplain then throw exception:

java.lang.NoSuchMethodError: org.apache.orc.TypeDescription.createRowBatch(I)Lorg/apache/orc/storage/ql/exec/vector/VectorizedRowBatch;
	at org.apache.iceberg.orc.OrcFileAppender.<init>(OrcFileAppender.java:85)
	at org.apache.iceberg.orc.ORC$WriteBuilder.build(ORC.java:212)
	at org.apache.iceberg.orc.ORC$DataWriteBuilder.build(ORC.java:434)
	at org.apache.iceberg.data.BaseFileWriterFactory.newDataWriter(BaseFileWriterFactory.java:149)
	at org.apache.iceberg.io.RollingDataWriter.newWriter(RollingDataWriter.java:52)
	at org.apache.iceberg.io.RollingDataWriter.newWriter(RollingDataWriter.java:32)
	at org.apache.iceberg.io.RollingFileWriter.openCurrentWriter(RollingFileWriter.java:108)
	at org.apache.iceberg.io.RollingDataWriter.<init>(RollingDataWriter.java:47)
	at org.apache.iceberg.spark.source.SparkWrite$UnpartitionedDataWriter.<init>(SparkWrite.java:694)
	at org.apache.iceberg.spark.source.SparkWrite$UnpartitionedDataWriter.<init>(SparkWrite.java:684)
	at org.apache.iceberg.spark.source.SparkWrite$WriterFactory.createWriter(SparkWrite.java:660)
	at org.apache.iceberg.spark.source.SparkWrite$WriterFactory.createWriter(SparkWrite.java:641)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:430)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:381)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I use config is
file format: ORC
catalog type: Hive
catalog name:testhive

but  I use parquet format no problem #4065

**Comment by nastra** [comment]
@V-yg how are you running the test and did you do any local modifications to it? Since `TestDelete` is an abstract class, are you running `TestCopyOnWriteDelete` or `TestMergeOnReadDelete`? Also is this with Spark 3.3?

The last [CI run](https://github.com/apache/iceberg/actions/workflows/spark-ci.yml?query=branch%3Aapache-iceberg-1.0.0) indicates that the test was passing, so I'm curious what has changed that would cause the test to fail that we don't see on CI.

**Comment by nastra** [comment]
This works for me locally and latest [CI on master](https://github.com/apache/iceberg/actions/workflows/spark-ci.yml?query=branch%3Amaster) also doesn't show any issues. @Fokko could you please double-check if those tests fail for you locally?

**Comment by V-yg** [comment]
The problem has been solved. It's my local environment. It's fine now @nastra

**Comment by jackieo168** [comment]
> The problem has been solved. It's my local environment. It's fine now @nastra

Hi @V-yg, may I ask what you did to resolve the issue?
