### ISSUE TITLE
Broadcast Join Failure

### ISSUE THREAD

**Issue by asheeshgarg** [apache/iceberg#621]
I am trying to do a join for the two dataframe size of the dataframes are roughly 30MB and 40MB for  30 days.

I am able to load the raw parquet and able to perform join.
But as soon as I do the same join using the same spark cluster with iceberg format I am getting 
```
Exception in thread "main" org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:226)
	at org.apache.spark.sql.execution.exchange.BroadcastExchangeExec.doExecuteBroadcast(BroadcastExchangeExec.scala:146)
	at org.apache.spark.sql.execution.InputAdapter.doExecuteBroadcast(WholeStageCodegenExec.scala:387)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeBroadcast$1.apply(SparkPlan.scala:144)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeBroadcast$1.apply(SparkPlan.scala:140)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.executeBroadcast(SparkPlan.scala:140)
	at org.apache.spark.sql.execution.joins.BroadcastHashJoinExec.prepareBroadcast(BroadcastHashJoinExec.scala:117)
	at org.apache.spark.sql.execution.joins.BroadcastHashJoinExec.codegenInner(BroadcastHashJoinExec.scala:211)
	at org.apache.spark.sql.execution.joins.BroadcastHashJoinExec.doConsume(BroadcastHashJoinExec.scala:101)
	at org.apache.spark.sql.execution.CodegenSupport$class.constructDoConsumeFunction(WholeStageCodegenExec.scala:216)
	at org.apache.spark.sql.execution.CodegenSupport$class.consume(WholeStageCodegenExec.scala:187)
	at org.apache.spark.sql.execution.ProjectExec.consume(basicPhysicalOperators.scala:35)
	at org.apache.spark.sql.execution.ProjectExec.doConsume(basicPhysicalOperators.scala:65)
	at org.apache.spark.sql.execution.CodegenSupport$class.consume(WholeStageCodegenExec.scala:189)
	at org.apache.spark.sql.execution.FilterExec.consume(basicPhysicalOperators.scala:85)
	at org.apache.spark.sql.execution.FilterExec.doConsume(basicPhysicalOperators.scala:206)
	at org.apache.spark.sql.execution.CodegenSupport$class.consume(WholeStageCodegenExec.scala:189)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2ScanExec.consume(DataSourceV2ScanExec.scala:37)
	at org.apache.spark.sql.execution.ColumnarBatchScan$class.produceRows(ColumnarBatchScan.scala:172)
	at org.apache.spark.sql.execution.ColumnarBatchScan$class.doProduce(ColumnarBatchScan.scala:85)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2ScanExec.doProduce(DataSourceV2ScanExec.scala:37)
	at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:90)
	at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:85)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.CodegenSupport$class.produce(WholeStageCodegenExec.scala:85)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2ScanExec.produce(DataSourceV2ScanExec.scala:37)
	at org.apache.spark.sql.execution.FilterExec.doProduce(basicPhysicalOperators.scala:125)
	at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:90)
	at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:85)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.CodegenSupport$class.produce(WholeStageCodegenExec.scala:85)
	at org.apache.spark.sql.execution.FilterExec.produce(basicPhysicalOperators.scala:85)
	at org.apache.spark.sql.execution.ProjectExec.doProduce(basicPhysicalOperators.scala:45)
	at org.apache.spark.sql.execution.CodegenSupport$$anonfun$produce$1.apply(WholeStageCodegenExec.scala:90)
```

**Comment by aokolnychyi** [comment]
@asheeshgarg, could you provide more details on how you created Iceberg tables and what are your table configs? A small snippet to reproduce the issue without business logic would be extremely helpful.

**Comment by asheeshgarg** [comment]
def writeData(dataFrame: DataFrame, path: String, format: String, mode: SaveMode): Unit = {
  val tables = new HadoopTables(spark.sparkContext.hadoopConfiguration)
  val schema = SparkSchemaUtil.convert(dataFrame.schema)
  val partitionSpec = PartitionSpec.builderFor(SparkSchemaUtil.convert(dataFrame.schema)).build()
  tables.create(schema, partitionSpec, path)
  dataFrame
    .write
    .format(format)
    .mode(mode)
    .partitionBy("DATE")
    .save(path)
}
val icebergTableLoc = s"${storeLocation}/iceberg/eqty/reference"
writeData(refDf, deltaLakeTableLoc, "iceberg", SaveMode.Append)

val icebergTableLoc = s"${storeLocation}/iceberg/eqty/pricing"
writeData(pricingDf, icebergTableLoc, "iceberg", SaveMode.Append)

Above method is used to generate the data which 30 days of the reference and pricing data.
Data loaded is pariting by date so I see roughly equally sized data in the reference and pricing store in the parquet file created in iceberg.

Read operation is performed using 
  spark.read.format("iceberg").load("iceberg/eqty/reference").join(spark.read.format("iceberg").load("iceberg/eqty/pricing"),Seq("ID_BB_GLOBAL","DATE")).count()

As soon as you do this you see the error I mentioned in the original request.
If you repartition data to more partition it worked.

As mentioned it worked directly with raw Parquet and I also tried the similar join using Apache delta it worked. So size of the data is really fine. 
As we don't want to arbitrarily reparation the data.

**Comment by asheeshgarg** [comment]
Ran the spark with debug logging and I have following observations

19/11/15 15:59:36 INFO Executor: Starting executor ID driver on host localhost
19/11/15 15:59:36 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 45811.
19/11/15 15:59:36 INFO NettyBlockTransferService: Server created on 100.80.47.20:45811
19/11/15 15:59:36 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
19/11/15 15:59:36 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 100.80.47.20, 45811, None)
19/11/15 15:59:36 INFO BlockManagerMasterEndpoint: Registering block manager 100.80.47.20:45811 with 34.0 GB RAM, BlockManagerId(driver, 100.80.47.20, 45811, None)
19/11/15 15:59:36 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 100.80.47.20, 45811, None)
19/11/15 15:59:36 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 100.80.47.20, 45811, None)
19/11/15 15:59:37 INFO SharedState: loading hive config file: file:/hadoop/conf/hive-site.xml
19/11/15 15:59:37 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/job/spark-warehouse').
19/11/15 15:59:37 INFO SharedState: Warehouse path is 'file:/job/spark-warehouse'.
19/11/15 15:59:37 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
19/11/15 15:59:42 INFO TableScan: Scanning table hdfs:///user/datalake/iceberg/eqty/reference snapshot 5286228287138102009 created at 2019-11-05 21:40:03.510 with filter true
19/11/15 15:59:42 INFO TableScan: Scanning table hdfs:///user/datalake/iceberg/eqty/pricing snapshot 9199449611237852387 created at 2019-11-05 22:14:58.716 with filter true
19/11/15 15:59:43 INFO DataSourceV2Strategy: 

19/11/15 15:59:46 INFO CodeGenerator: Code generated in 12.349638 ms
19/11/15 15:59:46 INFO ZlibFactory: Successfully loaded & initialized native-zlib library
19/11/15 15:59:46 INFO CodecPool: Got brand-new decompressor [.gz]
19/11/15 15:59:47 INFO MemoryStore: Block taskresult_0 stored as bytes in memory (estimated size 7.8 MB, free 34.0 GB)
19/11/15 15:59:47 INFO BlockManagerInfo: Added taskresult_0 in memory on 100.80.47.20:45811 (size: 7.8 MB, free: 34.0 GB)
19/11/15 15:59:47 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 8178722 bytes result sent via BlockManager)
19/11/15 15:59:47 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1, localhost, executor driver, partition 1, PROCESS_LOCAL, 138170 bytes)
19/11/15 15:59:47 INFO Executor: Running task 1.0 in stage 0.0 (TID 1)
19/11/15 15:59:48 INFO TransportClientFactory: Successfully created connection to /100.80.47.20:45811 after 59 ms (0 ms spent in bootstraps)
19/11/15 15:59:48 ERROR TransportResponseHandler: Still have 1 requests outstanding when connection from /100.80.47.20:45811 is closed
19/11/15 15:59:48 ERROR OneForOneBlockFetcher: Failed while starting block fetches
java.io.IOException: Connection from /100.80.47.20:45811 closed
	at org.apache.spark.network.client.TransportResponseHandler.channelInactive(TransportResponseHandler.java:146)
	at org.apache.spark.network.server.TransportChannelHandler.channelInactive(TransportChannelHandler.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)

**The executor dies immediately with the block fetch is called. The TableScan seems to be returning table label information 
19/11/15 15:59:42 INFO TableScan: Scanning table hdfs:///user/datalake/iceberg/eqty/reference snapshot 5286228287138102009 created at 2019-11-05 21:40:03.510 with filter true
19/11/15 15:59:42 INFO TableScan: Scanning table hdfs:///user/datalake/iceberg/eqty/pricing snapshot 9199449611237852387 created at 2019-11-05 22:14:58.716 with filter true

Does it include how many parquet files it has? It immediately fails make me think the code generated by the sql executor has some issues. If needed I can add the logs for sql generated by spark.**

**Comment by asheeshgarg** [comment]
Following is the code generated from spark
DEBUG CodeGenerator: 
/* 001 */ public Object generate(Object[] references) {
/* 002 */   return new GeneratedIteratorForCodegenStage1(references);
/* 003 */ }
/* 004 */
/* 005 */ // codegenStageId=1
/* 006 */ final class GeneratedIteratorForCodegenStage1 extends org.apache.spark.sql.execution.BufferedRowIterator {
/* 007 */   private Object[] references;
/* 008 */   private scala.collection.Iterator[] inputs;
/* 009 */   private org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter[] filter_mutableStateArray_0 = new org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter[2];
/* 010 */   private scala.collection.Iterator[] datasourcev2scan_mutableStateArray_0 = new scala.collection.Iterator[1];
/* 011 */
/* 012 */   public GeneratedIteratorForCodegenStage1(Object[] references) {
/* 013 */     this.references = references;
/* 014 */   }
/* 015 */
/* 016 */   public void init(int index, scala.collection.Iterator[] inputs) {
/* 017 */     partitionIndex = index;
/* 018 */     this.inputs = inputs;
/* 019 */     datasourcev2scan_mutableStateArray_0[0] = inputs[0];
/* 020 */     filter_mutableStateArray_0[0] = new org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter(2, 32);
/* 021 */     filter_mutableStateArray_0[1] = new org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter(2, 32);
/* 022 */
/* 023 */   }
/* 024 */
/* 025 */   protected void processNext() throws java.io.IOException {
/* 026 */     while (datasourcev2scan_mutableStateArray_0[0].hasNext()) {
/* 027 */       InternalRow datasourcev2scan_row_0 = (InternalRow) datasourcev2scan_mutableStateArray_0[0].next();
/* 028 */       ((org.apache.spark.sql.execution.metric.SQLMetric) references[0] /* numOutputRows */).add(1);
/* 029 */       do {
/* 030 */         boolean datasourcev2scan_isNull_1 = datasourcev2scan_row_0.isNullAt(1);
/* 031 */         UTF8String datasourcev2scan_value_1 = datasourcev2scan_isNull_1 ?
/* 032 */         null : (datasourcev2scan_row_0.getUTF8String(1));
/* 033 */
/* 034 */         if (!(!datasourcev2scan_isNull_1)) continue;
/* 035 */
/* 036 */         ((org.apache.spark.sql.execution.metric.SQLMetric) references[1] /* numOutputRows */).add(1);
/* 037 */
/* 038 */         int datasourcev2scan_value_0 = datasourcev2scan_row_0.getInt(0);
/* 039 */         filter_mutableStateArray_0[1].reset();
/* 040 */
/* 041 */         filter_mutableStateArray_0[1].write(0, datasourcev2scan_value_0);
/* 042 */
/* 043 */         if (false) {
/* 044 */           filter_mutableStateArray_0[1].setNullAt(1);
/* 045 */         } else {
/* 046 */           filter_mutableStateArray_0[1].write(1, datasourcev2scan_value_1);
/* 047 */         }
/* 048 */         append((filter_mutableStateArray_0[1].getRow()));
/* 049 */
/* 050 */       } while(false);
/* 051 */       if (shouldStop()) return;
/* 052 */     }
/* 053 */   }
/* 054 */
/* 055 */ }

**Comment by asheeshgarg** [comment]
Also if I disable spark.sql.autoBroadcastJoinThreshold=-1 it works fine as well

**Comment by rdblue** [comment]
Looks like the actual cause is missing from the originally reported stack trace. The later trace with the block fetch failure might be the problem, but it's hard to tell what's going on there.
