### ISSUE TITLE
 Couldn't initialize a SAX driver to create an XMLReader

### ISSUE THREAD

**Issue by y-bowen** [apache/iceberg#6393]
### Query engine

Flink 1.15.2
Iceberg 1.1.0
Hadoop 2.7.2
Openjdk 11
I use HadoopFileIO s3a.

### Question

when i create iceberg v2 table. i got 
`Caused by: com.amazonaws.SdkClientException: Couldn't initialize a SAX driver to create an XMLReader
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.<init>(XmlResponsesSaxParser.java:133)
	at com.amazonaws.services.s3.model.transform.Unmarshallers$ListObjectsV2Unmarshaller.unmarshall(Unmarshallers.java:134)
	at com.amazonaws.services.s3.model.transform.Unmarshallers$ListObjectsV2Unmarshaller.unmarshall(Unmarshallers.java:124)
	at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:62)
	at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:31)
	at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:69)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1734)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleSuccessResponse(AmazonHttpClient.java:1454)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1369)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5259)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5206)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5200)
	at com.amazonaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:963)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$listObjects$5(S3AFileSystem.java:1334)
	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:322)
	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:285)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.listObjects(S3AFileSystem.java:1327)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:2311)
	... 101 more
Caused by: org.xml.sax.SAXNotSupportedException: SAX feature 'http://xml.org/sax/features/external-general-entities' not supported.
	at oracle.xml.parser.v2.NonValidatingParser.setFeature(NonValidatingParser.java:2351)
	at oracle.xml.parser.v2.SAXParser.setFeature(SAXParser.java:287)
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.disableExternalResourceFetching(XmlResponsesSaxParser.java:254)
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.<init>(XmlResponsesSaxParser.java:131)
	... 126 more`

**Comment by amogh-jahagirdar** [comment]
Sorry for the delay, missed this issue somehow. 

@y-bowen, could you provide the details on which AWS SDK version you are using? Note AWS SDK v2 is required for Iceberg. Checkout https://iceberg.apache.org/docs/latest/aws/#flink for an example for Flink.

Looking at the stack trace, I see there are a few issues already opened in AWS SDK, for example 

https://github.com/aws/aws-sdk-java/issues/2184, https://github.com/aws/aws-sdk-java/issues/1622, https://github.com/aws/aws-sdk-java/issues/1588

All of these issues point to having conflicting XMLReaders on the same class path, so please do check that there is a single XMLReader on your class path.
