### ISSUE TITLE
Vectorized Read Issue

### ISSUE THREAD

**Issue by asheeshgarg** [apache/iceberg#6415]
### Apache Iceberg version

0.14.0

### Query engine

None

### Please describe the bug 🐞

@nastra 

I am using Vectorized read from Java API and able to load the data from Vectorized root from iceberg batches to arrow.

Some of the records I am not able to build in Arrow cache as the schema return are different

 VectorizedTableScanIterable iter = new VectorizedTableScanIterable(filteredScan, batchSize, false);) {
for (ColumnarBatch batch : iter) {
  VectorSchemaRoot batchRoot = batch.createVectorSchemaRootFromVectors();

batchRoot schema are returned different for a given table. 

Do we type cast the results to adhere to actual schema of Iceberg when we read the base files returned by the read?

**Comment by nastra** [comment]
@asheeshgarg thanks for the ticket. For anyone looking at this ticket it would be quite helpful if you could add additional details about the issue you're seeing (what is expected, what differs in the schema exactly, how does the schema look like, ...)

**Comment by asheeshgarg** [comment]
@nastra filled in the missing bits
So this schema that is define in Iceberg entity_status is UTF8
Schema<entity_id: Utf8, entity_name: Utf8, entity_status: Utf8, 
This is what is been generated by batchRoot Schema
Schema<entity_id: Utf8, entity_name: Utf8, entity_status: Int(32, true), 


There are other fields also coming as Int which are UTF8 it throws a error like below because of type mismatch. SPark Able to read the data fine

java.lang.IndexOutOfBoundsException: index: 0, length: 8388608 (expected: range(0, 15888))
        at org.apache.arrow.memory.ArrowBuf.checkIndex(ArrowBuf.java:701)
        at org.apache.arrow.memory.ArrowBuf.setBytes(ArrowBuf.java:955)
        at org.apache.arrow.vector.BaseFixedWidthVector.reAlloc(BaseFixedWidthVector.java:451)
        at org.apache.arrow.vector.BaseFixedWidthVector.setValueCount(BaseFixedWidthVector.java:732)
        at org.apache.arrow.vector.VectorSchemaRoot.setRowCount(VectorSchemaRoot.java:240)
        at org.apache.arrow.vector.VectorLoader.load(VectorLoader.java:86)

Expected behavior batches should return the data of schema type defined in iceberg/hive.

**Comment by nastra** [comment]
See https://github.com/apache/iceberg/blob/c07f2aabc0a1d02f068ecf1514d2479c0fbdd3b0/arrow/src/test/java/org/apache/iceberg/arrow/vectorized/ArrowReaderTest.java#L149-L210 for some background why the issue currently exists. 
I have opened https://github.com/apache/iceberg/pull/3024 a while ago, but it didn't get attention

**Comment by nastra** [comment]
@rdblue thoughts on getting the above issue fixed?

**Comment by nazq** [comment]
Happy to create a PR @rdblue , just want to make sure we're on the right track here

**Comment by nazq** [comment]
Excellent. Thanks for the pointer @nastra

**Comment by asheeshgarg** [comment]
@nastra thanks for the references seems to be the case. @rdblue this seems to be really the case with lot of datasets. Do we have any time line when https://github.com/apache/iceberg/pull/3024 will be merged.

**Comment by rdblue** [comment]
I agree with the analysis that the problem is that we are returning dictionary-encoded Arrow vectors. Maybe we're not doing that the right way. I'll take a look at #3024.

**Comment by asheeshgarg** [comment]
@nastra @nazq  so in the mean time we have merged the pull request and bundle a local jar with the #3024 
It work fine for most of the columns but we are getting 
java.lang.IndexOutOfBoundsException: index: 32749, length: 32 (expected: range(0, 32768))
        at org.apache.arrow.memory.ArrowBuf.checkIndex(ArrowBuf.java:701)
        at org.apache.arrow.memory.ArrowBuf.setBytes(ArrowBuf.java:765)
        at org.apache.arrow.vector.BaseVariableWidthVector.setBytes(BaseVariableWidthVector.java:1244)
        at org.apache.arrow.vector.BaseVariableWidthVector.set(BaseVariableWidthVector.java:1025)
        at org.apache.iceberg.arrow.DictEncodedArrowConverter.lambda$toVarCharVector$5(DictEncodedArrowConverter.java:153)
        at org.apache.iceberg.arrow.DictEncodedArrowConverter.initVector(DictEncodedArrowConverter.java:201)
        at org.apache.iceberg.arrow.DictEncodedArrowConverter.toVarCharVector(DictEncodedArrowConverter.java:150)
        at org.apache.iceberg.arrow.DictEncodedArrowConverter.toArrowVector(DictEncodedArrowConverter.java:47)
        at org.apache.iceberg.arrow.vectorized.ColumnVector.getArrowVector(ColumnVector.java:66)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at org.apache.iceberg.arrow.vectorized.ColumnarBatch.createVectorSchemaRootFromVectors(ColumnarBatch.java:58)
        at com.ReadIcebergTableTestV3.main(ReadIcebergTableTestV3.java:54)
when reading columns where distinct count is large for the dictionary. Will try to create a test case to replicate it.

@rdblue Arrow also added dataset where we can read the tabular data Arrow Vectors I was able to read the parquet file directly not sure if we like to add read support using the Arrow Dataset.

**Comment by marun224** [comment]
@nastra, @mayursrivastava, @amogh-jahagirdar, @rdblue 

It seems above error is occurring because of  issue at line no 173 in the class DictEncodedArrowConverter. I have commented on the PR #3024.

Can somebody take a look it and advise?

**Comment by nastra** [comment]
Just to circle back, this issue was fixed by https://github.com/apache/iceberg/pull/3024.
