### ISSUE TITLE
Wrong class, java.lang.Long, for object: 19367

### ISSUE THREAD

**Issue by dmgcodevil** [apache/iceberg#6587]
### Apache Iceberg version

Data is stored using Flink: `0.12.1`
Data is compacted using Spark `3.0.3`, Iceberg: `0.12.1`

### Query engine

None

### Please describe the bug 🐞

I have a timestamp field of type: `timestamptz`. I'm trying to compact files using Spark action but getting the following error:

```
Wrong class, java.lang.Long, for object: 19367
```

My schema:

```
{
      "id" : 10,
      "name" : "tick_timestamp",
      "required" : false,
      "type" : "timestamptz"
    }, {
      "id" : 11,
      "name" : "transaction_timestamp",
      "required" : false,
      "type" : "timestamptz"
    }
```

Partition specs:

```json
"partition-spec" : [ {
    "name" : "transaction_timestamp_day",
    "transform" : "void",
    "source-id" : 11,
    "field-id" : 1000
  }, {
    "name" : "id059_bucket",
    "transform" : "bucket[20]",
    "source-id" : 5,
    "field-id" : 1001
  }, {
    "name" : "tick_timestamp_day",
    "transform" : "day",
    "source-id" : 10,
    "field-id" : 1002
  } ],
  "default-spec-id" : 2,
  "partition-specs" : [ {
    "spec-id" : 0,
    "fields" : [ {
      "name" : "transaction_timestamp_day",
      "transform" : "day",
      "source-id" : 11,
      "field-id" : 1000
    }, {
      "name" : "id059_bucket",
      "transform" : "bucket[20]",
      "source-id" : 5,
      "field-id" : 1001
    } ]
  }, {
    "spec-id" : 1,
    "fields" : [ {
      "name" : "tick_timestamp_day",
      "transform" : "day",
      "source-id" : 11,
      "field-id" : 1000
    }, {
      "name" : "id059_bucket",
      "transform" : "bucket[20]",
      "source-id" : 5,
      "field-id" : 1001
    } ]
  }, {
    "spec-id" : 2,
    "fields" : [ {
      "name" : "transaction_timestamp_day",
      "transform" : "void",
      "source-id" : 11,
      "field-id" : 1000
    }, {
      "name" : "id059_bucket",
      "transform" : "bucket[20]",
      "source-id" : 5,
      "field-id" : 1001
    }, {
      "name" : "tick_timestamp_day",
      "transform" : "day",
      "source-id" : 10,
      "field-id" : 1002
    } ]
  } ]
```

Test:

```java
val task = table.newScan().filter().planFiles().asScala.head
Comparators.forType(table.spec.partitionType()).compare(task.file().partition(), task.file().partition())
```

Error:

```
Wrong class, java.lang.Long, for object: 19367
```

The one thing I noticed is that `task.file().partition()` returns the following type: 

```
{"type":"record","name":"PartitionData","namespace":"org.apache.iceberg","fields":[{"name":"tick_timestamp_day","type":["null",{"type":"int","logicalType":"date"}],"default":null,"field-id":1000},{"name":"id059_bucket","type":["null","int"],"default":null,"field-id":1001}]}
```

`tick_timestamp_day` has type `date` (int) instead of `timestamptz`. Any thoughts ?

**Comment by RussellSpitzer** [comment]
Could you post the full trace from the Spark code?

**Comment by dmgcodevil** [comment]
@RussellSpitzer 

```
java.lang.IllegalArgumentException: Wrong class, java.lang.Long, for object: 19371
	at org.apache.iceberg.PartitionData.get(PartitionData.java:120)
	at org.apache.iceberg.types.Comparators$StructLikeComparator.compare(Comparators.java:122)
	at org.apache.iceberg.types.Comparators$StructLikeComparator.compare(Comparators.java:102)
	at org.apache.iceberg.util.StructLikeWrapper.equals(StructLikeWrapper.java:76)
	at java.util.HashMap.getNode(HashMap.java:573)
	at java.util.HashMap.get(HashMap.java:558)
	at org.apache.iceberg.relocated.com.google.common.collect.AbstractMapBasedMultimap.put(AbstractMapBasedMultimap.java:185)
	at org.apache.iceberg.relocated.com.google.common.collect.AbstractListMultimap.put(AbstractListMultimap.java:115)
	at org.apache.iceberg.actions.BaseRewriteDataFilesAction.lambda$groupTasksByPartition$4(BaseRewriteDataFilesAction.java:253)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at org.apache.iceberg.actions.BaseRewriteDataFilesAction.groupTasksByPartition(BaseRewriteDataFilesAction.java:251)
	at org.apache.iceberg.actions.BaseRewriteDataFilesAction.execute(BaseRewriteDataFilesAction.java:212)
	at com.bloomberg.bval.datalake.iceberg.merger.DataFilesMerger$.execute(DataFilesMerger.scala:93)
	at com.bloomberg.bval.datalake.iceberg.merger.DataFilesMerger$.execute(DataFilesMerger.scala:64)
	at com.bloomberg.bval.datalake.iceberg.merger.DataFilesMerger$.main(DataFilesMerger.scala:33)
	at com.bloomberg.bval.datalake.iceberg.merger.DataFilesMerger.main(DataFilesMerger.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
```

**Comment by dmgcodevil** [comment]
@RussellSpitzer , I just realized that compaction (Flink, Spark) stopped working after I updated my partition spec:

https://bbgithub.dev.bloomberg.com/gist/rpliashkou/40f63ae0c2db036cfb2840185d916296

`iceberg7566440805144146453\test\test\data\timestamp1_day=null\timestamp2_day=2023-01-03\` is this a valid folder structure? 

Probably related to [this](https://github.com/apache/iceberg/issues/2375)

**Comment by dmgcodevil** [comment]
Partition spec before update:

```
    "fields" : [ {
      "name" : "timestamp1_day",
      "transform" : "day",
      "source-id" : 2,
      "field-id" : 1000
    } ]
```

After:

```
    "fields" : [ {
      "name" : "timestamp1_day",
      "transform" : "void",
      "source-id" : 2,
      "field-id" : 1000
    }, {
      "name" : "timestamp2_day",
      "transform" : "day",
      "source-id" : 3,
      "field-id" : 1001
    } ]
```

**Comment by RussellSpitzer** [comment]
That is valid, it basically represents a transform that previously existed but was dropped. This is how V1 tables have to represent table structure. This could be one of several bugs though that were fixed in 0.13 that handles partition evolution

**Comment by dmgcodevil** [comment]
@RussellSpitzer I forgot that we also partition by another field using `bucket` transform. original spec:

```json
  "partition-spec" : [ {
    "name" : "timestamp1_day",
    "transform" : "day",
    "source-id" : 2,
    "field-id" : 1000
  }, {
    "name" : "id_bucket",
    "transform" : "bucket[5]",
    "source-id" : 1,
    "field-id" : 1001
  } ],
```

Folder structure:

```
/timestamp1_day=2023-01-01/id_bucket=1/
```


After update:

Spec:


```json
  "partition-spec" : [ {
    "name" : "timestamp1_day",
    "transform" : "void",
    "source-id" : 2,
    "field-id" : 1000
  }, {
    "name" : "id_bucket",
    "transform" : "bucket[5]",
    "source-id" : 1,
    "field-id" : 1001
  }, {
    "name" : "timestamp2_day",
    "transform" : "day",
    "source-id" : 3,
    "field-id" : 1002
  } ]
```

Folder structure:

```
/timestamp1_day=null/id_bucket=1/timestamp2_day=2023-01-03/
```

The folder structure is different from the original, i.e.: `id_bucket`  comes before `timestamp2_day`. Is it expected?

I couldn't reproduce `Wrong class, java.lang.Long, for object: 19367`, I'll keep trying.

I updated my [example](https://bbgithub.dev.bloomberg.com/gist/rpliashkou/40f63ae0c2db036cfb2840185d916296)

**Comment by dmgcodevil** [comment]
cc/ @RussellSpitzer

**Comment by RussellSpitzer** [comment]
Have you tried with more recent version? The directory structure really doesn't matter and I'm pretty sure you are just hitting an older version bug.

**Comment by dmgcodevil** [comment]
Latest available version of `iceberg-flink-runtime` is `0.12.1`

**Comment by dmgcodevil** [comment]
I tried `0.13.2` and got the following error:

```
Required table missing : "DBS" in Catalog "" Schema "". DataNucleus requires this table to perform its persistence operations. Either your MetaData is incorrect, or you need to enable "datanucleus.schema.autoCreateTables"
org.datanucleus.store.rdbms.exceptions.MissingTableException: Required table missing : "DBS" in Catalog "" Schema "". DataNucleus requires this table to perform its persistence operations. Either your MetaData is incorrect, or you need to enable "datanucleus.schema.autoCreateTables"
	at org.datanucleus.store.rdbms.table.AbstractTable.exists(AbstractTable.java:606)
	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.performTablesValidation(RDBMSStoreManager.java:3385)
	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.run(RDBMSStoreManager.java:2896)
	at org.datanucleus.store.rdbms.AbstractSchemaTransaction.execute(AbstractSchemaTransaction.java:119)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.manageClasses(RDBMSStoreManager.java:1627)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.getDatastoreClass(RDBMSStoreManager.java:672)
	at org.datanucleus.store.rdbms.query.RDBMSQueryUtils.getStatementForCandidates(RDBMSQueryUtils.java:425)
	at org.datanucleus.store.rdbms.query.JDOQLQuery.compileQueryFull(JDOQLQuery.java:865)
	at org.datanucleus.store.rdbms.query.JDOQLQuery.compileInternal(JDOQLQuery.java:347)
	at org.datanucleus.store.query.Query.executeQuery(Query.java:1816)
	at org.datanucleus.store.query.Query.executeWithArray(Query.java:1744)
	at org.datanucleus.store.query.Query.execute(Query.java:1726)
	at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:374)
	at org.datanucleus.api.jdo.JDOQuery.execute(JDOQuery.java:216)
	at org.apache.hadoop.hive.metastore.MetaStoreDirectSql.ensureDbInit(MetaStoreDirectSql.java:181
```

Is it because we are running the old version of hive metastore ?

**Comment by RussellSpitzer** [comment]
That is because released are Flink version specific after that point, latest release is now is 1.1

https://repo.maven.apache.org/maven2/org/apache/iceberg/iceberg-flink-runtime-1.16/1.1.0/

Not that the Flink version should matter here. It's the latest Spark version you should be using since that's what is compacting

**Comment by RussellSpitzer** [comment]
Your metastore error says that no external hive metastore was configured and it's falling back to local file based hive mode. That's probably not what you want

**Comment by dmgcodevil** [comment]
Yes, we are using a standalone metastore backed by MySql database. I tested `0.13.2` w/o metastore and it's working. I believe we need to update the metastore db schema

**Comment by dmgcodevil** [comment]
Delete orphan files action is also affected after the schema change:

```
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Void
	at org.apache.iceberg.transforms.VoidTransform.toHumanString(VoidTransform.java:27)
	at org.apache.iceberg.ManifestsTable.partitionSummariesToRows(ManifestsTable.java:131)
	at org.apache.iceberg.ManifestsTable.manifestFileToRow(ManifestsTable.java:115)
	at org.apache.iceberg.AllManifestsTable$ManifestListReadTask.lambda$rows$0(AllManifestsTable.java:194)
	at org.apache.iceberg.io.CloseableIterable$4$1.next(CloseableIterable.java:113)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:462)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:465)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by dmgcodevil** [comment]
`0.13` should be fine. closing the issue. thanks @RussellSpitzer
