### ISSUE TITLE
Flaky checkstyle plugin run

### ISSUE THREAD

**Issue by ajantha-bhat** [apache/iceberg#7023]
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

Too many times, I am facing one flaky error (also other people are facing it too). Unable to know the reason. 

* What went wrong:
Execution failed for task ':iceberg-spark:iceberg-spark-3.3_2.12:checkstyleMain'.
> A failure occurred while executing org.gradle.api.plugins.quality.internal.CheckstyleAction
   > An unexpected error occurred configuring and executing Checkstyle.
      > java.lang.Error: Error was thrown while processing /home/runner/work/iceberg/iceberg/spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
Failure details:
https://github.com/apache/iceberg/actions/workflows/java-ci.yml

https://github.com/apache/iceberg/actions/runs/4309428443
https://github.com/apache/iceberg/actions/runs/4310045826
https://github.com/apache/iceberg/actions/runs/4306392493/
and many more

**Comment by ajantha-bhat** [comment]
Enabled the --stacktrace, --info and reproduced the issue in https://github.com/apache/iceberg/pull/7010

**Comment by ajantha-bhat** [comment]
```
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.antlr.v4.runtime.atn.ATNSimulator.getCachedContext(ATNSimulator.java:101)
	at org.antlr.v4.runtime.atn.ATNConfigSet.optimizeConfigs(ATNConfigSet.java:217)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.addDFAState(ParserATNSimulator.java:2124)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.addDFAEdge(ParserATNSimulator.java:2078)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.computeTargetState(ParserATNSimulator.java:619)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:454)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
	at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.classOrInterfaceType(JavaLanguageParser.java:3838)
```

Didn't find any issue related to GC in https://github.com/checkstyle/checkstyle

Planning to increase the gradle memory limits. Suggestions are welcome.

**Comment by nastra** [comment]
Might be related to https://github.com/checkstyle/checkstyle/commit/6778867ae4c69cda78b806d87dc39a16a8836271, which was fixed in Checkstyle 10.x. We are running with Checkstyle 9.1 (https://github.com/palantir/gradle-baseline/blob/4.42.0/versions.props#L17)

**Comment by ajantha-bhat** [comment]
>  Might be related to https://github.com/checkstyle/checkstyle/commit/6778867ae4c69cda78b806d87dc39a16a8836271, which was fixed in Checkstyle 9.3. We are running with Checkstyle 9.1 (https://github.com/palantir/gradle-baseline/blob/4.42.0/versions.props#L17)

Good find. I looked for GC in keyowrd. So couldn't find this. I will bump the checkstyle to 9.3 (last version with java 8 support) and try it. Instead of increasing the heap size.

**Comment by ajantha-bhat** [comment]
The devil is back! (issue from today's PR)
https://github.com/apache/iceberg/actions/runs/4364338400/jobs/7631533827


Should I increase the heap size or do we need to debug it once again? 

@XN137, @nastra

**Comment by nastra** [comment]
> The devil is back! (issue from today's PR) https://github.com/apache/iceberg/actions/runs/4364338400/jobs/7631533827
> 
> Should I increase the heap size or do we need to debug it once again?
> 
> @XN137, @nastra

+1 on increasing the heap for Gradle

**Comment by ajantha-bhat** [comment]
reproduced again with --info and --stacktrace 

https://github.com/apache/iceberg/pull/7043
https://github.com/apache/iceberg/actions/runs/4407525559/jobs/7721312588

Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.antlr.v4.runtime.atn.PredictionMode.getConflictingAltSubsets(PredictionMode.java:551)
	at org.antlr.v4.runtime.atn.PredictionMode.hasSLLConflictTerminatingPrediction(PredictionMode.java:241)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.computeTargetState(ParserATNSimulator.java:602)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:454)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
	at com.puppycrawl.tools.checkstyle.grammar.java.JavaLanguageParser.classOrInterfaceType(JavaLanguageParser.java:3838)
	
So, I guess increasing heap space should solve it in #7045.
