### ISSUE TITLE
When using the hive sql to write data into a partition table, an error occurs For a Date partition field, throw an IllegalStateException 

### ISSUE THREAD

**Issue by lurnagao** [apache/iceberg#7098]
### Apache Iceberg version

0.13.2

### Query engine

Hive 2.3.6

### Please describe the bug 🐞

create table is :
`create table iceberg_test(id int, name string) partitioned by (dt date) stored by 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler';`

then insert into :
`insert into iceberg_test values(1, 'zhangsan', '2023-0101');`

The exception is as follows:
`java.lang.IllegalStateException: Not an instance of java.lang.Integer: 2023-0101
      at org.apache.iceberg.data.GenericRecord.get(GenericRecord.java:123)
      at org.apache.iceberg.Accessors$PositionAccessor.get(Accessors.java:71)
      at org.apache.iceberg.Accessors$PositionAccessor.get(Accessors.java:58)
      at org.apache.iceberg.PartitionKey.partition(PartitionKey.java:104)`

**Comment by lurnagao** [comment]
closed by [https://github.com/apache/iceberg/pull/7179](url)
