### ISSUE TITLE
Structured streaming writes to partitioned table fails when spark.sql.extensions is set to IcebergSparkSessionExtensions

### ISSUE THREAD

**Issue by norootnoloot** [apache/iceberg#7226]
### Apache Iceberg version

1.2.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

According to the documentation, when using Iceberg, one should set `spark.sql.extensions` to `org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions`, but setting this property seems to cause an exception to be thrown when trying to write to an Iceberg table using Spark structured streaming.

The exception that is thrown is:

```
Exception in thread "main" org.apache.spark.sql.streaming.StreamingQueryException: days(ts) is not currently supported
=== Streaming Query ===
Identifier: [id = cfb83943-cd87-4c84-bf25-a290e8891e19, runId = ddf71690-7e5d-41f6-8a8e-84c425683a26]
Current Committed Offsets: {}
Current Available Offsets: {MemoryStream[ts#3,a#4,b#5]: 0}

Current State: ACTIVE
Thread State: RUNNABLE

Logical Plan:
WriteToMicroBatchDataSource spark_catalog.default.test_iceberg_table, cfb83943-cd87-4c84-bf25-a290e8891e19, [path=test_iceberg_table, fanout-enabled=true, checkpointLocation=/tmp/spark-checkpoint-16659193840247202419], Append
+- StreamingDataSourceV2Relation [ts#3, a#4, b#5], org.apache.spark.sql.execution.streaming.MemoryStreamScanBuilder@4533d1cf, MemoryStream[ts#3,a#4,b#5]
```

Code to reproduce:

```scala
package com.example

import org.apache.spark.sql.execution.streaming.MemoryStream
import org.apache.spark.sql.streaming.Trigger
import org.apache.spark.sql.{Encoders, SparkSession}

import java.nio.file.Files
import java.sql.Timestamp

case class Bla(ts: Timestamp, a: String, b: Double)

object MinEx {
  def main(args: Array[String]): Unit = {
    val warehouseDir = Files.createTempDirectory("spark-warehouse-iceberg-").toString
    val checkpointDir = Files.createTempDirectory("spark-checkpoint-").toString
    val spark = SparkSession.builder()
      .config("spark.sql.catalog.spark_catalog", "org.apache.iceberg.spark.SparkSessionCatalog")
      .config("spark.sql.catalog.spark_catalog.type", "hadoop")
      .config("spark.sql.catalog.spark_catalog.warehouse", warehouseDir)
      .config("spark.sql.warehouse.dir", warehouseDir)
      .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
      .appName("BugRepro")
      .master("local[*]")
      .enableHiveSupport()
      .getOrCreate()

    spark.sql("create table test_iceberg_table(ts timestamp, a string, b double) using iceberg partitioned by (days(ts))")

    implicit val sqlContext = spark.sqlContext
    implicit val encoder = Encoders.product[Bla]
    val memStream = MemoryStream[Bla]
    val now = System.currentTimeMillis()
    val day = 86400000
    memStream.addData(List(
      Bla(new Timestamp(now), "test", 12.34),
      Bla(new Timestamp(now - 1 * day), "test 1d", 33.34),
      Bla(new Timestamp(now - 3 * day), "test 3d", 44.34),
      Bla(new Timestamp(now - 2 * day), "test 2d", 55.34),
    ))

    memStream.toDF()
      .writeStream
      .format("iceberg")
      .outputMode("append")
      .option("path", "test_iceberg_table")
      .option("fanout-enabled", true)
      .option("checkpointLocation", checkpointDir)
      .trigger(Trigger.Once())
      .start()
      .awaitTermination()
  }
}
```

The code works as expected when the statement that configures `spark.sql.extensions` is commented out.

**Comment by meetsitaram** [comment]
I had the same issue, but worked when I changed the configs from `spark.sql.catalog.spark_catalog` to `spark.sql.catalog.iceberg`. 

```scala
SparkConf()
    .set("spark.sql.catalog.iceberg", "org.apache.iceberg.spark.SparkCatalog")
    .set("spark.sql.catalog.iceberg.catalog-impl", "hadoop")
    .set("spark.sql.catalog.iceberg.catalog.warehouse", config.warehouse)
    .set("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
```

**Comment by Fokko** [comment]
Can reproduce this locally. Found in Iceberg 1.0.0 onward.

**Comment by Fokko** [comment]
@adigerber I know that it is a while ago, but which version of Spark are you using?

**Comment by Fokko** [comment]
Able to reproduce this using:

```sh
rm -rf /tmp/warehouse
rm -rf /tmp/spark-checkpoint

mkdir -p /tmp/warehouse
mkdir -p /tmp/spark-checkpoint

./bin/spark-shell \
 --packages org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:1.0.0 \
 --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions \
 --conf spark.sql.catalog.demo=org.apache.iceberg.spark.SparkCatalog \
 --conf spark.sql.catalog.demo.type=hadoop \
 --conf spark.sql.catalog.demo.warehouse=/tmp/warehouse \
 --conf spark.sql.warehouse.dir=/tmp/warehouse \
 --conf spark.sql.defaultCatalog=demo 
```

```scala
spark.sql("create table test_iceberg_table(ts timestamp, a string, b double) using iceberg partitioned by (days(ts))")


import java.nio.file.Files
import java.sql.Timestamp
import org.apache.spark.sql.execution.streaming.MemoryStream
import org.apache.spark.sql.streaming.Trigger
import org.apache.spark.sql.{Encoders, SparkSession}

case class Bla(ts: Timestamp, a: String, b: Double)

implicit val sqlContext = spark.sqlContext
implicit val encoder = Encoders.product[Bla]
val memStream = MemoryStream[Bla]
val now = System.currentTimeMillis()
val day = 86400000
memStream.addData(List(
  Bla(new Timestamp(now), "test", 12.34),
  Bla(new Timestamp(now - 1 * day), "test 1d", 33.34),
  Bla(new Timestamp(now - 3 * day), "test 3d", 44.34),
  Bla(new Timestamp(now - 2 * day), "test 2d", 55.34),
))

memStream.toDF()
  .writeStream
  .format("iceberg")
  .outputMode("append")
  .option("path", "/tmp/warehouse/test_iceberg_table")
  .option("checkpointLocation", "/tmp/spark-checkpoint")
  .option("fanout-enabled", true)
  .trigger(Trigger.Once())
  .start()
  .awaitTermination()
```

Any idea @aokolnychyi? Not really looking forward to bisecting between 0.13.1 and 1.0.0 :3

**Comment by Fokko** [comment]
Spark 3.1 with Iceberg 1.3.0 works fine. It seems that something is off with Spark 3.2+

**Comment by Fokko** [comment]
The stack trace:

```
23/06/19 17:45:53 ERROR MicroBatchExecution: Query [id = 2507e68d-0fb2-4aa2-98e4-427bfa1326c5, runId = 308060c0-6572-4328-9588-ece2b00c054a] terminated with error
org.apache.spark.sql.AnalysisException: days(ts) is not currently supported
	at org.apache.spark.sql.catalyst.expressions.V2ExpressionUtils$.$anonfun$toCatalyst$1(V2ExpressionUtils.scala:64)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.catalyst.expressions.V2ExpressionUtils$.toCatalyst(V2ExpressionUtils.scala:64)
	at org.apache.spark.sql.execution.datasources.v2.DistributionAndOrderingUtils$.$anonfun$prepareQuery$1(DistributionAndOrderingUtils.scala:36)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at org.apache.spark.sql.execution.datasources.v2.DistributionAndOrderingUtils$.prepareQuery(DistributionAndOrderingUtils.scala:36)
	at org.apache.spark.sql.execution.datasources.v2.V2Writes$$anonfun$apply$1.applyOrElse(V2Writes.scala:93)
	at org.apache.spark.sql.execution.datasources.v2.V2Writes$$anonfun$apply$1.applyOrElse(V2Writes.scala:43)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:560)
	at org.apache.spark.sql.execution.datasources.v2.V2Writes$.apply(V2Writes.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2Writes$.apply(V2Writes.scala:39)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:211)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:208)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:200)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:200)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:179)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:88)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:179)
	at org.apache.spark.sql.execution.streaming.IncrementalExecution.$anonfun$optimizedPlan$1(IncrementalExecution.scala:81)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:185)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:510)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:185)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:184)
	at org.apache.spark.sql.execution.streaming.IncrementalExecution.optimizedPlan$lzycompute(IncrementalExecution.scala:82)
	at org.apache.spark.sql.execution.streaming.IncrementalExecution.optimizedPlan(IncrementalExecution.scala:79)
	at org.apache.spark.sql.execution.QueryExecution.assertOptimized(QueryExecution.scala:136)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:154)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:151)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runBatch$15(MicroBatchExecution.scala:656)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:375)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:373)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:68)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runBatch(MicroBatchExecution.scala:646)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$2(MicroBatchExecution.scala:256)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:375)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:373)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:68)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$1(MicroBatchExecution.scala:219)
	at org.apache.spark.sql.execution.streaming.SingleBatchExecutor.execute(TriggerExecutor.scala:39)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:213)
	at org.apache.spark.sql.execution.streaming.StreamExecution.$anonfun$runStream$1(StreamExecution.scala:307)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:285)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:208)
```

Spark 3.2 uses a V2 data source.

**Comment by adigerber** [comment]
> @adigerber I know that it is a while ago, but which version of Spark are you using?

Either 3.3.1 or 3.3.2.
IIRC it still happens in Spark 3.3.2 + Iceberg 1.2.1

**Comment by Fokko** [comment]
Able to reproduce this:
```java
@Test
public void testStructuredStreaming() throws TimeoutException, StreamingQueryException {
  sql("DROP TABLE IF EXISTS %s", tableName("structured_streaming"));

  sql("create table %s(ts timestamp) using iceberg partitioned by (days(ts))", tableName("structured_streaming"));

  List<TimestampRow> nums = new ArrayList<TimestampRow>();
  nums.add(new TimestampRow(Timestamp.valueOf("2021-01-01 00:00:00")));
  nums.add(new TimestampRow(Timestamp.valueOf("2021-01-02 00:00:00")));
  nums.add(new TimestampRow(Timestamp.valueOf("2021-01-03 00:00:00")));

  MemoryStream<TimestampRow> ms = new MemoryStream<>(100, spark.sqlContext(), null, Encoders.bean(TimestampRow.class));

  ms.addData(JavaConverters.asScalaIteratorConverter(nums.iterator()).asScala().toSeq());

  ms.toDF()
          .writeStream()
          .format("iceberg")
          .outputMode("append")
          .option("checkpointLocation", "/tmp/spark-checkpoint")
          .option("fanout-enabled", true)
          .trigger(Trigger.Once())
          .toTable(tableName("structured_streaming"))
          .awaitTermination();
}
```

Seems that a regular query does not hit `V2ExpressionUtils`

**Comment by Fokko** [comment]
Was able to chase this down. Looks like the catalog is not passed down to the execution. 

```scala
    // TODO (SPARK-27484): we should add the writing node before the plan is analyzed.
    sink match {
      case s: SupportsWrite =>
        val relationOpt = plan.catalogAndIdent.map {
          case (catalog, ident) => DataSourceV2Relation.create(s, Some(catalog), Some(ident))
        }
        WriteToMicroBatchDataSource(
          relationOpt,
          table = s,
          query = _logicalPlan,
          queryId = id.toString,
          extraOptions,
          outputMode)
```

The `relationOpt` is `None`

**Comment by Fokko** [comment]
Closing in. One workaround is to use `toTable('test_iceberg_table ')` instead of `start()`.

**Comment by shuvaevv** [comment]
> Closing in. One workaround is to use `toTable('test_iceberg_table ')` instead of `start()`.

@Fokko For Spark 3.3.0 and + Iceberg 1.2.1, calling the `toTable` method didn't solve the issue.
Code:
```
df.writeStream
  .format("iceberg")
  .outputMode("append")
  .option("checkpointLocation", checkpointLocation)
  .toTable(tableName)
  .awaitTermination()
```

Error: 
`org.apache.spark.sql.AnalysisException: hours(timestamp) is not currently supported`

**Comment by Fokko** [comment]
@shuvaevv Sorry for the late reply, I missed this one. Do you have a stacktrace? I've cleaned up the PR, and that should be ready for the next release.

**Comment by Marcus-Rosti** [comment]
same issue for me

**Comment by Marcus-Rosti** [comment]
> The stack trace:
> 
> ```
> 23/06/19 17:45:53 ERROR MicroBatchExecution: Query [id = 2507e68d-0fb2-4aa2-98e4-427bfa1326c5, runId = 308060c0-6572-4328-9588-ece2b00c054a] terminated with error
> org.apache.spark.sql.AnalysisException: days(ts) is not currently supported
> 	at org.apache.spark.sql.catalyst.expressions.V2ExpressionUtils$.$anonfun$toCatalyst$1(V2ExpressionUtils.scala:64)
> 	at scala.Option.getOrElse(Option.scala:189)
> 	at org.apache.spark.sql.catalyst.expressions.V2ExpressionUtils$.toCatalyst(V2ExpressionUtils.scala:64)
> 	at org.apache.spark.sql.execution.datasources.v2.DistributionAndOrderingUtils$.$anonfun$prepareQuery$1(DistributionAndOrderingUtils.scala:36)
> 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
> 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
> 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
> 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
> 	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
> 	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
> 	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
> 	at org.apache.spark.sql.execution.datasources.v2.DistributionAndOrderingUtils$.prepareQuery(DistributionAndOrderingUtils.scala:36)
> 	at org.apache.spark.sql.execution.datasources.v2.V2Writes$$anonfun$apply$1.applyOrElse(V2Writes.scala:93)
> 	at org.apache.spark.sql.execution.datasources.v2.V2Writes$$anonfun$apply$1.applyOrElse(V2Writes.scala:43)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:584)
> 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:584)
> 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
> 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
> 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
> 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
> 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
> 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:560)
> 	at org.apache.spark.sql.execution.datasources.v2.V2Writes$.apply(V2Writes.scala:43)
> 	at org.apache.spark.sql.execution.datasources.v2.V2Writes$.apply(V2Writes.scala:39)
> 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:211)
> 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
> 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
> 	at scala.collection.immutable.List.foldLeft(List.scala:91)
> 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:208)
> 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:200)
> 	at scala.collection.immutable.List.foreach(List.scala:431)
> 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:200)
> 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:179)
> 	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:88)
> 	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:179)
> 	at org.apache.spark.sql.execution.streaming.IncrementalExecution.$anonfun$optimizedPlan$1(IncrementalExecution.scala:81)
> 	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
> 	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:185)
> 	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:510)
> 	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:185)
> 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
> 	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:184)
> 	at org.apache.spark.sql.execution.streaming.IncrementalExecution.optimizedPlan$lzycompute(IncrementalExecution.scala:82)
> 	at org.apache.spark.sql.execution.streaming.IncrementalExecution.optimizedPlan(IncrementalExecution.scala:79)
> 	at org.apache.spark.sql.execution.QueryExecution.assertOptimized(QueryExecution.scala:136)
> 	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:154)
> 	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:151)
> 	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runBatch$15(MicroBatchExecution.scala:656)
> 	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:375)
> 	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:373)
> 	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:68)
> 	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runBatch(MicroBatchExecution.scala:646)
> 	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$2(MicroBatchExecution.scala:256)
> 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
> 	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:375)
> 	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:373)
> 	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:68)
> 	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$1(MicroBatchExecution.scala:219)
> 	at org.apache.spark.sql.execution.streaming.SingleBatchExecutor.execute(TriggerExecutor.scala:39)
> 	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:213)
> 	at org.apache.spark.sql.execution.streaming.StreamExecution.$anonfun$runStream$1(StreamExecution.scala:307)
> 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
> 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
> 	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:285)
> 	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:208)
> ```
> 
> Spark 3.2 uses a V2 data source.

same stack trace for me on 1.3.1 and spark 3.3

**Comment by Marcus-Rosti** [comment]
toTable wasn't a fix

**Comment by aokolnychyi** [comment]
This is a Spark issue, not an Iceberg issue (at least in 3.4). We may consider fixing Spark 3.3 and older but I am not so sure about 3.4. In Spark 3.4, we are relying on the function catalog API to resolve transforms. @Marcus-Rosti, could you confirm `toTable` works in 3.4? I believe you tried 3.3 before.

@Fokko is right that `start()`, unlike `toTable()` does not populate the catalog, hence we can't resolve the transforms. I believe the right solution would be to fix Spark to use `SupportsCatalogOptions` when loading `Table` from `TableProvider`.

**Comment by FabricioZGalvani** [comment]
Hello, my friends.

I'm using Structured streaming writes to partitioned table, and I'm using Iceberg's transformations to partition.

Trying to record with .start(), I get the same error, but testing to use the approach of passing toTable('iceberg_table') instead of start(), it worked.

I am using Iceberg 1.3.0 and Spark 3.4.0.

This way it didn't work
```
df.writeStream.format("iceberg").outputMode("append").trigger(
    once=True
).option("path", iceberg_table).option("fanout-enabled", "true").option(
    "checkpointLocation",
    checkpoint_location,
).start().awaitTermination()
```

This way it worked:
```
df.writeStream.format("iceberg").outputMode("append").trigger(
    once=True
).option("path", iceberg_table).option("fanout-enabled", "true").option(
    "checkpointLocation",
    checkpoint_location,
).toTable(
    iceberg_table
).awaitTermination()
```

**Comment by Marcus-Rosti** [comment]
> Hello, my friends.
> 
> I'm using Structured streaming writes to partitioned table, and I'm using Iceberg's transformations to partition.
> 
> Trying to record with .start(), I get the same error, but testing to use the approach of passing toTable('iceberg_table') instead of start(), it worked.
> 
> I am using Iceberg 1.3.0 and Spark 3.4.0.
> 
> This way it didn't work
> 
> ```
> df.writeStream.format("iceberg").outputMode("append").trigger(
>     once=True
> ).option("path", iceberg_table).option("fanout-enabled", "true").option(
>     "checkpointLocation",
>     checkpoint_location,
> ).start().awaitTermination()
> ```
> 
> This way it worked:
> 
> ```
> df.writeStream.format("iceberg").outputMode("append").trigger(
>     once=True
> ).option("path", iceberg_table).option("fanout-enabled", "true").option(
>     "checkpointLocation",
>     checkpoint_location,
> ).toTable(
>     iceberg_table
> ).awaitTermination()
> ```

Yeah I got an error with iceberg 1.3 and spark 3.3, that's interesting

**Comment by arundh93** [comment]
> Hello, my friends.
> 
> I'm using Structured streaming writes to partitioned table, and I'm using Iceberg's transformations to partition.
> 
> Trying to record with .start(), I get the same error, but testing to use the approach of passing toTable('iceberg_table') instead of start(), it worked.
> 
> I am using Iceberg 1.3.0 and Spark 3.4.0.
> 
> This way it didn't work
> 
> df.writeStream.format("iceberg").outputMode("append").trigger(
>     once=True
> ).option("path", iceberg_table).option("fanout-enabled", "true").option(
>     "checkpointLocation",
>     checkpoint_location,
> ).start().awaitTermination()
> This way it worked:
> 
> df.writeStream.format("iceberg").outputMode("append").trigger(
>     once=True
> ).option("path", iceberg_table).option("fanout-enabled", "true").option(
>     "checkpointLocation",
>     checkpoint_location,
> ).toTable(
>     iceberg_table
> ).awaitTermination()

For me as well toTable works in spark 3.4

However it fails on a multi executor setup

**Comment by aokolnychyi** [comment]
If I remember correctly, Spark 3.3 does not have the function catalog. Therefore, we can't resolve Iceberg transforms. I think the right approach is either to use `toTable` in Spark 3.4 and above or fix Spark.

**Comment by kaijiezhang0319** [comment]
hello @aokolnychyi .  We are meeting similar issue.  Spark 3.3.1  and iceberg 1.1.0.   We previously use spark3.2.1 and iceberg 1.1.0 it works fine.   And we find the issue when we bump up to spark 3.3.1.     Any suggestion is appreciate. thanks

**Comment by greg-roberts-bbc** [comment]
We're encountering this issue using iceberg 1.4.3 on Spark 3.3.0 (AWS Glue 4.0) and using `toTable` hasn't fixed the issue.

**Comment by greg-roberts-bbc** [comment]
We've found a workaround in our use case. (Iceberg 1.4.3, Spark 3.3.0 on Glue 4.0).

Our previous flow was:

```
# set up readStream
read_stream = spark.readStream.format(
<setup read stream>
.load()

# dataframe operations
df = read_stream.select(
<various dataframe operations>
)

# setup write stream
write_stream = df.writeStream.format("iceberg").outputMode("append").trigger(
    processingTime=job_args["TRIGGER_PROCESSING_TIME"]
).options(**{
    "fanout-enabled": job_args["FANOUT_ENABLED"],
    "checkpointLocation": job_args["CHECKPOINT_LOCATION"],
}).toTable(TABLE)
```

which always failed on the insert with the above described error.

Our new flow is to use processBatch:

```
def process_batch(df, batch_id):
    df = df.select(
    <various dataframe operations>
    )

    df.writeTo(TABLE).append()


read_stream.writeStream.forEachBatch(process_batch).start()
```

The above is for completeness, as we're actually using Glue's inbuilt [`GlueContext.forEachBatch`](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-crawler-pyspark-extensions-glue-context.html#aws-glue-api-crawler-pyspark-extensions-glue-context-forEachBatch) but it [does exactly the same thing](https://github.com/awslabs/aws-glue-libs/blob/master/awsglue/context.py#L602).

and this is no longer failing. We're able to write to the table with partition transforms (we're using `hour()` to partition our data).

Interestingly, the data is now being written to S3 as you'd expect for the S3FileIO implementation (i.e. writes are prefixed with a [random string](https://iceberg.apache.org/docs/latest/aws/#object-store-file-layout).

It would be nice to use the inbuilt write triggers as described [in the docs](https://iceberg.apache.org/docs/latest/spark-structured-streaming/#streaming-writes) but we are happy with a working solution. and this allows us to add MERGE behaviour in with SQL. 

Hope someone else finds this useful!

**Comment by greg-roberts-bbc** [comment]
@stevenlii 

> But this way there is no checkpointLocation. How do you manage the offset?

As I said, we're using `GlueContext.forEachBatch` which allows you to specify the checkpoint location as follows:

```
glue_context.forEachBatch(
    frame=read_stream,
    batch_function=process_batch,
    options={
        "windowSize": job_args["TRIGGER_PROCESSING_TIME"],
        "fanout-enabled": job_args["FANOUT_ENABLED"],
        "checkpointLocation": job_args["CHECKPOINT_LOCATION"],
        "persistDataFrame": "false",
    }
)
```

The equivalent call to `writeStream.forEachBatch` would be something like:

`read_stream.writeStream.foreachBatch(process_batch).trigger(processingTime=windowSize).option("checkpointLocation", checkpointLocation)`

As can be seen in the Glue source code I linked above, here: https://github.com/awslabs/aws-glue-libs/blob/master/awsglue/context.py#L641

**Comment by wfxxh** [comment]
spark version: 3.3.3 , iceberg version: 1.4.3 ,same stack trace for me.
my table is:

> CREATE TABLE iceberg_catalog.doi.doi_log (
  date_time TIMESTAMP,
  ip STRING,
  protocol STRING,
  operation STRING,
  response STRING,
  duration STRING,
  doi STRING)
USING iceberg
PARTITIONED BY (days(date_time))
TBLPROPERTIES (
  'format' = 'iceberg/parquet',
  'format-version' = '2',
  'write.metadata.delete-after-commit.enabled' = 'true',
  'write.metadata.previous-versions-max' = '20',
  'write.parquet.bloom-filter-enabled.column.doi' = 'true',
  'write.parquet.compression-codec' = 'zstd',
  'write.target-file-size-bytes' = '1073741824')

the error is "org.apache.spark.sql.AnalysisException: days(date_time) is not currently supported"
when I set 'write.distribution-mode=none' the error is "days(date_time) ASC NULLS FIRST is not currently supported"
My code is like 

> val kafkaDF = spark read from kafka topic
   kafkaDF.writeStream
      .outputMode("append")
      .queryName("doi")
      .option("checkpointLocation", "path/to/checkpoint")
      .option("fanout-enabled", "true")
      .trigger(Trigger.ProcessingTime(1, TimeUnit.MINUTES))
      .format("iceberg")
      .toTable("iceberg_catalog.doi.doi_log")

**Comment by darklord1807** [comment]
Same error. Any update?
