### ISSUE TITLE
Failed to find data source: iceberg. Please find packages at

### ISSUE THREAD

**Issue by dragon-feng** [apache/iceberg#7268]
### Query engine

spark

### Question

This problem cannot be solved using issues #4628, hadoop version 3.1.0, spark version 3.2.3, and iceberg version 0.14.1
	
 diagnostics: User class threw exception: java.lang.ClassNotFoundException: 
Failed to find data source: iceberg. Please find packages at
http://spark.apache.org/third-party-projects.html
       
	at org.apache.spark.sql.errors.QueryExecutionErrors$.failedToFindDataSourceError(QueryExecutionErrors.scala:443)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:670)
	at org.apache.spark.sql.streaming.DataStreamWriter.startInternal(DataStreamWriter.scala:362)
	at org.apache.spark.sql.streaming.DataStreamWriter.start(DataStreamWriter.scala:248)
	at com.myit.app.streaming.StructStreamingIceberg$.main(StructStreamingIceberg.scala:87)
	at com.myit.app.streaming.StructStreamingIceberg.main(StructStreamingIceberg.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:737)

**Comment by NhatDuy11** [comment]
Can someone tell me if I am using Spark 2.4.5 and Scala 2.11.12 which version of Apache Iceberg should I use?, thank you very much everyone!

**Comment by imkindia12** [comment]
@NhatDuy11 your spark version appear the time you invoke spark-shell, Using V2 version is helps in using time travel and other ILM features.
