### ISSUE TITLE
TestMetricsRowGroupFilterTypes fails on certain machines, bisects to ORC lib upgrade

### ISSUE THREAD

**Issue by islamismailov** [apache/iceberg#7303]
### Apache Iceberg version

1.2.0 (latest release)

### Query engine

None

### Please describe the bug 🐞

I see this test fail on some machines we have in production. I wasn't able to narrow down why but I ssh'ed into that host and was able to git bisect to this commit which essentially upgrades Apache ORC library version: `9b373b1541e7ec5f187fb775477dba2e3b8d11bc`. Might be related to timestamp column and timezone settings on a particular host. Perhaps @williamhyun might have an idea. `1.8.1` passes the test, and both `1.8.2` and `1.8.3` are broken.

Here's the stacktrace:

`org.apache.hadoop.fs.ChecksumException: Checksum error: /tmp/stats-row-group-filter-types-test.orc at 2048 exp: -140057062 got: -514400478	
at org.apache.hadoop.fs.FSInputChecker.verifySums(FSInputChecker.java:323)	
at org.apache.hadoop.fs.FSInputChecker.readChecksumChunk(FSInputChecker.java:279)	
at org.apache.hadoop.fs.FSInputChecker.fill(FSInputChecker.java:214)	
at org.apache.hadoop.fs.FSInputChecker.read1(FSInputChecker.java:232)	
at org.apache.hadoop.fs.FSInputChecker.read(FSInputChecker.java:196)	
at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.read(ChecksumFileSystem.java:198)	
at org.apache.hadoop.fs.FSInputStream.readFully(FSInputStream.java:78)	
at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:107)	
at org.apache.orc.impl.ReaderImpl.read(ReaderImpl.java:702)	
at org.apache.orc.impl.ReaderImpl.extractFileTail(ReaderImpl.java:806)	
at org.apache.orc.impl.ReaderImpl.<init>(ReaderImpl.java:567)	
at org.apache.orc.OrcFile.createReader(OrcFile.java:385)	
at org.apache.iceberg.data.TestMetricsRowGroupFilterTypes.createOrcInputFile(TestMetricsRowGroupFilterTypes.java:193)	
at org.apache.iceberg.data.TestMetricsRowGroupFilterTypes.createInputFile(TestMetricsRowGroupFilterTypes.java:166)	
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
at java.lang.reflect.Method.invoke(Method.java:498)	
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)	
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)	
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)	
at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)	
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)	
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)	
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)	
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)	
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)	
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)	
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)	
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)	
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)	
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)	
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)	
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)	
at org.junit.runners.Suite.runChild(Suite.java:128)	
at org.junit.runners.Suite.runChild(Suite.java:27)	
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)	
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)	
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)	
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)	
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)	
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)	
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)	
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)	
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)	
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)	
at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)	
at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)	
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
at java.lang.reflect.Method.invoke(Method.java:498)	
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)	
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)	
at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)	
at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)	
at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)	
at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)	
at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)	
at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)	
at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)	
at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)	
at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)`

**Comment by Fokko** [comment]
cc @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you for pinging me, @Fokko .

**Comment by dongjoon-hyun** [comment]
According to Apache ORC 1.8.2 release note, there is no change about no timestamp column and timezone.
- https://github.com/apache/orc/releases/tag/v1.8.2

The following three are the technical code changes.
- [ORC-1332](https://issues.apache.org/jira/browse/ORC-1332) Avoid NegativeArraySizeException when using searchArgument
- [ORC-1343](https://issues.apache.org/jira/browse/ORC-1343) Disable ENABLE_INDEXES
- [ORC-1338](https://issues.apache.org/jira/browse/ORC-1338) Set bloom filter fpp to 1%

**Comment by dongjoon-hyun** [comment]
Could you share some detail info for that machine, @islamismailov ?

**Comment by islamismailov** [comment]
@dongjoon-hyun can you actually check `1.8.0` - I know that version consistently passes. I still see problems with `1.8.1`

I do think it's somehow related to timestamp since issue seems to disappear and re-appear. I found a similar problem that has happened before:

https://github.com/apache/iceberg/issues/1113

**Comment by dongjoon-hyun** [comment]
May I rephrase your comments?

1. In the PR description, you wrote
> 1.8.1 passes the test, and both 1.8.2 and 1.8.3 are broken.

2. In the previous comment, you wrote
> can you actually check 1.8.0 - I know that version consistently passes. I still see problems with 1.8.1

Which version do you want to report your issues, @islamismailov ?

**Comment by islamismailov** [comment]
My initial assessment was wrong. The problem still reproduces on `1.8.1`. `1.8.0` works fine though @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you for your confirmation, @islamismailov .

**Comment by dongjoon-hyun** [comment]
According to Apache ORC 1.8.1 release note, there exists three bug fixes.

https://github.com/apache/orc/releases/tag/v1.8.1

Although I took a look,

1. [ORC-1283](https://issues.apache.org/jira/browse/ORC-1283) ENABLE_INDEXES does not take effect
    - This is recovered back at v1.8.2
2. [ORC-1288](https://issues.apache.org/jira/browse/ORC-1288) Invalid memory freeing with ZLIB compression
    - This is C++ change which is irrelevant to Java world.
3. [ORC-1291](https://issues.apache.org/jira/browse/ORC-1291) NullPointerException in TypeDescription
    - This changes only the hashCode of types.

[As I asked before](https://github.com/apache/iceberg/issues/7303#issuecomment-1502051086), we need more details about your some machines (`I see this test fail on some machines we have in production.`) if you want to investigate more, @islamismailov .

**Comment by islamismailov** [comment]
This is the command to run the test `./gradlew :iceberg-data:test --tests "org.apache.iceberg.data.TestMetricsRowGroupFilterTypes"`

**Comment by dongjoon-hyun** [comment]
I cannot reproduce it locally. I used Java 8 on Apple Silicon Mac.
```
$ sw_vers
ProductName:	macOS
ProductVersion:	12.6.4
BuildVersion:	21G526

$ git log -n1
commit fc6bd1e7ab92086611bab87037b9edd17f99ed40 (HEAD -> master, origin/master, origin/HEAD)
Author: Ajantha Bhat <ajanthabhat@gmail.com>
Date:   Tue Apr 11 21:49:52 2023 +0530

    Nessie: Fix testcase failures (#7320)

$ ./gradlew :iceberg-data:test --tests "org.apache.iceberg.data.TestMetricsRowGroupFilterTypes"

BUILD SUCCESSFUL in 2s
23 actionable tasks: 1 executed, 22 up-to-date
```

**Comment by RussellSpitzer** [comment]
This also does not reproduce on any of our CI's, could you please give more information about the environment in which this test is being run? Is it failing on the same machine every time, or is it variable?

**Comment by dongjoon-hyun** [comment]
Do you still see the issues, @islamismailov ? For a record, Apache ORC 1.8.3 is used in Apache Spark, Hive, Arrow community with various environments. Since there is no this kind of report, I'm highly interested in what is going on your environment.
- Apache Spark: https://github.com/apache/spark/blob/master/pom.xml#L145
- Apache Hive: https://github.com/apache/hive/blob/master/pom.xml#L182
- Apache Arrow: https://github.com/apache/arrow/blob/main/java/adapter/orc/pom.xml#L40

**Comment by islamismailov** [comment]
I have not dug deeper on this. I just reverted ORC library version to `1.8.0` version and left it at that.

**Comment by islamismailov** [comment]
It fails on certain machines some of the time, so it's hard to catch. I have a feeling that it's related to timestamp column handling.

**Comment by dongjoon-hyun** [comment]
Got it. Thank you for the updates.
