### ISSUE TITLE
Spark: migrate hive table to iceberg table(using hive metastore)

### ISSUE THREAD

**Issue by ZhendongBai** [apache/iceberg#7328]
### Apache Iceberg version

1.1.0

### Query engine

Spark

### Please describe the bug 🐞

spark sql 3.2.1 ，execute `CALL spark_catalog.system.migrate('spark_catalog.iceberg_db.test_migration_hive_to_iceberg')`
i add the logger error to print the exception stack,show as below:
```pre
23/04/12 13:18:53 ERROR actions.MigrateTableSparkAction: Failed to perform the migration, aborting table creation and restoring the original table
org.apache.iceberg.exceptions.NoSuchIcebergTableException: Not an iceberg table: spark_catalog.iceberg_db.test_migration_hive_to_iceberg (type=null)
	at org.apache.iceberg.exceptions.NoSuchIcebergTableException.check(NoSuchIcebergTableException.java:33)
	at org.apache.iceberg.hive.HiveTableOperations.validateTableIsIceberg(HiveTableOperations.java:728)
	at org.apache.iceberg.hive.HiveTableOperations.doRefresh(HiveTableOperations.java:224)
	at org.apache.iceberg.BaseMetastoreTableOperations.refresh(BaseMetastoreTableOperations.java:97)
	at org.apache.iceberg.BaseMetastoreTableOperations.current(BaseMetastoreTableOperations.java:80)
	at org.apache.iceberg.BaseMetastoreCatalog$BaseMetastoreCatalogTableBuilder.createTransaction(BaseMetastoreCatalog.java:207)
	at org.apache.iceberg.CachingCatalog$CachingTableBuilder.createTransaction(CachingCatalog.java:279)
	at org.apache.iceberg.spark.SparkCatalog.stageCreate(SparkCatalog.java:181)
	at org.apache.iceberg.spark.SparkSessionCatalog.stageCreate(SparkSessionCatalog.java:162)
	at org.apache.iceberg.spark.actions.BaseTableCreationSparkAction.stageDestTable(BaseTableCreationSparkAction.java:157)
	at org.apache.iceberg.spark.actions.MigrateTableSparkAction.doExecute(MigrateTableSparkAction.java:124)
	at org.apache.iceberg.spark.actions.BaseSparkAction.withJobGroupInfo(BaseSparkAction.java:127)
	at org.apache.iceberg.spark.actions.MigrateTableSparkAction.execute(MigrateTableSparkAction.java:109)
	at org.apache.iceberg.spark.procedures.MigrateTableProcedure.call(MigrateTableProcedure.java:102)
```

**Comment by ajantha-bhat** [comment]
I think catalog name should not be present in the tableName argument. 

Please refer the examples here
https://iceberg.apache.org/docs/latest/spark-procedures/#examples-5
