### ISSUE TITLE
Failed to initialize S3FileIO when writing to minio using spark

### ISSUE THREAD

**Issue by kukayiyi** [apache/iceberg#7396]
### Query engine

spark

### Question

I encountered the following error when reading and writing using iceberg+spark+minio
`
Exception in thread "main" java.lang.IllegalArgumentException: Cannot initialize FileIO, missing no-arg constructor: org.apache.iceberg.aws.s3.S3FileIO
	at org.apache.iceberg.CatalogUtil.loadFileIO(CatalogUtil.java:312)
	at org.apache.iceberg.hadoop.HadoopCatalog.initialize(HadoopCatalog.java:118)
	at org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:239)
	at org.apache.iceberg.CatalogUtil.buildIcebergCatalog(CatalogUtil.java:284)
	at org.apache.iceberg.spark.SparkCatalog.buildIcebergCatalog(SparkCatalog.java:135)
	at org.apache.iceberg.spark.SparkCatalog.initialize(SparkCatalog.java:537)
	at org.apache.iceberg.spark.SparkSessionCatalog.buildSparkCatalog(SparkSessionCatalog.java:77)
	at org.apache.iceberg.spark.SparkSessionCatalog.initialize(SparkSessionCatalog.java:307)
	at org.apache.spark.sql.connector.catalog.Catalogs$.load(Catalogs.scala:60)
	at org.apache.spark.sql.connector.catalog.CatalogManager.$anonfun$catalog$1(CatalogManager.scala:53)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
	at org.apache.spark.sql.connector.catalog.CatalogManager.catalog(CatalogManager.scala:53)
	at org.apache.spark.sql.connector.catalog.CatalogManager.currentCatalog(CatalogManager.scala:122)
	at org.apache.spark.sql.connector.catalog.LookupCatalog.currentCatalog(LookupCatalog.scala:34)
	at org.apache.spark.sql.connector.catalog.LookupCatalog.currentCatalog$(LookupCatalog.scala:34)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.currentCatalog(Analyzer.scala:188)
	at org.apache.spark.sql.connector.catalog.LookupCatalog$CatalogAndIdentifier$.unapply(LookupCatalog.scala:125)
	at org.apache.spark.sql.connector.catalog.LookupCatalog$NonSessionCatalogAndIdentifier$.unapply(LookupCatalog.scala:72)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:565)
	at com.yisa.iceberg.MinioIcebergExample.main(MinioIcebergExample.java:77)
`
My config is:
`
("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
("spark.sql.catalog.demo", "org.apache.iceberg.spark.SparkSessionCatalog")
("spark.sql.catalog.demo.io-impl", "org.apache.iceberg.aws.s3.S3FileIO")
("spark.sql.catalog.demo.warehouse", "s3a://iceberg")
("spark.sql.catalog.demo.s3.endpoint", "http://127.0.0.19000")
("spark.sql.defaultCatalog", "demo")
("spark.sql.catalogImplementation", "in-memory")
("spark.sql.catalog.demo.type", "hadoop")
("spark.executor.heartbeatInterval", "300000")
("spark.network.timeout", "400000");
("spark.hadoop.fs.s3a.access.key", "minioadmin");
("spark.hadoop.fs.s3a.secret.key", "minioadmin");
("spark.hadoop.fs.s3a.endpoint",  "127.0.0.1:9000");
("spark.hadoop.fs.s3a.connection.ssl.enabled", "false");
("spark.hadoop.fs.s3a.path.style.access", "true");
("spark.hadoop.fs.s3a.attempts.maximum", "1");
("spark.hadoop.fs.s3a.connection.establish.timeout", "5000");
("spark.hadoop.fs.s3a.connection.timeout", "10000");
`
This config is based on:https://blog.min.io/manage-iceberg-tables-with-spark/
I used the following jar package: 
`
<dependency>
    <groupId>org.apache.spark</groupId>
    <artifactId>spark-core_2.12</artifactId>
    <version>3.3.2</version>
</dependency>
<dependency>
    <groupId>org.apache.spark</groupId>
    <artifactId>spark-sql_2.12</artifactId>
    <version>3.3.2</version>
</dependency>
<dependency>
    <groupId>org.apache.hadoop</groupId>
    <artifactId>hadoop-aws</artifactId>
    <version>3.3.2</version>
</dependency>
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-bundle</artifactId>
    <version>1.12.452</version>
</dependency>
<dependency>
    <groupId>org.apache.iceberg</groupId>
    <artifactId>iceberg-spark-runtime-3.3_2.12</artifactId>
    <version>1.2.1</version>
</dependency>
`
ll I did was read a CSV file from Minio and convert it to an Iceberg table for storage, just like the link I attached above. I also tried writing a regular dataset as an Iceberg table and got the same error.By the way, I have tried it on java/python/spark-sql and reported the same error.

**Comment by nastra** [comment]
Iceberg 1.2.1 uses AWS Bundle 2.20.18. Can you try with that version?

**Comment by andreanerla** [comment]
I actually had the same issue when writing to AWS Glue Data Catalog. The issue was that I didn't specify URI location for the Glue Database.

**Comment by Guaniuzzt** [comment]
("spark.sql.catalog.demo.s3.endpoint", "http://127.0.0.9000")
=========================================
I think your s3 endpoint should be http://127.0.0.1:9000

**Comment by mwullink** [comment]
had the same problem, using rest catalog, s3 , iceberg 1.3.1  and spark 3.4.1
problem was fixed by removing following option:

--conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions

**Comment by nastra** [comment]
> had the same problem, using rest catalog, s3 , iceberg 1.3.1 and spark 3.4.1 problem was fixed by removing following option:
> 
> --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions

People might search for this issue and think that this is a viable solution. This isn't the case and I don't see how this would fix it.

The problem is caused by 
a) mixed AWS SDK versions on the classpath 
b) missing AWS SDK version on the classpath

The solution is to make sure that you're using the correct AWS SDK version for the right Iceberg version, which is mentioned in https://iceberg.apache.org/docs/latest/aws/#spark.

Going forward (starting with Iceberg 1.4.0), Iceberg will provide an `org.apache.iceberg:iceberg-aws-bundle` artifact, which will contain the correct version of the AWS SDK dependencies.

**Comment by mwullink** [comment]
thanks for the info, a iceberg-aws-bundle will make things much easier.

**Comment by umathivagit** [comment]
Dear All, I faced similar issue and found that including Iceberg and Minio official documentation, the samples given are not working , also there is no working found anywhere in internet to enable minio as a storage location to define it as metadata/data files location...Here is the code base (working version) of managing the Iceberg catalog on Minio...there were few issues on the mismatch of iceberg version vs aws bundle and also few more additional options I had to setup to get this working...after successful run you should see the table get created inside the minio like below...

![image](https://github.com/user-attachments/assets/68cfa30f-14b9-4e0c-95df-d1325b27793f)

Also most important thing create access keys in the minio browser (as I have highlighted in the second screen shot click on the icon , it will bring up the access keys and then create access keys those keys are the ones you need to pass it on the below configurations while creating the spark session)

![image](https://github.com/user-attachments/assets/a0f5c49f-2e10-4c3d-9283-d06d63f73981)

.config('spark.hadoop.fs.s3a.access.key', "<<accesskey>>")\
.config('spark.hadoop.fs.s3a.secret.key', "<<secretkey>>")\
Please make sure add below user environment variables as well
AWS_ACCESS_KEY_ID = accesskey
AWS_SECRET_ACCESS_KEY = secretkey
AWS_REGION = us-east-1
MINIO_ROOT_USER = minioadmin
MINIO_ROOT_PASSWORD = minioadmin
MINIO_REGION = us-east-1
This code base stores the catalog into  Postgres and the metadata/data files into minio object storage

**Here is the working code:**

> from pyspark.sql import SparkSession, Row
> 
> 
> ### Initialize Spark session with Iceberg JDBC catalog configuration
> spark = SparkSession.builder \
>     .appName("udaydemo-app") \
>     .config('spark.jars.packages', 'org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.2,org.postgresql:postgresql:42.2.23,org.apache.iceberg:iceberg-aws-bundle:1.5.2') \
>     .config('spark.sql.catalog.uday_minio_catalog','org.apache.iceberg.spark.SparkCatalog')\
>     .config("spark.sql.catalog.uday_minio_catalog.catalog-impl", "org.apache.iceberg.jdbc.JdbcCatalog")\
>     .config("spark.sql.catalog.uday_minio_catalog.uri", "jdbc:postgresql://<<replace your postgres host address>>/<<database name>>") \
>     .config("spark.sql.catalog.uday_minio_catalog.verifyServerCertificate", "true") \
>     .config("spark.sql.catalog.uday_minio_catalog.useSSL", "true") \
>     .config("spark.sql.catalog.uday_minio_catalog.jdbc.user", "<<replace your username>>") \
>     .config("spark.sql.catalog.uday_minio_catalog.jdbc.password", "<<replace your password>>) \
>     .config("spark.sql.catalog.uday_minio_catalog.jdbc.driver", "org.postgresql.Driver") \
>     .config("spark.sql.catalog.uday_minio_catalog.warehouse", "s3a://demo-icare")\
>     .config("spark.sql.catalog.uday_minio_catalog.s3.endpoint","http://127.0.0.1:9000")\
>     .config("spark.sql.catalog.uday_minio_catalog.io-impl", "org.apache.iceberg.aws.s3.S3FileIO")\
>     .config('spark.hadoop.fs.s3a.access.key', "<<minio access key>>")\
>     .config('spark.hadoop.fs.s3a.endpoint.region','us-east-1')\
>     .config("spark.hadoop.fs.s3a.secret.key", "<<minio secret key>>")\
>     .config("spark.sql.catalog.uday_minio_catalog.s3a.path-style-access", "true")\
>     .config("spark.sql.catalogImplementation","in-memory")\
>     .config("spark.executor.heartbeatInterval", "300000")\
>     .config("spark.network.timeout", "400000")\
>     .config("spark.hadoop.fs.s3a.connection.ssl.enabled", "false")\
>     .config("spark.hadoop.fs.s3a.path.style.access", "true")\
>     .config("spark.hadoop.fs.s3a.attempts.maximum", "1")\
>     .config("spark.hadoop.fs.s3a.connection.establish.timeout", "5000")\
>     .config("spark.hadoop.fs.s3a.connection.timeout", "10000")\
>     .getOrCreate()
> 
> sc = spark.sparkContext
> sc.setLogLevel("ERROR")
> 
> ### Create an Iceberg table
> spark.sql("""
>         CREATE TABLE IF NOT EXISTS uday_minio_catalog.product (
>         id INT,
>         name STRING,
>         price INT
>     ) USING iceberg""")
> 
> spark.sql("""
>     INSERT INTO uday_minio_catalog.product VALUES 
>         (1, 'laptop', 50000), 
>         (2, 'workstation', 100000),
>         (3, 'server', 250000)
>     """)
> 
> spark.sql("SELECT * FROM uday_minio_catalog.product").show(truncate=False)
> 
> spark.stop()

**Comment by nastra** [comment]
@umathivagit you might want to look at the Spark [config](https://github.com/tabular-io/docker-spark-iceberg/blob/main/spark/spark-defaults.conf#L23-L29
) that the [Spark quickstart demo](https://iceberg.apache.org/spark-quickstart/) is using. That demo also uses MinIO and you can check the `docker-compose.yml` for what settings are required
