### ISSUE TITLE
Issue while connecting with Local Spark. 

### ISSUE THREAD

**Issue by mayurchoubey** [apache/iceberg#7490]
### Apache Iceberg version

1.2.1 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

    Aborting task java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/apache/iceberg/aws/s3/signer/S3ObjectMapper.initModule()Lorg/apache/iceberg/shaded/com/fasterxml/jackson/databind/module/SimpleModule; @16: invokevirtual
  Reason:
    Type 'org/apache/iceberg/rest/RESTSerializers$ErrorResponseSerializer' (current frame, stack[2]) is not assignable to 'org/apache/iceberg/shaded/com/fasterxml/jackson/databind/JsonSerializer'
  Current Frame:
    bci: @16
    flags: { }
    locals: { }
    stack: { 'org/apache/iceberg/shaded/com/fasterxml/jackson/databind/module/SimpleModule', 'java/lang/Class', 'org/apache/iceberg/rest/RESTSerializers$ErrorResponseSerializer' }
  Bytecode:
    0000010: b600 6e12 69bb 001d 59b7 006f b600 7312
    0000020: 75bb 0020 59b7 0076 b600 6e12 75bb 0023
    0000030: 59b7 0077 b600 7312 79bb 0010 59b7 007a
    0000040: b600 6e12 7cbb 0010 59b7 007a b600 6e12
    0000050: 79bb 000d 59b7 007d b600 7312 7cbb 000d
    0000060: 59b7 007d b600 7312 7fbb 000a 59b7 0080
    0000070: b600 6e12 82bb 000a 59b7 0080 b600 6e12
    0000080: 7fbb 0007 59b7 0083 b600 7312 82bb 0007
    0000090: 59b7 0083 b600 73b0                    
	at org.apache.iceberg.aws.s3.signer.S3V4RestSignerClient.httpClient(S3V4RestSignerClient.java:177) ~[iceberg-spark-runtime-3.3_2.13-1.2.1.jar:?]
	at org.apache.iceberg.aws.s3.signer.S3V4RestSignerClient.sign(S3V4RestSignerClient.java:301) ~[iceberg-spark-runtime-3.3_2.13-1.2.1.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.SigningStage.lambda$signRequest$0(SigningStage.java:71) ~[sdk-core-2.20.20.jar:?]
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDuration(MetricUtils.java:50) ~[sdk-core-2.20.20.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.SigningStage.signRequest(SigningStage.java:70) ~[sdk-core-2.20.20.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.SigningStage.execute(SigningStage.java:55) ~[sdk-core-2.20.20.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.SigningStage.execute(SigningStage.java:40) ~[sdk-core-2.20.20.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.20.20.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.20.20.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.20.20.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.20.20.jar:?

**Comment by mayurchoubey** [comment]
Here are the version of the jars :  
**implementation 'org.apache.iceberg:iceberg-core:1.2.1'
implementation 'org.apache.iceberg:iceberg-spark-runtime-3.3_2.13:1.2.1'
implementation 'software.amazon.awssdk:bundle:2.20.18'
implementation 'software.amazon.awssdk:url-connection-client:2.20.18'**

**Comment by nastra** [comment]
@mayurchoubey are you running plain Spark with those dependencies or is that a Java application that uses those dependencies? You shouldn't need `org.apache.iceberg:iceberg-core:1.2.1` as that is already included in `org.apache.iceberg:iceberg-spark-runtime-3.3_2.13:1.2.1`

**Comment by nastra** [comment]
I was talking offline with @mayurchoubey and the issue ended up being mixed AWS SDK library versions on the classpath. 
In order to fix the issue, it was required to specify each AWS SDK library individually rather than using the `bundle` jar.

```
    implementation 'org.apache.iceberg:iceberg-spark-runtime-3.3_2.13:1.2.1'

    // force awssdk version required by Iceberg
    implementation "software.amazon.awssdk:utils:2.20.18"
    implementation "software.amazon.awssdk:url-connection-client:2.20.18"
    implementation "software.amazon.awssdk:s3:2.20.18"
    implementation "software.amazon.awssdk:glue:2.20.18"
    implementation "software.amazon.awssdk:dynamodb:2.20.18"
    implementation "software.amazon.awssdk:kms:2.20.18"
    implementation "software.amazon.awssdk:sts:2.20.18"
    implementation "software.amazon.awssdk:sdk-core:2.20.18"
    implementation "software.amazon.awssdk:aws-core:2.20.18"
```
