### ISSUE TITLE
When transforming partition values exists, writing using upsert mode failed

### ISSUE THREAD

**Issue by zhaomin1423** [apache/iceberg#7550]
### Apache Iceberg version

1.2.1 (latest release)

### Query engine

Flink

### Please describe the bug 🐞

Spark DDL:

```
CREATE TABLE spark_catalog.db.demo (
    id bigint,
    data string,
    category string,
    ts bigint)
USING iceberg
PARTITIONED BY (bucket(16, id), category)
TBLPROPERTIES ('format-version'='2');
```
Exception information when writing  it with upsert mode.
```
java.lang.IllegalStateException: In UPSERT mode, partition field '1000: id_bucket: bucket[16](1)' should be included in equality fields: '[category]'

	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkState(Preconditions.java:821)
	at org.apache.iceberg.flink.sink.FlinkSink$Builder.appendWriter(FlinkSink.java:455)
	at org.apache.iceberg.flink.sink.FlinkSink$Builder.chainIcebergOperators(FlinkSink.java:358)
	at org.apache.iceberg.flink.sink.FlinkSink$Builder.append(FlinkSink.java:374)
```

**Comment by pvary** [comment]
Isn't the issue is the other way around? Shouldn't the Identity columns contain the `id` column?

**Comment by zhaomin1423** [comment]
> Isn't the issue is the other way around? Shouldn't the Identity columns contain the `id` column?

Thank you, it was my mistake that caused it.
