### ISSUE TITLE
java.lang.RuntimeException: Metastore operation failed error reason

### ISSUE THREAD

**Issue by figo10203** [apache/iceberg#791]
Hi guys, I'm new to apache iceberg.
When I want to create a table with hive like below. 

val catalog = new HiveCatalog(spark.sessionState.newHadoopConf())

  val name = TableIdentifier.of("default", "logs")
  val schema = new Schema(
    NestedField.required(1, "level", StringType.get()),
    NestedField.required(2, "event_time", DateType.get()),
    NestedField.required(3, "message", StringType.get()))

  val table = catalog.createTable(name, schema)

then an error happen, could you please help me out for this issue, I didn't
set any hive transaction conf.  Thanks a lot!

java.lang.RuntimeException: Metastore operation failed for default.logs1
  at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:186)
  at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:102)
  at org.apache.iceberg.BaseMetastoreCatalog.createTable(BaseMetastoreCatalog.java:67)
  at org.apache.iceberg.hive.HiveCatalog.createTable(HiveCatalog.java:60)
  at org.apache.iceberg.catalog.Catalog.createTable(Catalog.java:84)
  ... 49 elided
Caused by: org.apache.thrift.TApplicationException: Internal error processing lock
  at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
  at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
  at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_lock(ThriftHiveMetastore.java:3906)
  at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.lock(ThriftHiveMetastore.java:3893)
  at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.lock(HiveMetaStoreClient.java:1863)
  at org.apache.iceberg.hive.HiveTableOperations.lambda$acquireLock$5(HiveTableOperations.java:243)
  at org.apache.iceberg.hive.ClientPool.run(ClientPool.java:56)
  at org.apache.iceberg.hive.HiveTableOperations.acquireLock(HiveTableOperations.java:243)
  at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:131)
  ... 53 more

**Comment by rdsr** [comment]
@figo10203, there could be an exception in your Metastore logs. We should also check that for clues.

**Comment by figo10203** [comment]
thank you. @rdsr can I know what's the location of Metastore logs in linux system?

**Comment by figo10203** [comment]
Hi @rdsr, I found an underlying error in hive.log which is below:

![image](https://user-images.githubusercontent.com/12635964/74485209-19d5cd80-4e6f-11ea-8122-2f26a007c390.png)

So why it happend. there is no "hl_agent_info" column in my hive table. why iceberg check it?

**Comment by rdsr** [comment]
I think that error is coming from the under DB backing the Metastore.  I'd check to see if your Hive setup is operational as is even before using Iceberg

**Comment by figo10203** [comment]
hi @rdsr , I am using EMR. hive can work for other query. How can I check then?

**Comment by figo10203** [comment]
hi @rdsr, still not clear what do you mean by "backing" the metastore?

**Comment by pvary** [comment]
I think this issue is a duplicate of #798
@figo10203: Could you please check my comment there?

Thanks,
Peter
