### ISSUE TITLE
can not create iceberg table by hive catalog in emr with maridb

### ISSUE THREAD

**Issue by figo10203** [apache/iceberg#798]
Hi everyone,
when I use HiveCatalog to create hive table in EMR 5.29.

val catalog = new **HiveCatalog**(spark.sessionState.newHadoopConf())
val schema = SparkSchemaUtil.convert(spark.table("agg_user_retention_weekly_500GB_table").schema) 

  val up_iceberg_path = "s3://nikebi-managed/prod/dcu-dev/iceberg/iceberg_500g"
  **val table = catalog.create(schema, null, up_iceberg_path)**

 It keeps going wrong with below dscription:
java.lang.RuntimeException: Metastore operation failed for default.agg_user_retention_weekly_iceberg_1TB_table1
  at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:186)
  at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:102)
  at org.apache.iceberg.BaseMetastoreCatalog.createTable(BaseMetastoreCatalog.java:67)
  at org.apache.iceberg.hive.HiveCatalog.createTable(HiveCatalog.java:60)
  at org.apache.iceberg.catalog.Catalog.createTable(Catalog.java:84)
  ... 49 elided
Caused by: org.apache.thrift.TApplicationException: Internal error processing lock
  at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
  at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
  at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_lock(ThriftHiveMetastore.java:3906)
  at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.lock(ThriftHiveMetastore.java:3893)
  at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.lock(HiveMetaStoreClient.java:1863)
  at org.apache.iceberg.hive.HiveTableOperations.lambda$acquireLock$5(HiveTableOperations.java:243)
  at org.apache.iceberg.hive.ClientPool.run(ClientPool.java:56)
  at org.apache.iceberg.hive.HiveTableOperations.acquireLock(HiveTableOperations.java:243)
  at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:131)
  ... 53 more

Caused by: java.sql.SQLException: Unknown column '**hl_agent_info**' in 'field list'
Query is: insert into **HIVE_LOCKS** (hl_lock_ext_id, hl_lock_int_id, hl_txnid, hl_db, hl_table, hl_partition,hl_lock_state, hl_locki
type, hl_last_heartbeat, hl_user, hl_host, hl_agent_info) values(3773, 1,0, 'default', 'agg_user_retention_weekly_iceberg_1TB_ta
le1', null, 'w', 'e', 1581838637000, 'rfeng1', 'ip-10-233-4-125', 'Unknown')                                                    i
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:119)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:198)
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:328)                                         3
        ... 25 more
                                                                                                                                3
        at org.apache.hadoop.hive.metastore.txn.TxnHandler.enqueueLockWithRetry(TxnHandler.java:1080) ~[hive-exec-2.3.4-amzn-0.j
r:2.3.4-amzn-0]
        at org.apache.hadoop.hive.metastore.txn.TxnHandler.lock(TxnHandler.java:872) ~[hive-exec-2.3.4-amzn-0.jar:2.3.4-amzn-0]
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.lock(HiveMetaStore.java:6364) ~[hive-exec-2.3.4-amzn-0.jar:?
.3.4-amzn-0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]                                           2
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]                 2
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invokeInternal(RetryingHMSHandler.java:148) ~[hive-exec-2.3.4-amz
-0.jar:2.3.4-amzn-0]
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invoke(RetryingHMSHandler.java:107) ~[hive-exec-2.3.4-amzn-0.

I don't know why **maridb** will do this operation and EMR by default doesn't open hive transaction. Can somebody please help me out? 

Thanks in advance.

**Comment by pvary** [comment]
Most probably EMR uses Hive where the HIVE_LOCK table schema not synched with the code. Most probably this not causes problems for EMR because it does not uses DBLockManager or Locking at all.
On the other hand Iceberg uses locks and tries to use the tables. Since the schema is not correct. It fails.

Could you please try it with a more recent version of EMR and check if the issues still exists?

Thanks,
Peter

**Comment by pvary** [comment]
@figo10203: Could we close this issue as abandoned? Or is this problem still exists?

Thanks,
Peter
