### ISSUE TITLE
Can not parse sort order when there are more than one sql extensions specified and iceberg extension is not placed at the right most position

### ISSUE THREAD

**Issue by puchengy** [apache/iceberg#8004]
### Apache Iceberg version

1.3.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

running data file rewrite with sort option and encountered 
```
java.lang.IllegalStateException: Cannot parse order: parser is not an Iceberg ExtendedParser
	at org.apache.iceberg.spark.ExtendedParser.parseSortOrder(ExtendedParser.java:64)
	at org.apache.iceberg.spark.procedures.RewriteDataFilesProcedure.checkAndApplyStrategy(RewriteDataFilesProcedure.java:160)
	at org.apache.iceberg.spark.procedures.RewriteDataFilesProcedure.lambda$call$0(RewriteDataFilesProcedure.java:111)
	at org.apache.iceberg.spark.procedures.BaseProcedure.execute(BaseProcedure.java:100)
	at org.apache.iceberg.spark.procedures.BaseProcedure.modifyIcebergTable(BaseProcedure.java:81)
	at org.apache.iceberg.spark.procedures.RewriteDataFilesProcedure.call(RewriteDataFilesProcedure.java:100)
```

This is due to there are more than one sql extensions specified
```
spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,x.y.secondExtensions
```

Line that broke

https://github.com/apache/iceberg/blob/1f1ec4be478feae79b04bcea3e9a8556d8076054/spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/ExtendedParser.java#L55

The current workaround is always place iceberg extension on the right most position.

**Comment by ajantha-bhat** [comment]
Yeah, this problem is only for sort order parsing of REWRITE call procedure because Iceberg uses some custom parsing code to parse sort order as of now. 

From spark, parser from rightmost position extension will be the main parser. if it fails to parse it, it will pass to other parser that it wraps and so on. But in case of custom parser logic, this passing logic cannot be implemented as the interface is not standard.
