### ISSUE TITLE
Athena could not read iceberg table created by pyiceberg with glue catalog

### ISSUE THREAD

**Issue by ktk1012** [apache/iceberg#8013]
### Apache Iceberg version

1.3.0 (latest release)

### Query engine

Athena

### Please describe the bug 🐞

pyiceberg version: 0.4.0

Athena query runs indefinitely on table which created by pyiceberg

Below code creates test iceberg table in glue data catalog. And than, running any query on athena console shows loading indicator indefinitely. I'm working on athena engine version 3

 ---
```python
from pyiceberg import partitioning, schema, transforms, types
from pyiceberg.table import sorting
from pyiceberg.catalog import load_catalog

_target_table_schema = schema.Schema(
    types.NestedField(
        1,
        "id",
        types.LongType(),
        True,
    ),
    types.NestedField(
        2,
        "timestamp",
        types.TimestampType(),
        True,
    ),
    types.NestedField(
        3,
        "block_hash",
        types.StringType(),
        True,
    ),
    types.NestedField(
        4,
        "external",
        types.BooleanType(),
        True,
    ),
)

_target_table_partition = partitioning.PartitionSpec(
    partitioning.PartitionField(
        1,
        1000,
        transforms.TruncateTransform(10000),
        name="id_trunc_10000",
    ))

_target_table_sort_order = sorting.SortOrder(
    sorting.SortField(
        1,
        transforms.IdentityTransform(),
        sorting.SortDirection.ASC,
    ),
    sorting.SortField(
        2,
        transforms.IdentityTransform(),
        sorting.SortDirection.ASC,
    ),
)

glue_catalog = load_catalog("glue", type='glue')

glue_catalog.create_table(
    identifier = ("test_database", "test_table"),
    schema=_target_table_schema,
    location="s3://<some_location>",  # Speicify some s3 location
    partition_spec=_target_table_partition,
    sort_order=_target_table_sort_order
)
```

**Comment by ktk1012** [comment]
With further investigation, I figured out that engine throws error due to missing `current-snapshot-id`.

From v2 format [spec](https://iceberg.apache.org/spec/#table-metadata) is optional, but engine mandate `current-snapshot-id`.
Also even spark also throws similar error. Is it valid behavior?

```
23/07/09 14:54:32 WARN Tasks: Retrying task after failure: Cannot parse missing long: current-snapshot-id
java.lang.IllegalArgumentException: Cannot parse missing long: current-snapshot-id
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
	at org.apache.iceberg.util.JsonUtil.getLong(JsonUtil.java:133)
	at org.apache.iceberg.TableMetadataParser.fromJson(TableMetadataParser.java:436)
	at org.apache.iceberg.TableMetadataParser.fromJson(TableMetadataParser.java:303)
	at org.apache.iceberg.TableMetadataParser.read(TableMetadataParser.java:273)
	at org.apache.iceberg.TableMetadataParser.read(TableMetadataParser.java:266)
	at org.apache.iceberg.BaseMetastoreTableOperations.lambda$refreshFromMetadataLocation$0(BaseMetastoreTableOperations.java:189)
	at org.apache.iceberg.BaseMetastoreTableOperations.lambda$refreshFromMetadataLocation$1(BaseMetastoreTableOperations.java:208)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413)
	at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203)
	at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
```

**Comment by ktk1012** [comment]
I'll close this issue, #8050 will resolve it.
