### ISSUE TITLE
remove_orphan_files throws reached maximum depth exception  in AWS EMR-6.11.0

### ISSUE THREAD

**Issue by ganeshkumar269** [apache/iceberg#8022]
### Apache Iceberg version

1.2.0

### Query engine

Spark

### Please describe the bug 🐞

calling remove_orphan_files procedure via SparkSQL in emr-6.11.0 on a table that has delete files throws the following exception
```sql
CALL <catalog>.system.remove_orphan_files( table => '<table_name>')
```
`
Caused by: java.lang.RuntimeException: Could not list sub directories, reached maximum depth: 2000
	at org.apache.iceberg.spark.actions.DeleteOrphanFilesSparkAction$ListDirsRecursively.call(DeleteOrphanFilesSparkAction.java:473)
	at org.apache.iceberg.spark.actions.DeleteOrphanFilesSparkAction$ListDirsRecursively.call(DeleteOrphanFilesSparkAction.java:437)
	at org.apache.spark.api.java.JavaRDDLike.$anonfun$mapPartitions$1(JavaRDDLike.scala:153)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:855)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:855)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.rdd.UnionRDD.compute(UnionRDD.scala:106)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:138)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1516)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
`

after debugging a little, I have found the root cause to be this part of the code which is in DeleteOrphanFilesSparkAction.listDirRecursively:356 (iceberg-1.2.0)
```java
for (FileStatus file : fs.listStatus(path, pathFilter)) {
  if (file.isDirectory()) {
    subDirs.add(file.getPath().toString());
  } else if (file.isFile() && predicate.test(file)) {
    matchingFiles.add(file.getPath().toString());
  }
}
```
fs.listStatus on s3://<parent_prefix>/data directory returns the same s3://<parent_prefix>/data directory as part of the result, thus forming a recursive loop until reaching the max depth of 2000. 

Just to be sure I ran the fs.listStatus separately on EMR machine for two paths, s3://<parent_prefix>/data and s3://<parent_prefix>/metadata.
s3://<parent_prefix>/metadata does not return itself in the result, but s3://<parent_prefix>/data does. upon further inspection, I figured this could be due to the presence of delete files in the s3://<parent_prefix>/data directory which are located in s3://<parent_prefix>/data// prefix on s3. I tried running remove_orphan_files procedure on a table with no delete files and it was completed successfully.

I have observed this only on EMR, running locally works as expected.

**Comment by przemekd** [comment]
@ganeshkumar269 I've observed the same. One workaround for that might be to use the hadoop s3 file system implementation:
 ```
 --conf spark.hadoop.fs.s3.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
 ```
Seems that this non-POSIX compatible path problem (#6758) is solved for metadata files already (#6777), but not for data files (#6772).
