### ISSUE TITLE
how to create iceberg hive catalog-type catalog in flink with kerberos

### ISSUE THREAD

**Issue by ztqchn** [apache/iceberg#8213]
### Query engine

Flink

### Question

when my program already login kerberos, I can create normal hive catalog and hive tables can be seen,
this time I use flinksql like
"CREATE CATALOG iceberg WITH ( 
'type'='iceberg', 
'catalog-type'='hive', 
'uri'='thrift://100.116.3.226:9083', 
'clients'='5', 
'property-version'='1', 
'warehouse'='hdfs://xxx/data/iceberg_catalog_warehouse','hive-conf-dir'='xxx/conf'
)"
to create iceberg catalog, it will failed because of 

java.lang.RuntimeException: Failed to create namespace default in Hive Metastore
	at org.apache.iceberg.hive.HiveCatalog.createNamespace(HiveCatalog.java:281)
	at org.apache.iceberg.flink.FlinkCatalog.createDatabase(FlinkCatalog.java:204)
	at org.apache.iceberg.flink.FlinkCatalog.open(FlinkCatalog.java:121)
	at org.apache.flink.table.catalog.CatalogManager.registerCatalog(CatalogManager.java:211)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.createCatalog(TableEnvironmentImpl.java:1471)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1212)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:765)
	at FlinkEngIcebergTest.createTable(FlinkEngIcebergTest.java:97)
	at FlinkEngIcebergTest.beforeClass(FlinkEngIcebergTest.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.apache.thrift.transport.TTransportException
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_database(ThriftHiveMetastore.java:741)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_database(ThriftHiveMetastore.java:728)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createDatabase(HiveMetaStoreClient.java:800)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:150)
	at com.sun.proxy.$Proxy8.createDatabase(Unknown Source)
	at org.apache.iceberg.hive.HiveCatalog.lambda$createNamespace$8(HiveCatalog.java:270)
	at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:58)
	at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:51)
	at org.apache.iceberg.hive.CachedClientPool.run(CachedClientPool.java:76)
	at org.apache.iceberg.hive.HiveCatalog.createNamespace(HiveCatalog.java:269)
	... 26 more

I can't find document about  how to create flink iceberg catalog with kerberos environment, would you like to help me about this problem?

**Comment by nastra** [comment]
For setting up Flink with Kerberos you might want to take a look at the Flink docs [here](https://nightlies.apache.org/flink/flink-docs-release-1.17/docs/deployment/security/security-kerberos/). Iceberg itself doesn't do anything special for Kerberos, so it is up to how you configure Flink in this case.

**Comment by pvary** [comment]
@HuiHang-Yu: The correct Flonk catalog configuration is documented in the [doc](https://iceberg.apache.org/docs/1.5.0/flink/#catalog-configuration)s. Kerberos configuration should be done through the Flink Kerberos configuration.

**Comment by zhouchitc** [comment]
@ztqchn I think you should add <hive-conf-dir> when using kerberos, like:
CREATE CATALOG hive_catalog WITH (
  'type'='iceberg',
  'catalog-type'='hive',
  'uri'='thrift://xxxxxx:9083',
  'clients'='2',
  'property-version'='1',
  'hive-conf-dir'='/local-hiveconf/',
  'warehouse'='hdfs:///warehouse/hive'
);

Btw, I put hive-site.xml in /local-hiveconf/hive-site.xml. If I set hive-conf-dir=hdfs:///hive-conf, there would be a problem that “cant find hive-site.xml”.
