### ISSUE TITLE
upgrade iceberg from 0.14.1 to 1.2.1, flink task error with InvalidClassException: org.apache.iceberg.BaseFileScanTask; local class incompatible: stream classdesc serialVersionUID = -4104519524386879586, local class serialVersionUID = -4407317454711722253

### ISSUE THREAD

**Issue by chenwyi2** [apache/iceberg#8220]
### Apache Iceberg version

1.2.1

### Query engine

Flink

### Please describe the bug 🐞

when i upgrade iceberg from 0.14.1 to 1.2.1, use flink 1.1.5, some task failed with "InvalidClassException: org.apache.iceberg.BaseFileScanTask; local class incompatible: stream classdesc serialVersionUID = -4104519524386879586, local class serialVersionUID = -4407317454711722253", the more detail is below. 
Caused by: java.io.InvalidClassException: org.apache.iceberg.BaseFileScanTask; local class incompatible: stream classdesc serialVersionUID = -4104519524386879586, local class serialVersionUID = -4407317454711722253
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1885) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1975) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1567) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) ~[?:1.8.0_202]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431) ~[?:1.8.0_202]
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:617) ~[flink-dist-1.15.0.jar:1.15.0]
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:602) ~[flink-dist-1.15.0.jar:1.15.0]
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:589) ~[flink-dist-1.15.0.jar:1.15.0]
	at org.apache.iceberg.flink.source.split.IcebergSourceSplit.deserializeV1(IcebergSourceSplit.java:117) ~[flink-catalog-connector-iceberg-hive3-2.0.3-SNAPSHOT.jar:?]
	at org.apache.iceberg.flink.source.split.IcebergSourceSplitSerializer.deserialize(IcebergSourceSplitSerializer.java:50) ~[flink-catalog-connector-iceberg-hive3-2.0.3-SNAPSHOT.jar:?]
	at org.apache.iceberg.flink.source.split.IcebergSourceSplitSerializer.deserialize(IcebergSourceSplitSerializer.java:31) ~[flink-catalog-connector-iceberg-hive3-2.0.3-SNAPSHOT.jar:?]
	at org.apache.flink.core.io.SimpleVersionedSerialization.readVersionAndDeSerialize(SimpleVersionedSerialization.java:227) ~[flink-dist-1.15.0.jar:1.15.0]
wu should specify explicitly serialVersionUID in Serializable or subclass?

**Comment by ConeyLiu** [comment]
It should be caused by restoring jobs from the state. @stevenzwu should this be fixed by #1698?

**Comment by chenwyi2** [comment]
@stevenzwu #1698 can be compatible with previous versions? if i used java Serializable in checkpoint state before, then cherry up this patch, and restart job, the job can running successfully？

**Comment by chenwyi2** [comment]
> It should be caused by restoring jobs from the state. @stevenzwu should this be fixed by #1698?

#1698 can be compatible with previous versions? if i used java Serializable in checkpoint state before, then cherry up this patch, and restart job, the job can running successfully？
