### ISSUE TITLE
The need for adding hadoop-aws dependencies for `add_files` procedure

### ISSUE THREAD

**Issue by tj---** [apache/iceberg#8322]
### Query engine

**Spark**
Using the [quick-start](https://iceberg.apache.org/spark-quickstart/) guide, I am adding Parquet files (in MinIO) to an Iceberg table.

### Question

Unless the hadoop-aws dependencies are added (as mentioned in the [Hadoop S3A FileSystem](https://iceberg.apache.org/docs/latest/aws/#hadoop-s3a-filesystem) reference), `add_files` procedure continues to fail.
**Question**: Can this function without the aws v1 dependencies being added (`aws sdk v2` bundle is already present)?

This is the stack trace:
```
java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at org.apache.spark.sql.execution.streaming.FileStreamSink$.ancestorIsMetadataDirectory(FileStreamSink.scala:104)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.$anonfun$rootPaths$1(InMemoryFileIndex.scala:62)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.$anonfun$rootPaths$1$adapted(InMemoryFileIndex.scala:62)
	at scala.collection.immutable.Stream.filterImpl(Stream.scala:506)
	at scala.collection.immutable.Stream.filterImpl(Stream.scala:204)
	at scala.collection.TraversableLike.filterNot(TraversableLike.scala:403)
	at scala.collection.TraversableLike.filterNot$(TraversableLike.scala:403)
	at scala.collection.AbstractTraversable.filterNot(Traversable.scala:108)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.<init>(InMemoryFileIndex.scala:62)
	at org.apache.iceberg.spark.Spark3Util.getPartitions(Spark3Util.java:872)
	at org.apache.iceberg.spark.procedures.AddFilesProcedure.importFileTable(AddFilesProcedure.java:177)
```

**Comment by nastra** [comment]
@tj--- could you please share your full catalog configuration and the exact command you're running with the full stack trace?

**Comment by tj---** [comment]
Sure. 

<details>
<summary>The Rest Catalog configuration (click to expand...)</summary>

```
Map<String, String> properties = new HashMap<>();

properties.put(CatalogProperties.CATALOG_IMPL, "org.apache.iceberg.rest.RESTCatalog");
properties.put(CatalogProperties.URI, "http://rest:8181");
properties.put(CatalogProperties.WAREHOUSE_LOCATION, "s3a://warehouse/wh");
properties.put(CatalogProperties.FILE_IO_IMPL, "org.apache.iceberg.aws.s3.S3FileIO");
properties.put(AwsProperties.S3FILEIO_ENDPOINT, "http://minio:9000");


RESTCatalog catalog = new RESTCatalog();
Configuration conf = new Configuration();
catalog.setConf(conf);
catalog.initialize("demo", properties);
catalog.name();
```
</details>

<details>
<summary>Spark config (click to expand...)</summary>

```
SparkSession spark = SparkSession
  .builder()
  .master("local[*]")
  .appName("Java API Demo")
  .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
  .config("spark.sql.catalog.demo", "org.apache.iceberg.spark.SparkCatalog")
  .config("spark.sql.catalog.demo.catalog-impl", "org.apache.iceberg.rest.RESTCatalog")
  .config("spark.sql.catalog.demo.uri", "http://rest:8181")
  .config("spark.sql.catalog.demo.io-impl", "org.apache.iceberg.aws.s3.S3FileIO")
  .config("spark.sql.catalog.demo.s3.endpoint", "http://minio:9000")
  .config("spark.sql.catalog.demo.s3a.endpoint", "http://minio:9000")
  .config("spark.sql.defaultCatalog", "demo")
  .config("spark.eventLog.enabled", "true")
  .config("spark.eventLog.dir", "/home/iceberg/spark-events")
  .config("spark.history.fs.logDirectory", "/home/iceberg/spark-events")
  .config("spark.hadoop.fs.s3a.endpoint", "http://minio:9000")
  .config("spark.hadoop.fs.s3a.access.key", "<Access_Key>")
  .config("spark.hadoop.fs.s3a.secret.key", "<Secret>")
  .config("spark.hadoop.fs.s3a.path.style.access", "true")
  .config("spark.hadoop.fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
  // The equivalent s3 configs seem to be necessary for Spark procedure calls
  // as it throws this error "org.apache.iceberg.exceptions.RuntimeIOException: Failed to get file system for path: s3:"
  .config("spark.hadoop.fs.s3.endpoint", "http://minio:9000")
  .config("spark.hadoop.fs.s3.access.key", "<Access_Key>")
  .config("spark.hadoop.fs.s3.secret.key", "<Secret>")
  .config("spark.hadoop.fs.s3.path.style.access", "true")
  .config("spark.hadoop.fs.s3.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
  .getOrCreate();
```
</details>

Relevant call:
```
String query = "CALL demo.system.add_files("
             + "table => 'demo.nyc.logs4'"
             + ",source_table => '`avro`.`s3a://warehouse/foo2`'"
             + ",check_duplicate_files => false"
             + ")";

spark.sql(query).show()
```
<details>
<summary>Complete stack trace (click to expand...)</summary>

```
ANTLR Tool version 4.8 used for code generation does not match the current runtime version 4.9.3
ANTLR Tool version 4.8 used for code generation does not match the current runtime version 4.9.3
---------------------------------------------------------------------------
java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at org.apache.spark.sql.execution.streaming.FileStreamSink$.ancestorIsMetadataDirectory(FileStreamSink.scala:104)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.$anonfun$rootPaths$1(InMemoryFileIndex.scala:62)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.$anonfun$rootPaths$1$adapted(InMemoryFileIndex.scala:62)
	at scala.collection.immutable.Stream.filterImpl(Stream.scala:506)
	at scala.collection.immutable.Stream.filterImpl(Stream.scala:204)
	at scala.collection.TraversableLike.filterNot(TraversableLike.scala:403)
	at scala.collection.TraversableLike.filterNot$(TraversableLike.scala:403)
	at scala.collection.AbstractTraversable.filterNot(Traversable.scala:108)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.<init>(InMemoryFileIndex.scala:62)
	at org.apache.iceberg.spark.Spark3Util.getPartitions(Spark3Util.java:872)
	at org.apache.iceberg.spark.procedures.AddFilesProcedure.importFileTable(AddFilesProcedure.java:177)
	at org.apache.iceberg.spark.procedures.AddFilesProcedure.lambda$importToIceberg$0(AddFilesProcedure.java:148)
	at org.apache.iceberg.spark.procedures.BaseProcedure.execute(BaseProcedure.java:104)
	at org.apache.iceberg.spark.procedures.BaseProcedure.modifyIcebergTable(BaseProcedure.java:85)
	at org.apache.iceberg.spark.procedures.AddFilesProcedure.importToIceberg(AddFilesProcedure.java:139)
	at org.apache.iceberg.spark.procedures.AddFilesProcedure.call(AddFilesProcedure.java:114)
	at org.apache.spark.sql.execution.datasources.v2.CallExec.run(CallExec.scala:34)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:118)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:195)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:103)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:827)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:65)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:94)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:512)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:104)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:512)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:488)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:94)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:81)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:79)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:219)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:827)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:640)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:827)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:630)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:671)
	at .(#32:1)
```

</details>

**Comment by nastra** [comment]
The problem is that you specify HDFS-related settings that you don't need. You can remove all of the `spark.hadoop.fs` settings.
All you need is this:
```
  .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
  .config("spark.sql.catalog.demo", "org.apache.iceberg.spark.SparkCatalog")
  .config("spark.sql.catalog.demo.catalog-impl", "org.apache.iceberg.rest.RESTCatalog")
  .config("spark.sql.catalog.demo.uri", "http://rest:8181")
  .config("spark.sql.catalog.demo.io-impl", "org.apache.iceberg.aws.s3.S3FileIO")
  .config("spark.sql.catalog.demo.s3.endpoint", "http://minio:9000")
  .config("spark.sql.defaultCatalog", "demo")
  .config("spark.sql.catalog.demo.warehouse", "...")
```
Note that I added `spark.sql.catalog.demo.warehouse` above, because that was missing.

Once you removed those, change your warehouse location to not use `s3a` but just `s3`. 


> Question: Can this function without the aws v1 dependencies being added (aws sdk v2 bundle is already present)?
You shouldn't need AWS SDK V1 dependencies. Only the AWS SDK V2 dependencies are required (`2.20.18`).

**Comment by tj---** [comment]
Thanks for the help, Eduard. However, I guess I am missing something here. I had put in those Hadoop-related configs as this config (alone) was leading to errors. Here are details:

<details>
<summary>Spark config (with only the sql configs)</summary>

```
import org.apache.spark.sql.SparkSession;

SparkSession spark = SparkSession
  .builder()
  .master("local[*]")
  .appName("Java API Demo")
  .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
  .config("spark.sql.catalog.demo", "org.apache.iceberg.spark.SparkCatalog")
  .config("spark.sql.catalog.demo.catalog-impl", "org.apache.iceberg.rest.RESTCatalog")
  .config("spark.sql.catalog.demo.uri", "http://rest:8181")
  .config("spark.sql.catalog.demo.io-impl", "org.apache.iceberg.aws.s3.S3FileIO")
  .config("spark.sql.catalog.demo.s3.endpoint", "http://minio:9000")
  .config("spark.sql.defaultCatalog", "demo")
  .config("spark.sql.catalog.demo.warehouse", "s3://warehouse/")
  .getOrCreate();
```
</details>

<details>
<summary>Stack trace of the resulting failure</summary>

```
---------------------------------------------------------------------------
org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "s3"
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3443)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at org.apache.spark.sql.execution.streaming.FileStreamSink$.ancestorIsMetadataDirectory(FileStreamSink.scala:104)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.$anonfun$rootPaths$1(InMemoryFileIndex.scala:62)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.$anonfun$rootPaths$1$adapted(InMemoryFileIndex.scala:62)
	at scala.collection.immutable.Stream.filterImpl(Stream.scala:506)
	at scala.collection.immutable.Stream.filterImpl(Stream.scala:204)
	at scala.collection.TraversableLike.filterNot(TraversableLike.scala:403)
	at scala.collection.TraversableLike.filterNot$(TraversableLike.scala:403)
	at scala.collection.AbstractTraversable.filterNot(Traversable.scala:108)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.<init>(InMemoryFileIndex.scala:62)
	at org.apache.iceberg.spark.Spark3Util.getPartitions(Spark3Util.java:872)
	at org.apache.iceberg.spark.procedures.AddFilesProcedure.importFileTable(AddFilesProcedure.java:177)
	at org.apache.iceberg.spark.procedures.AddFilesProcedure.lambda$importToIceberg$0(AddFilesProcedure.java:148)
	at org.apache.iceberg.spark.procedures.BaseProcedure.execute(BaseProcedure.java:104)
	at org.apache.iceberg.spark.procedures.BaseProcedure.modifyIcebergTable(BaseProcedure.java:85)
	at org.apache.iceberg.spark.procedures.AddFilesProcedure.importToIceberg(AddFilesProcedure.java:139)
	at org.apache.iceberg.spark.procedures.AddFilesProcedure.call(AddFilesProcedure.java:114)
	at org.apache.spark.sql.execution.datasources.v2.CallExec.run(CallExec.scala:34)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:118)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:195)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:103)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:827)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:65)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:94)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:512)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:104)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:512)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:488)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:94)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:81)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:79)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:219)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:827)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:640)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:827)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:630)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:671)
	at .(#18:1)
```

</details>

**Comment by nastra** [comment]
The problem is most likely `source_table => '`parquet`.`s3://warehouse/foo2`'` because there's currently no setting that would indicate which FileIO to use for this and so it can't read the parquet file from S3.

A workaround would be to copy that file to your local file system and then use that local path.

**Comment by tj---** [comment]
I am trying to evaluate the use of existing Parquet files (or Hive table) for reading them through Iceberg tables. If I copy them to a local path, it would beat the purpose of using the existing files without actually ingesting them.
I have a workaround (adding the Hadoop-related configs and th) which requires additional jars but was wondering if something can be done without that.

**Comment by RussellSpitzer** [comment]
I think one of the issues here is that Add_files doesn't use FileIO to actually list files. It uses HadoopFS so we would need the hadoop libs. Now that we have "listPrefix" support though we can potentially remove that dependency if a FileIO is configured with prefix support. We have the same issue in RemoveOrphans cc: @anuragmantri

**Comment by hpylypets-ua** [comment]
So what's the plan to fix this or any workarounds?

How can I migrate existing files on the s3 to the iceberg aws glue catalog backed with s3?

it fails as indicated above with `No FileSystem for scheme "s3"`.
Does it mean that I need to rewrite data files??

I tried to use s3a, but then it fails to read catalog metadata with the same error.
`org.apache.iceberg.exceptions.RuntimeIOException: Failed to get file system for path: s3://hp-bucket2/dir/iceberg-catalog/db.db/table2/metadata/stage-23-task-811-manifest-61f714f0-2fe7-4c89-9531-36a6f99d3ed1.avro`

**Comment by hpylypets-ua** [comment]
Or maybe I can add existing data files programmatically with Java SDK without using spark add_files procedure?

**Comment by nicornk** [comment]
Is there any solution for this? Burned a few hours on this issue, trying out multiple different dependency configurations :(

**Comment by prassee** [comment]
this issue still prevails for pyspark as well
