### ISSUE TITLE
How to clean s3/oss orphan files with spark?

### ISSUE THREAD

**Issue by MarsKT** [apache/iceberg#8368]
### Query engine

spark

### Question

How can I clean orphaned files if I use oss/s3 as storage.DeleteOrphanFilesSparkAction just support hadoop fileSystem.

**Comment by nastra** [comment]
You can check https://iceberg.apache.org/docs/latest/spark-procedures/#remove_orphan_files for some instructions.
This procedure uses the `FileIO` implementation that is configured for the underlying table, so the statement that it only supports the Hadoop filesystem isn't correct.

How does your catalog configuration look like and how do are you calling the procedure?

**Comment by MarsKT** [comment]
> You can check https://iceberg.apache.org/docs/latest/spark-procedures/#remove_orphan_files for some instructions. This procedure uses the `FileIO` implementation that is configured for the underlying table, so the statement that it only supports the Hadoop filesystem isn't correct.
> 
> How does your catalog configuration look like and how do are you calling the procedure?

Thanks for answering this question.When i use s3FileIo, i get this error:
org.apache.iceberg.exceptions.RuntimeIOException: org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "S3"
	at org.apache.iceberg.spark.actions.DeleteOrphanFilesSparkAction.listDirRecursively(DeleteOrphanFilesSparkAction.java:298) ~[polars-iceberg-spark-runtime-0.14.01.jar:?]
	at org.apache.iceberg.spark.actions.DeleteOrphanFilesSparkAction.buildActualFileDF(DeleteOrphanFilesSparkAction.java:243) ~[polars-iceberg-spark-runtime-0.14.01.jar:?]
	at org.apache.iceberg.spark.actions.DeleteOrphanFilesSparkAction.doExecute(DeleteOrphanFilesSparkAction.java:214) ~[polars-iceberg-spark-runtime-0.14.01.jar:?]
	at org.apache.iceberg.spark.actions.BaseSparkAction.withJobGroupInfo(BaseSparkAction.java:112) ~[polars-iceberg-spark-runtime-0.14.01.jar:?]
	at org.apache.iceberg.spark.actions.DeleteOrphanFilesSparkAction.execute(DeleteOrphanFilesSparkAction.java:198) ~[polars-iceberg-spark-runtime-0.14.01.jar:?]
	at com.fanruan.polars.lake.optimizer.SimpleTableOptimizer.cleanOrphanFile(SimpleTableOptimizer.java:85) ~[classes/:?]
	at com.fanruan.polars.lake.optimizer.SimpleTableOptimizerTaskExecutor.processCleanOrphanFile(SimpleTableOptimizerTaskExecutor.java:157) ~[classes/:?]
	at com.fanruan.polars.lake.optimizer.SimpleTableOptimizerTaskExecutor$OptimizerTaskEater.run(SimpleTableOptimizerTaskExecutor.java:191) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "S3"
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3585) ~[hadoop-client-api-3.3.6.jar:?]
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3608) ~[hadoop-client-api-3.3.6.jar:?]
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174) ~[hadoop-client-api-3.3.6.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3712) ~[hadoop-client-api-3.3.6.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3663) ~[hadoop-client-api-3.3.6.jar:?]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:557) ~[hadoop-client-api-3.3.6.jar:?]
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365) ~[hadoop-client-api-3.3.6.jar:?]
	at org.apache.iceberg.spark.actions.DeleteOrphanFilesSparkAction.listDirRecursively(DeleteOrphanFilesSparkAction.java:275) ~[polars-iceberg-spark-runtime-0.14.01.jar:?]
	... 13 more

**Comment by MarsKT** [comment]
> You can check https://iceberg.apache.org/docs/latest/spark-procedures/#remove_orphan_files for some instructions. This procedure uses the `FileIO` implementation that is configured for the underlying table, so the statement that it only supports the Hadoop filesystem isn't correct.
> 
> How does your catalog configuration look like and how do are you calling the procedure?

And, After reading the source code, I found that the comment in DeleteOrphanFilesSparkAction.java
:
An action that removes orphan metadata, data and delete files by listing a given location and
comparing the actual files in that location with content and metadata files referenced by all
valid snapshots. **The location must be accessible for listing via the Hadoop** {@link FileSystem}.

**Comment by nastra** [comment]
> The location must be accessible for listing via the Hadoop FileSystem

Sorry, I completely forgot about this requirement. This might be fixed by https://github.com/apache/iceberg/pull/7914
