### ISSUE TITLE
Python: Cannot resolve avro file

### ISSUE THREAD

**Issue by frankliee** [apache/iceberg#8487]
### Apache Iceberg version

The master branch.

### Query engine

Python

### Please describe the bug 🐞

I have created a simple iceberg table by using  spark with iceberg.

```
scala> sql("create table ice.default.ice_t1( a string, b string, c int) using iceberg")
scala> sql("insert into ice.default.ice_t1 values('a','a',1),('b','b',2)")
scala> sql("select * from ice.default.ice_t1").show(false)
+---+---+---+
|a  |b  |c  |
+---+---+---+
|a  |a  |1  |
|b  |b  |2  |
+---+---+---+
```

Then I use pyiceberg to query this table by the following code.

```
from pyiceberg.catalog import load_catalog
catalog = load_catalog("default")
catalog.list_namespaces()
table = catalog.load_table("default.ice_t1")
from pyiceberg.expressions import GreaterThanOrEqual
scan = table.scan(
    row_filter=GreaterThanOrEqual("c", 1),
    selected_fields=("a", "b", "c"),
    limit=100,
)
[task.file.file_path for task in scan.plan_files()]
```
However, it seems that pyiceberg cannot resolve the avro file.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pyiceberg/table/__init__.py", line 827, in plan_files
    for manifest_entry in chain(
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyiceberg/table/__init__.py", line 829, in <lambda>
    lambda args: _open_manifest(*args),
  File "/usr/local/lib/python3.8/dist-packages/pyiceberg/table/__init__.py", line 698, in _open_manifest
    for manifest_entry in manifest.fetch_manifest_entry(io, discard_deleted=True)
  File "/usr/local/lib/python3.8/dist-packages/pyiceberg/manifest.py", line 348, in fetch_manifest_entry
    with AvroFile[ManifestEntry](
  File "/usr/local/lib/python3.8/dist-packages/pyiceberg/avro/file.py", line 175, in __enter__
    self.reader = resolve(self.schema, self.read_schema, self.read_types, self.read_enums)
  File "/usr/local/lib/python3.8/dist-packages/pyiceberg/avro/resolver.py", line 212, in resolve
    return visit_with_partner(
  File "/usr/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/pyiceberg/schema.py", line 591, in _
    return visitor.schema(schema, partner, visit_with_partner(schema.as_struct(), struct_partner, visitor, accessor))  # type: ignore
  File "/usr/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/pyiceberg/schema.py", line 601, in _
    field_result = visit_with_partner(field.field_type, field_partner, visitor, accessor)  # type: ignore
  File "/usr/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/pyiceberg/schema.py", line 601, in _
    field_result = visit_with_partner(field.field_type, field_partner, visitor, accessor)  # type: ignore
  File "/usr/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/pyiceberg/schema.py", line 623, in _
    key_partner = accessor.map_key_partner(partner)
  File "/usr/local/lib/python3.8/dist-packages/pyiceberg/avro/resolver.py", line 391, in map_key_partner
    raise ResolveError(f"File/read schema are not aligned for map, got {partner_map}")
pyiceberg.exceptions.ResolveError: File/read schema are not aligned for map, got None
```

**Comment by Fokko** [comment]
@frankliee Thanks for raising this. Do you have more information about the Spark/PyIceberg versions? I got this running on my end:

Spark:
<img width="1393" alt="image" src="https://github.com/apache/iceberg/assets/1134248/c5f2afb5-9b8f-41de-b46f-42db3ab71236">

Python:
<img width="1172" alt="image" src="https://github.com/apache/iceberg/assets/1134248/01c97d85-812d-45f5-ac03-17c5196daa9d">

**Comment by frankliee** [comment]
@Fokko Thanks for your reminder, I have found the reason is that the wrong iceberg version is used.

**Comment by frankliee** [comment]
I could query the iceberg table by the latest version.

**Comment by Fokko** [comment]
Thank you for letting me know. Also pyiceberg==0.5.0rc1 is available on PyPi for testing :)
