### ISSUE TITLE
spark read error with Failed to open file

### ISSUE THREAD

**Issue by chenwyi2** [apache/iceberg#8635]
### Query engine

spark 

### Question

when i query table with spark with error:
Caused by: org.apache.iceberg.exceptions.RuntimeIOException: Failed to open file: qbfs://online01/warehouse/bi_warehouse_ods_ice.db/ods2_qos_allpay_7_72_724/metadata/eb017bb0-5b27-4180-8c0a-18a8e19671ee-m0.avro
	at org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:102)
	at org.apache.iceberg.avro.AvroIterable.getMetadata(AvroIterable.java:65)
	at org.apache.iceberg.ManifestReader.readMetadata(ManifestReader.java:141)
	at org.apache.iceberg.ManifestReader.readPartitionSpec(ManifestReader.java:121)
	at org.apache.iceberg.ManifestReader.<init>(ManifestReader.java:114)
	at org.apache.iceberg.ManifestFiles.read(ManifestFiles.java:131)
	at org.apache.iceberg.ManifestFiles.readPaths(ManifestFiles.java:95)
	at org.apache.iceberg.spark.actions.BaseSparkAction$ReadManifest.call(BaseSparkAction.java:174)
	at org.apache.iceberg.spark.actions.BaseSparkAction$ReadManifest.call(BaseSparkAction.java:165)
	at org.apache.spark.sql.Dataset.$anonfun$flatMap$2(Dataset.scala:2876)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage9.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.shuffle.writer.RssShuffleWriter.doWrite(RssShuffleWriter.java:200)
	at org.apache.spark.shuffle.writer.RssShuffleWriter.write(RssShuffleWriter.java:167)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1470)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: Unexpected EOF with 4 bytes remaining to read
	at org.apache.iceberg.shaded.org.apache.avro.file.DataFileReader.openReader(DataFileReader.java:67)
how can i recover? and why this happen?

**Comment by manuzhang** [comment]
You may verify whether your avro file is intact with Spark SQL
```sql
select * from avro.`qbfs://online01/warehouse/bi_warehouse_ods_ice.db/ods2_qos_allpay_7_72_724/metadata/eb017bb0-5b27-4180-8c0a-18a8e19671ee-m0.avro`
```

**Comment by chenwyi2** [comment]
thank you , i think this file is corrupted, but how can i recovery this file? because with this corrupted file, i cannot write or query.

**Comment by MehulBatra** [comment]
and how this file got corrupted, as we also face this issue alot?
