### ISSUE TITLE
TestIcebergSourceFailover fails when running with JDK17

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#8680]
### Apache Iceberg version

main (development)

### Query engine

Flink

### Please describe the bug 🐞

Happens when running ./gradlew :iceberg-flink:iceberg-flink-1.17:test with JDK17

```
TestIcebergSourceFailover > testContinuousWithJobManagerFailover FAILED
    java.lang.IllegalAccessError: class org.apache.flink.util.NetUtils (in unnamed module @0x306cf3ea) cannot access class sun.net.util.IPAddressUtil (in module java.base) because module java.base does not export sun.net.util to unnamed module @0x306cf3ea
        at org.apache.flink.util.NetUtils.unresolvedHostToNormalizedString(NetUtils.java:207)
        at org.apache.flink.util.NetUtils.unresolvedHostAndPortToNormalizedString(NetUtils.java:235)
        at org.apache.flink.runtime.rpc.akka.AkkaBootstrapTools.startRemoteActorSystem(AkkaBootstrapTools.java:167)
        at org.apache.flink.runtime.rpc.akka.AkkaBootstrapTools.startRemoteActorSystem(AkkaBootstrapTools.java:112)
        at org.apache.flink.runtime.rpc.akka.AkkaRpcServiceUtils$AkkaRpcServiceBuilder.createAndStart(AkkaRpcServiceUtils.java:358)
        at org.apache.flink.runtime.rpc.akka.AkkaRpcServiceUtils$AkkaRpcServiceBuilder.createAndStart(AkkaRpcServiceUtils.java:327)
        at org.apache.flink.runtime.rpc.akka.AkkaRpcServiceUtils$AkkaRpcServiceBuilder.createAndStart(AkkaRpcServiceUtils.java:247)
        at org.apache.flink.runtime.minicluster.MiniCluster.createRemoteRpcService(MiniCluster.java:1140)
        at org.apache.flink.runtime.minicluster.MiniCluster.start(MiniCluster.java:397)
        at org.apache.flink.runtime.testutils.MiniClusterResource.startMiniCluster(MiniClusterResource.java:246)
        at org.apache.flink.runtime.testutils.MiniClusterResource.before(MiniClusterResource.java:110)
        at org.apache.flink.test.util.MiniClusterWithClientResource.before(MiniClusterWithClientResource.java:64)
```

**Comment by stevenzwu** [comment]
Flink only added Java 17 support in the upcoming 1.18 release.
https://issues.apache.org/jira/browse/FLINK-15736
