### ISSUE TITLE
Flaky test: TestSparkReaderDeletes.testEqualityDeleteWithDeletedColumn

### ISSUE THREAD

**Issue by ajantha-bhat** [apache/iceberg#8855]
TestSparkReaderDeletes > [format = orc, vectorized = false, planningMode = DISTRIBUTED] > testEqualityDeleteWithDeletedColumn

PR:8854

Build: https://github.com/apache/iceberg/actions/runs/6546667781/job/17777591189?pr=8854    

```
 java.lang.AssertionError: Metric 'number of row deletes applied' not found in last execution
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.apache.iceberg.spark.source.SparkSQLExecutionHelper.lastExecutedMetricValue(SparkSQLExecutionHelper.java:45)
        at org.apache.iceberg.spark.source.TestSparkReaderDeletes.deleteCount(TestSparkReaderDeletes.java:203)
        at org.apache.iceberg.data.DeleteReadTests.checkDeleteCount(DeleteReadTests.java:188)
        at org.apache.iceberg.spark.source.TestSparkReaderDeletes.testEqualityDeleteWithDeletedColumn(TestSparkReaderDeletes.java:421)
```

**Comment by manuzhang** [comment]
@ajantha-bhat please help review #9445 to fix this test.

**Comment by nastra** [comment]
@manuzhang Is this test still flaky? The logic around `SparkSQLExecutionHelper` has been updated in the meantime

**Comment by manuzhang** [comment]
yes, I've seen failure with latest `SparkSQLExecutionHelper`.
