### ISSUE TITLE
org.apache.iceberg.spark.source.SerializableTableWithSize cannot be cast to org.apache.iceberg.Table

### ISSUE THREAD

**Issue by HilbertGodel** [apache/iceberg#8978]
### Apache Iceberg version

1.4.1 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

I connected to spark connect server with python, showing the exception below.
However, spark-shell works for me.

`
org.apache.iceberg.spark.source.SerializableTableWithSize cannot be cast to org.apache.iceberg.Table
	at org.apache.iceberg.spark.source.SparkInputPartition.table(SparkInputPartition.java:88)
	at org.apache.iceberg.spark.source.BatchDataReader.<init>(BatchDataReader.java:50)
	at org.apache.iceberg.spark.source.SparkColumnarReaderFactory.createColumnarReader(SparkColumnarReaderFactory.java:52)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.advanceToNextIter(DataSourceRDD.scala:79)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.hasNext(DataSourceRDD.scala:63)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.columnartorow_nextBatch_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.hashAgg_doAggregateWithKeys_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:140)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:104)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

Iceberg Version: iceberg-spark-runtime-3.5_2.12:1.4.1
Spark Version 3.5.0

**Comment by tenstriker** [comment]
we are facing this issue as well. I think it's happening with iceberg version `1.4.0` and above. It works with `1.3.x` but 1.3.x only available with spark 3.4. 
So issue is reproducible for `iceberg-spark-runtime-3.5_2.12-1.4.3.jar` And it isn't for `iceberg-spark-runtime-3.4_2.12-1.3.1.jar`

**Comment by zryogi** [comment]
Can confirm this is still an issue in `iceberg-spark-runtime-3.5_2.12-1.8.0`

**Comment by tuantran0910** [comment]
Hi, any updates on this issue? I am facing this problem too
