### ISSUE TITLE
locationProvider should be marked as transient in SerializableTable

### ISSUE THREAD

**Issue by przemekd** [apache/iceberg#9025]
### Feature Request / Improvement

Right now, when trying to use SerializableTable object to read from a table, it fills its location provider, which is not ideal. E.g. if a table has a custom location provider set through `write.location-provider.impl` trying to read such table using Spark (without providing custom location provider implementation JAR) gives:

```
java.lang.IllegalArgumentException: Unable to find a constructor for implementation org.iceberg.custom.LocationProviders$DefaultLocationProvider of interface org.apache.iceberg.io.LocationProvider. Make sure the implementation is in classpath, and that it either has a public no-arg constructor or a two-arg constructor taking in the string base table location and its property string map.
        at org.apache.iceberg.LocationProviders.locationsFor(LocationProviders.java:52)
        at org.apache.iceberg.BaseMetastoreTableOperations.locationProvider(BaseMetastoreTableOperations.java:243)
        at org.apache.iceberg.BaseTable.locationProvider(BaseTable.java:245)
        at org.apache.iceberg.SerializableTable.<init>(SerializableTable.java:84)
        at org.apache.iceberg.spark.source.SerializableTableWithSize.<init>(SerializableTableWithSize.java:36)
        at org.apache.iceberg.spark.source.SerializableTableWithSize.copyOf(SerializableTableWithSize.java:48)
        at org.apache.iceberg.spark.source.SparkBatch.planInputPartitions(SparkBatch.java:77)
        at org.apache.spark.sql.execution.datasources.v2.BatchScanExec.inputPartitions$lzycompute(BatchScanExec.scala:63)
```

### Query engine

None

**Comment by przemekd** [comment]
@nastra could you assign me to this one please?
