### ISSUE TITLE
Zorder not support timestampNTZType

### ISSUE THREAD

**Issue by JMin824** [apache/iceberg#9348]
### Apache Iceberg version

1.3.1

### Query engine

Spark

### Please describe the bug 🐞

I try to use spark3.4 to rewrite file by zorder and I found that there timestampNTZ is not supported.
when I create a table using this sql:
`CREATE TABLE t1 (id int, tz TIMESTAMP, ntz TIMESTAMP_NTZ) using iceberg`
then insert some value into table, and  rewrite file by zorder like this:
`CALL hive_catalog.system.rewrite_data_files(table => 'test.t1', strategy => 'sort', sort_order => 'zorder(id,ntz)');`
there is error message:
`java.lang.IllegalArgumentException: Cannot use column ntz of type TimestampNTZType in ZOrdering, the type is unsupported
        at org.apache.iceberg.spark.actions.SparkZOrderUDF.sortedLexicographically(SparkZOrderUDF.java:316) ~[iceberg-spark-runtime-3.4_2.12-1.3.1.jar:?]
        at org.apache.iceberg.spark.actions.SparkZOrderDataRewriter.lambda$zValue$0(SparkZOrderDataRewriter.java:125) ~[iceberg-spark-runtime-3.4_2.12-1.3.1.jar:?]`

**Comment by JMin824** [comment]
I try to add timestampntz in SparkZOrderUDF.java, but in spark3.4 ntz cant not cast to bigint, anyone can solve it?
