### ISSUE TITLE
append() fails with DataframeWriterV2's writeTo api

### ISSUE THREAD

**Issue by mkavinashkumar** [apache/iceberg#9874]
### Apache Iceberg version

1.4.3 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

I get an error when I try to append data using the writeTo api in pyspark with dataframes to append data to a both v2  and v1 iceberg tables. Is this an error in my setup or a known limitation?
**Below is the code snippet:**
```
from pyspark.sql.types import StructType, StructField, IntegerType, StringType
from pyspark.sql import Row

# Data
data = [
    Row(1, "Software Engineer", "Engineering", 25000, "NA"),
    Row(2, "Director", "Sales", 22000, "EMEA")
]

# Parallelize the data and create an RDD
rdd = spark.sparkContext.parallelize(data)

# Define the schema
schema = StructType([
    StructField("id", IntegerType(), True),
    StructField("role", StringType(), True),
    StructField("department", StringType(), True),
    StructField("salary", IntegerType(), True),
    StructField("region", StringType(), True)
])

# Create a DataFrame from RDD
df = spark.createDataFrame(rdd, schema)
df.writeTo("iceberg_test.employee_df_v2_2").tableProperty("format-version", "2").create()

df_2 = spark.createDataFrame(rdd, schema)
df.writeTo("iceberg_test.employee_df_v2_2").append()
```
**Stacktrace:**
```
Fail to execute line 25: df.writeTo("iceberg_test.employee_df_v2_2").append()
Traceback (most recent call last):
  File "/mnt/volume8/yarn/nm/usercache/admin/appcache/application_1704921312430_0788/container_e03_1704921312430_0788_01_000001/tmp/python4571889082826602192/zeppelin_python.py", line 167, in <module>
    exec(code, _zcUserQueryNameSpace)
  File "<stdin>", line 25, in <module>
  File "/mnt/volume8/yarn/nm/usercache/admin/appcache/application_1704921312430_0788/container_e03_1704921312430_0788_01_000001/pyspark.zip/pyspark/sql/readwriter.py", line 2042, in append
    self._jwriter.append()
  File "/mnt/volume8/yarn/nm/usercache/admin/appcache/application_1704921312430_0788/container_e03_1704921312430_0788_01_000001/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1323, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/mnt/volume8/yarn/nm/usercache/admin/appcache/application_1704921312430_0788/container_e03_1704921312430_0788_01_000001/pyspark.zip/pyspark/errors/exceptions/captured.py", line 175, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: Cannot write into v1 table: `spark_catalog`.`iceberg_test`.`employee_df_v2_2`.
```
**Environment: spark 3.4.1, iceberg 1.4.3**
spark.jars.packages: 	org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.4.3,org.apache.iceberg:iceberg-spark-extensions-3.4_2.12:1.4.3
spark.sql.catalog.spark_catalog: 	org.apache.iceberg.spark.SparkSessionCatalog 	
spark.sql.extensions: 	org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions 	
spark.sql.catalog.spark_catalog.type: 	hive

**Comment by hussein-awala** [comment]
It could be related to the catalog, could you try `SparkCatalog` instead of `SparkSessionCatalog`?

**Comment by tiagoposse** [comment]
I'm facing the same issue:
**Environment**: spark 3.5.2, iceberg 1.5.2, nessie 0.96.1

my config is:
```
conf = SparkConf() \
    .setAppName("Apache Iceberg with PySpark") \
    .setMaster("local[*]") \
    .setAll([
        ('spark.jars.packages', 'org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.2,org.projectnessie.nessie-integrations:nessie-spark-extensions-3.5_2.12:0.96.1,software.amazon.awssdk:bundle:2.28.2,software.amazon.awssdk:url-connection-client:2.28.2'),
        ("spark.driver.memory", "4g"),
        ("spark.executor.memory", "4g"),
        ("spark.sql.shuffle.partitions", f"{partition_size}"),
        ('spark.sql.adaptive.coalescePartitions.initialPartitionNum', f"{(os.cpu_count())}"),
        ('spark.sql.adaptive.coalescePartitions.parallelismFirst', 'false'),
        ('spark.sql.files.minPartitionNum', "1"),
        ('spark.sql.files.maxPartitionBytes', '500mb'),
        
        # Add Iceberg SQL extensions like UPDATE or DELETE in Spark
        ('spark.sql.extensions', 'org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions'),

        ('spark.sql.catalog.nessie', 'org.apache.iceberg.spark.SparkCatalog'),
        ('spark.sql.catalog.nessie.uri', self.nessie_uri),
        ('spark.sql.catalog.nessie.ref', 'main'),
        ('spark.sql.catalog.nessie.authentication.type', 'NONE'),
        ('spark.sql.catalog.nessie.catalog-impl', 'org.apache.iceberg.nessie.NessieCatalog'),
        ('spark.sql.catalog.nessie.s3.endpoint', self.s3_endpoint),
        ('spark.sql.catalog.nessie.warehouse', self.warehouse),
        ('spark.sql.catalog.nessie.io-impl', 'org.apache.iceberg.aws.s3.S3FileIO'),
        ('spark.hadoop.fs.s3a.access.key', self.aws_access_key),
        ('spark.hadoop.fs.s3a.secret.key', self.aws_secret_key),
    ])
spark = SparkSession.builder.config(conf=conf).getOrCreate()
```

Writing like:
```
df \
    .writeTo(f"{self.table_name}") \
    .using("iceberg") \
    .append()
```

Stacktrace:
```
File "/Users/posse/work/meltano/.meltano/loaders/target-iceberg/venv/lib/python3.10/site-packages/target_iceberg/sinks.py", line 143, in write_data.append()                  
File "/Users/posse/work/meltano/.meltano/loaders/target-iceberg/venv/lib/python3.10/site-packages/pyspark/sql/readwriter.py", line 2107, in append 
  self._jwriter.append()     
File "/Users/posse/work/meltano/.meltano/loaders/target-iceberg/venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__ 
  return_value = get_return_value( 
File "/Users/posse/work/meltano/.meltano/loaders/target-iceberg/venv/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
  raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: Cannot write into v1 table: `spark_catalog`.`default`.`genesys`. 
```

I'm using SparkCatalog, so this did not solve it for me.
Any help would be greatly appreciated. Can also provide more info if needed

**Comment by tiagoposse** [comment]
For anyone searching this, my problem was missing this property:
```
('spark.sql.defaultCatalog', 'nessie'),
```

**Comment by nastra** [comment]
The error `Cannot write into v1 table` usually means you're using the `SparkSessionCatalog` and created the table without `USING iceberg`. The table ends up being a DataSource V1 table and via `df.write(...)` you're ending up with a `DataFrameWriterV2, which requires the table to be a DataSource V2 table.
